### ISSUE TITLE
Compute SSR rendering in Node.js worker threads

### ISSUE THREAD

**Issue by brillout** [brillout/vite-plugin-ssr#10]
At scale, rendering pages in worker threads can become crucial. If you need this, write a comment here.

EDIT: not to be confused with Cloudflare Workers, which is already supported https://vite-plugin-ssr.com/cloudflare-workers

**Comment by gryphonmyers** [comment]
Just commenting that this is a good idea :). This plugin + Vite is already so, so much faster and more efficient than many alternative solutions, but as a wise animal once said, _gotta go fast_.

**Comment by huygn** [comment]
yes 👀

**Comment by harrytran998** [comment]
@brillout Yeah, I think it should be on the list waiting for the crutial feature.

**Comment by brillout** [comment]
@harrytran998 Do you have a use case that needs this?

**Comment by nrgnrg** [comment]
We're looking to do a React dynamic render in workers in the coming months, this support for this would be ideal for us

**Comment by nrgnrg** [comment]
The plan is to implement admin dashboards using the new React 18 SSR architecture (streaming HTML, partial hydration...) with a dynamic render served from CF Workers.

**Comment by brillout** [comment]
Closing since no one is asking for it. Let me know if you hit performance bottlenacks due to scale, this ticket may help.
