### ISSUE TITLE
List of status code for `renderErrorPage()` and redirect()`

### ISSUE THREAD

**Issue by brillout** [brillout/vite-plugin-ssr#1008]
AFAICT the only status codes that are relevant in the context of rendering a page are the following.

For `redirect()`:
 - `301`
 - `302`

> `307` and `308` have no added benefit (since the requests are always `GET`) while having the drawbacks of some HTTP clients not supporting them. Thus `307` and `308` should be discouraged.

For `renderErrorPage()`:
 - `401`
 - `403`
 - `404`
 - `429`
 - `500`
 - `503`

Am I missing a status code? If you believe so, let me know and I'll add it.

**Comment by alexdriaguine** [comment]
We have been using 400 for some of our pages and getting pointed here from a warning.

The use case is an endpoint which takes a query parameter (sessionId), which we have noticed sometimes is omitted (it is required for the page to fetch the content needed), so 400 Bad Request seems appropriate here. Guess 404 could also be used since the resource is not found anymore but 400 feels better (😅)

**Comment by brillout** [comment]
Hm, it's a good question whether `400` should be added :thinking:

The way I see is that it can(/should?) be a `500` instead of a `400`: it's a bug in your source code. The `400` code makes a lot of sense for RESTful APIs, but not so much when rendering a page.

 I'm even inclined to think that it's counter productive, because [the error page](https://vike.dev/error-page) now has to handle `abortStatusCode === 400` which is redudant as it would most likely render the exact same page as if `abortStatusCode === 500`.

From the perspective of "what error should be shown to the user", I think consolidating these internal errors into one status code `500` makes sense.

Or do you see any drawback of using `500` instead of `400`?

**Comment by brillout** [comment]
Actually, I it should be a `404` since the URL may come from the user.

> Guess 404 could also be used since the resource is not found anymore but 400 feels better (😅)

Any concrete drawback of using `404` instead of `400`? The "feels better" part may come from the practice of using `400` for RESTful APIs which isn't that relevant in Vike's context.

**Comment by brillout** [comment]
Another user, also using `400` for missing query parameters:
- https://github.com/vikejs/vike/issues/2696

After thinking more about it, I still think Vike's official recommendation should be to use `404` instead of `400`.

My argument being: in the following, you would expect a `404` (not a `400`) for the typo `<a href="/prodct/42">`, right?

```html
<a href="/product?id=42"> <!-- ✅ Query param => 200 -->
<a href="/product"> <!-- ❌ Missing query param => 404 -->

<a href="/product/42"> <!-- ✅ Route param => 200 -->
<a href="/product"> <!-- ❌ Missing route param => 404 -->

<a href="/prodct/42"> <!-- ❌ Typo => 404 -->
```

All of these are both conceptually and technically the exact same situation, so I'd expect them to return the same status code `404`.

This isn't only theoretical, it also makes implementing [the error page](https://vike.dev/error-page) easier. (Ohterwise you'd also need to handle `abortStatusCode === 400` in your error page.)

I understand that the common status code for malformed API requests is `400`, but AFAICT this practice is only relevant for APIs.
