### ISSUE TITLE
node_modules\vite-plugin-ssr\dist\cjs\utils\filesystemPathHandling.js:23     (0, assert_1.assert)(!path.includes(sepWin32), errMsg(path));

### ISSUE THREAD

**Issue by JPF12** [brillout/vite-plugin-ssr#1017]
### Description

Debug info (this is for the vite-plugin-ssr maintainers; you can ignore this): Not a posix path

I do not know how this bug appeared, I was just following the normal vue3 and documentation to build, when the introduction of components will not load properly, the program stops
![image](https://github.com/brillout/vite-plugin-ssr/assets/26289682/54135cbf-de7e-4019-a32d-beca289fcf0e)

**Comment by JPF12** [comment]
Found the reason, when the component content is empty, this error occurs, but feel that the program directly stops, not very reasonable, hope to improve the error message

**Comment by brillout** [comment]
I agree. If you can give me the full stack trace then I'll be able to fix it.
