### ISSUE TITLE
Running into "react-refresh/only-export-components" when using `documentProps`

### ISSUE THREAD

**Issue by infomiho** [brillout/vite-plugin-ssr#1026]
### Setup

I was playing around with the plugin starting from the default `npm init vite-plugin-ssr@latest` with selecting the `React + TS` option.

### Adding `documentProps`

Based on the info located here: https://vite-plugin-ssr.com/head#by-page-static I've tried to add some title to the About page and then run the "production server" with `npm run prod`. 

```js
import './code.css'

export function Page() {
  return (
    <>
      <h1>About</h1>
      <p>
        Example of using <code>vite-plugin-ssr</code>.
      </p>
    </>
  )
}

export const documentProps = {
  title: 'About SpaceX',
  description: 'Our mission is to explore the galaxy.'
}
```

This results in a ESLint warning and doesn't run the server successfully:
```
.../pages/about/index.page.tsx
warning  Fast refresh only works when a file only export components. Use a new file to share constant or functions between components  react-refresh/only-export-components
```

I see that the `.eslintrc.cjs` sets the rule to `warn` but this still stops the server from starting. Is there a different way to define the static props so the linter would be happy?

**Comment by brillout** [comment]
You can try a re-export. (A proper HMR implementation should be able to support re-exports.)

FYI the [V1 design](https://vite-plugin-ssr.com/migration/v1-design) doesn't have this issue.

**Comment by brillout** [comment]
Closing because it isn't a bug per se, but let's continue the disucssion.
