### ISSUE TITLE
Internal assertion failed

### ISSUE THREAD

**Issue by bob057** [brillout/vite-plugin-ssr#104]
Uncaught (in promise) Error: [vite-plugin-ssr@0.1.0-beta.43][Internal Failure] You stumbled upon a bug in `vite-plugin-ssr`'s source code (an internal assertion failed). This should definitely not be happening, and you should create a new issue at https://github.com/brillout/vite-plugin-ssr/issues/new that includes this error stack (the error stack is enough to debug this). Or reach out on Discord. A fix will be written promptly.
    at newError2 (newError.ts:18)
    at assert (assert.ts:21)
    at getPageById (getPage.client.ts:46)
    at async getPage (getPage.client.ts:19)
    at async hydrate (_default.page.client.js:6)

**Comment by brillout** [comment]
Let me have a look

**Comment by brillout** [comment]
Actually, the best would be that you update to `vite-plugin-ssr@0.1.2` and let me know if the error persists.

**Comment by bob057** [comment]
Thanks for the quick reply. It works now after upgrading and changing ${html.dangerouslySetHtml(appHtml)} to ${html.dangerouslySkipEscape(appHtml)}

**Comment by brillout** [comment]
Yes, make sure to check the `CHANGELOG.md` while upgrading.
