### ISSUE TITLE
URL's hash segment is missing in the urlParsed object

### ISSUE THREAD

**Issue by luciorubeens** [brillout/vite-plugin-ssr#1042]
### Description

Hey, I'm trying to access the current hash segment, but it's empty. For context, here is the code:

```tsx
// http://localhost:3000/#reviews

// Filename: _default.page.server.tsx
export async function render(pageContext: PageContext) {
  console.log(pageContext.urlParsed)
  // ...
}
```

It seems to be on purpose based on this file: [vite-plugin-ssr/client/getPageContext.ts](https://github.com/brillout/vite-plugin-ssr/blob/main/vite-plugin-ssr/client/getPageContext.ts). How can i get the full URL?

**Comment by brillout** [comment]
I don't think it's possible to reliably access the hash from the server. (HTTP requests don't include the hash.)

VPS could add a warning about this though. Leaving this open to explore whether a warning can be added.

**Comment by brillout** [comment]
Warning added.

Btw. in case your company is up for it: https://github.com/sponsors/brillout.
