### ISSUE TITLE
You stumbled upon a bug in vite-plugin-ssr's source code.

### ISSUE THREAD

**Issue by ImSwordTooth** [brillout/vite-plugin-ssr#1047]
### Description

Thank you for your support❤️.

`"vite-plugin-ssr": "^0.4.126"`

bug log:
> You stumbled upon a bug in vite-plugin-ssr's source code. Go to https://github.com/brillout/vite-plugin-ssr/issues/new and copy-paste this error. (The error's stack trace is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes vite-plugin-ssr more robust.  
> 
> |     at parseGlobResults (/usr/share/nginx/html/node_modules/vite-plugin-ssr/dist/cjs/shared/getPageFiles/parseGlobResults.js:22:24)
> |     at setPageFiles (/usr/share/nginx/html/node_modules/vite-plugin-ssr/dist/cjs/shared/getPageFiles/setPageFiles.js:9:98)
> |     at initGlobalContext (/usr/share/nginx/html/node_modules/vite-plugin-ssr/dist/cjs/node/runtime/globalContext.js:40:41)
> |     at async renderPage (/usr/share/nginx/html/node_modules/vite-plugin-ssr/dist/cjs/node/runtime/renderPage.js:24:9)
> |     at async /usr/share/nginx/html/deploy.js:14:22

**Comment by ImSwordTooth** [comment]
Sorry, I made a mistake. I thought it was the latest version. Just upgrade to 0.4.133.


But when I used 0.4.133，my IDE（webstorm）report: 

> Can't analyze vite.config.js: coding assistance will ignore module resolution rules in this file......

and the error trace was hidden, I cant get it。
This bug only affects coding assistance，no any other substantial damage.

![image](https://github.com/brillout/vite-plugin-ssr/assets/43266605/e8890663-4137-45b8-ba11-097850a184f1)

**Comment by brillout** [comment]
> Can't analyze vite.config.js: coding assistance will ignore module resolution rules in this file......

I'm not familiar with that one.

Can you try to run your app with the terminal instead of using your IDE and report back the full stack trace?

**Comment by ImSwordTooth** [comment]
> Can you try to run your app with the terminal instead of using your IDE and report back the full stack trace?

There are no bug reports on the terminal.Perhaps this is an issue with the IDE. Sorry for the inconvenience. Thank you again for your time. I'll close this issue.

**Comment by brillout** [comment]
> Perhaps this is an issue with the IDE

Feel free to let me know if you want help debugging this.

(Btw. in case your company is up for it: https://github.com/sponsors/brillout.)
