### ISSUE TITLE
Testimonials

### ISSUE THREAD

**Issue by brillout** [brillout/vite-plugin-ssr#105]
Let me know how `vite-plugin-ssr` has worked out for you. I'll add your testimonial to the website.

Edit: If you are company, something you could include in the testimonial is what it is you are building with vite-plugin-ssr. Especially if it's something you cannot easily build with Next.js/Nuxt (e.g. large scale enterprise projects).

**Comment by brillout** [comment]
> thank you for this lovely (and so easily extensible) tool

[ref](https://github.com/brillout/vite-plugin-ssr/issues/117#issue-947458155) @aral

Do you mind if I use your quote on vite-plugin-ssr.com's website? Anything you want me to change/add to your quote?

**Comment by brillout** [comment]
> Vite plugin SSR is very (refreshingly) decoupled from rendering frameworks. It just expects html to get rendered asynchronously and doesn't care which framework you use to get there.

[ref](https://discord.com/channels/815937377888632913/815937377888632916/862022573814579200) @gryphonmyers 

Do you mind if I use your quote on vite-plugin-ssr.com? Anything you want me to change/add to your quote?

**Comment by brillout** [comment]
> I'm making a transition from using next.js [...], just a little more steps to get things all working like a well oiled machine.

[ref](https://discord.com/channels/815937377888632913/815937377888632916/843016948303790112) @yoroshikun 

Do you mind if I use your quote on vite-plugin-ssr.com? Anything you want me to change/add to your quote?

**Comment by brillout** [comment]
@chrisvariety 
@joeyshipley

A testimonial would be awesome :-) But if you're busy then don't mind.

**Comment by yoroshikun** [comment]
All good to use the testimony :)

**Comment by brillout** [comment]
> A testimonial would be awesome :-) But if you're busy then don't mind.

cc @stephensamra

**Comment by stephensamra** [comment]
@brillout absolutely! cc @LydiaF

**Comment by joeyshipley** [comment]
I've fought with various node/express/ssr things over the last year and only met with more trouble than it's worth. This one is the first that has come together almost painlessly and you have been super responsive to anything that has come up.

**Comment by brillout** [comment]
> Haha, that’s an understatement. It’s amazing the level of complexity involved in JS tooling at the moment :)
> (Which is why vite-plugin-ssr is such a breath of fresh air. I really appreciate the modular “do one thing well” approach.)

[ref](https://github.com/aral/vite-plugin-ssr-svelte/issues/1#issuecomment-883357333) @aral

**Comment by gryphonmyers** [comment]
> > Vite plugin SSR is very (refreshingly) decoupled from rendering frameworks. It just expects html to get rendered asynchronously and doesn't care which framework you use to get there.
> 
> [ref](https://discord.com/channels/815937377888632913/815937377888632916/862022573814579200) @gryphonmyers 
> 
> Do you mind if I use your quote on vite-plugin-ssr.com? Anything you want me to change/add to your quote?

Sure

**Comment by stephensamra** [comment]
vite-plugin-ssr is an extremely well thought out plugin. Usually, SSR in Node.js involves a fair amount of complexity and often some haphazard, glued together solutions. This package is the exact opposite! The conventions are sensible, the API is stable and robust, all while being extensible with regards to how you build your app. I can't recommend it enough if you need SSR with Vite. We were building our app with Next.js but it eventually became too slow to build due to the amount of files (~15,000). After migrating to Vite + vite-plugin-ssr, we saw our build times drop 5x!

**Comment by brillout** [comment]
@stephensamra Evan You has retweeted your testimonial... https://twitter.com/youyuxi/status/1423324336845426691

**Comment by brillout** [comment]
> You're totally right the code should be as modular as possible. I admire your mentality of "do one thing and do it right". Each module of code should have a well defined responsibility and solve one unique problem for a set of closely related use cases.
> Another strong pillar of vite-plugin-ssr is the fact that it's framework and tooling agnostic, so it's very easy to swap out this stuff under the hood, no vendor lock-in.

[From discord](https://discord.com/channels/815937377888632913/815937377888632916/893950768602820749).
