### ISSUE TITLE
follow some of NextJS file conventions for the route.

### ISSUE THREAD

**Issue by BanDroid** [brillout/vite-plugin-ssr#1055]
### Description

follow NextJS features for loading, custom error handling, and 404 page.

i know we could implement this manually using client routing, but i hope it could be just simpler like NextJS so we could have different custom loading, error, and not found for each route easily.

**Comment by brillout** [comment]
That's the plan with `vike-react`. That said, feel free to elaborate on specific features if you believe that some aspects of the Vike + vike-react combo don't provide a seamless zero-config DX a la Next.js. Closing in the meantime.
