### ISSUE TITLE
vite-ssr error with vite ?

### ISSUE THREAD

**Issue by FLavalliere** [brillout/vite-plugin-ssr#106]
I'm trying to get a vue boilerplate or maybe an vue-ssr with vite and lambda  / aws-serverless-express...

await fastify.register(require('fastify-vite'), {
    // Where your vite.config.js is located
    // Defaults to process.cwd() if unset
    root: __dirname + '/',
  })
  console.error(__dirname + '/');

And i am receiving this error 

Any clue:
Listening on http://localhost:3000
Error: failed to load module for ssr: ..../boilerplate-vue/entry/server.js
    at instantiateModule (...../node_modules/vite/dist/node/chunks/dep-0ed4fbc0.js:69933:15)

**Comment by brillout** [comment]
Are you using vite-plugin-ssr?

**Comment by swina** [comment]
Just following the instructions for Vue boilerplate

```
npm install
npm run dev
```

Opening the browser http://localhost:3000

```
[vite] Error when evaluating SSR module /pages/_default/_default.page.server.js:
SyntaxError: Unexpected token '.'
    at new Function (<anonymous>)
    at instantiateModule (C:\whoobe-alpha\whoobe-ssr\node_modules\vite\dist\node\chunks\dep-0ed4fbc0.js:69982:9) (x2)
```



**package.json**

```
{
  "scripts": {
    "dev": "npm run server",
    "prod": "npm run build && npm run server:prod",
    "build": "vite build && vite build --ssr",
    "server": "node ./server",
    "server:prod": "cross-env NODE_ENV=production node ./server"
  },
  "dependencies": {
    "@vitejs/plugin-vue": "^1.2.3",
    "@vue/compiler-sfc": "^3.0.11",
    "@vue/server-renderer": "^3.0.11",
    "cross-env": "^7.0.3",
    "express": "^4.17.1",
    "vite": "^2.3.6",
    "vite-plugin-ssr": "^0.1.2",
    "vue": "^3.0.11"
  }
}

```

Thanks

**Comment by brillout** [comment]
Let me have a look

**Comment by brillout** [comment]
I cannot reproduce, what's your Node version? Does `$ rm node_modules/.vite/` solve the prob?

**Comment by swina** [comment]
Removed `node_modules/.vite` still same problem

`Node v. 12.22.0`

Strange is the `npm run prod` is working

**Comment by brillout** [comment]
It's prob your Node.js Version. Does it work with Node `v13`?

**Comment by swina** [comment]
Hi I can't try with v13 or even v14 on this machine. I can give a try later on a different machine. Thanks btw.

Have a good day

**Comment by brillout** [comment]
The problem is the Node.js version, it will work with v13.

**Comment by brillout** [comment]
You can now use the latest boilerplate which now works with Node v12 `$ npm init vite-plugin-ssr@latest`.

**Comment by swina** [comment]
Great I will give a try when I am back in office. Thank you very much!

**Comment by FLavalliere** [comment]
Yes i noticed that it was working with node 14 after a few tries :/

**Comment by swina** [comment]
Ok now no problems even with node 12. Thank you again. 
I am very interested in this plugin since I am working on a project that is still in alpha version (very alpha).
You can find a demo here:

https://whoobe-generator.vercel.app/

And the editor here

https://whoobe-studio-demo.vercel.app/  
(since the backend is at the moment on heroku free plan, can take some seconds to connect, wait for the login, username and password are set automatically to admin - password, since is a demo ...)

My goal is to create all pages prerendered (nuxt style) in order to have a serverless full static output

Thank you again.
Antonio

**Comment by brillout** [comment]
Nice demo, seems quite functional already.

> My goal is to create all pages prerendered (nuxt style) in order to have a serverless full static output

👍 Make sure to check out the pre-rendering guide.

**Comment by swina** [comment]
Yes I will start wirh some prerendering test in the weekend I'll let you know if I have any problem or question. Thanks.

**Comment by brillout** [comment]
The pre-rendering design should, I believe, allow you to achieve anything you want regarding pre-rendering. The docs may be less-than-ideal though. So let me know if there are some hiccups in your journey. Also on Discord if you prefer.
