### ISSUE TITLE
Support for type:module?

### ISSUE THREAD

**Issue by jaswrks** [brillout/vite-plugin-ssr#1064]
### Description

Just added this to an existing project to test it out and got the following when attempting to build. It looks like the `mvdan-sh` dependency is trying to use `require` inside my project, which is using `type: "module"` and `vite.config.mjs`.

```
Failed to load config from vite.config.mjs
error during build:
TypeError: Cannot set property require of #<Object> which has only a getter
    at Object.<anonymous> (mvdan-sh/index.js:5:181)
```

**Comment by brillout** [comment]
I don't think this is related to vite-plugin-ssr.
