### ISSUE TITLE
bug after loading page

### ISSUE THREAD

**Issue by bob057** [brillout/vite-plugin-ssr#108]
`_default.page.client.js:9 Uncaught (in promise) Error: [vite-plugin-ssr@0.1.2][Internal Failure] You stumbled upon a bug in `vite-plugin-ssr`'s source code (an internal `assert()` failed). This should definitely not be happening, and you should create a new issue at https://github.com/brillout/vite-plugin-ssr/issues/new that includes this error stack (the error stack is usually enough to debug internal errors). Or reach out on Discord. A fix will be written promptly. Debug info:

 `{"pageId":"/ssr/pages/reset","pageFilePaths":["/ssr/pages/account.page.vue","/ssr/pages/login.page.vue","/ssr/pages/mailsent.page.vue","/ssr/pages/resetpassword.page.vue","/ssr/pages/_error.page.vue","/ssr/pages/about/index.page.vue","/ssr/pages/index/index.page.vue","/ssr/pages/marketer/index.page.vue","/ssr/pages/projects/index.page.vue"]}` (the debug info is for the `vite-plugin-ssr` maintainers; you can ignore this).

    at newError2 (newError.ts:18)
    at assert (assert.ts:23)
    at getPageFile (getPageFiles.shared.ts:62)
    at async getPageById (getPage.client.ts:33)
    at async getPage (getPage.client.ts:15)
    at async hydrate (_default.page.client.js:6)

newError2 @ newError.ts:18
assert @ assert.ts:23
getPageFile @ getPageFiles.shared.ts:62
async function (async)
hydrate @ _default.page.client.js:6
(anonymous) @ _default.page.client.js:3`

**Comment by brillout** [comment]
If you reload the page, does the error persist?

**Comment by bob057** [comment]
yes, the error returns in the same way

**Comment by brillout** [comment]
Until we get to the bottom of this, you can `$ rm node_modules/.vite/` and see if it works again.

> Do you have a file `ssr/pages/reset.page.*` or `ssr/pages/about/reset.page.*`?

I would also remove/recreate all `reset.page.*` files and see if it works.

**Comment by bob057** [comment]
The location of the file is ssr/pages/reset.page.* I executed  rm node_modules/.vite/, but the error still occurs. I also renamed the file.

The html page:

`
<html>
<body>


<!DOCTYPE html>
--
  | <html lang="en">
  | <head>
  | <script type="module" src="/@vite/client"></script>
  | <meta charset="UTF-8" />
  | <link rel="icon" href="/ssr/assets/logo.png" />
  | <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  | <meta name="description" content="projectTitle" />
  | <title>Groene Marketeers</title>
  | </head>
  | <body class="reset">
  | <div id="app"><div class="container"><div class="row"><div class="col"><a class="navbar-brand" href="#">projectTitle</a></div><div class="col"><nav class="navbar navbar-expand-lg" data-v-d1014864><div class="container" data-v-d1014864><a class="navbar-brand" href="#" data-v-d1014864> projectTitle <br data-v-d1014864> projectTitle</a><button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" data-v-d1014864><span class="navbar-toggler-icon" data-v-d1014864></span></button><div id="navbarSupportedContent" class="collapse navbar-collapse" data-v-d1014864><ul class="navbar-nav ms-auto mb-2 mb-lg-0" data-v-d1014864><li class="nav-item" data-v-d1014864><a class="nav-link" href="/" data-v-d1014864>home</a></li><li class="nav-item" data-v-d1014864><a class="nav-link" href="/match" data-v-d1014864>match</a></li><li class="nav-item" data-v-d1014864><a class="nav-link" href="/marketeers" data-v-d1014864>marketeers</a></li><li class="nav-item" data-v-d1014864><a class="nav-link" href="/projecten" data-v-d1014864>projecten</a></li><li class="nav-item" data-v-d1014864><a class="nav-link" href="/about" data-v-d1014864>contact</a></li><li class="nav-item" data-v-d1014864><button class="btn btn-primary" data-v-d1014864>inloggen</button></li><li class="nav-item" data-v-d1014864><button class="btn btn-primary" data-v-d1014864>registreren</button></li></ul></div></div></nav></div></div><div class="row align-items-center"><div class="div-login-form"><p>er is een mail verstuurd met daarin een link om het wachtwoord te resetten</p><br><a href="/login">Terug naar inloggen</a></div></div></div></div>
  | <script>window.__vite_plugin_ssr__pageContext = {_pageId:"\u002Fssr\u002Fpages\u002Freset",pageId:void 0,pageProps:{},routeParams:{}}</script><script type="module" src="/ssr/pages/_default/_default.page.client.js"></script></body>
  | </html>


</body>
</html>`

**Comment by brillout** [comment]
But if you remove your `ssr/pages/reset.page.*` files then it does work correct?

So the problem is with your `ssr/pages/reset.page.*` files, right?

What is the content of your `ssr/pages/reset.page.*` files?

If it's an option for you I can have a look at your repository. That would be the quickest way.

**Comment by bob057** [comment]
After executing `rm node_modules/.vite/` it works now. The reset page only contains a link back to the login screen.

**Comment by brillout** [comment]
Do you know how to reproduce this error? I've got a couple of users hitting this error but I couldn't reproduce so far.

I'm superseding this ticket with https://github.com/brillout/vite-plugin-ssr/issues/109.
