### ISSUE TITLE
When you install it it keeps loading

### ISSUE THREAD

**Issue by Dennise89** [brillout/vite-plugin-ssr#1094]
### Description

I just installed a fresh copy of vite-ssr-plugin and put it on a droplet at DigitalOcean. It runs, but it keeps loading (can't see the favicon and shows loading circle) and on mobile it takes a long time on first load and it also keeps loading.

After a while it's done with loading but takes a very long time.

Any ideas?

**Comment by brillout** [comment]
It's most likely unrelated to VPS.

**Comment by Dennise89** [comment]
@brillout Why close it? Have to switch to something else then...

**Comment by brillout** [comment]
From what you've written so far, it very much seems like an issue that has nothing to do with vite-plugin-ssr.

If you believe it's a vite-plugin-ssr bug then create a *minimal* reproducion and I'll have a look at it.

**Comment by Dennise89** [comment]
Well just like I said. It's a FRESH install of vite-plugin-ssr. So I have done nothing with the code yet.
I set up my nginx server to listen to port 3000 and use pm2 to run the npm run prod command.

Do you want me to share the URL with you?

This is my NGINX config

`
server {
    server_name mydomain.com www.mydomain.com;
    root /var/www/mydomain.com;

    location / {
        add_header  X-Robots-Tag "noindex, nofollow, nosnippet, noarchive";
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $http_host;
        proxy_pass http://127.0.0.1:3000;
    }

    location ~ /.well-known {
        allow all;
    }

    index index.html index.htm;

    client_max_body_size 50m;

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/mydomain.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/mydomain.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


}
server {
    if ($host = mydomain.com) {
        return 301 https://www.mydomain.com$request_uri;
    } # managed by Certbot

    if ($host = www.mydomain.com) {
        return 301 https://www.mydomain.com$request_uri;
    } # managed by Certbot

    server_name mydomain.com www.mydomain.com;
    listen 80;
    return 404; # managed by Certbot
}
`

**Comment by brillout** [comment]
> I set up my nginx server to listen to port 3000 and use pm2

That's likely the culprit.

Isolate the issue and create a minimal reproduction, I'll have a look at it then.

**Comment by Dennise89** [comment]
What do you need? A URL only? Or also access to the server?

**Comment by brillout** [comment]
Google what minimal reproduction means. I believe antfu wrote some neat article about it.

**Comment by Dennise89** [comment]
@brillout That's not something I can do I think. Still requires you to install the package on a droplet or something.. Guess I will have to abandon your package.

Thanks for the effort tho.

**Comment by brillout** [comment]
I don't think it's related to DigitalOcean, so a minimal reproduction should be possible.

**Comment by Dennise89** [comment]
Yea probably. But I have no clue where/how I can setup a server where you have access to and where I can set it up exactly like I have. So I think we're not going to figure this out.

**Comment by Dennise89** [comment]
@brillout Okay, I think I found the issue. I did a little searching and apparently the response is never ended. So I added res.end() to server/index.js and Now it's super fast.

Now I'm going to check if it still works with fetching data and stuff.

**Comment by brillout** [comment]
I'd strongly recommend to read the whole article: https://antfu.me/posts/why-reproductions-are-required. It makes a *massive* difference for maintainers.

**Comment by Dennise89** [comment]
@brillout Yea I know and I understand. But I don't really know how to create a reproduction since it is on a webserver and not a site.
![Schermafbeelding 2023-08-25 om 19 10 12](https://github.com/brillout/vite-plugin-ssr/assets/11348419/98c702a4-d8e5-4753-b975-b4e789a2a2d1)

I get this error.

**Comment by brillout** [comment]
Everything still points to something unrelated to VPS.

**Comment by Dennise89** [comment]
@brillout Yea, I'm probably doing something wrong, but I have no clue what. It tries to ping port 24678 but nothing is on that port.

I want to thank you for your time and effort so far. I know it's not your problem this is not working.

**Comment by brillout** [comment]
I'd actually love to further assist even for an issue unrelated to vite-plugin-ssr but that's something I usually only do for sponsors.

**Comment by Dennise89** [comment]
@brillout We can make a deal, if you help me debug this, I will become a sponsor. What amount are we talking about?

**Comment by brillout** [comment]
[Company sponsorship](https://github.com/sponsors/brillout), which starts at 200$ / month.

**Comment by Dennise89** [comment]
@brillout Ah okay, I can't afford that as I'm not making any money yet with my app/site.

**Comment by Dennise89** [comment]
@brillout I decided to stop using this middleware. Thanks for the effort though. Hope you get your goal of 5k a month.

**Comment by brillout** [comment]
Why did you decide against using vite-plugin-ssr?

**Comment by Dennise89** [comment]
@brillout because it’s not working on production for me and I don’t know how to fix it. It’s working fine locally, but on production it doesn’t.
And I’m not getting any help to fix it so that’s why I decided to go with another solution.

**Comment by brillout** [comment]
Again, if you provide a minimal reproduction (this can be a step-by-step guide) then I'll have a look at it.

I'm inclined to think it's unrelated to vite-plugin-ssr. As you can understand, I'm relunctant to provide help for user land issues that may very well end up having nothing to do with vite-plugin-ssr.

That's why I'm pushing for a minimal reproduction (/ minimal guide to reproduce).

**Comment by xyng** [comment]
Just to add should others come to this issue while migrating from Vite to Vike (this is the only issue I have found related to that port).
Check your vite config for `ssl`!

If you are using the express server given in the vike example, that does use plaintext.
So, Vite tries to ping via http. But since Vite runs with SSL enabled, the response is empty.

Removing ssl from the Vite config resolves the issue.
