### ISSUE TITLE
typescript error: `navigate` and `reload` are `never` 

### ISSUE THREAD

**Issue by samuelstroschein** [brillout/vite-plugin-ssr#1106]
### Description

Hi @brillout, 

The type casting below leads to an import error in our project:

https://github.com/brillout/vite-plugin-ssr/blob/64f684f8e8709b1e0fb8ae06570120b4291e72be/vite-plugin-ssr/node/client/router.ts#L7-L8

An import like the below leads to "This expression is not callable. Type `never` has no call signatures". Typescript imports the `never` cast. 

```ts
import { navigate } from "vite-plugin-ssr/client/router"
```
_See https://github.com/inlang/inlang/blob/22c4bb9fa7e04365640d828930e18cc8ef15a679/source-code/website/src/pages/editor/index.page.tsx#L3_

The source-code for the website and vite plugin ssr config can be found here https://github.com/inlang/inlang/tree/main/source-code/website

**Comment by brillout** [comment]
> "vite-plugin-ssr": "0.4.115"

Can you update to the latest version and try agin?

I'll re-open if you still get the error.

**Comment by samuelstroschein** [comment]
The bug occurs with VPS 0.4.120. 

Ups, wrong link. Development is happening on the [`armageddon` branch](https://github.com/inlang/inlang/tree/armageddon/source-code/website). VPS is updated to the latest version 0.4.120 on `armageddon`.

**Comment by brillout** [comment]
True latest version is 0.4.140
