### ISSUE TITLE
Error with loading module

### ISSUE THREAD

**Issue by mathiso** [brillout/vite-plugin-ssr#1108]
### Description

We get this error when trying to start our Vite SSR application in an Azure AppService with Windows environment. The error occured when upgrading from 0.4.131 to 0.4.140

Error: [vite-plugin-ssr@0.4.131][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Go to https://github.com/brillout/vite-plugin-ssr/issues/new and copy-paste this error. (The error's stack trace is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes vite-plugin-ssr more robust.at loadImportBuild (C:\home\site\wwwroot\node_modules\vite-plugin-ssr\dist\cjs\node\runtime\globalContext\loadImportBuild.js:16:28)at async initGlobalContext (C:\home\site\wwwroot\node_modules\vite-plugin-ssr\dist\cjs\node\runtime\globalContext.js:37:30)at async renderPage (C:\home\site\wwwroot\node_modules\vite-plugin-ssr\dist\cjs\node\runtime\renderPage.js:24:9)at async file:///C:/home/site/wwwroot/server.js:79:29

**Comment by brillout** [comment]
> The error occured when upgrading from 0.4.131 to 0.4.140

The error seem to suggest otherwise though:

> Error: [vite-plugin-ssr@0.4.131][Bug] You stumbled

Are you sure you're using 140? If yes, then I'll need a reproduction for that one.

**Comment by brillout** [comment]
Thanks for circling back on this. I'll have a look at how to improve the error message when this happens.

**Comment by brillout** [comment]
@mathiso Did you patch vite-plugin-ssr to suppress the following error about different versions being loaded?

https://github.com/brillout/vite-plugin-ssr/blob/9f547b82487fdd8199c5d7de89d0a33196c45d7f/vite-plugin-ssr/utils/assertSingleInstance.ts#L34-L37

You should have gotten that error and I can't think of a reason why you didn't.

Closing in the meantime.

**Comment by mathiso** [comment]
Yes, we did, thanks!

**Comment by brillout** [comment]
Thanks for the reply, good to know. It actually happened a couple of times already that users want/try to circumvent this limitation. Hopefully 3a66e952396b739bbedb6f8f8d7bac1d64026e90 will further discourage this practice.

Btw., would your company be up for [sponsoring](https://github.com/sponsors/brillout)? Sponsors makes a *massive* difference.
