### ISSUE TITLE
v1: The +config.h.js in different pages will be overwritten.

### ISSUE THREAD

**Issue by BlackCubeNo99** [brillout/vite-plugin-ssr#1109]
### Description

I have two pages, a and b. I created `+config.h.js` in their respective directories with the following structure:

```bash
├── pages
  ├── a
    ├── +Page.vue
    ├── +config.h.js
  ├── b
    ├── +Page.vue
    ├── +config.h.js
```

```js
// pages/a/+config.h.js
export dfeault {
  Layout,
  passToClient: ['pageProps', 'urlPathname'],
}
```

```js
// pages/b/+config.h.js
export dfeault {
  Layout,
}
```

My page b doesn't have the passToClient configuration, but after running it, I found that the passToClient configuration still exists.

**Comment by brillout** [comment]
That's surprising, can you create a little reproduction?

**Comment by BlackCubeNo99** [comment]
Thank you for your reply. After retesting, I found that if my pages are named `about` and `about2`, they will overwrite each other. Is this caused by the file routing matching logic?
