### ISSUE TITLE
Flexible page groups convention

### ISSUE THREAD

**Issue by flodlc** [brillout/vite-plugin-ssr#1113]
### Description

I'm using a custom implementation of Layouts based on the page config.
In some situations it could be useful to share a config value between a group of pages without impacting the route paths.

As I workaround I can use `pages` or `src` as the group folder name and have the shared config at the root of this folder.
But it's limited to 2/3 folder groups because of the name restriction and the names don't reflect the domain.

What would you think about a more flexible convention to ignore folder names from routing ?
Next use `(myFolder)` naming convention for pages groups. It could be good to follow this convention that feels natural.

Here is an exemple:

````
└── pages
        └── +page.tsx
        └── (auth)
                └── login
                        └── +page.tsx
                └── create-account
                         └── +page.tsx
                └ +config.ts
        └── (blog)
                └── page1
                        └── +page.tsx
                └── page2
                        └── +page.tsx
                 └ +config.ts
````

**Comment by brillout** [comment]
👍 I guess we can close this then. Although I do agree that there could be a simpler DX for simple use cases.

In case I didn't tell you already and your company is up for it: https://github.com/sponsors/brillout.
