### ISSUE TITLE
Vue SFC parsing error while mixing Local and Global Styles

### ISSUE THREAD

**Issue by mellester** [brillout/vite-plugin-ssr#112]
I ran into a issue with my vue setup.
Multiple single file component had a scoped style added too it see the [docs](https://vue-loader.vuejs.org/guide/scoped-css.html#mixing-local-and-global-styles) for a example.

This gave me a html parsing error on a div that looked like this.
`<div class="example" data-v-f3f3eg9 data-v-f3f3eg9>`
Basically a duplicate data attribute. because of the random nature of it I can not recreate a reproducible version of this

**Comment by brillout** [comment]
👍 Let me know if you manage to reproduce it.

**Comment by brillout** [comment]
Closing in the meantime. Let me know if you can reproduce.
