### ISSUE TITLE
File system routing only supports depth of 1 when app isn't at root

### ISSUE THREAD

**Issue by DreamwareDevelopment** [brillout/vite-plugin-ssr#1129]
### Description

I have a structure like so:

```
apps/
└── frontend/
    ├── src/
    │   ├── pages/
    │   │   ├── _default.page.route.tsx
    │   │   ├── index.page.client.tsx
    │   │   └── examples/
    │   │       ├── html_js/
    │   │       │   ├── index.page.server.tsx
    │   │       │   └── _default.page.client.tsx
    │   │       ├── html_only/
    │   │       │   └── index.page.server.tsx
    │   │       ├── spa/
    │   │       │   └── index.page.client.tsx
    │   │       └── ssr/
    │   │           └── index.page.tsx
    │   ├── renderer/
    │   │   ├── _default.page.server.tsx
    │   │   └── _default.page.client.tsx
    │   └── main.ts
    └── ...
```

_default.page.route.tsx:
`export const filesystemRoutingRoot = '/';`

Everything was working until I moved the individual page folders into the examples directory.

`{"manifestKeys":["_chunk-181d5f07.js","_chunk-4d04ce61.js","apps/frontend/src/pages/html_js/_default.page.client.tsx","apps/frontend/src/pages/html_js/index.page.server.tsx?extractAssets&lang.css","apps/frontend/src/pages/html_js/index.page.server.tsx?extractAssets&lang.tsx","apps/frontend/src/pages/html_only/index.page.server.tsx?extractAssets&lang.css","apps/frontend/src/pages/html_only/index.page.server.tsx?extractAssets&lang.tsx","apps/frontend/src/pages/index.page.client.tsx","apps/frontend/src/pages/ssr/index.page.css","apps/frontend/src/pages/ssr/index.page.tsx","apps/frontend/src/renderer/_default.page.client.tsx","apps/frontend/src/renderer/_default.page.server.tsx?extractAssets&lang.tsx","node_modules/vite-plugin-ssr/dist/esm/client/client-routing-runtime/entry.js","node_modules/vite-plugin-ssr/dist/esm/client/server-routing-runtime/entry.js"],"id":"/apps/frontend/src/pages/examples/ssr/index.page.tsx"}`

**Comment by DreamwareDevelopment** [comment]
When I tried the domain driven structure as documented:
```
apps
└── frontend
    └── src
        ├── auth
        │   └── pages
        │       ├── _default.page.route.tsx
        │       └── index.page.client.tsx
        ├── examples
        │   ├── pages
        │   │   ├── _default.page.route.tsx
        │   │   ├── html_js
        │   │   │   └── index.page.server.tsx
        │   │   ├── spa
        │   │   │   └── index.page.client.tsx
        │   │   └── ssr
        │   │       └── index.page.tsx
        ├── renderer
        │   ├── _default.page.client.tsx
        │   └── _default.page.server.tsx
        ├── server
        │   └── app.ts
        └── main.ts
```
auth/pages/_default.page.route.tsx:
`export const filesystemRoutingRoot = '/auth';`
examples/pages/_default.page.route.tsx:
`export const filesystemRoutingRoot = '/';`

I encountered the following:

`{"manifestKeys":["_chunk-181d5f07.js","_chunk-4d04ce61.js","apps/frontend/src/pages/html_js/_default.page.client.tsx","apps/frontend/src/pages/html_js/index.page.server.tsx?extractAssets&lang.css","apps/frontend/src/pages/html_js/index.page.server.tsx?extractAssets&lang.tsx","apps/frontend/src/pages/html_only/index.page.server.tsx?extractAssets&lang.css","apps/frontend/src/pages/html_only/index.page.server.tsx?extractAssets&lang.tsx","apps/frontend/src/pages/index.page.client.tsx","apps/frontend/src/pages/ssr/index.page.css","apps/frontend/src/pages/ssr/index.page.tsx","apps/frontend/src/renderer/_default.page.client.tsx","apps/frontend/src/renderer/_default.page.server.tsx?extractAssets&lang.tsx","node_modules/vite-plugin-ssr/dist/esm/client/client-routing-runtime/entry.js","node_modules/vite-plugin-ssr/dist/esm/client/server-routing-runtime/entry.js"],"id":"/apps/frontend/src/examples/pages/ssr/index.page.tsx"}`

**Comment by DreamwareDevelopment** [comment]
Here's the interesting bit, I just confirmed that both of these work when using Vite's dev server which I spin up like so:
```
/// <reference types="vite/client" />

import 'dotenv/config';
import Fastify from 'fastify';
import httpDevServer from 'vavite/http-dev-server';
import { app } from './server/app';
import FastifyStatic from '@fastify/static';
import { fileURLToPath } from 'url';
import { AddressInfo } from 'net';

const port = process.env.FRONTEND_SERVER_PORT ? Number(process.env.FRONTEND_SERVER_PORT) : 3000;
export const isProduction = process.env.NODE_ENV === 'production';

async function startServer() {
  const fastify = Fastify({
		trustProxy: true,
		serverFactory: httpDevServer
		? (handler) => {
			// eslint-disable-next-line @typescript-eslint/no-non-null-assertion
				httpDevServer!.on("request", handler);
				// eslint-disable-next-line @typescript-eslint/no-non-null-assertion
				return httpDevServer!;
		  }
		: undefined,
    logger: true,
  });

	if (isProduction) {
		// Path only exists in production
    const url = new URL("../client/assets", import.meta.url);
		await fastify.register(FastifyStatic, {
			root: fileURLToPath(url),
			prefix: "/assets/",
		});
	}
  fastify.register(app);

  if (httpDevServer) {
		// Fastify insists on calling listen itself.
		// devServer ignores listen calls but calls the callback.
		fastify
			.listen({ port: (httpDevServer.address() as AddressInfo).port })
			.catch(err => {
				console.error(err);
				process.exit(1);
			});
	} else {
		console.log("Starting prod server");
		fastify.listen({ port, host: '0.0.0.0' }).catch(err => {
			console.error(err);
			process.exit(1);
		});
	}
}

startServer().catch(err => {
	console.error(err);
	process.exit(1);
});
```

**Comment by DreamwareDevelopment** [comment]
*sighs exhaustedly* it wasn't a problem with the plugin. But a problem with my build system. I was only building half of the application due to the "--ssr" flag. So I suspect that when vite-plugin-ssr had the updated server build and looked for the client files in their new locations, it didn't find them because the client build was never getting updated. I didn't find this until I gave up on the above issue and started writing frontend code and noticed I wasn't getting updates in my production environment. I'll close this issue, but @brillout I think the error message here could be less opaque. A miss on a file is better than just saying "there's a bug".

**Comment by brillout** [comment]
I'm glad you resolved your issue.

I agree that error messages should be helpful (whenever possible). Copy-paste the full error message and its stack trace and I'll have a look at it (even better would be a minimal reproduction as it isn't clear to me how you got into that situation).

Let me know if you believe there is something vite-plugin-ssr could have helped you with beyond a nicer error message.

Btw. is [sponsoring](https://github.com/sponsors/brillout) something your company would be up for?

**Comment by DreamwareDevelopment** [comment]
Yeah I moved on past it. Iirc the function at the top of the stack was getManifest. And as we discussed on discord, I'm not in a financial situation to be able to sponsor the project at this time. But that could change soon!

**Comment by brillout** [comment]
👍
