### ISSUE TITLE
Internal assert() failed (v0.1.2)

### ISSUE THREAD

**Issue by bob057** [brillout/vite-plugin-ssr#113]
I encountered this bug:

Uncaught (in promise) Error: [vite-plugin-ssr@0.1.2][Internal Failure] You stumbled upon a bug in `vite-plugin-ssr`'s source code (an internal `assert()` failed). This should definitely not be happening, and you should create a new issue at https://github.com/brillout/vite-plugin-ssr/issues/new that includes this error stack (the error stack is usually enough to debug internal errors). Or reach out on Discord. A fix will be written promptly. Debug info: `{"pageId":"/ssr/pages/resetMailConfirmation","pageFilePaths":["/ssr/pages/account.page.vue","/ssr/pages/login.page.vue","/ssr/pages/mailsent.page.vue","/ssr/pages/resetpassword.page.vue","/ssr/pages/_error.page.vue","/ssr/pages/about/index.page.vue","/ssr/pages/index/index.page.vue","/ssr/pages/marketer/index.page.vue","/ssr/pages/projects/index.page.vue"]}` (the debug info is for the `vite-plugin-ssr` maintainers; you can ignore this).
    at newError2 (newError.ts:18)
    at assert (assert.ts:23)
    at getPageFile (getPageFiles.shared.ts:62)
    at async getPageById (getPage.client.ts:33)
    at async getPage (getPage.client.ts:15)
    at async hydrate (_default.page.client.js:6)

**Comment by brillout** [comment]
It's the same error than https://github.com/brillout/vite-plugin-ssr/issues/104 and https://github.com/brillout/vite-plugin-ssr/issues/108.

Can you publish a reproduction?

**Comment by bob057** [comment]
Sorry, I looked over it. Don't know how to reproduce it correctly

**Comment by brillout** [comment]
No worries.

Let me know if you can find a way to reproduce this.

Also let me know if it starts to become too annoying.
