### ISSUE TITLE
Guard doesn't appear to work for multiple files.

### ISSUE THREAD

**Issue by DreamwareDevelopment** [brillout/vite-plugin-ssr#1138]
### Description

Hi! I'm just building the redirect logic of trying to access a page behind login without being authenticated. I got it working by putting the guard statement in the same location as each page (duplicating files), however, applying guard to multiple pages from either the /pages/index.page.route.ts root or /pages/admin/index.pages.ts doesn't work as documented. Maybe this functionality isn't under test and broke at some point?

**Comment by DreamwareDevelopment** [comment]
Accidentally made as enhancement and not bug, sorry @brillout

**Comment by brillout** [comment]
Make sure to update to the latest version: there was a patch about this recently.

Closing but let me know if you still run into issues and I'll then re-open.

**Comment by Bob-Jung** [comment]
It still doesn't seem to work. @brillout

**Comment by brillout** [comment]
@Bob-Jung Yes that's a 0.4 design limitation: is upgrading to the V1 design an option for you? (It's going to be officially released very soon.)
