### ISSUE TITLE
A version of the default vue starter template from vite-plugin-ssr that uses @small-tech/https for automatic TLS 

### ISSUE THREAD

**Issue by aral** [brillout/vite-plugin-ssr#117]
Hey Romuald,

I was just playing with the vue starter template and managed to add automatic TLS (both during dev and production) to it with two dependencies and four lines of code. Thought you might find it interesting. Shared it here:

https://github.com/aral/vite-plugin-ssr-with-tls

And here’s a direct link to a patch so you can see exactly what (and how little) has changed at a glance:

https://github.com/aral/vite-plugin-ssr-with-tls#patch

Enjoy + thank you for this lovely (and so easily extensible) tool.

**Comment by brillout** [comment]
Hey Aral,

Neat!

I've added your example to the list of community examples, see the newly updated [readme](https://github.com/brillout/vite-plugin-ssr#readme).

Rom :-)

**Comment by aral** [comment]
Oh, neat, thanks :)
