### ISSUE TITLE
In the docs the Windi CSS integration guide is called Tailwind CSS

### ISSUE THREAD

**Issue by SpeeedWagon** [brillout/vite-plugin-ssr#119]
[link to problem](https://vite-plugin-ssr.com/tailwind-css)

**Comment by brillout** [comment]
Windi CSS is fully compatible with Tailwind CSS v2 - is there a reason you want to use Tailwind CSS instead of Windi CSS?

**Comment by SpeeedWagon** [comment]
Personally I was confused a little bit by the naming, Tailwind CSS has a different installation process  than Windi CSS.
For me Tailwind CSS works best because of the Tailwind UI components, very easy to start a project with it

**Comment by brillout** [comment]
That makes a lot of sense, I updated the docs https://vite-plugin-ssr.com/tailwind-css.

Let me know if you object with anything (else).

Thanks for open this ticket.
