### ISSUE TITLE
Favicon Error!

### ISSUE THREAD

**Issue by folamy** [brillout/vite-plugin-ssr#121]
Hello @brillout, I am really impressed by progress of this project. Well done sir!

So, I cloned git@github.com:brillout/vite-plugin-ssr, and everything seems to work well so far. However, I am getting a error on the console concerning favicon.ico
Please, how do I resolve this?

**Comment by folamy** [comment]
Fixed!
I had to clear my browser history.

**Comment by brillout** [comment]
👍
