### ISSUE TITLE
.tsx/.jsx files require React in scope: ReferenceError: React is not defined

### ISSUE THREAD

**Issue by bnn1** [brillout/vite-plugin-ssr#124]
Hello.  

**The problem**:  
jsx containing files require `React` (`import React from 'react'`) to be in scope.  
As I know react doesn't require `React` to be in scope since version 17 (see https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html).  

**Steps to reproduce**:  
1. Bootstrap a new project with `yarn create vite-plugin-ssr`
2. Select `react` or `react-ts` as a template
3. Run dev server: `yarn dev`
3. Remove `import React from 'react'` from either pages or components
4. Open `http://localhost:3000`

**Expected behavior**:  
App loads without errors  

**Actual behavior**:  
`ReferenceError: React is not defined` is thrown.  

Any clue?

**Comment by brillout** [comment]
There is work-in-progress on Vite's side to support the new JSX transformer.

In the meantime just include `import React from 'react'` in your files.

Let me know if you have other questions.
