### ISSUE TITLE
[devalue: Cannot stringify a function] Can't get dynamic component tree to SSR properly

### ISSUE THREAD

**Issue by CanRau** [brillout/vite-plugin-ssr#127]
Hey there,

First of all, I'm sorry that I have to open this issue here, I'm quite new to SSR and it's probably possible to find my answers somewhere somehow, though I'm already pretty stressed out as I don't understand what's going wrong and that I don't understand it 🤯😅

So I'm trying to render the following JSON
```json
{
  "title": "CanRau.com Homepage",
  "content": [
    {
      "component": "section",
      "props": {
        "className": "bg-nord1 mx-auto pt-2 text-nord5",
        "key": "indexSection"
      },
      "children": [
        {
          "component": "Hero",             <-- Here lies the problem
          "props": {
            "className": "bg-primary",
            "key": "indexHero"
          }
        },
        {
          "component": "h1",
          "props": {
            "className": "bg-red",
            "key": "indexH1"
          },
          "children": "H1"
        }
      ]
    }
  ]
}
```
Everything works fine until I introduce custom components like `"component": "Hero"` which will be replaced with a, well, custom component.

This is the code to dynamically render the tree

```js
const renderDynamicComponents = (tree, components) =>
  tree.map((item, index) => {
    if (!item.component) return item;

    const Comp = item.component;
    const props = item.props ?? {};

    if (!props?.key) {
      throw new Error(
        `Component is missing a unique 'key' for ${console.log(
          JSON.stringify({ index, component: Comp })
        )}`
      );
    }

    if (item.children !== undefined) {
      if (typeof item.children === "string") {
        props.children = item.children;
      } else if (Array.isArray(item.children)) {
        props.children = renderDynamicComponents(item.children, components);
      }
    }

    if (components?.[Comp] !== undefined) {
      return createElement(components[Comp], props);
    }

    return createElement(Comp, props);
  });
```

which sadly throws

```
Error: Cannot stringify a function
    at walk ([..]/node_modules/devalue/dist/devalue.umd.js:29:20)
```

I thought I figured a solution by only running `renderDynamicComponents` on the client, then I realized that that's defeating the purpose of SSR tho 🤦🏻‍♂️

### My problem
I don't fully understand why this is happening, when I
```
// ..
props.children = renderDynamicComponents(item.children, components);
console.log(props.children);
// ..
```
I get: 
```js
{
    '$$typeof': Symbol(react.element),
    type: [Function: HeroComponent],          <--- this is most probably the issue, right?
    key: 'indexHero',
    ref: null,
    props: { className: 'bg-primary' },
    _owner: null,
    _store: {}
  },
  {
    '$$typeof': Symbol(react.element),
    type: 'h1',
    key: 'indexH1',
    ref: null,
    props: { className: 'bg-red', children: 'H1' },
    _owner: null,
    _store: {}
  }
```

Thought I'm smart again, for a split second, trying to `HeroComponent.prototype.toString = () => "hero";`, though nothing 🥲

What can I do about this, what options do I have?
The example JSON will be coming from my CMS, I thought about using MDX instead though I'd highly prefer less abstraction, as it's machine handled and edited using the CMS's UI anyway.

Please help 🥺

**Comment by brillout** [comment]
Let me have a look

**Comment by brillout** [comment]
You should `passToClient` the JSON and not Vue components. You cannot serialize and cannot `passToClient` Vue components.

So make sure you transform your JSON two times: one time on the server side (e.g. in your `render()` hook), and another time in the browser-side (in your `_default.page.client.js`).

**Comment by CanRau** [comment]
Thank you for taking the time 🙏

I'm using `React`, sorry for not mentioning, and am not sure I fully understand what you're saying.

Initially I ran `renderDynamicComponents` within `index.page.tsx`'s `export const Page`'s `return` now I'm doing it within `_default.page.server.tsx` `render()`

```
const pageHtml = ReactDOMServer.renderToString(
    <PageLayout>
      <Page {...pageProps}>
        {renderDynamicComponents(pageProps?.file?.content, components, true)}
      </Page>
    </PageLayout>
  );
```

and `index.page.client.tsx`
```
async function hydrate() {
  const pageContext = await getPage();
  const { Page, pageProps } = pageContext;

  ReactDOM.hydrate(
    <PageLayout>
      <Page {...pageProps}>
        {renderDynamicComponents(pageProps.file.content, components, true)}
      </Page>
    </PageLayout>,
    document.getElementById("page-view")
  );
}
```

**Comment by brillout** [comment]
Hm seems like it should work.

The bottom line is that one of your `pageContext.prop` cannot be serialized. Find out which one it is.

What is the entire stack trace of following error?
```
Error: Cannot stringify a function
    at walk ([..]/node_modules/devalue/dist/devalue.umd.js:29:20)
```

**Comment by CanRau** [comment]
> The bottom line is that one of your pageContext.prop cannot be serialized. Find out which one it is.

I'll try and have a look

```
Error: Cannot stringify a function
    at walk ([..]/node_modules/devalue/dist/devalue.umd.js:29:20)
    at [..]/node_modules/devalue/dist/devalue.umd.js:62:73
    at Array.forEach (<anonymous>)
    at walk ([..]/node_modules/devalue/dist/devalue.umd.js:62:41)
    at Array.forEach (<anonymous>)
    at walk ([..]/node_modules/devalue/dist/devalue.umd.js:46:28)
    at [..]/node_modules/devalue/dist/devalue.umd.js:62:73
    at Array.forEach (<anonymous>)
    at walk ([..]/node_modules/devalue/dist/devalue.umd.js:62:41)
    at [..]/node_modules/devalue/dist/devalue.umd.js:62:73
```

**Comment by brillout** [comment]
You can try `JSON.stringify(pageContext.pageProps)` and see if that chokes.

**Comment by CanRau** [comment]
> You can try `JSON.stringify(pageContext.pageProps)` and see if that chokes.

Where should I do this?

Interesting I just deferred the `JSON.parse` from `index.page.server.ts` to `_default.page.server.tsx` and `index.page.client.tsx`, so sending the raw string to pageProps and now it seems to work 🥳
I'm kinda hesitant as I already thought I found a solution couple of times 😅🤣

**Comment by brillout** [comment]
Also a *full* devalue error stack trace would help tell if the error does originate from `vite-plugin-ssr`. Add this at the begenning of your server code:

```
Error.stackTraceLimit = Infinity;
```

**Comment by brillout** [comment]
Ok neat 👍 

> I'm already pretty stressed out 

Bugs are always fixable after enough digging. Always.

**Comment by CanRau** [comment]
> Bugs are always fixable after enough digging. Always.

Definitely true that, though sometimes a "[rubber ducking](https://en.wikipedia.org/wiki/Rubber_duck_debugging)" can do wonders 🐣😇 
So thanks for your very valuable input and again for this amazing peace of software 🤩🙏


> Error.stackTraceLimit = Infinity;

For reference, this is the full stack trace
```
Error: Cannot stringify a function
    at walk ([..]/node_modules/devalue/dist/devalue.umd.js:29:20)
    at [..]/node_modules/devalue/dist/devalue.umd.js:62:73
    at Array.forEach (<anonymous>)
    at walk ([..]/node_modules/devalue/dist/devalue.umd.js:62:41)
    at Array.forEach (<anonymous>)
    at walk ([..]/node_modules/devalue/dist/devalue.umd.js:46:28)
    at [..]/node_modules/devalue/dist/devalue.umd.js:62:73
    at Array.forEach (<anonymous>)
    at walk ([..]/node_modules/devalue/dist/devalue.umd.js:62:41)
    at [..]/node_modules/devalue/dist/devalue.umd.js:62:73
    at Array.forEach (<anonymous>)
    at walk ([..]/node_modules/devalue/dist/devalue.umd.js:62:41)
    at Array.forEach (<anonymous>)
    at walk ([..]/node_modules/devalue/dist/devalue.umd.js:46:28)
    at [..]/node_modules/devalue/dist/devalue.umd.js:62:73
    at Array.forEach (<anonymous>)
    at walk ([..]/node_modules/devalue/dist/devalue.umd.js:62:41)
    at [..]/node_modules/devalue/dist/devalue.umd.js:62:73
    at Array.forEach (<anonymous>)
    at walk ([..]/node_modules/devalue/dist/devalue.umd.js:62:41)
    at [..]/node_modules/devalue/dist/devalue.umd.js:62:73
    at Array.forEach (<anonymous>)
    at walk ([..]/node_modules/devalue/dist/devalue.umd.js:62:41)
    at Object.devalue ([..]/node_modules/devalue/dist/devalue.umd.js:66:6)
    at injectPageInfo ([..]/node_modules/vite-plugin-ssr/html/injectAssets.node.ts:209:40)
    at Object.injectAssets_internal ([..]/node_modules/vite-plugin-ssr/html/injectAssets.node.ts:162:16)
    at executeRenderHook ([..]/node_modules/vite-plugin-ssr/renderPage.node.ts:552:20)
    at renderPageId ([..]/node_modules/vite-plugin-ssr/renderPage.node.ts:169:26)
    at renderPage ([..]/node_modules/vite-plugin-ssr/renderPage.node.ts:131:20)
    at [..]/server/index.ts:50:20
```

**Comment by brillout** [comment]
Thanks :-).

Have fun building ;-).

**Comment by brillout** [comment]
It will now tell you which prop it is that cannot be serialized.

**Comment by CanRau** [comment]
😍 sounds fantastic 👌

Romuald Brillout ***@***.***> schrieb am Fr., 6. Aug. 2021,
05:52:
