### ISSUE TITLE
prerender --no-extra-dir [ERR_REQUIRE_ESM]

### ISSUE THREAD

**Issue by mdtomo** [brillout/vite-plugin-ssr#131]
The `--no-extra-dir` option for prerender raises the following error with example/vue-full with `vite-plugin-ssr prerender --no-extra-dir` 

`Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\Users\Documents\projects\test\node_modules\node-fetch\src\index.js
require() of ES modules is not supported.
require() of C:\Users\Documents\projects\test\node_modules\node-fetch\src\index.js from C:\Users\Documents\projects\test\dist\server\assets\index.page.server.ad9be3fc.js is an ES 
module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\Users\Documents\projects\test\node_modules\node-fetch\package.json.`

It makes sense that the server rendered code would use commonJS to load modules so I'm not sure what the work around is?

**Comment by brillout** [comment]
Let me have a look

**Comment by brillout** [comment]
I couldn't reproduce.

Note that if you use the beta version of `node-fetch` then downgrading the the stable version will likely solve the problem. (The `node-fetch` beta in general has still many known bugs.)

Or help me reproduce your error I'll dig deeper into what caused the error.

**Comment by mdtomo** [comment]
You're correct it's a bug in node-fetch. I was using version node-fetch 3.0.0-beta.9. I switched to version 2.6.1 and it's working as expected. Thanks!
