### ISSUE TITLE
Prerender concurrency

### ISSUE THREAD

**Issue by gryphonmyers** [brillout/vite-plugin-ssr#134]
Similar to https://github.com/brillout/vite-plugin-ssr/issues/59

With a large site and/or large pageContext payloads, it is increasingly possible to exhaust build machine's RAM. If prerender jobs were chunked (making sure to flush each job's memory usage upon completion), this issue could be mitigated. Concurrency as a configurable option would allow for this to be tuned to the site's resource consumption and build machine's resource limits.

**Comment by brillout** [comment]
Ideally there would be an option `` --parallel `number` `` that defaults to the number of CPU cores.

For now we can make the central loop sequential and let's see how it goes.

https://github.com/brillout/vite-plugin-ssr/blob/99318439b5282bce81e845b7ea6f4ceec11565a2/vite-plugin-ssr/node/prerender.ts#L150-L151

Thoughts?

I'd finish some changes to the docs before I implement this but feel free to take a stab at it.

**Comment by brillout** [comment]
New option `--parallel` released in `0.2.10`.

**Comment by brillout** [comment]
Little fix release in `0.2.11`.

Let me know if you can manage to resolve your mem issues with `--parallel 1`. Also note that the default behavior is now more mem friendly; so also try without using `--parallel` at all.
