### ISSUE TITLE
Rename createPageRender() to createPageRenderer()

### ISSUE THREAD

**Issue by orenelbaum** [brillout/vite-plugin-ssr#135]
createPageRender sounds like the function actually renders the page, but it returns a renderer, so I think that it should be renamed.

**Comment by brillout** [comment]
You're right. Other names that you believe should be changed?

**Comment by orenelbaum** [comment]
I'll take another look at the API to see if I can find any.

**Comment by brillout** [comment]
👌

**Comment by orenelbaum** [comment]
Ok so these are the ones I found:
- `addPageContext()` ⇒ `addToPageContext()`
- `html()` ⇒ `sanitizeHtml()`
- `pageContext.routeParams` ⇒ `pageContext.queryParms `(or `pageContext.pathParams`)
- route string ⇒ path string ? (not sure about this one)
- In the docs replace the term "route parameters" with "path parameters"
- pageContext.urlNormalized ⇒ pageContext.normalizedUrl
- pageContext.urlParsed ⇒ pageContext.parsedUrl

In NextJS `pageContext.routeParams` is `useRouter().query`. They also refer to them in the docs as path parameters (in the path regex), and query parameters (in the actual request once the values are populated).
In React Router they use `useParams()` and in the docs they call them URL parameters. I'm not a fan of this naming cause it's too vauge.

As to `pageContext.urlNormalized` vs `pageContext.normalizedUrl` I can see the reasoning behind both so this is a bit more of a personal opinion. I think that `normalizedUrl` is a bit more beginner friendly.

Other things that are confusing but are not related to naming:

- [The `.page.client.js` page](https://vite-plugin-ssr.com/.page.client.js):
The example is not very clear to me. I'm not sure what the API is here and it doesn't export anything.

- Default template: the scripts in `package.json` are a bit confusing and messy with the naming.

**Comment by brillout** [comment]
> Default template: the scripts in package.json are a bit confusing and messy with the naming.

I understand it's confusing at first but it's actually quite convenient to have fine grain scripts over the different steps of dev & prod. I use these all the time and I expect users to also end up using it all the time.

> The example is not very clear to me. I'm not sure what the API is here and it doesn't export anything.

Good point, I updated the example. I hope it's clearer now. https://vite-plugin-ssr.com/.page.client.js

> The only one of these that really bugs me and I really think should be changed is addPageContext.

`addPageContext` is to be understand as "add further page context" and not as "add soemthing to the page context object". If you think "pageContext" as the `pageContext` object then I agree that `addToPageContext` is better. If you think "pageContext" as the high-level concept of a page's context, then I prefer `addPageContext`.

As for the routing names, the whole documentation reolves around the terminology of "routing". It's a conscious decision on my part to go all-in with the terminology "routing". Makes things clearer in the long haul.

The other propsed changed are fairly minor, I'm not sure they justify introducing a breaking change.

I do definitely agree that `createPageRenderer` is better. Breaking change is justified here. I'll do it at the appropriate moment.

**Comment by orenelbaum** [comment]
I understood the idea with `addPageContext` after I wrote this comment, but I think that it's really confusing and it sounds like you're adding a new context object. Maybe it doesn't confuse people who are used to this kind of naming but again it confused me and I think that it will confuse beginners.
And as for routing I think that the current names are fine but they could be more specific. I think that using only the term router maybe makes things more clear if I already know that this is the naming style, but looking at the names for the first time `routeParams` is not 100% clear, you would think that it's probably the values provided to the path parameters but it could also mean other things. with `queryPathParams` it's 100% clear the first time you see it cause it can't mean anything else.
However I don't think that any of these are really important and maybe they don't justify breaking changes (although maybe they could be alternate names?)
I'm however not so sure about the `html` function. I read some of the comments in this [issue](https://github.com/brillout/vite-plugin-ssr/issues/92) and I'm not sure if `html` also injects scripts automatically? This was really confusing for me the first time I saw this as the naming doesn't say anything about what the function is doing, and even the docs don't say anything about script injection. I'm not sure if it would be worth it to change it into a long name like `sanitizeHtmlAndInjectScripts` or  maybe something like `prepareHtml`. Maybe in that case it could be nice to have an alternative name and use it in the docs and templates so they can be more accessible to beginners without reading all of the docs, cause there are a lot of them.

**Comment by brillout** [comment]
> Maybe it doesn't confuse people who are used to this kind of naming but again it confused me and I think that it will confuse beginners.

Ok that's good to know.

I'm actually probably going to rename `addPageContext` to `onBeforeRender`.

> with `queryPathParams` it's 100% clear the first time you see it cause it can't mean anything else

The problem with that name is that it's actually misnommer: query parameters usually denote something else.

The query is the set of key-value pairs that go after the `?` in a URL, separated by `&` characters.

For example, in the URL: `http://127.0.0.1:8000/items/?skip=0&limit=10`.

As for `html`, it's common to name string template tags to what they represent.

```ts
const someJsxString = jsx`
<>
  <h1>Hello</h1>
  <p>
    World.
  <p>
</>`;

const someHtmlString = html`
<!DOCTYPE html>
<html>
  <body>
    Hello world.
  </body>
</html>`;
```

Although I do agree it's not ideal that it's not clear what `html` does exactly.

**Comment by orenelbaum** [comment]
> > with `queryPathParams` it's 100% clear the first time you see it cause it can't mean anything else
> 
> The problem with that name is that it's actually misnommer: query parameters usually denote something else.

Yeah I agree that it could be confused with the query string. But that's why I added 'path', I feel like with 'path' in the name it's clear that it's not the query string. But it's probably an overkill, `routeParams` is clear enough.

Anyway, I brought to your attention all the names that I thought maybe should be changed, so I'm closing the issue.

**Comment by brillout** [comment]
👍 And thanks for your input.

I'm leaving the ticket open for `createPageRenderer`.

**Comment by brillout** [comment]
I'm going to rename `html` to `sanitize` and `dangerouslySkipEscape` to `dangerouslySkipSanitize`.

You're right, it's clearer. I've seen people being confused.

**Comment by orenelbaum** [comment]
Awesome!

**Comment by brillout** [comment]
It actually doesn't inject scripts. So I guess `sanitize` is quite appropriate here.

**Comment by orenelbaum** [comment]
Oh alright. So `sanitize` would be good.

**Comment by brillout** [comment]
Done. I went for `escapeInject`; it's ugly but clear.

Thank you for your feedback ❤️.
