### ISSUE TITLE
Can't get it working with Pulumi

### ISSUE THREAD

**Issue by CanRau** [brillout/vite-plugin-ssr#137]
So I'm trying to deploy to AWS Lambda using [Pulumi](https://www.pulumi.com/), I'm not sure, it might be a Pulumi bundling issue, though before I hadn't issues with that.

I've got a separate `./server/lambda.ts` which includes `import "../dist/server/importBuild";`
And as `importBuild` includes `const { __private: { importBuild } } = require("vite-plugin-ssr")` it should import `vite-plugin-ssr/dist/cjs/index.js` or am I missing some additional Typescript config? I've added `"esModuleInterop": true,` with no change

Here's the full error I get when testing the Lambda via AWS Console:
```
{
  "errorType": "Error",
  "errorMessage": "Cannot find module 'vite-plugin-ssr/dist/cjs/index.js'\nRequire stack:\n- /var/task/__index.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
  "trace": [
    "Error: Cannot find module 'vite-plugin-ssr/dist/cjs/index.js'",
    "Require stack:",
    "- /var/task/__index.js",
    "- /var/runtime/UserFunction.js",
    "- /var/runtime/index.js",
    "    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:745:27)",
    "    at Module.require (internal/modules/cjs/loader.js:961:19)",
    "    at require (internal/modules/cjs/helpers.js:92:18)",
    "    at /var/task/__index.js:48:73",
    "    at Runtime.__f1 [as handler] (/var/task/__index.js:120:6)",
    "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
  ]
}
```

**Update:** just updated `vite-plugin-ssr` from `0.2.3` to `0.2.9` and `vite` from `2.4.2` to `2.5.0` without any luck

**Comment by jamesladd** [comment]
Hi CanRau,
I have AWS Lambda serving my project with Vite and vite-ssr-plugin.
I'm using serverless.com and have a YML I can share.
The key part is this I think:

> functions:
  app:
    handler: sls/index.handler
    events:
      - http:
          path: /
          method: any
      - http:
          path: /{proxy+}
          method: any

My sls/index.handler looks like this (almost the same as the vite-ssr-plugin example:

`
const serverless = require('serverless-http')
const express = require('express')
const { createPageRender } = require('vite-plugin-ssr')

const isProduction = true
const base = '/foo/'
const root = `${__dirname}/..`

const app = express()
app.use(express.static(`${root}/dist/client`, { index: false }))

let viteDevServer
const renderPage = createPageRender({ viteDevServer, isProduction, root, base })
app.get('*', async (req, res, next) => {
  const url = req.originalUrl
  console.log('url', base, url)
  const pageContext = { url }
  const result = await renderPage(pageContext)
  if (result.nothingRendered) return next()
  res.status(result.statusCode).send(result.renderResult)
})
module.exports.handler = serverless(app)
`
Happy to share a zip etc and get you going.
Maybe you can help me with an issue where I can't get the plugin to reference a base path correctly?

**Comment by jamesladd** [comment]
Ah, got it all working with minimal fuss. 
Happy to share.

**Comment by brillout** [comment]
@CanRau What's your Node.js version? I suspect you are using an older version.

**Comment by brillout** [comment]
> just updated vite-plugin-ssr from 0.2.3 to 0.2.9

The error then chagned to `Error: Cannot find module 'vite-plugin-ssr/dist/cjs/node/index.js` correct? (Note the additional `node/` in the path.)

Where does `node_modules/vite-plugin-ssr/` live in comparison to `server/lambda.ts` and `dist/server/importBuild.js`?

**Comment by CanRau** [comment]
Hey thanks for taking the time 🙏

The error stays actually the same, right didn't notice the additional /node 🤔

It's:

./package.json
./node_modules
./server/lambda.ts
./dist/server/
So it's basically the default folder structure if I'm not mistaken.

So I import `import "../dist/server/importBuild";` like in the examples.

**Comment by brillout** [comment]
This doesn't seem to be related to vite-plugin-ssr.

The error

>  "Cannot find module 'vite-plugin-ssr/dist/cjs/node/index.js'

contradicts the fact that the file `node_modules/vite-plugin-ssr/dist/cjs/node/index.js` does exist.

Something's wrong with the Pulumi environment. I'd open a GitHub issue over there.

You can try to `require('vite-plugin-ssr')` directly in your `lambda.ts` and see if it works. I'd investigate in that direction.

**Comment by brillout** [comment]
@CanRau Any news on this?

**Comment by CanRau** [comment]
Nope not really https://github.com/pulumi/pulumi-aws/issues/1608

Also I'm currently evaluating switching to Deno which so far looks pretty promising as to my liking 😇

**Comment by brillout** [comment]
Okay. I guess we can close this since it's more about pulimi than vite-plugin-ssr.

> switching to Deno

👍 Deno is exciting. What's your stack atm with Deno?

**Comment by CanRau** [comment]
Playing around with my own stack at the moment, going to share on Twitter when I deploy and plan to share tutorials and probably boilerplates/starters
So far it's pretty basic though, no HMR etc

alephjs.org looks interesting though

**Comment by brillout** [comment]
Neat. Ping me when there's something published. I'm curious.

I really like Deno but I'm a bit worried about the ecosystem being a lot smaller over there. Thoughts?
