### ISSUE TITLE
HTML Streaming

### ISSUE THREAD

**Issue by brillout** [brillout/vite-plugin-ssr#138]
> Here's one example of using `renderToNodeStream`
> 
> https://github.com/GoogleChromeLabs/progressive-rendering-frameworks-samples/blob/82ccd045264753c11966c59bb63dcba76b8b9f5c/react-streaming-ssr/server.js#L83-L113
> 
> What sticks out to me in that example is the [the first write](https://github.com/GoogleChromeLabs/progressive-rendering-frameworks-samples/blob/82ccd045264753c11966c59bb63dcba76b8b9f5c/react-streaming-ssr/server.js#L98) includes the `<head>` assets

Should be possible to do the same by using `pageContext._pageAssets` instead of `html._injectAssets()`.

@jfsiii
@lukasluecke
@orenelbaum

**Comment by OfekA** [comment]
@brillout Do you think this rendering strategy could work with `vite-plugin-ssr`?

**Comment by brillout** [comment]
@OfekA Yes it should work. See the CF workers example and return the stream in `render()` instead of returning an HTML string.

**Comment by OfekA** [comment]
@brillout I've managed to use `renderToNodeStream` with `express` to stream the app, but what I'm having difficulties with is sending the wrapping HTML for the app with the page assets.

Any chance you can make an example for it?

**Comment by brillout** [comment]
I'm thinking about implementing a new built-in functionallity:

```js
escapeInject`<!DOCTYPE HTML>
  <html>
    <head>
    </head>
    <body>
      <div id="app">${injectStream(appHtmlStream)}</div>
    </body>
  </html>`
```
(`html` is renamed `escapeInject` in the upcoming `0.3.0` version).

The plugin would then automatically inject the assets.

In the meantime you can do this:

```js
// Note how div#app is empty
const htmlWrapper = html.injectAssets(`<!DOCTYPE HTML>
  <html>
    <head>
    </head>
    <body>
      <div id="app"></div>
    </body>
  </html>`)

const parts = htmlWrapper.split('<div id="app"></div>')

const streamBegin = parts[0] + '<div id="app">'
const streamEnd = '</div>' + parts[1]

// We can now construct the stream ourself
```

**Comment by OfekA** [comment]
Thanks @brillout! I think the `injectStream` API will make things a lot easier, especially after the changes in 3.0+

**Comment by brillout** [comment]
@OfekA I started working on it

**Comment by brillout** [comment]
https://github.com/brillout/vite-plugin-ssr/blob/f0c799852e34e965772ac66b952b6d5d08b9c825/examples/react-full/renderer/_default.page.server.tsx#L16
https://github.com/brillout/vite-plugin-ssr/blob/f0c799852e34e965772ac66b952b6d5d08b9c825/examples/react-full/renderer/_default.page.server.tsx#L30
https://github.com/brillout/vite-plugin-ssr/blob/f0c799852e34e965772ac66b952b6d5d08b9c825/examples/react-full/server/index.ts#L34-L35

I will also implement a CF workers Vue HTML streaming example.

**Comment by brillout** [comment]
Docs at https://vite-plugin-ssr.com/html-streaming

**Comment by OfekA** [comment]
@brillout I've been testing out the new streaming feature, trying to delay rendering until some promise(s) resolve. 

A simple example:

```vue
// index.page.vue
<template>
  <div>
    {{ lazyload }}
  </div>
</template>

<script lang="ts">
export default {
  async setup() {
    await delay(5000)
    const lazyload = 'lazyload'
    return { lazyload }
  }
}

function delay(delayInms: number) {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(2)
    }, delayInms)
  })
}
</script>
```

But when running this I get the following error:
```bash
Error [ERR_METHOD_NOT_IMPLEMENTED]: The _read() method is not implemented
    at Readable._read (internal/streams/readable.js:623:9)
    at Readable.read (internal/streams/readable.js:462:10)
    at maybeReadMore_ (internal/streams/readable.js:610:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 'ERR_METHOD_NOT_IMPLEMENTED'
}
error Command failed with exit code 1.
```

Any idea what I'm doing wrong or if this is even possible?

**Comment by brillout** [comment]
Does the error disappear if you make it sync (i.e. `setup()` instead of `async setup()`)?

**Comment by OfekA** [comment]
@brillout Do you mean like this?

```vue
<template>
  <div>
    {{ lazyload }}
  </div>
</template>

<script lang="ts">
export default {
  setup() {
    delay(5000)
    const lazyload = 'lazyload'
    return { lazyload }
  }
}

function delay(delayInms: number) {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(2)
    }, delayInms)
  })
}
</script>
```

That doesn't throw the error, but that doesn't wait for the promise to resolve so it doesn't really solve the problem.

**Comment by brillout** [comment]
I'm asking to make sure it's `async` that causes the error.

Sure it should work with `async` as well, since the whole purpose of HTML streaming is to enable efficient suspensed SSR.

**Comment by brillout** [comment]
@OfekA 

Did you wrap it with `<suspense>`? See https://v3.vuejs.org/api/sfc-script-setup.html#top-level-await

Do you know whether `Error [ERR_METHOD_NOT_IMPLEMENTED]: The _read() method is not implemented` originates from vite-plugin-ssr or Vue?

**Comment by OfekA** [comment]
@brillout 

I tried it with Suspense as well, got the same error, but I may have used it wrong.

Regarding the origin of the error, I'm not entirely sure..

**Comment by brillout** [comment]
> Regarding the origin of the error, I'm not entirely sure..

It would help to know. I'm fairly busy with another ticket right now, so I'll gladly take any help I can 😊.

**Comment by OfekA** [comment]
> > Regarding the origin of the error, I'm not entirely sure..
> 
> It would help to know. I'm fairly busy with another ticket right now, so I'll gladly take any help I can 😊.

Definitely, I'll report back with findings soon 😊

**Comment by brillout** [comment]
Perfect 👌

**Comment by OfekA** [comment]
@brillout 

I checked again with `Suspense` and it doesn't work - same error.

Regarding the origin of the error, I tried debugging the code from `vite-plugin-ssr` but I didn't manage to, not really sure how to debug it...

**Comment by brillout** [comment]
@OfekA I'd debug this by setting `console.log()`s in `node_modules/vite-plugin-ssr/` as well as `node_modules/vue/` to understand the execution flow that leads to the error. The error originates somehwere in one of these two pacakges.

**Comment by brillout** [comment]
If you can shed some light on what causes the error, I'll implement the required changes to fix it.

**Comment by OfekA** [comment]
@brillout Exactly what I tried, for some reason I couldn't see the `console.log` in `/node_modules/vite-plugin-ssr/node/renderPage.ts` - maybe I shouldn't be trying in the `.ts` files?

**Comment by brillout** [comment]
Yes put them in `dist/`

**Comment by brillout** [comment]
@OfekA Neat 👌 I will update vite-plugin-ssr tomorrow.

`readableNodeOriginal` is set by Vue so I'm not sure why Vue doesn't set `read()`.

**Comment by brillout** [comment]
> On another note, I thought of making a PR that implements a simple example, first in vue-full and then in react-full + add tests, thoughts?

Yes that'd be lovely actually.

**Comment by nitedani** [comment]
Could you please document an example using renderToPipeableStream? renderToNodeStream no longer does streaming in react 18.

**Comment by brillout** [comment]
@nitedani See https://github.com/brillout/react-streaming and the 0.4 branch has a couple of examples of using it with vps.
