### ISSUE TITLE
Teleport Support

### ISSUE THREAD

**Issue by cagataycivici** [brillout/vite-plugin-ssr#144]
When ssr plugin is used to render a component that uses teleport following error is given;

Using a component with SSR results in an error: Hydration completed but contains mismatches

Is it a known issue or should the component author needs to do something for compatibility with vite-plugin-ssr?

An example from PrimeVue -> https://github.com/primefaces/primevue/issues/1397

**Comment by brillout** [comment]
Thanks for the ping. AFACIT it's unrelated to the plugin so let's discuss over there. (Nice job on Primefaces btw!)

**Comment by louwers** [comment]
For future reference, the Vue docs now have a guide on how to handle Teleports with SSR: https://vuejs.org/guide/scaling-up/ssr.html#teleports
