### ISSUE TITLE
Pre-rendering (SSG) Solid example Hydration failed when deployed to apache php server

### ISSUE THREAD

**Issue by jouyoku** [brillout/vite-plugin-ssr#146]
Pre-rendering (SSG) Solid example could build and run locally, but when I deployed it to apache php server, error occurs as follow.

Is it bug or the problem of apache settings?

Thank you.

```
index.page.ad9a6b6e.js:1 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'nextSibling')
    at index.page.ad9a6b6e.js:1
    at c (index.page.ad9a6b6e.js:1)
    at vendor.a3dda7ec.js:1
    at _ (vendor.a3dda7ec.js:1)
    at k (vendor.a3dda7ec.js:1)
    at index.page.ad9a6b6e.js:1
    at u (index.page.ad9a6b6e.js:1)
    at vendor.a3dda7ec.js:1
    at _ (vendor.a3dda7ec.js:1)
    at k (vendor.a3dda7ec.js:1)
```

**Comment by brillout** [comment]
Seems like it's unrelated to the plugin. But let me know if you believe it's a plugin problem :-).

**Comment by jouyoku** [comment]
Sorry to disturb you.
I found it works in MAMP, so I closed the issue.
This plugin is really great.
Thank you.

**Comment by brillout** [comment]
No worries. Am glad it worked out for you.
