### ISSUE TITLE
"document is not defined" when using bootstrap js

### ISSUE THREAD

**Issue by axelthat** [brillout/vite-plugin-ssr#148]
So I have this component which uses `collapse.js` of `bootstrap`,

```
<script lang="ts" setup>
import { onMounted } from "@vue/runtime-core"
import Collapse from "bootstrap/js/dist/collapse"

onMounted(() => {
  new Collapse(document.body)
})
</script>

<template>
  <div>
    <slot></slot>
  </div>
</template>
```

I get this error: `ReferenceError: document is not defined`. On nuxt, you could do,
```
onMounted(() => {
  if(process.client) {
    new Collapse(document.body)
  }
})
```

How do I do the same?

**Comment by axelthat** [comment]
Okay this is weird. I console logged `document` and I got no error. I get error only when using the bootstrap js library.

**Comment by brillout** [comment]
Your issue is not related to the plugin.

**Comment by brillout** [comment]
But to answer your question: `if (typeof window !== "undefined") window.document.body`.

**Comment by axelthat** [comment]
@brillout But it doesn't happen without SSR. I tried it on regular vite project and everything works fine. Even doing `if (typeof window !== "undefined")` doesn't work.

**Comment by brillout** [comment]
It's an SSR problem, but not a vite-plugin-ssr problem.

Dig on bootstrap's side.

**Comment by axelthat** [comment]
Okay thanks

**Comment by axelthat** [comment]
For anyone that stumbles upon this issue:
https://github.com/twbs/bootstrap/issues/33722
https://github.com/twbs/bootstrap/issues/34265
https://github.com/twbs/bootstrap/pull/33131

**Comment by brillout** [comment]
Thanks for sharing. What solution did you end up choosing?

**Comment by axelthat** [comment]
This one: https://github.com/twbs/bootstrap/issues/33722

**Comment by brillout** [comment]
From Discord:

> By the way, i found that directly include bootstrap cdn in the documentHtml solved the issue also, just another workaround for quick and dirty solve.
> [\[Source\]](https://discord.com/channels/815937377888632913/815937377888632916/890118237726064670)

Reply: 
> It's a legit fix if you ask me. IIRC Bootstrap recommends loading bootstrap from their CDN; they will maintain the CDN links for the forseeable future.
> [\[Source\]](https://discord.com/channels/815937377888632913/815937377888632916/890201810084704317)

**Comment by axelthat** [comment]
Yeah but that will include the whole bootstrap js file. I only needed some components. So did the lazy loading js way.

**Comment by brillout** [comment]
Makes sense.
