### ISSUE TITLE
Configuring an absolute URL for Base URL causes renderPage to return `null` for `httpResponse`

### ISSUE THREAD

**Issue by rjschill87** [brillout/vite-plugin-ssr#149]
Within `analyzeUrl`, it appears the URL's `origin` is removed prior to the comparison against the provided `baseUrl`:

https://github.com/brillout/vite-plugin-ssr/blob/663886c94cb1fb2b52ac153716bafb65a9e7176e/vite-plugin-ssr/node/renderPage.ts#L1010-L1016

Because of this, it appears `hasBaseUrl` can never be `true`, causing `{ httpResponse: null }` to be returned here:

https://github.com/brillout/vite-plugin-ssr/blob/663886c94cb1fb2b52ac153716bafb65a9e7176e/vite-plugin-ssr/node/renderPage.ts#L63-L66

**Comment by brillout** [comment]
If the `baseUrl` contains the origin then yes you're right this will fail. I'll fix this. In the meantime is removing the origin from the base URL an option for you?

**Comment by rjschill87** [comment]
@brillout Yup! Still in the testing phases, and do have some workarounds considered, so not production-critical at the moment. Just something noticed during tested that I wanted to bring to attention.

**Comment by brillout** [comment]
👍 I'll fix this tomorrow

**Comment by brillout** [comment]
Released in `v3.0.2`.
