### ISSUE TITLE
Conflict of onBeforeRender between _default.page.server.js and .page.server.js

### ISSUE THREAD

**Issue by IT-iddiot** [brillout/vite-plugin-ssr#154]
As I refer to the example of vuex provided, everything works well. But whenever I add a custom `.page.server.js`, an error of `Argument 'str' should be a string but we got 'typeof str === "undefined"'` will occur, and the whole page will become empty

Seems like the onBeforeRender in _default.page.server.js and .page.server.js conflicts with each other, as everything will back to normal again when I delete/clear the custom `.page.server.js` file

To reproduce: 
```
git clone git@github.com:IT-iddiot/vite-plugin-ssr-bug-reproduce.git
cd vite-plugin-ssr-bug-reproduce
npm install
npm run start
```
If you visit localhost:3000 now, everything should work normally.

Now you go to pages/index.page.server.js, and uncomment all the code inside. If you check the browser now, the page will be empty. 

I am curious is there any way to use Vuex and customer .page.server.js at the same time. 
Any help is appreciated, Thank you

**Comment by brillout** [comment]
Yes this is a design limitation: only one onBeforeRender is ever called. I've some plan to improve the situation. In the meantime what you can do is to export a function that you use on both the default's onBeforeRender and the page's onBeforeRender.

**Comment by brillout** [comment]
The tracking ticket: https://github.com/brillout/vite-plugin-ssr/issues/153

**Comment by IT-iddiot** [comment]
Actually what I want to do is to set different SEO meta tags for every page. It's okay to keep the onBeforeRender in _default.server.page.js, since I found that you allow <head> tags customization in the nested view component. 

But the example given in https://vite-plugin-ssr.com/html-head#head-defined-by-component is for React. I tried to pass $pageContext to all components by using app.config.globalProperties, but i am unable to edit it in the nested view component. I tried again by provide the $pageContext, inject it in the nested view component and edit the documentProps inside it, but still cannot. 

Is there any way I can edit the <title> tags in the nested Vue component?

To reproduce:
```
git clone git@github.com:IT-iddiot/vite-plugin-ssr-bug-reproduce.git
cd vite-plugin-ssr-bug-reproduce
npm install
npm run start
```

**Comment by brillout** [comment]
I will have a look

**Comment by brillout** [comment]
Replace `internalInstance.appContext.config.$pageContext.documentProps` with `internalInstance.appContext.config.globalProperties.$pageContext.documentProps` and it will work.

Also you can use composition API, see link in https://github.com/brillout/vite-plugin-ssr/issues/157

**Comment by IT-iddiot** [comment]
> Replace `internalInstance.appContext.config.$pageContext.documentProps` with `internalInstance.appContext.config.globalProperties.$pageContext.documentProps` and it will work.
> 
> Also you can use composition API, see link in #157

Strange, even I have edited the $pageContext.documentProps, but my title and description doesn't update

![Title and description doesn't update](https://user-images.githubusercontent.com/47970788/136060865-e9178fc4-f63a-4aae-ba0c-ce534b585d93.jpg)

```
  const internalInstance = getCurrentInstance()
  internalInstance.appContext.config.globalProperties.$pageContext.documentProps = {
    title: 'title',
    description: 'description',
  }
```

**Comment by brillout** [comment]
Hm, I tried and it worked for me, so I'm thinking it's a problem on your side.

Maybe try `internalInstance.appContext.config.globalProperties.$pageContext.documentProps.title = 'title'` instead.

**Comment by IT-iddiot** [comment]
Inspired by the solution here https://github.com/brillout/vite-plugin-ssr/issues/34#issuecomment-821974773, now I manage my SEO metadata through Vuex, which works quite well for me now. 

Here is a simple example: 

1. In Vuex store, add state of title and description, and a mutation to update them
```
// store.js
import Vuex from 'vuex'

export { createStore }

function createStore() {
  const store = Vuex.createStore({
    state() {
      return {
        title: 'Default title',
        description: 'Default description',
      }
    },

    mutations: {
      setMetaTags(state, { title, description }) {
        state.title = title;
        state.description = description;
      }
    }
  })

  return store
}
```
2. In the page component or any nested component, commit the mutation in beforeCreate/created/serverPrefetch hook
```
<script setup>
import { useStore } from 'vuex';

/**
 * All the code inside <script setup> will run around 
 * the beforeCreate and created lifecycle hooks, unless
 * you explicitly wrap the code under other lifecycle.
 * Refer: https://v3.vuejs.org/guide/composition-api-lifecycle-hooks.html#lifecycle-hooks
 */
const store = useStore();

store.commit('setMetaTags', {
  title: "Custom title",
  description: "Custom description",
})

</script>
```
3. Now in `_default.page.server.js`, use the title and description from your Vuex store
```
import { renderToString } from '@vue/server-renderer'
import { escapeInject, dangerouslySkipEscape } from 'vite-plugin-ssr'
import { createApp } from './app'

export { render }
export { onBeforeRender }
export { passToClient }

const passToClient = ['INITIAL_STATE']

async function render(pageContext) {
  const { appHtml, INITIAL_STATE } = pageContext

  /**
   * assign custom meta info here
   */
  const title = INITIAL_STATE?.title ?? 'Default title here'
  const description = INITIAL_STATE?.description ?? 'Default description here'

  return escapeInject`<html>
    <head>
      <title>${title}</title>
      <meta name="description" content="${description}">
    </head>
    <body>
      <div id="root">
        ${dangerouslySkipEscape(appHtml)}
      </div>
    </body>
  </html>`
}

async function onBeforeRender(pageContext) {
  const { Page } = pageContext
  const { app, store } = createApp({ Page })

  const appHtml = await renderToString(app)

  const INITIAL_STATE = store.state

  return {
    pageContext: {
      INITIAL_STATE,
      appHtml
    }
  }
}
```
4. Now the meta info should be updated
![custom ](https://user-images.githubusercontent.com/47970788/136067309-a8b19832-3c63-4420-9372-3a201a71da82.jpg)


It works for me now, although I am not sure whether this is a good way to do it. I have tried [@vueuse/head](https://github.com/vueuse/head) and [vue-meta@next](https://github.com/nuxt/vue-meta/tree/next) before, but none of them works for me.

But I still looking forward to the ability to use onBeforeRender on default server js and custom page server js at the same time,  cause now I stuck with the custom tracking code per page haha. 

Anyway, thank you for this awesome tool 👍🏼

**Comment by brillout** [comment]
I'm glad you found something to your pleasing.

If you believe there is a bug in `vite-plugin-ssr`, feel free to push.

> But I still looking forward to the ability to use onBeforeRender on default server js and custom page server js at the same time, cause now I stuck with the custom tracking code per page haha.

I'm actually working on it at the moment.
