### ISSUE TITLE
Vuex devtool always shows initial state

### ISSUE THREAD

**Issue by IT-iddiot** [brillout/vite-plugin-ssr#160]
As I clone the example of vuex, I notice that the vuex state in my devtool doesn't update after mutation, even though everything is working well without issue, and the component devtool is able to get the updated state

**Component devtool**

![vue tool 1](https://user-images.githubusercontent.com/47970788/136080087-c71d6a7e-8259-4357-9cc2-ced79695af62.jpg)

**Vuex devtool**

![vue tool 2](https://user-images.githubusercontent.com/47970788/136080117-628e6b3a-8138-4c68-8677-a01df5dfd63d.jpg)

Or this is an issue on Vue SSR, or Vuex devtool lack of SSR support?

**Comment by brillout** [comment]
Very unlikely an issue with `vite-plugin-ssr`. If you have some evidence showing otherwsie, let me know and I'll dig.
