### ISSUE TITLE
Use Vite to process Node.js server code (e.g. Express.js)

### ISSUE THREAD

**Issue by brillout** [brillout/vite-plugin-ssr#169]
So far the recommended way is to use vanilla Node.js (or with `ts-node`) to run the user's Node.js server code (e.g. Express.js).

The reason being that Vite has some troubles with server-only deps (https://github.com/vitejs/vite/discussions/4921, https://github.com/vitejs/vite/discussions/4230).

But these will get fixed and then we should start using Vite for server code as well. E.g. `vite-node` (https://github.com/antfu/vite-node/issues/2), tsm, or esno. (https://github.com/antfu/vite-node/issues/2#issuecomment-940212917.)

**Comment by stychu** [comment]
Hey @brillout. Wanted to ask if this is something on the radar? I kinda struggle to make this work with vite. 
Alternative would be nodemon but I wish it couuld be done with vite and ideally with vite features applied

**Comment by brillout** [comment]
Yes, it is on the Radar.

Long/middle term: [HatTip](https://github.com/hattipjs/hattip).

In the meantime you can use [`vavite`](https://github.com/cyco130/vavite). See the [vite-plugin-ssr + vavite example](https://github.com/cyco130/vavite/tree/main/examples/vite-plugin-ssr).

**Comment by stychu** [comment]
Thanks for the suggestions. Vavite seems like the deal. At least it's working 👌

**Comment by brillout** [comment]
Closing in favor of https://github.com/brillout/vite-plugin-ssr/issues/562.
