### ISSUE TITLE
comparing it to next.js

### ISSUE THREAD

**Issue by hyusetiawan** [brillout/vite-plugin-ssr#170]
I am very impressed with this plugin, I am curious, how does this compare to next.js? like in terms of performance, philosophy, direction etc. Laid out side by side like that would give context to the project.

**Comment by ka-work** [comment]
I am most curious to see how vite-esbuild-rollup vs next-swc-webpack turns out.

**Comment by brillout** [comment]
Done https://github.com/brillout/vite-plugin-ssr/issues/158#issuecomment-1250068578
