### ISSUE TITLE
Add css-in-js integration to docs

### ISSUE THREAD

**Issue by DonnyVerduijn** [brillout/vite-plugin-ssr#172]
The docs should explain how styles should be collected, passed and injected into the template.
I have a working setup using pageContext, so i would like to know others their opinions on this before making a PR.

**Comment by brillout** [comment]
Yes that would be nice indeed. What css-in-js tool did you end up using?

**Comment by brillout** [comment]
https://vite-plugin-ssr.com/css-in-js let me know if you believe something's missing.

**Comment by brillout** [comment]
As for a `index.html`, JS as a string template language is more powerful than using some DSL.
