### ISSUE TITLE
TypeError: Cannot set property urlNormalized of #<Object> which has only a getter

### ISSUE THREAD

**Issue by Stouffi** [brillout/vite-plugin-ssr#174]
I've upgraded from 0.3.4 to 0.3.12 today and I'm encountering the issue below when I issue this command

**EDIT: After testing with previous releases, The error appears from the release 0.3.11** 

```sh
vite build && vite build --ssr && vite-plugin-ssr prerender
# Build and build SSR both succeed...
vite-plugin-ssr 0.3.12 pre-rendering HTML...
/Users/stouffi/projects/Libertrip/viteuf/.yarn/__virtual__/vite-plugin-ssr-virtual-53aa919ee5/0/cache/vite-plugin-ssr-npm-0.3.12-0b9c9a4d63-dae87df8f3.zip/node_modules/vite-plugin-ssr/dist/cjs/node/cli/bin.js:30
    throw rejectValue;
    ^

TypeError: Cannot set property urlNormalized of #<Object> which has only a getter
    at Function.assign (<anonymous>)
    at executeOnBeforeRenderHooks (/Users/stouffi/projects/Libertrip/viteuf/.yarn/__virtual__/vite-plugin-ssr-virtual-53aa919ee5/0/cache/vite-plugin-ssr-npm-0.3.12-0b9c9a4d63-dae87df8f3.zip/node_modules/vite-plugin-ssr/dist/cjs/node/renderPage.js:438:16)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async prerenderPage (/Users/stouffi/projects/Libertrip/viteuf/.yarn/__virtual__/vite-plugin-ssr-virtual-53aa919ee5/0/cache/vite-plugin-ssr-npm-0.3.12-0b9c9a4d63-dae87df8f3.zip/node_modules/vite-plugin-ssr/dist/cjs/node/renderPage.js:242:5)
    at async /Users/stouffi/projects/Libertrip/viteuf/.yarn/__virtual__/vite-plugin-ssr-virtual-53aa919ee5/0/cache/vite-plugin-ssr-npm-0.3.12-0b9c9a4d63-dae87df8f3.zip/node_modules/vite-plugin-ssr/dist/cjs/node/prerender.js:166:57
```

I've both tested with vite 2.5.10 and 2.6.9 and got the same result.

After a quick search, I've found an issue from esbuild with similar error message:
https://github.com/evanw/esbuild/issues/587

But I cannot say wether it's related or not.

**Comment by brillout** [comment]
Do you change `urlNormalized` somewhere in your code?

**Comment by Stouffi** [comment]
No, I have defined onBeforeRender in a few `.page.server.js` including `_default.page.server.js`. But I don't mutate the pageContext, I'm returning new references. In the stack trace, I see that Object.assign is used to mutate the pageContext object. I'm wondering if this was not the case with 0.3.10 and before ?

**Comment by brillout** [comment]
I can't reproduce, so I'm thinking there is something special about your user code that triggers this.

Do you do antyhing peculiar with routing / the `pageContext.url*` props?

If you give me a reproduction I'll be able to fix this.

**Comment by mate-h** [comment]
Had this issue as well because I was using lodash's `set` function to return the `pageContext` in the `onBeforeRender` hook. Replacing the set function with a simple nested object fixed it.

**Comment by brillout** [comment]
I've some bigger plans regarding `pageContext` handling that includes improve clear & helpful error messages about "wrong" `pageContext` handling, i.e. you are not suppose to mutate `pageContext` directly.

**Comment by mate-h** [comment]
Neat, the new docs and better error message will resolve this issue. I would also love to see typings for the `onBeforeRender` hook. A wildcard module declaration only works for when you want to `import` from any `.page.server.ts` file which is not really a use case.

```ts
declare module "*.page.server.ts" {
  function onBeforeRender<CTX, NewContext>(ctx: CTX & PageContextBuiltIn): Promise<AddPageContext<NewContext>|null|undefined>
}
```

For now, the runtime error is enough though.

```
The `onBeforeRender()` hook exported by /pages/index.page.server.ts should return `undefined`, `null`, or `{ pageContext: { /*...*/ }}` (a JavaScript object with a single key `pageContext`).
```

**Comment by brillout** [comment]
> Neat, the new docs and better error message will resolve this issue

Released.

> A wildcard module declaration

It would not help that much anyways. The holy grail here is cross-file type checking e.g. https://github.com/brillout/vite-plugin-ssr/issues/176#issuecomment-950315850
