### ISSUE TITLE
Fully dynamic URLs (e.g. from database)

### ISSUE THREAD

**Issue by antoineanorra** [brillout/vite-plugin-ssr#175]
I use ClientRouting, and I want to have fully dynamic URLs (from database)
For that, I use the catch-all page (with the route in /*).

catch-all.page.server.js sends me back a JSON with the .vue file to import on catch-all.page.vue.

So when the user clicks on a link, for example /view2, it makes a call to catch-all.page.server.js -> it sends me back a JSON with the new .vue file (component) to load, but the <script setup> of catch-all.page.vue is only called once, so it can't import the component I sent back

Maybe it's easier if you explain it with code: 

`catch-all.page.route.js` :
```js
export default () => true
````

`catch-all.page.server.js`
```js
async function onBeforeRender(pageContext) {
    const url = pageContext.realUrl;
    let viewFile = "";

   if (url == "/view1")
      viewFile = "Product";
   if (url == "/view2")
      viewFile = "Catagory";

    const pageProps = { data: { viewFile: viewFile, extras: "some extras", locale: "en" } }
    return {
        pageContext: {
            pageProps
        }
    }
}

export { onBeforeRender }
```

`catch-all.page.vue`
```vue
<template>
    <Component :is="component" :data="data" />
</template>

<script setup>
import { defineAsyncComponent } from 'vue'
import { useI18n } from 'vue-i18n'
const props = defineProps(['data'])

const {  locale } = useI18n({ useScope: 'global' })
locale.value = props.data.locale;

console.log("hello"); // I see that is call 1 time, even if I change page(/link)

const component = defineAsyncComponent({
  loader: () => import(`../themes/${props.data.viewFile}.vue`)
})
</script>
```

So my problem is that the catch-all page should be able to unload and reload as if I was going to another page in order to load my dynamically loaded components

**Comment by brillout** [comment]
Hm, it actually should be the case. Repro?

**Comment by brillout** [comment]
Fix described at https://discord.com/channels/815937377888632913/815937377888632916/907952345911005184
