### ISSUE TITLE
[TypeScript] Type check accross files

### ISSUE THREAD

**Issue by brillout** [brillout/vite-plugin-ssr#176]
Currently:

```ts
// server/index.js

app.get("*", async (req) => {
  const pageContextInit = {
    url: req.url,
    someInitProp: 'hello :-)'
  }
  const pageContext = await renderPage(pageContextInit)
  // TS complains that `someNewProp` is not defined on `pageContext`
  console.log(pageContext.someNewProp) // prints `42`
});
```

```ts
// some.page.server.js

import type { PageContextBuiltIn } from "vite-plugin-ssr";

epxort async function onBeforeRender(pageContext: PageContextBuiltIn) {
  // TS complains that `someInitProp` is not defined on `pageContext`
  console.log(pageContext.someInitProp) // prints `hello :-)`
  return {
    pageContext: {
      someNewProp: 42
    },
  };
}
```

How can we improve the situation?

AFAICT, something like [Next.js' utility types](https://nextjs.org/docs/basic-features/typescript#static-generation-and-server-side-rendering) don't add any value compared to `vite-plugin-ssr`'s [`PageContextBuiltIn`](https://vite-plugin-ssr.com/pageContext#typescript).

Contribution welcome.

CC @stouffi

**Comment by magne4000** [comment]
[redux-toolkit](https://redux-toolkit.js.org/tutorials/typescript) has some really nice patterns regarding Typescript usage, it kinda look like [this solution you proposed](#issuecomment-950314783).

I would even go for something like this:
```ts
export  { renderPage, onBeforeRender };
const { renderPage, onBeforeRender } = createDefine<PageContextInit, PageContextAfterOnBeforeRender>();
```

I also like your [first proposed solution](#issuecomment-950296223), as it makes all of this less error prone I guess.

**Comment by brillout** [comment]
@magne4000 What would be neat is a little TS playground to experiment our ideas. Something simple with only `renderPage()` and `onBeforeRender()`; that should be enough to showcase cross-file type checking.
 
> ```ts
> export { renderPage, onBeforeRender };
> const { renderPage, onBeforeRender } = createDefine<PageContextInit, PageContextAfterOnBeforeRender>();
> ```

What exactly do you mean? Note that we cannot use a `createHooks()` function to define all hooks at once. Because one hook may be defined in `.page.server.js` (i.e. only exectued in Node.js) while another in `.page.js` or `.page.route.js` (i.e. also executed in the browser).

**Comment by magne4000** [comment]
I was thinking that helpers like `renderPage` (or probably more like `createPageRenderer` in fact) could be used as I described above, instead of behing imported directly from `vite-plugin-ssr`. The intermediary redeclaration redefines it with proper typing. Or it could jsut be a simple override like [`useDispatch` in redux-toolkit](https://redux-toolkit.js.org/usage/usage-with-typescript#getting-the-dispatch-type), so:
```
export { createPageRenderer };

// `createDefine` as a global helper to define typed version of otherwise imported helpers.
// but as you said, all hooks are not defined al at once, so I dunno if this is possible
const { createPageRenderer } = createDefine<PageContextInit, PageContextAfterOnBeforeRender>();

// OR manual override. kinda more cumbersome to type, but we can override each hooks separately
const createPageRenderer = (...args: TBD) => createPageRenderer<PageContextInit, PageContextAfterOnBeforeRender>(...args);
```

Regarding `onBeforeRender`, same principle with a usage like this:
```
export default hook; // type is { onBeforeRender: ... } with right typings

const hook = onBeforeRender(pageContext => {
  // TS knows about `pageContext.user`
  console.log(pageContext.user) // prints `{ id: 42, name: 'Alan Turing' }`

  return {
    pageContext: {
      movie: {
        id: 1137,
        title: 'Star Wars'
      },
      // TS will complain
      someUnknownProp: 'bla'
    }
  }
});
```

But I find this harder to write and understand than current version of `onBeforeRender`, so I'm more a fan of something like `declare module '*.page.server.ts' ...` stuff for this

**Comment by brillout** [comment]
@magne4000 what do you think of https://github.com/brillout/vite-plugin-ssr/issues/176#issuecomment-950315850? AFAICT that would be the best and it should be possible. (I guess that, in principle, any type can be generated without JS).

**Comment by magne4000** [comment]
This works well for the most cases IMO, like `onBeforeRender` hook, but it's more complicated for `renderPage`:

```ts
// server/index.js

import { PageContextInit } from '../types'

app.get("*", async (req) => {
  const pageContextInit: PageContextInit = {
    url: req.url,
    user: {
      id: 42,
      name: 'Alan Turing'
    }
  }

  // ! `renderPage` does not enforce any typing for `pageContextInit`.
  // This means that if a developer forget to type `pageContextInit`, it will not throw any error.
  const pageContext = await renderPage(pageContextInit)
  // ...
});
```

If `renderPage` is used as-is, its typing will always be loose if not enforced through project specific overrides. So if I use `renderPage` on 2 different files, nothing checks that I pass the same `PageContextInit` to both of them.
But as the current state of this lib, it seems that it's the only function that would need a project specific override if we want strict typings everywhere. This, combined with your type only solution (+ even `declare module ...` solution that I find complementary and optional) should do the work for all use cases (that I'm aware of)

**Comment by brillout** [comment]
I guess we'd need to try. PR welcome.

**Comment by brillout** [comment]
There doesn't seem to be a way to achieve this; see disucssion at https://github.com/brillout/vite-plugin-ssr/pull/219.
