### ISSUE TITLE
console warnings: "Sourcemap ... points to missing source files"

### ISSUE THREAD

**Issue by DonnyVerduijn** [brillout/vite-plugin-ssr#183]
When running the server in a node environment, it seems that source maps are not mapped correctly. However, these files do actually exist. It only happens server side.

![Screenshot 2021-10-27 205135](https://user-images.githubusercontent.com/7514017/139128625-b67285a4-04b3-4498-8a48-01400ff8d518.png)

I did a little research on this and setting the `DEBUG=vite:sourcemap` environment variable on the command, points out the specific files. 

![Screenshot 2021-10-27 205503](https://user-images.githubusercontent.com/7514017/139129040-fd0379b0-91b5-4278-8bb6-8f3fac0001b1.png)

**Comment by Silbad** [comment]
Hello, How can this problem be solved? I encounter the same errors :
![image](https://user-images.githubusercontent.com/31576982/182021090-0739a423-1c01-47d8-9ea0-d0ee0db8f588.png)

**Comment by brillout** [comment]
@Silbad who is emitting these warnings?

**Comment by brillout** [comment]
Never mind I could reproduce, let me fix this.
