### ISSUE TITLE
Better typing for `renderPage`?

### ISSUE THREAD

**Issue by magne4000** [brillout/vite-plugin-ssr#184]
First of all, thank you for this awesome lib (and really useful documentation)!

I was playing around with `createPageRenderer` (I'm using Typescript + Vercel + SolidJS) like so:
```ts
const renderPage = createPageRenderer(...);
...
const pageContext = await renderPage(pageContextInit);
```

Here, my `pageContext` should have custom fields that could be returned (like `redirectTo` as in your examples, or `cookies`, that is responsible to set Cookies on headers).

So I checked the `renderPage` typings:

![image](https://user-images.githubusercontent.com/1098371/139259341-fe5c3704-1354-4706-a104-43db67fe55e1.png)

Good, there is a `PageContextAdded` type that I can use:
```ts
const pageContext = await renderPage<MyCustomType, typeof pageContextInit>(pageContextInit);
```

This should have been enough I guess, but the right typing is not quite right IMO:
```ts
PageContextInit & (({ httpResponse: HttpResponse } & PageContextAdded) | { httpResponse: null })
```

Looking closer, `PageContextAdded` is added to the return type only if `httpResponse` is of type `HttpResponse`, which in both of my use cases (redirect and cookies) is not necessarily the case.

Perhaps I'm doing this wrong? But if not, here is the typing I propose:
```ts
PageContextInit & { httpResponse: HttpResponse | null } & PageContextAdded
// or with Partial but it could mess some type definitions
PageContextInit & { httpResponse: HttpResponse | null } & Partial<PageContextAdded>
// see https://www.typescriptlang.org/play?#code/C4TwDgpgBACghgcwgYQPYDtgQB7AIIAmBEBUAvFAN4BQUUcAXFOgK4C2ARhAE4A0tUDk1ace-AL5QAPlSgBjYey7co4gNzVqoSFAAa5WHG7AAlnAA2AHnhI0mHPiIkAfBupyMAZ2BRsTfRSU9EwAjLyCTABMqhoe6N5QIEw2KBhYuITEpIHBUGERUNHqmiYAZlAAFNgAdHAAlFQCdAD0zVAAogBKnQDynU3yXj5CzEo8BjUcGuIl5RUgtQ00dC1tAHKoUDzcqCpwnlvYkHJYBANxCSMiygYLU9TiQA
```

**Comment by brillout** [comment]
Released in `v0.3.20`.
