### ISSUE TITLE
Pre-rendered site serves some routes as generic index

### ISSUE THREAD

**Issue by gryphonmyers** [brillout/vite-plugin-ssr#19]
As an example, my generated site yields:

```
index.html
news.html
/news
  news-article-1.html
```
When I point a basic HTTP server at the generated files, /news/ resolves to a generic HTML index of the /news directory. This is because the news directory takes precedence over the news.html file, so news.html is ignored and there is no /news/index.html so it uses a generic index. 

My suggestion would be to just name all HTML files index.html in directories with their identifiers. This should lead to more predictable routing.

**Comment by brillout** [comment]
I had issue with that in the past: some static deploy tools don't understand one of the two formats (I don't remember if it was `path/index.html` or `path.html` which was problematic). If I remember correctly it was GitHub pages who was buggy about it. What's your experience on that?

I'll implement your suggestion, worst case we'll see when users complain about it.

**Comment by gryphonmyers** [comment]
I've never had issues with index.html based file trees, but I haven't used a great variety of static hosting services (I mostly use S3). You could make this a configuration option in case some deployments want it the other way?

**Comment by brillout** [comment]
Yes that's the plan.
