### ISSUE TITLE
Custom client and server input flags to read from different directories for each during build

### ISSUE THREAD

**Issue by dymart** [brillout/vite-plugin-ssr#190]
hi @brillout,

I was wondering if you would be open to allowing vite-plugin-ssr to have more flags to read and write to different directories for the build. This would build on top of my previous contribution. I created a rough version here: https://github.com/dymart/vite-plugin-ssr/tree/flags

The flags help it work with the bazel build system so that vite build and vite build --ssr can happen in parallel and then their outputs can be fed into vite-plugin-ssr. 

I'm open to suggestions and changes to how this works,
thanks

**Comment by brillout** [comment]
Can't you achieve this with `mv` instead?

**Comment by dymart** [comment]
Hi brillout,

That would be nice but the way that bazel prefers to handle inputs and outputs from different steps is by using distinct file names or directory names. So with that it is much easier to keep track of the two directories that are outputs from vite build and vite build --ssr and then simply pass the location of those two distinct directories into the vite-plugin-ssr build. This also means that there is one less step where files might have to be moved across a network as all of these steps could be taking place on different machines. 

Hopefully that makes sense, if you want to know more or discuss further let me know :) 

If you are alright with those proposed changes I can clean up my work and create a pr from it. I'm also open to discuss the naming and interaction between the flags. My goal is to not affect anyone who does not set these new flags and not add much complexity to the plugin. The changes seem relatively noninvasive. If you see a changes that would make it easier to maintain please let me know as well!

Thanks

**Comment by brillout** [comment]
It's still quite messy in my head why you need all these extra flags and how they help.

Is there a way to add only one / a minimal amount of flags to make it work?

> That would be nice but the way that bazel prefers to handle inputs and outputs from different steps is by using distinct file names or directory names. So with that it is much easier to keep track of the two directories that are outputs from vite build and vite build --ssr and then simply pass the location of those two distinct directories into the vite-plugin-ssr build.

Wouldn't that equally work when the two directories are `dist/client/` and `dist/server/`?

**Comment by dymart** [comment]
Maybe a little more information about how things are built with bazel would help. Bazel uses a sandbox for its builds and outputs. So you cannot write or change files as you would normally that are inside your project folder. That is why I added the output flag initially because the output folder needs to be specified in the sandbox or the build outputs are not available. This output directory in the sandbox looks like bazel-out/{more bazel paths}...{project paths}.../{rule name}. The output folder needs to be variable inside the project depending on where it is located to ensure bazel can manage it inside the sandbox so you can't simply write to a hard coded dist location. Hopefully that makes it a little more clear why I wanted to add the output flag in the first place. Building on the fact that outputs are located in this sandbox that is also where dependencies are imported and made available. Given that vite build and vite build --ssr are dependencies for vite-plugin-ssr their outputs are located in this sandbox as well. So to read these inputs flags are necessary to point to the correct location in the sandbox where the directories with the outputs of those builds will be located. Simply writing to dist in the relative path of the directory and then reading from there is not an option. 

Please let me know if this can justify adding the input and output flags to your project. If you want to discuss more let me know.

thanks :)

**Comment by brillout** [comment]
Alternatively, you could define `vite build && vite build --ssr && vite-plugin-ssr prerender` as one monolithic block, so that Bazel considers this a single unit, correct?

**Comment by dymart** [comment]
Unfortunately, that isn't an option with bazel rules. Each step calls one of the tools directly and then passes specific flags to it. So creating a monolithic block with multiple commands is not an option. 

Please let me know if this can justify adding the input and output flags to your project. If you want to discuss more let me know.

thanks :)

**Comment by brillout** [comment]
In principle you could wrap all commens in a single CLI; bazel wouldn't know and that should work, right?

**Comment by dymart** [comment]
Like I mentioned above running everything together is not an option with rules in bazel. I have already created a working set of rules with as few changes as required to your plugin to work with bazel in the fork of this repository. My goal with my changes was already to change as little as possible to allow it to run with bazel. These flags allow it to work very well with bazel. I was hoping the do one thing do it well ethos of this project would also apply to other projects that would like to use it.

Thank you for your suggestions and work arounds but I do need an answer to my original question. 
Is the use case and justification I have provided enough to have these flags added?

thanks :)

**Comment by brillout** [comment]
If Bazel is that intrusive and rigid, that's on Bazel not vite-plugin-ssr.

I'm reluctant to accommodate that many options for a tool that has interoperability issues.

Again, in principle, it should be possible to create a dummy CLI that wraps everything. I don't see why this wouldn't work. E.g. if you'd use SvelteKit then you'd also essentially use a CLI that wraps all these operations.

Sorry to push back but I care about keeping things simple; a zillion options down the road is not ideal.

**Comment by dymart** [comment]
Thank you for the direct answer. I understand your points as well, that's why I wanted to explore adding this in an issue before creating a pr. Thanks for discussing it with me.

I really enjoy this plugin and think you are doing great work with it :)

**Comment by brillout** [comment]
>  dummy CLI

This really should work. That should be fairly easy by using Vite's and `vite-plugin-ssr`'s API.
