### ISSUE TITLE
Set right content type for `.pageContext.json` HTTP response

### ISSUE THREAD

**Issue by brillout** [brillout/vite-plugin-ssr#191]

**Comment by brillout** [comment]
Re-opening until implementation of a warning when `pageContext.httpReponse.contentType` is not used.

**Comment by brillout** [comment]
`pageContext.httpResponse.contentType` released in `0.3.21`.

> until implementation of a warning when `pageContext.httpReponse.contentType` is not used.

I expect browsers to be clever enough to not run any script in URLs that don't have a proper HTML structure. However, if setting `text/html` for a `.json` URL is indeed an attack vector, then I'll implement a warning when users don't use `pageContext.httpResponse.contentType`.

If someone has some evidence for potential attack vectors, let me know.

**Comment by brillout** [comment]
> Browser parsing of HTML is very tolerant. I tested again in firefox 93 and chromium 94. The script is indeed executed.

![2021-11-03_11-21-08_](https://user-images.githubusercontent.com/1005638/140033726-2e76ae17-23ac-43b3-b235-442308c153ed.png)

**Comment by brillout** [comment]
Latest release `0.3.23` now rejects URLs that have a wrong content type, forcing `vite-plugin-ssr` users to set the right content type.

**Comment by Ericarthurc** [comment]
If your using HTML streaming over a pipe make sure to set your contentType and statusCode headers before consuming the response in the pipe

```ts
    const { statusCode, contentType } = httpResponse;
    res.status(statusCode).type(contentType);

    httpResponse.pipe(res);
```

If you dont set the content type before consuming the response in the pipe you will get this content type = null error on server handlers from the `onBeforeRender` function on a page reload after hydration.

**Comment by richvoronov** [comment]
If you use `fastify v4`, you need to set the header natively with `reply.raw.setHeader`. If you set contentType using the `.header()` or `.type()` method from fastify, you will get an error. I do not know the reason for the bug, but it was not pleasant to find out about its existence :/

use this 
```
server.get('*', async (request, reply) => {
...

reply.status(statusCode);
reply.raw.setHeader("Content-Type", contentType);
httpResponse.pipe(reply.raw)
```

**Comment by Ericarthurc** [comment]
> If you use `fastify v4`, you need to set the header natively with `reply.raw.setHeader`. If you set contentType using the `.header()` or `.type()` method from fastify, you will get an error. I do not know the reason for the bug, but it was not pleasant to find out about its existence :/
> 
> use this
> 
> ```
> server.get('*', async (request, reply) => {
> ...
> 
> reply.status(statusCode);
> reply.raw.setHeader("Content-Type", contentType);
> httpResponse.pipe(reply.raw)
> ```

It's because pipe doesn't set the content type header, you need to manually set it before your consume the body of the response, then you can't set the header.
So set it manually before spending the pipe.
