### ISSUE TITLE
<link rel=preload> must have a valid as value (chrome and firefox) when use less styles

### ISSUE THREAD

**Issue by txus2202** [brillout/vite-plugin-ssr#196]
i installed less in my project but i see an error in console of generated preload links by my less styled components.

error: Preload of http://localhost:3000/pages/index/index.page.vue?vue&type=style&index=0&scoped=true&lang.less was ignored due to unknown “as” or “type” values, or non-matching “media” attribute.

i think is necessary add as="style"

How can I introduce this "as" somehow in my preload links?

**Comment by brillout** [comment]
What exactly is the preload tag? Do yo get this in prod or dev?

**Comment by txus2202** [comment]
in pro and dev.
In my components i use this style label to add the styles:
<style scoped lang="less">
...
</style>

**Comment by brillout** [comment]
Seems like a problem with Vue, not with vite-plugin-ssr.

But give me a repro and I'll have a look.

**Comment by txus2202** [comment]
unfortunately I can't provide you with the repository, but to reproduce it, you just need to add it to the package "less": "^4.1.2" as a dependency, install and use <style scoped lang = "less"> ... </style> in any component

**Comment by brillout** [comment]
Do it yourself and publish the repo and I'll have a look.

Closing in the meantime.

**Comment by brillout** [comment]
Fix released in `0.3.28`.
