### ISSUE TITLE
Call pre-rendering via the javascript api

### ISSUE THREAD

**Issue by SherinBloemendaal** [brillout/vite-plugin-ssr#201]
Hi,

According to the docs, it should be possible to use the `npx vite-plugin-ssr prerender` command or use the javascript api `import { prerender } from 'vite-plugin-ssr/cli` but the javascript api does not work for me. `vite-plugin-ssr/cli` does not exist. Let me explain why we want to use this.

Our use case: 
We are building a website editor, the structure/content is saved in our Api as JSON and its possible to publish these changes afterwards (transform the JSON to a static generated website). We want to build a micro service that simply receives a JSON and outputs a list of static generated files wich we can fetch and put on a S3 bucket or anything else for example. 
We want to use a Cloudflare worker for this. 

Do you need a reproduction repository? In my opinion its pretty clear what goes wrong.

Thanks.
Kind regards,
Sherin

**Comment by brillout** [comment]
Just tried and the following does work.

```js
const { prerender } = require("vite-plugin-ssr/cli");
console.log(prerender)
```

What's your Node.js version?

**Comment by SherinBloemendaal** [comment]
```
sherin@sherin:~$ node -v
v14.18.0
sherin@sherin:~$ npm -v
8.0.0
```

**Comment by SherinBloemendaal** [comment]
> Just tried and the following does work.
> 
> ```js
> const { prerender } = require("vite-plugin-ssr/cli");
> console.log(prerender)
> ```
> 
> What's your Node.js version?

```
sherin@sherin:~$ node -v
v14.18.0
sherin@sherin:~$ npm -v
8.0.0
```

**Comment by brillout** [comment]
Should work. It's probably a problem with your node_modules installation.

In doubt, feel free to share a minimal reproduction.

**Comment by SherinBloemendaal** [comment]
> Should work. It's probably a problem with your node_modules installation.
> 
> In doubt, feel free to share a minimal reproduction.

Okay thanks for looking! I will create a minimal reproduction at the office tomorrow. (Europe/Amsterdam timezone)

**Comment by brillout** [comment]
Let me know if you still hit the problem

**Comment by SherinBloemendaal** [comment]
When using require, i get the following error after running the cloudflare worker in Miniflare (`miniflare --port 3000 worker/script.js`):
`
👀  ./src/worker/index.js
Module not found: Error: Can't resolve 'vite-plugin-ssr/cli' in '/home/sherin/projects/***/***-vite/src/worker'
resolve 'vite-plugin-ssr/cli' in '/home/sherin/projects/***/***-vite/src/worker'
  Parsed request is a module
  using description file: /home/sherin/projects/***/***-vite/package.json (relative path: ./src/worker)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /home/sherin/projects/***/***-vite/src/worker/node_modules doesn't exist or is not a directory
      /home/sherin/projects/***/***-vite/src/node_modules doesn't exist or is not a directory
      /home/sherin/projects/maglr/node_modules doesn't exist or is not a directory
      /home/sherin/projects/node_modules doesn't exist or is not a directory
      /home/sherin/node_modules doesn't exist or is not a directory
      /home/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /home/sherin/projects/***/***-vite/node_modules
        using description file: /home/sherin/projects/***/***-vite/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: /home/sherin/projects/***/***-vite/node_modules/vite-plugin-ssr/package.json (relative path: ./cli)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /home/sherin/projects/***/***-vite/node_modules/vite-plugin-ssr/cli doesn't exist
            .wasm
              Field 'browser' doesn't contain a valid alias configuration
              /home/sherin/projects/***/***-vite/node_modules/vite-plugin-ssr/cli.wasm doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              /home/sherin/projects/***/***-vite/node_modules/vite-plugin-ssr/cli.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /home/sherin/projects/***/***-vite/node_modules/vite-plugin-ssr/cli.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /home/sherin/projects/***/***-vite/node_modules/vite-plugin-ssr/cli.json doesn't exist
            as directory
              /home/sherin/projects/***/***-vite/node_modules/vite-plugin-ssr/cli doesn't exist
[/home/sherin/projects/***/***-vite/src/worker/node_modules]
[/home/sherin/projects/***/***-vite/src/node_modules]
[/home/sherin/projects/maglr/node_modules]
[/home/sherin/projects/node_modules]
[/home/sherin/node_modules]
[/home/node_modules]
[/node_modules]
[/home/sherin/projects/***/***-vite/node_modules/vite-plugin-ssr/cli]
[/home/sherin/projects/***/***-vite/node_modules/vite-plugin-ssr/cli.wasm]
[/home/sherin/projects/***/***-vite/node_modules/vite-plugin-ssr/cli.mjs]
[/home/sherin/projects/***/***-vite/node_modules/vite-plugin-ssr/cli.js]
[/home/sherin/projects/***/***-vite/node_modules/vite-plugin-ssr/cli.json]
 @ ./src/worker/index.js 2:0-48 15:21-30
Error: webpack returned an error. Try configuring `entry` in your webpack config relative to the current working directory, or setting `context = __dirname` in your webpack config.
`

**Comment by brillout** [comment]
Seems like a problem on your side.

**Comment by SherinBloemendaal** [comment]
Steps to reproduce:
- Clone https://github.com/brillout/vite-plugin-ssr/tree/master/examples/cloudflare-workers
- `npm install`
- Go to: `worker/ssr.js` and add `import { prerender } from "vite-plugin-ssr/cli";` or `const { prerender } = require("vite-plugin-ssr/cli");`
- `npm run dev:miniflare` and you can see the error

What am i doing wrong?

**Comment by brillout** [comment]
Why do you want to use `prerender()` in a worker? AFAICT this doesn't make
sense.

**Comment by SherinBloemendaal** [comment]
> Our use case: We are building a website editor, the structure/content is saved in our Api as JSON and its possible to publish these changes afterwards (transform the JSON to a static generated website). We want to build a micro service that simply receives a JSON and outputs a list of static generated files wich we can fetch and put on a S3 bucket or anything else for example. We want to use a Cloudflare worker for this.

We want to "prerender" dynamic content.

**Comment by brillout** [comment]
`vite-plugin-ssr/node/prerender.ts` has not been designed to work in a Worker.

That said, you can try to modify it to make it work.

If you manage to do it, I'll consider merging your changes in.

**Comment by brillout** [comment]
I'm just realizing, an OSS collaborator of mine is looking for freelancing work; so if that's something you'd be up to, we can make it work in exchange for monetary compensation.

**Comment by SherinBloemendaal** [comment]
> I'm just realizing, an OSS collaborator of mine is looking for freelancing work; so if that's something you'd be up to, we can make it work in exchange for monetary compensation.

Okay thank you, we can talk about this via the email. You can contact me at sherin@maglr.com. Thanks :)

**Comment by brillout** [comment]
I'll contact you shortly. Sure :-), win-win situation I guess :-).

**Comment by SherinBloemendaal** [comment]
Did you already e-mail me? I haven't received anything yet. 

Thanks.

Kind regards,
Sherin

**Comment by brillout** [comment]
Yes I did send an email to sherin@maglr.com

> Hi Sherin,
> 
> As discussed on GitHub, we (me and potentially a collaborator of mine) can implement https://github.com/brillout/vite-plugin-ssr/issues/213 on a contract basis.
> 
> We can implement #213 blindly without knowing much about your use case, but it's probably best to know more (than what you already shared in https://github.com/brillout/vite-plugin-ssr/issues/201#issue-1048772317), so that we can foresee any potential problems beyond just implementing #213.
> 
> Kind regards,
> Rom

**Comment by SherinBloemendaal** [comment]
Hi,

We are still interested but i prefer using the email to discuss. I checked my spam but got nothing. Can you please send me an email again?

**Comment by brillout** [comment]
Just re-sent you the email.
