### ISSUE TITLE
[feat] API/POST endpoints without a front

### ISSUE THREAD

**Issue by magne4000** [brillout/vite-plugin-ssr#202]
### Use case
I need to be able to have API endpoints (mostly POST requests) that will be called not by a user, but by other server (e.g. a CRON that calls a `/api/something`, with an API key).
- Those endpoints are never shown to the user
- They are only server side
- They do not need to go through rendering UI

I'm using `vite-plugin-ssr` with Vercel, but this applies to all types of deployments.

### Current limitations
- All posts are going through `api/render.ts` (Vercel specific)
  - Here I add `body` from the request to the pageContext
- Declare a `.page.server.ts` with exported `onBeforeRender` to handle the request
  - I can read the `body` fron the pageContext
- Also declare `.page.client.ts` or `.page.ts` otherwise `vite-plugin-ssr` generates an error
- Return specific data in `onBeforeRender`, like `{ pageContext: { noRender: true } }`
- In `api/render.ts`, handle the specific case where `noRender` is true

### What would I want?
- `api/render.ts` calls `renderPage`, which could be avoided because I know I do not want to render
- Be able to simply create a new `api/?` enpoint, or something as simple as that
- Probably utils to allow/forbid endpoints a POST endpoints
- A solution could be to not require `.page.client.ts` behind some logic, or have other files like `.api.server.ts` to handle post requests

This is kinda specific to Vercel regarding the use of `api/render.ts`, with a tweak to the rewrites config and the localhost server, I think I could easily fix this, but I wonder if we could have a generic reusable way to do POST requests across platforms.

**Comment by brillout** [comment]
Yes rewrite seems to be the canonical way to do it. For example:

```
{
  "rewrites": [
    {
      "source": "/((?!api/).*)",
      "destination": "/api/render.js"
    }
  ]
}
```

So that all URL `/api/*` requests aren't routed to the file `/api/render.js`.

Let me know how it goes.

**Comment by brillout** [comment]
In general I believe that API is out of scope for this plugin. Let me know if you disagree.

And keep me in touch what you ended up doing.

**Comment by magne4000** [comment]
> In general I believe that API is out of scope for this plugin. Let me know if you disagree

I agree. The minimal requirement regarding this matter is that this plugin should not block or make it more difficult to handle API calls. Perhaps the existing examples should include an example that demonstrate how to still handle API calls next to this plugin. It may be trivial for some, but for Vercel it isn't

> Let me know how it goes.

The `vercel.json` I'm using (not fully tested yet in production, will be edited if something doesn't work)
```vercel.json
{
  "rewrites": [
    {
      "source": "/((?!(assets|api)/).*)",
      "destination": "/api/render.ts"
    }
  ]
}
```

<hr>

In `server/index.ts` (local express dev server)
```ts
// one import per endpoint
import something from '../api/something';

// Add the following above `app.get('*', ...`
app.all("/api/something", something); // one of these per imported endpoint
```
There probably is a solution that could streamline this thanks to an express middleware.

**Comment by brillout** [comment]
Makes sense 👍 

Btw. we will soon release an RPC implementation (https://twitter.com/brillout/status/1460963504698101774) which will, basically, be a better alternative to Vercel/Next.js's `/api/*` thing.
