### ISSUE TITLE
Next.js & Nuxt Migration Table

### ISSUE THREAD

**Issue by brillout** [brillout/vite-plugin-ssr#209]
For each Next.js / Nuxt feature, a little how to do it with vite-plugin-ssr.

E.g. layouts, nested routes, ...

We can start to collect the mapping in this ticket.

**Comment by brillout** [comment]
`/api/*` -> Telefunc

**Comment by brillout** [comment]
Layout -> https://vite-plugin-ssr.com/default-page#multiple-defaults

**Comment by brillout** [comment]
`getStaticProps()` -> contribution welcome :-)

**Comment by patryk-smc** [comment]
I wrote a small comparison table based on my experience with both vite-plugin-ssr and Next.js. It's definitely not complete but should be a good starting point

[vite-vs-next.csv](https://github.com/brillout/vite-plugin-ssr/files/8080797/vite-vs-next.csv)

**Comment by brillout** [comment]
@patryk-smc That's actually quite convenient 👌. I will add this to vps's docs once the goal is to maximize the number of users. (The goal right now is to release Vike.)

**Comment by brillout** [comment]
Closing because of lack of interest.

That said, contribution much welcome to write such mgiration table.
