### ISSUE TITLE
Pre-rendering in Cloudflare Workers

### ISSUE THREAD

**Issue by brillout** [brillout/vite-plugin-ssr#213]
`vite-plugin-ssr/node/prerender.ts` is currently not been designed to work in a Cloudflare Worker.

But, in principle, it should be possible to run pre-rendering in a Cloudflare Worker.

**Comment by brillout** [comment]
@SherinBloemendaal Closing but let me know if you still need this.

**Comment by brillout** [comment]
Done.

Example:
 - https://vite-ssr-worker.brillouttests.workers.dev/
 - https://vite-ssr-worker.brillouttests.workers.dev/prerender

I'd suggest following API:

```js
import { prerender } from 'vite-plugin-ssr/cli'

// Analogous to `pageContextInit` in `renderPage()`.
const pageContextInit = {
  // Make Cloudflare Workers's `fetch()` available as `pageContext.fetch`.
  fetch: (...args) => fetch(...args),
}
const onPagePrerender = (filePath, fileContent) => {
  // We can do whatever we want with the prerendered page result
  // E.g. write `fileContent` to `/tmp/${filePath}`
}
await prerender({ pageContextInit, onPagePrerender })
```

@SherinBloemendaal Would that work for you?

**Comment by SherinBloemendaal** [comment]
> Done.
> 
> Example:
> 
> * https://vite-ssr-worker.brillouttests.workers.dev/
> * https://vite-ssr-worker.brillouttests.workers.dev/prerender
> 
> I'd suggest following API:
> 
> ```js
> import { prerender } from 'vite-plugin-ssr/cli'
> 
> // Analogous to `pageContextInit` in `renderPage()`.
> const pageContextInit = {
>   // Make Cloudflare Workers's `fetch()` available as `pageContext.fetch`.
>   fetch: (...args) => fetch(...args),
> }
> const onPagePrerender = (filePath, fileContent) => {
>   // We can do whatever we want with the prerendered page result
>   // E.g. write `fileContent` to `/tmp/${filePath}`
> }
> await prerender({ pageContextInit, onPagePrerender })
> ```
> 
> @SherinBloemendaal Would that work for you?

Yes, it would also be nice to get a list of assets for each page optionally. Is that possible?

**Comment by brillout** [comment]
Yes, all static assets live at `$root/dist/client/` so that's not a problem.

**Comment by brillout** [comment]
We can simply do this:

```js
const onPagePrerender = (filePath, fileContent, pageContext) => {
  // We can do whatever we want with the prerendered page result
  // E.g. write `fileContent` to `/tmp/${filePath}`
  const pageAssets = await pageContext._getPageAssets();
}
```

**Comment by SherinBloemendaal** [comment]
> We can simply do this:
> 
> ```js
> const onPagePrerender = (filePath, fileContent, pageContext) => {
>   // We can do whatever we want with the prerendered page result
>   // E.g. write `fileContent` to `/tmp/${filePath}`
>   const pageAssets = await pageContext._getPageAssets();
> }
> ```

That would be nice. Does that function already exist?

**Comment by brillout** [comment]
No but it's quick to implement. The main difficulty was to be able to run pre-rendering on Cloudflare Workers which now works.

**Comment by SherinBloemendaal** [comment]
> No but it's quick to implement. The main difficulty was to be able to run pre-rendering on Cloudflare Workers which now works.

Ok that would be very nice. If that feature is implemented, then we can start testing it :)
