### ISSUE TITLE
Nested template / alternative PageWrapper

### ISSUE THREAD

**Issue by oliverpool** [brillout/vite-plugin-ssr#214]
Thank you for this great library.

I have a question regarding nested template / PageWrapper.

I want to generate a site with a blog (however the site is not only a blog).
How can I specify a different template for the blog articles (which are markdown files) ?

Currently I have the following structure:
```
renderer/_default.page.server.ts // import { createApp } from "./app"; 
renderer/app.ts                  // function createApp(...) {...   return h(PageWrapper, ...)
renderer/PageWrapper.vue // default Wrapper

pages/blog/_PostWrapper.vue // Wrapper I want to use for blog articles

pages/index/index.page.vue
pages/blog/2020/eine-idee-nimmt-gestalt-an.page.md
```

The markdown rendering is working fine thanks to `vite-plugin-md`, however I would like the blog articles not to be rendered inside `PageWrapper`, but in another template (to render the title for instance).

How can I achieve this ?

---

### Attempt 1: add a `pages/blog/_default.page.server.js` file with the following content:
```
import { render as renderRoot } from "../../renderer/_default.page.server";

import PostWrapper from "./_PostWrapper.vue";

export const passToClient = ["pageProps", "urlPathname"];
export { render };

async function render(pageContext) {
  pageContext.PageWrapper = PostWrapper;
  return renderRoot(pageContext);
}
```

And adjust the `createApp` function with `h(pageContext.PageWrapper || PageWrapper,...)`

However the browser console complaints:
> Uncaught (in promise) Error: [vite-plugin-ssr@0.3.19][Wrong Usage] `pageContext.PageWrapper` is not available in the browser. Make sure that `passToClient.includes('PageWrapper')`. (Currently `passToClient` is `['pageProps', 'urlPathname']`.) More infos at https://vite-plugin-ssr.com/passToClient

I also tried embedding my `PageWrapper` on the `pageContext.Page`, but it triggers another error in the browser:
> [Vue warn]: Hydration children mismatch in <div>: server rendered element contains fewer child nodes than client vdom. 

---

There is probably some easier (and more correct) way to achieve this, but I can't figure it out...

I would greatly appreciate any help or example !

**Comment by brillout** [comment]
There are many ways to achieve this but the `vite-plugin-ssr` idiomatic way is to have two different renderers.

See https://vite-plugin-ssr.com/default-page#multiple-defaults.

Does that make sense to you?

Thanks for reaching out, it's something important missing in the docs.

**Comment by brillout** [comment]
Although, if the rendering differs only for one page, you can also use a `pageContext.pageExports.skipPageShell` instead of having 2 renderers, e.g. https://github.com/vikejs/vike.land

**Comment by oliverpool** [comment]
I have tried adding a `_default.page.client.js` (I was confused at first, because it doesn't support `render`, I need to define `hydrate`).

I now have the following files:
`pages/blog/_default.page.client.js`
```
import { hydrate as hydrateRoot } from "../../renderer/_default.page.client";

import PostWrapper from "./_PostWrapper.vue";

hydrate();

async function hydrate() {
  console.log("BLOG");
  await hydrateRoot(PostWrapper);
}
```

`pages/blog/_default.page.server.js`
```
import { render as renderRoot } from "../../renderer/_default.page.server";

import PostWrapper from "./_PostWrapper.vue";

export const passToClient = ["pageProps", "urlPathname"];
export { render };

async function render(pageContext) {
  return renderRoot(pageContext, PostWrapper);
}
```

And I adjusted the `createApp` function with `h(pageWrapper || DefaultPageWrapper,...)` (taken as argument).

It still logs a `Hydration completed but contains mismatches.`

Moreover it breaks the home page (the custom template is shown, as well as the hydration mismatch log). Strangely enough I can see the `BLOG` log on the homepage, but according to https://vite-plugin-ssr.com/default-page#multiple-defaults the code of `pages/blog/_default.page.client.js` should only apply for blog pages.

Do you have any any what am I doing wrong?

**Comment by brillout** [comment]
> Moreover it breaks the home page (the custom template is shown, as well as the hydration mismatch log). Strangely enough I can see the `BLOG` log on the homepage, but according to https://vite-plugin-ssr.com/default-page#multiple-defaults the code of `pages/blog/_default.page.client.js` should only apply for blog pages.

Move them to `pages/blog/renderer/_default.page.*` (create a `renderer/` directory), does it work then?

If it still doesn't then give me your `git ls-files`

**Comment by oliverpool** [comment]
> create a `renderer/` directory

Ah right, I overlooked that!

---

In the meantime, I found a working solution: make the wrapper depend on the url:

`renderer/app.ts`
```ts
function createApp(pageContext: PageContext) {
  const { Page, pageProps } = pageContext;
  var pageWrapper = DefaultPageWrapper;
  if (
    pageContext.urlPathname.startsWith("/blog/") &&
    pageContext.urlPathname != "/blog/"
  ) {
    pageWrapper = PageWrapperBlog; // here it is!
  }
  const PageWithLayout = defineComponent({
    render() {
      return h(
        pageWrapper,
        {},
        {
          default() {
            return h(Page, pageProps || {});
          },
        }
      );
    },
  });
```

I removed all the `_default.*` files and it seems to work fine!

This fulfills my requirement, and I don't see any drawback to this solution.

Thank you so much for you very quick replies and your input!
