### ISSUE TITLE
How to redirect + `useClientRouter` ?

### ISSUE THREAD

**Issue by chrisvariety** [brillout/vite-plugin-ssr#22]
As far as I can tell, the `render` function isn't called during client-side routing, so the current way to redirect outlined in the Readme doesn't seem to work when also using client-side routing. I tried using `navigate`, which worked well for client-side, but errors out when accessing the URL directly because `navigate` cannot be called on the server (see also #21). Is there a universal way to use client-side routing + redirects?

I could do something like this but it feels tacky:

```js
// movie.page.server.js
export { render }

function render({ contextProps }) {
  if (contextProps.movieId === null) {
    return { redirectTo: '/movie/add' }
  }
}

// movie.page.js
import { navigate } from "vite-plugin-ssr/client/router";

export { Page };

const Page = ({ movieId }) => {
  if (typeof window !== 'undefined' && movieId === null) {
    navigate('/movie/add');
  }

  return ...;
};
```

Thanks in advance!

**Comment by chrisvariety** [comment]
A few separate notes on `useClientRouter`, happy to open a separate issue, just let me know.

1. It doesn't look like it forwards along query strings when calling the internal `index.pageProps.json` route, so something like this always returns `1` when rendering client-side, but returns the correct page server-side:

```js
async function addContextProps({ contextProps }) {
  return {
    page: parseInt(contextProps.request.query.page) || 1
  };
}

function setPageProps({ contextProps: { page } }) {
  return { page };
}
```

2. The response to the internal `index.pageProps.json` route is being served as `text/html` instead of `application/json`, at least in my config. This doesn't detrimentally impact anything as far as I can tell, just figured I'd flag it as something semi-weird.

**Comment by brillout** [comment]
0. See https://github.com/brillout/vite-plugin-ssr/commit/b30248d00dbab1ce9abcbcba8b6e2625e56738d2. Let me know if that works for you.
1. Let me implement this. I'll let you know once it's implemented, ETA today.
2. Yes that's because Express doesn't set the content type based on the URL (the URL ends with `.json` so it should be clever enough to set the content type accordingly but it unfortunately doesn't). It shouldn't cause problems though. If it does then let me know; and you can then also correct the content type at your server integration point until a fix is released.

**Comment by chrisvariety** [comment]
@brillout b30248d works great, thanks so much for the additional clarity. 

Happy to close this out or leave it open for "1", up to you.

**Comment by brillout** [comment]
1 is done; 4d58d4c.

Handling query strings is quite intricate; I may have missed some detail. Let me know if you run into any hiccup.

I will release in a moment.

> Happy to close this out or leave it open for "1", up to you.

We can leave this open until you have tried and are happy with 1.

**Comment by chrisvariety** [comment]
Seems to be working great, thanks again @brillout !!
