### ISSUE TITLE
[Workarounds] HTML transformers not applied for SSR apps

### ISSUE THREAD

**Issue by brillout** [brillout/vite-plugin-ssr#224]
HTML transformers are not applied in production.

Most notably:
 - vite-plugin-pwa
 - Vite Plugin HTML minifiers.
 - Vite's built-in Base URL rewriter.
   > (Which rewrites `<link rel="icon" href="/favicon.png">` to `<link rel="icon" href="/some/base-url/favicon.png">`.)

[In production Vite is not loaded at all](https://github.com/brillout/vite-plugin-ssr/issues/402) which means that we cannot apply HTML transformers in production.

> That said, it should be possible to apply HTML transformer for pre-rendered apps, see [#354 - comment](https://github.com/brillout/vite-plugin-ssr/issues/354#issuecomment-1174976350).

### Workaround: vite-plugin-pwa

See https://github.com/brillout/vite-plugin-ssr/issues/388#issuecomment-1199280084.

### Workaround: HTML minifiers

Use a HTML minifier directly in your `render()` function instead of using a Vite plugin HTML minifier.

### Workaround: Base URL

Instead of:

```js
// _default.page.server.js

export function render() {
  return escapeInject`
    <html>
      <head>
        <link rel="icon" href="/logo.svg" />
      </head>
      <body>
        <!-- ... -->
      </body>
    </html>`
}
```

Do this:

```js
// _default.page.server.js

import logoUrl from './logo.svg'

export function render() {
  return escapeInject`
    <html>
      <head>
        <link rel="icon" href="${logoUrl}" />
      </head>
      <body>
        <!-- ... -->
      </body>
    </html>`
}
```

Or this:

```js
// _default.page.server.js

export function render() {
  return escapeInject`
    <html>
      <head>
        <link rel="icon" href="${import.meta.env.BASE_URL + '/logo.svg'}" />
      </head>
      <body>
        <!-- ... -->
      </body>
    </html>`
}
```

**Comment by brillout** [comment]
For pre-rendered apps, see https://github.com/brillout/vite-plugin-ssr/issues/354.

**Comment by coryvirok** [comment]
I've been trying to figure out how to minify my html for prerendered pages.

You mention a workaround is to use an html minifier in `render()` but I'm not sure how to get that to work, since `render()` is expected to return a "string generated with the `escapeInject` template tag".

Here's what I've tried:

```js
export async function render(pageContext: PageContextServer) {
  const html = escapeInject`<!DOCTYPE html>
    <html lang="en">
      ...
    </html>`

  // @ts-ignore
  if (pageContext._isPreRendering) {
    const minifier = await import('html-minifier')
    const res = minifier.minify(html.toString())
    console.log('>>>>>>>>', res.toString())
    return res
  }
  return html
}
```

Which results in the error:

```
>>>>>>>> [object Object]
Error: [vite-plugin-ssr@0.4.54][Wrong Usage] The `render()` hook exported by /src/pages/_default.page.server.ts returned a plain JavaScript string which is forbidden; instead, it should return a string generated with the `escapeInject` template tag or a string returned by `dangerouslySkipEscape()`, see https://vite-plugin-ssr.com/escapeInject
    at executeRenderHook (node_modules/vite-plugin-ssr/dist/cjs/node/renderPage.js:550:33)
    at async prerenderPage (node_modules/vite-plugin-ssr/dist/cjs/node/renderPage.js:335:30)
    at async node_modules/vite-plugin-ssr/dist/cjs/node/prerender.js:304:57
```

How would you recommend using an html minifier in `render()`?

**Comment by brillout** [comment]
I'd apply an HTML minifier on `const { httpResponse: { body } } = await renderPage({ urlOriginal })`.

**Comment by coryvirok** [comment]
Thx. However that code isn't run during pre-rendering. But your suggestion makes me think this is better done as a separate build step after `vite build`.
