### ISSUE TITLE
Setting `cssCodeSplit: false` results in no CSS injected to generated html

### ISSUE THREAD

**Issue by spacedawwwg** [brillout/vite-plugin-ssr#225]
```
import vue from '@vitejs/plugin-vue';
import ssr from 'vite-plugin-ssr/plugin';
import { UserConfig } from 'vite';
import path from 'path';

const config: UserConfig = {
  resolve: {
    alias: {
      '~': path.resolve(__dirname, './src'),
    },
  },
  plugins: [vue(), ssr()],
  build: {
    cssCodeSplit: false,
  },
};

export default config;
```

**Comment by brillout** [comment]
That's probably a Vite bug. Closing until shown otherwise.

**Comment by spacedawwwg** [comment]
@brillout correct, after you said that I went looking and it seems it's been fixed in Vite 2.7 beta https://github.com/vitejs/vite/commit/51a02ff902c3afa4dff76b43f75b9221768cd7f8

**Comment by spacedawwwg** [comment]
Though, having tested with 2.7.0-beta.9 it is still an issue so it might be worth monitoring

**Comment by spacedawwwg** [comment]
@brillout as of vite 2.9, `cssCodeSplit: false` still is not injected into the SSR html.

How is the CSS injected into VPS? I'm wondering if there is something I can investigate why this would not work for VPS but does in a standard vite app.

**Comment by brillout** [comment]
What is happening and what are you expecting instead?

**Comment by spacedawwwg** [comment]
Rather than multiple CSS files generated, a single CSS file is compiled.
<img width="554" alt="image" src="https://user-images.githubusercontent.com/1691867/176609593-1426d4b5-1d65-4ff9-9762-49baea3d024e.png">
The single CSS file is generated and available in assets.

The same as the multiple CSS files are injected into the head, I'd expect the same for the single generated file

**Comment by brillout** [comment]
Why do you want this?

Curious; you seem to import CSS from `.page.route.js` files, why do you do this?

**Comment by brillout** [comment]
vps doesn't do the splitting, it's a Rollup thing. Note, however, that the vps client entry uses dynamic imports which probably explains why you observe certain splitting behavior with vps and not with Vite.

As for your motivation, I don't understand it. I don't see how CSS is a performance bottleneck for your app, and I see even less how what you want to achieve would help.

**Comment by spacedawwwg** [comment]
> vps doesn't do the splitting, it's a Rollup thing. Note, however, that the vps client entry uses dynamic imports which probably explains why you observe certain splitting behavior with vps and not with Vite.
> 
> As for your motivation, I don't understand it. I don't see how CSS is a performance bottleneck for your app, and I see even less how what you want to achieve would help.

@brillout Yes, I understand the splitting is not a VPS thing and the bundling of JS works exactly as I'd expected it would when I use `manualChunks` for splitting each of my Vue components (as with any other Vite app I build without VPS). It reduces the size of the bundled `_default.page.client.js` drastically and only loads in the component JS it needs for each page (rather than the default bundling that seems to create quite a massive single payload that includes more component code that each page needs).

Unfortunately, what that chunking also does is create an individual CSS file for each of those Vue.js components, meaning i have ~20 CSS files being injected into the HTML page (and Lighthouse isn't a fan of that). Instead I want to bypass that by using `cssCodeSplit: false` and then use PurgeCSS to strip out any CSS not used after an SSG build has run.

Also, another great thing about `cssCodeSplit: false` is that it is really beneficial for compiling things like async component CSS, which by default does not get injected when using SSR. So even though a component is rendered on the server, the CSS is only loaded by JS and 'non-js' users get unstyled server rendered component (which isn't great).

If `cssCodeSplit: false` is a Vite setting/feature VPS is not going to support, that's obviously fine. I just wouldn't mind knowing "why?" and maybe also a note in the documentation with a reason why it isn't supported (as I imagine other users may wonder why a core setting does not work for them, too).

**Comment by brillout** [comment]
> the default bundling that seems to create quite a massive single payload

I didn't observe that, nor did any other user. Create a minimal reproduction showcasing what you mean and I'll have a look at it.

Rather than fighting Rollup's way of splitting, let's see if we can fix it at its core.

**Comment by spacedawwwg** [comment]
@brillout I'm wondering if we can maybe look into the `cssCodeSplit: false` setting again

I didn't want to pen a new issue as we'd discussed it here already.

I have put together a minimal reproduction. This is the vue-ts template with `cssCodeSplit: false` simply added to `vite.config.ts`.

To reproduce the issue of the CSS not being injected into the HTML, you need to run the build in production (i.e. not in dev mode)

https://github.com/spacedawwwg/vite-css-code-split-reproduction

**Comment by brillout** [comment]
Indeed I could reproduce.

It's a Vite bug: if you look at `dist/client/manifest.json` (generated by Vite), you'll see that, while the `style.css` entry is in there, the manifest is missing the `css` arrays referencing `style.css`. Compare with `cssCodeSplit: true`.

**Comment by spacedawwwg** [comment]
I've just tested this after upgrading to vite 4, the style.css is not generated in the manifest but is not injected with vite plugin ssr. I will take a look into your source doe and see if if I can find the issue

**Comment by brillout** [comment]
👍 Keep me updated.

**Comment by spacedawwwg** [comment]
@brillout from what I can tell, it seems to be that the asset is skipped over around `getManifestEntry` and `findEntryWithKeyEnd` 

Looking at `getManifestEntry`, I'm not 100% sure what the rule would need be to allow `style.css` to be added as an entry file. Just wondering if you could maybe point me in the right direction?

**Comment by brillout** [comment]
The `style.css` manifest entry isn't referenced anywhere in the manifest, correct? Maybe we can add a rule "if there is a `style.css` entry that isn't referenced anywhere and there is no other CSS then include it". Correct me if I'm wrong but I believe that should be a fairly reliable workaround.

**Comment by brillout** [comment]
Fixed, see https://github.com/brillout/vite-plugin-ssr/issues/644.
