### ISSUE TITLE
Pass data to layout before render

### ISSUE THREAD

**Issue by Mushroomfunk** [brillout/vite-plugin-ssr#226]
Hello, thank you for this library, its pretty cool. 
I have a question, i need to fetch data and pass it to my layout before render, how can i do this without vue-router, with standart library routing? As far as I understand i can call onBeforeRender only at "page" (server or not) files, but i need pass data with navigation and other from my API to layout, e.g. PageShell.vue in renderer folder.

**Comment by brillout** [comment]
Thanks for opening this ticket.

Updated the docs: https://vite-plugin-ssr.com/data-fetching#global-data.

Do you still have questions?

**Comment by brillout** [comment]
There is a bug in the deploy script, changes are not live yet.

**Comment by brillout** [comment]
Live now.

**Comment by brillout** [comment]
https://vite-plugin-ssr.com/data-fetching#global-logic

**Comment by pooledge** [comment]
Hmm I might be wrong but I guess what @Mushroomfunk mentions here is a way to pass some data, which is common for multiple pages, rather than requesting it in the context of each page. E. g. navigation could be requested only once on server to build a static menu outside of an interchangeable page component. 

@Mushroomfunk could you maybe provide us with an example you are trying to achieve this within?

**Comment by brillout** [comment]
> E. g. navigation could be requested only once on server to build a static menu outside of an interchangeable page component.

I would have said that https://vite-plugin-ssr.com/data-fetching#global-logic does answer that question, but seems like you disagree?

**Comment by pooledge** [comment]
Meaning `_default.page.server.js` is where the server-side fetching and injection would take place regardless of the entry I guess?

**Comment by Mushroomfunk** [comment]
@brillout @pooledge `onBeforeRender()` in `_default.page.server.ts` always runs when we change page in browser, but i need to call this function on server only once when user opens site and pass data from it to my layout file. 
I tried to implement it by adding new property with async fetched data in `pageContextInit `object in `server/index.js` (from vue-full example), but it breaks prerendering and only works on dev server.

**Comment by pooledge** [comment]
Ah, I guess @Mushroomfunk tries to achieve somewhat isomorphic data fetching mechanism combining `onBeforeRender()` hook [for a page](https://vite-plugin-ssr.com/data-fetching#client-routing) skipping the `onBeforeRender()` hook of `_default.page.server.js` every time **but initially**. This all given Client Routing is in place.

A good example of this model is [`load()` function](https://kit.svelte.dev/docs#loading) for a single SvelteKit's layout as it only runs **once** on server upon app initialisation, opposed to its siblings in pages: fetching data once on SSR **and** later asynchronously on route change in browser.

@brillout correct me if I'm wrong but I don't see how [isomorphic hooks section](https://vite-plugin-ssr.com/onBeforeRender-multiple#isomorphic-hooks) or https://vite-plugin-ssr.com/data-fetching#global-logic covers this scenario. Moreover in attempt to reproduce this I've ran into inability to define `/renderer/_default.page.ts` and `/pages/index.page.ts` alongside `/pages/index.page.vue`: wrong usage is reported in both cases.

**Comment by brillout** [comment]
It does; have you read https://vite-plugin-ssr.com/onBeforeRender-isomorphic?

**Comment by Mushroomfunk** [comment]
Rom, can you please make an example where be initial data fetch one time in layout of overall app when user opens any route, and inject this data to SSR? With client routing.
I will be really grateful. Maybe i'm stupid and don't fully understand how library works.

**Comment by Mushroomfunk** [comment]
Without call this data fetch when user navigate over pages of couse.

**Comment by brillout** [comment]
@Mushroomfunk Does https://vite-plugin-ssr.com/data-fetching#global-logic answer your question?
