### ISSUE TITLE
Can not add any page

### ISSUE THREAD

**Issue by YouYII** [brillout/vite-plugin-ssr#227]
runtime-core.esm-bundler.js:6591 [Vue warn]: Invalid vnode type when creating vnode: null.
[Vue warn]: Hydration children mismatch in <div>: server rendered element contains more child nodes than client vdom. 

Reproduction process

1. Initialize a project 'NPM init vite plugin SSR'. Here I use Vue ts

2. Copy about / index.page.ts as test.page.ts

3. Visit http://localhost:3000/about/test

Note that you must manually restart the dev server before this problem occurs. If you perform a hot reload, you cannot encounter this problem

"dependencies": {
    "@types/express": "^4.17.13",
    "@types/node": "^16.11.0",
    "@vitejs/plugin-vue": "^1.9.3",
    "@vue/compiler-sfc": "^3.2.20",
    "@vue/server-renderer": "^3.2.20",
    "cross-env": "^7.0.3",
    "express": "^4.17.1",
    "ts-node": "^10.3.0",
    "typescript": "^4.4.4",
    "vite": "2.6.7",
    "vite-plugin-ssr": "^0.3.33",
    "vue": "^3.2.20"
  }

**Comment by brillout** [comment]
Doesn't seem to be a problem with vite-plugin-ssr.

Let me know if you disagree.
