### ISSUE TITLE
Cannot read property 'modules' of undefined at _sfc_main.setup

### ISSUE THREAD

**Issue by txus2202** [brillout/vite-plugin-ssr#228]
Good Morning,
First of all, I apologize if this problem does not apply here, it is not my intention to disturb.

I have run into a problem when trying to make **npm link** between a component library and my vue project with vite ssr pluggin.

The steps that I follow are the following:
1. run` npm link` in my component library.
2. run `npm link components-library` in my vue project with vite ssr plugin.
3 run `npm run dev` in my vue project with vite ssr plugin.

At that time when I visit localhost the server throws me the following error:
```
TypeError: Cannot read property 'modules' of undefined
     at _sfc_main.setup (/node_modules/components-library/src/components/myComponent/index.vue:43:16)
```

if I do not perform the npm link, everything works correctly with my dependency, the fact is that I need to work with npm link.

Does anyone know if it's a vite ssr plugin problem or something else?
Thank you very much in advance.

**Comment by brillout** [comment]
It's not related to vite-plugin-ssr. Try to update @vitejs/plugin-vue to its latest version.

**Comment by txus2202** [comment]
thank you so much for the idea.
Sorry for the disturbances.

**Comment by Krevetco** [comment]
it helped! thanks a lot
