### ISSUE TITLE
Possible memory leak in the solid example 

### ISSUE THREAD

**Issue by makoven** [brillout/vite-plugin-ssr#229]
When you run the [solid example](https://github.com/brillout/vite-plugin-ssr/tree/master/examples/solid), a warning:
"computations created outside a createRoot or render will never be disposed"
appears in the console.

https://github.com/solidjs/solid/issues/759

The author of the solid @ryansolid suggested that _"something is being rendered not under the synchronous execution of the reactive graph"_

**Comment by brillout** [comment]
PR welcome

**Comment by ryansolid** [comment]
For anyone interested it was an issue with module resolution in Solid that was unearthed as part of recent updates to Vite. It has been updated in Solid 1.2.6.

**Comment by makoven** [comment]
@ryansolid Thank you for responding so quickly :)
