### ISSUE TITLE
Hybrid Routing

### ISSUE THREAD

**Issue by brillout** [brillout/vite-plugin-ssr#231]
As mentioned in https://vite-plugin-ssr.com/SR-vs-CR Client Routing provides the best performance while Server Routing provides the simplest architecture.

An alternative is to:
 1. Dynamically load the HTML of the next page. (No full page-reload: we use `window.fetch()` to load the HTML.)
 2. Dissect that HTML in the browser-side
 3. Inject the new HTML parts into the DOM

This is common practice outside the JS world, e.g. Ruby on Rails: https://github.com/hotwired/turbo.

The big benefit here is that we keep the simple architecture of Server Routing, while having fast page transitions similar to Client Routing.

Note that Client Routing is still needed for:
 - Highest performance (e.g. for things like https://vite-plugin-ssr.com/onBeforeRender-isomorphic)
 - Component states that need to be preserved upon page changes
 - React Server Components

Server Routing is also still needed for zero browser-side JavaScript.

We could call this *Hydrid Routing*.

**Comment by brillout** [comment]
I will be working on this after we release Telefunc's MVP and Vike's MVP.

**Comment by redbar0n** [comment]
Another option might be to use use Inertia.js ?

> I recently discovered Inertia.js. Which is like HOTwire Turbo (aka. Turbolinks) but sending **JSON over the wire** containing props data and the the name of the client side JS-component to inject it into. So that you could develop an SPA (using React/Vue/Svelte), with the same app mental model and DX, though also **avoiding having an API**. You get this by letting Inertia.js hot-swap components and data (props), and let the **server take care of the routing**. So it occupies this weird spot between an SPA and an MPA, since it, like Turbo, will "serve an MPA off a single page", as you said.
>
>So Inertia uses **client-side rendering** (CSR/SPA) by default, and like Qwik is also saying "not everything needs to be rendered on the server". (Even though Inertia can even do SSR now.)

https://dev.to/redbar0n/comment/1i765

**Comment by redbar0n** [comment]
Why is client routing needed for server components?

**Comment by brillout** [comment]
The custom implementation would much more lightweight than using Inertia.js.

Client Routing is optional; you don't need it and hydrid routing won't actually use it.

**Comment by redbar0n** [comment]
>Note that Client Routing is still needed for:
>…
>* React Server Components

I didn’t understand this.. what did you mean?

**Comment by redbar0n** [comment]
one downside with fetching the entire page HTML (like Turbolinks did), is that it’s slightly more data sent over the wire, but more importantly: the data for the unused parts of the page would be populated from the DB:

https://twitter.com/ryanflorence/status/1318977141422264320?s=21

So it ought to be some way to receive partial pge updates and only trigger the resolvers needed to populate that part of the page…

Maybe @ryansolid has some ideas here. He’s all about partial page hydration, and has a vested interest in awesome SSR for Vite since it would benefit @solidjs

**Comment by brillout** [comment]
Most apps don't need partial page transitions; full transitions are usually good enough.

For apps where partial page transitions make a real difference, they can use React 18 + Client Routing. (React 17 doesn't support partial data fetching.)

As for RSC, in principle, it should be possible to fetch the React elements of the new page without doing Server Routing. But it has to be seen how RSC evolves.

**Comment by doeixd** [comment]
> So it ought to be some way to receive partial pge updates and only trigger the resolvers needed to populate that part of the page…
> 

Nested routing would help solve this problem



>An alternative is to:
>
>Dynamically load the HTML of the next page. (No full page-reload: we use window.fetch() to load the HTML.)
>Dissect that HTML in the browser-side
>Inject the new HTML parts into the DOM

If someone is using a frontend js lib like React, Svelte, or Solid, how would hydration of the newly inserted components work? And if this solution is not meant for people using frontend frameworks, why can't the user just use htmx/turbolinks/unpoly paired with nested routing themselves?

**Comment by ryansolid** [comment]
I think the tricky part to consider with nested hybrid routing is that parts of the UI outside of the route may also need to change. Like the navigation bar selection. We could handle this with Islands to be sure but it does mean slightly different requirements for what is considered interactive.

There is also the question of reload on mutation as well. To be fair this isn't limited to nested routing, but SPA patterns could refresh all the data and maintain state where MPAs will reload the whole page. Being in this middle ground this is one place where SPA type behavior is actually more beneficial. However, it poses a difficult question when certain rendering is only ever available on the server. In essence we do need to re-render the whole page on the server but probably need to preserve our Islands.

**Comment by redbar0n** [comment]
@brillout you should watch these sections from Ryan and Nikhil's recent stream on [Partial Hydration? + Hybrid Nested Routing](https://youtu.be/eAwuPvRXNdY?t=10802) (using the [Islands Architecture](https://www.patterns.dev/posts/islands-architecture/)). In a lot of ways it surpasses the [Hotwire.dev](https://hotwired.dev/) Turbo + Stimulus approach. 
* Pro:
  * Less kB over-the-wire (since [Solid is smaller than Stimulus](https://twitter.com/magnemg/status/1556690067527188482?s=20&t=_zlHSofs58V1pocXzxBimA))
  * Preserves familiar JSX component tree (known from React and Solid).
* Con: 
  * Islands architecture might introduce some sneaky cases with inter-component communication, and enforce some more discipline on developers.

**Comment by brillout** [comment]
@ryansolid Thanks for the reply.

@redbar0n Thanks for the resources.

I think it's too early to tell whether it makes sense: the ecosystem is evolving a lot (e.g. offscreen rendering and server components which both involve the routing process). It's not clear where things will end up. Let's wait and see how the dust settles.

For now, supporting Server Routing as well as Client Routing works out for the vast majority of users, if not all.

Closing in the meantime. We can re-open this if a need arises for it.

**Comment by redbar0n** [comment]
Leaving this here for future inspiration, showing Svelte's hybrid with their `use:enhance` attribute: https://youtu.be/3QEoJRjxnxQ?t=3991

**Comment by redbar0n** [comment]
SolidStart’s take on hybrid routing: https://github.com/solidjs/solid-start/issues/400
