### ISSUE TITLE
Build fails with "custom directive is missing corresponding SSR transform and will be ignored" error

### ISSUE THREAD

**Issue by DhvanilPatel** [brillout/vite-plugin-ssr#233]
Hi — firstly, thank you so much for this wonderful Vite plugin. It has saved me so much time! :)

I'm using [vue-lazyload-next](https://github.com/caozhong1996/vue-lazyload-next) for lazy loading images for my SSR application. 

However, when I run the command `npx vite build && npx vite build --ssr && npx vite-plugin-ssr prerender` to build the site, I'm facing this error — `[vite:vue] Custom directive is missing corresponding SSR transform and will be ignored.`

Can you recommend me what to do in this case? If there are any other libraries for lazy-loading which work well with SSR, please feel free to recommend them as well.

Thank you so much! ✨

**Comment by brillout** [comment]
Seems a problem with Vite's Vue plugin / `vue-lazyload-next`.

I don't think it's related to `vite-plugin-ssr` thus closing. I'll re-open if shown otherwise.

I would open a ticket at `vue-lazyload-next`'s repo.

**Comment by DhvanilPatel** [comment]
I see. Thanks for your reply. I was able to get it running after using https://github.com/vueuse/patch-vue-directive-ssr :)
