### ISSUE TITLE
Silly Question - Change pages folder on the server

### ISSUE THREAD

**Issue by konoma-lipp** [brillout/vite-plugin-ssr#237]
Hi there

Really like what you have done here.  I apologize in advance for this very long issue, tough my setup seems to be a little weird and therefore it requires some explanation :)

## What I have:

I would like to migrate an existing product to vite-plugin-ssr.

We have multiple customers that are using our product and they need different pages.

During the startup I get an enivronment variable which defines the current customer. Let's call it customerA

## What I would like to do:

Let's assume we do have the following pages folder:

-- pages/customerA/2020/index/index.page.tsx
-- pages/customerA/2020/about/index.page.tsx
-- pages/customerB/2020/index/index.page.tsx
-- pages/customerB/2020/about/index.page.tsx

## Couple of things I have to consider:

- The url I am hitting is something like `http://localhost:5000/en/2020/` or `http://localhost:5000/:language/:year/:others?`
- The language parameter has to be ignored and only passed down as a pageContext value (or I add a route string, but I would like to avoid so many single line *.route.ts files  if it can be  handled otherwise, I know people tend to forget these kind of things), this is only relevant for I18n in the react application
- We have to use client side navigation in order to use transitions and effects
- Based on the customer information I have on the server I would like to set the basePath of the  `pages` directory, basically ignoring all other pages that are not relevant at this point in time and set it to `pages/customerA`
- Client side navigation should work as expected. Keep links like `/en/2020` or `/en/2020/about` 

## What I have tried so far

I started with a `onBeforeRoute` hook that basically works the same as the i18n example in the documentation [here](https://vite-plugin-ssr.com/i18n#with-pre-rendering).

1. Adjusted `_default.page.server.tsx` and updated `passToClient` to include the additional fields `customer, year, language, subPage`
2. Verified in `_default.page.client.tsx` that the custom fields are availble (they are)
3. Added an `onBeforeRoute`  hook which looks like this: 

```
export function onBeforeRoute(pageContext: any) {
  console.log(pageContext);
  let { url, customer, year, language, subPage } = pageContext;

  if (!isNode()) {
    // on the client I do not want to add the customer to the url, so links should look like /<language>/<page> as usual
    return { pageContext: { url: pageContext.url, customer, report, language, subPage } };
  }

  console.log('previous url', url);
  const cleanedUrl = url.replace(`/${language}/`, '');
  const newUrl = `/${customer}/${cleanedUrl}`;

  console.log('new url', cleanedUrl, newUrl);

  return {
    pageContext: {
      customer,
      year,
      language,
      subPage,

      url: newUrl,
    },
  };
}
```

Here are my findings:
1. appending the customer to the url is working fine on the server, the pages are indeed being rendered and then returned to the client
2. since this method is isomorphic the client also executes this method whenever I hover an `<a>` tag. Unfortunately the pageContext does **NOT** include my custom properties anymore. Therefore all of my custom pageContext properties are undefined. (I am assuming I am doing something wrong, or a potential bug?)
3. The routing seems to mismatch now and the client side routing is broken. All clicks result in a full page reload

## Things I could change

1. I could keep the pages file separate per client and only copy the relevant pages for the customer. Tough I fear this might result in some copy/pasting of files and therefore errors if people are not fully aware of what they are doing. 
2. Completely switch to a client side routing solution (i.e react router) and therefore skip the `onBeforeRoute` hook alltogether

Again, sorry for this very long issue. But I appreciate any hints or help :)

Cheers,
Christoph

**Comment by brillout** [comment]
Didn't read the whole thing, but what is your reason to not have one seperate app per customer?

In general, it's better if you tell me exactly what you need from vite-plugin-ssr instead me having to understand your use case which seems quite fringe.

**Comment by konoma-lipp** [comment]
As of now the software is the same for all customers. Hence, no need for multiple applications.

Assuming the following folder structure for the pages:

```
-- pages/customerA/2020/index/index.page.tsx
-- pages/customerA/2020/about/index.page.tsx
-- pages/customerB/2020/index/index.page.tsx
-- pages/customerB/2020/about/index.page.tsx
```

I want to make sure that whenever we have the software running for customerA, only pages from `customerA` are being rendered by the plug-in. The new `pages` directory would be `pages/customerA/` instead of `pages` only.

That sums it up I think ;)

**Comment by brillout** [comment]
There could be many solutions to this, but i'd need to dig into your use case, which would be too time consuming for me to do.

That said, if you believe there is something about vite-plugin-ssr that could be improved that would affect not only you but also many other users, then feel free to let me know.

Closing in the meantime.
