### ISSUE TITLE
Pass extra pageContext while using default onBeforeRender

### ISSUE THREAD

**Issue by loafofpiecrust** [brillout/vite-plugin-ssr#238]
Hi so I'm using `onBeforeRender` in `_default.page.server.tsx` to prerender my React app. I use `urql` for fetching all of my data and in this default `onBeforeRender`, I extract data from the urql cache to pass to the client. Now, I have some paths with route strings and a `prerender()` function in `*.page.server.ts` where I list all the pages to render at those routes:

```ts
export async function prerender() {
  const { data } = await client.query(...)
  return data.pages.nodes
    .map((page) => ({
      url: `/${page.link}`,
    }))
}
```

Now, if I pass `pageContext` with extra information like `{ id: page.id }`, which makes it easier to query data for each specific page, then the _default `onBeforeRender` doesn't get called, meaning the page doesn't do the SSR prepass for initial query results. I'd ideally like to have both; pass `pageContext` here which provides data for `onBeforeRender` to pass as a prop to my component. How can I make this work?

**Comment by brillout** [comment]
Thanks for reaching out; I improved the docs https://github.com/brillout/vite-plugin-ssr/commit/e92104befe2a85e4ceaaf9d39268f47d339eb557.

Does that make sense?
