### ISSUE TITLE
React Server Components

### ISSUE THREAD

**Issue by brillout** [brillout/vite-plugin-ssr#240]
In the context of [Shopify's Hydrogen framework](https://github.com/Shopify/hydrogen), Shopify developed a Vite plugin for React Server Components.

We should explore how we to integrate Vite/vite-plugin-ssr with React Server Components.

Contribution welcome, e.g.:
 - Developing a standalone Vite plugin for React Server Components (@frandiox told me that the plugin developed by Shopify is tightly coupled to Hydrogen).
 - Add a new `examples/react-server-components` to this repository.

See:
 - https://reactjs.org/blog/2020/12/21/data-fetching-with-react-server-components.html
 - https://github.com/facebook/react/pull/22952

**Comment by frandiox** [comment]
The plugin developed in [this PR](https://github.com/facebook/react/pull/22952) is not coupled anymore with Hydrogen. Ideally anyone can use that plugin for RSC.

**Comment by thomasgauvin** [comment]
The link you shared is currently 404ing, do you have an update on this situation? Seems like a dependency on Vite (https://github.com/vitejs/vite/discussions/4591) which depends on React (https://github.com/facebook/react/pull/22952)? This is an awesome framework and it would be great if RSCs were supported

**Comment by brillout** [comment]
Both Vite and the React team are interested. The main piece missing is updating https://github.com/facebook/react/pull/22952 to the [v2 convention](https://github.com/reactjs/rfcs/pull/227).

There just needs someone championing this. @thomasgauvin if you're up for the task, definitely let us know.

**Comment by thomasgauvin** [comment]
Thanks for letting me know! Taking this on isn't something that I can commit to at this time, though I look forward to seeing progress. Any good resources you would share for someone looking to contribute to Vite plugins and this project?

**Comment by brillout** [comment]
Vite's docs + poking around :-).
