### ISSUE TITLE
Renderer Plugins

### ISSUE THREAD

**Issue by brillout** [brillout/vite-plugin-ssr#242]
The idea is that the user can use a renderer plugin instead of writing `renderer/_default.*` files.

```js
// renderer/index.js
// React + GraphQL
export { renderer } from '@vite-plugin-ssr/react-apollo-graphql`
```
```js
// /renderer/index.js
// Vue + RPC 
export { renderer } from '@vite-plugin-ssr/vue-telefunc`

```
```js
// /renderer/index.js
// A company internal custom renderer 
export { renderer } from '@some-org/some-renderer`
```

Users can (completely) overwrite aspects of the `renderer` plugin by defining `renderer/_default.*` files as they do today.

Renderer plugins enable a zero-config DX. In other words, all that's left for the user to do is to write a `/renderer/PageShell.js` and the `/pages/*.page.js` files.

Contribution welcome to implement such renderers.

Write a comment here or hit me up on Discord if you are interested in this, I'll then quickly implement the plugin architecture.

**Comment by naveennamani** [comment]
#275 this may also provide more meaning to this renderer plugins concept.
