### ISSUE TITLE
Preact/compat issue with external React components

### ISSUE THREAD

**Issue by Daiz** [brillout/vite-plugin-ssr#245]
Hello, I've been trying to get a vite-plugin-ssr experiment using Preact going recently, and ran into an issue when trying to use a React component library ([react-icons](https://react-icons.github.io/react-icons/) in this case) that **only** manifest specifically when using the vite-plugin-ssr setup (running on Node 14, but I doubt this is the issue).

[I have a minimal demonstration repository up here.](https://github.com/Daiz/vps-preact-compat-bug) Some notes:

- This setup is based on the react-ts vite-plugin-ssr init, bared down even further.
- `@vite/plugin-react` has been swapped to `@preact/preset-vite` in vite.config.ts.
- I also have [vite-tsconfig-paths](https://github.com/aleclarson/vite-tsconfig-paths) since I was using it in my real repo and wanted to see if it was possibly causing issues. It doesn't seem to be the case though, as:
- Running vite's own dev server (either via `vite` on CLI or via the JS API as seen in [`server-vite.js`](https://github.com/Daiz/vps-preact-compat-bug/blob/master/server-vite.js)) works just fine.
- Running vite in `middlewareMode: "ssr"` and with express works just fine too. (see [`server-express.js`](https://github.com/Daiz/vps-preact-compat-bug/blob/master/server-express.js)).
- It's just when using the vite-plugin-ssr setup ([`server-vps.js`](https://github.com/Daiz/vps-preact-compat-bug/blob/master/server-vps.js)) where trying to get the index page results in the following error:

```
Server running at http://localhost:1337
[vite] Error when evaluating SSR module /pages/index.page.tsx:
Error: Cannot find module 'react' imported from 'I:\Daiz\vps-preact-compat-bug\node_modules\react-icons\lib\cjs\iconBase.js'
    at viteResolve (I:\Daiz\vps-preact-compat-bug\node_modules\vite\dist\node\chunks\dep-0351185a.js:60123:25)
    at Function.<anonymous> (I:\Daiz\vps-preact-compat-bug\node_modules\vite\dist\node\chunks\dep-0351185a.js:60137:20)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (I:\Daiz\vps-preact-compat-bug\node_modules\react-icons\lib\cjs\iconBase.js:26:13)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
```

As the error stack indicates, for whatever reason the react-icons component clearly doesn't seem to get `react` aliased to `preact/compat` which is what `@preact/preset-vite` correctly sets up and which works in all the other setups. As for why it's happening only in this case, I'm honestly kind of stumped. One thing unique to the vite-plugin-ssr setup compared to the others is the usage of [preact-render-to-string](https://github.com/preactjs/preact-render-to-string) in [`renderer/_default.page.server.tsx`](https://github.com/Daiz/vps-preact-compat-bug/blob/master/renderer/_default.page.server.tsx) but I also tried changing [`src/main.tsx`](https://github.com/Daiz/vps-preact-compat-bug/blob/master/src/main.tsx) to use this module for rendering (and setting with innerHTML) in the vite/express dev server setup and that works just fine.

With all this testing it does seem to me like the root of the issue here lies somewhere within vite-plugin-ssr itself, thus why I'm opening this issue.

**Comment by brillout** [comment]
I don't see how vite-plugin-ssr would be the problem here; vite-plugin-ssr doesn't interfere in how Vite resolves modules; I suspect it to be a problem between Vite and Preact.

I'd dig into the error stack you attached which is thrown by Vite.

**Comment by Daiz** [comment]
But as mentioned, this resolve issue happens **only** when using the vite-plugin-ssr server setup. In every other situation, the Vite resolving works just fine.

**Comment by Daiz** [comment]
Well, my next guess is that this could have something to do with Vite's [SSR Externals](https://vitejs.dev/guide/ssr.html#ssr-externals) as the error stack points to Vite trying to load the CJS version of the library when it ships with an ESM version, but at the same time trying to fiddle with config settings related to that seems to produce no results whatsoever, just the exact same result every time...

**Comment by Daiz** [comment]
I guess I can open this issue in the Vite repository instead, since ultimately it seems to be some form of SSR dependency issue with Vite itself, I guess.
