### ISSUE TITLE
CSS Loading is causing content to flash

### ISSUE THREAD

**Issue by alexgrozav** [brillout/vite-plugin-ssr#248]
Hey @brillout! Amazing work on this. 

I'm working on migrating inkline.io to `vite-plugin-ssr`, but I've encountered a blocker. When importing `.scss` files, the content seems to be flashing (both in dev and production build).

Also, I'm wondering if an integration with something like [critters](https://www.npmjs.com/package/critters) could solve the issue.

What do you suggest I do?

Reproduction: https://github.com/inkline/inkline.io/tree/vite-plugin-ssr

![Jan-26-2022 17-27-05](https://user-images.githubusercontent.com/6179477/151193013-6832d970-88a0-49bb-89b7-b3a35071b5ed.gif)

**Comment by brillout** [comment]
Do you have a minimal reproduction for this?

I suspect the problem to be with your codebase. Did you change someting while migrating?

If it's deployed somehwere I can have a look to see if the HTML is nomimal.

**Comment by brillout** [comment]
Had a look; it seems indeed to be a problem with your codebase. Inspect and you'll see that the flashing is caused by two CSS files being loaded at a later point.

**Comment by alexgrozav** [comment]
Thank you for taking the time to look into this! I'll try to recreate the project and copy the files over progressively. Hopefully, that fixes my problem!
