### ISSUE TITLE
Catch-All Routes documentation issue

### ISSUE THREAD

**Issue by magne4000** [brillout/vite-plugin-ssr#250]
The documentation for [Catch-All Routes](https://vite-plugin-ssr.com/catch-all) have an example that sets a `user` prop in `routeParams`, but currently `routeParams` only allows primitive props, not objects.

If `routeParams` should only contain primitive props, how should this example be updated in a way that `await db.fetchUser(userId)` would not have to be called once again in `onBeforeRender`? We could just remove `user` from `routeParams`, but that's not a viable prod solution.

**Comment by brillout** [comment]
Fixed.
