### ISSUE TITLE
Add example for API routes

### ISSUE THREAD

**Issue by sukiejosh** [brillout/vite-plugin-ssr#253]
I was hoping there could be an option to create or enable/disable api routes or you could create an example on how to do that in the examples folder ....thanks, and great work on this library

**Comment by brillout** [comment]
See https://vite-plugin-ssr.com/api-routes.

I'm leaving this open until I implement `examples/telefunc/` and/or `examples/api-routes/`.

**Comment by milenkovic** [comment]
I was trying to get `vite-plugin-ssr` running with `Nestjs`, however I run into similar problem, I dint found any(at least not an easy) way to implement API routes. It sounds a bit limiting to prevent something like this. Or maybe I missed some configuration?

**Comment by brillout** [comment]
See recommendation at https://vite-plugin-ssr.com/api-routes.

**Comment by brillout** [comment]
> I'm leaving this open until I implement `examples/telefunc/`

Done.
