### ISSUE TITLE
What is the best way to define common functions in a context?

### ISSUE THREAD

**Issue by revenkroz** [brillout/vite-plugin-ssr#256]
I have an application that I am trying to rewrite from Nuxt to vite-plugin-ssr, but there is some difficulties. 

The app uses simple authentication with access token stored in cookies. This token should be used for requests to the remote API via `onBeforeRender` and in components (or in an application store). While it's easy with components and you can create an http-client (`fetch`) instance that is available everywhere, with `onBeforeRender` it's quite difficult because this function is outside the app and it is executed both on the server and on the client (when you go from page to page).

Is there any to implement something like this using `vite-plugin-ssr` API?

```ts
async function onBeforeRender(pageContext: PageContext & PageContextBuiltIn) {
  const params = pageContext.routeParams;

  const [schedule, latestNews] = await Promise.all([
    // user specific schedule
    $fetch('schedule'),
    // personalised news feed
    $fetch('posts', { 
      query: {
        limit: 10,
      },
    }),
  ]);
  // ...
}
```

Where `$fetch` is a custom fetch function that was created with the app and contains default headers with authorization token.

The same question if I want access the store in `onBeforeRender` — is there any way to define context functions before `onBeforeRender` in use them in it?

**Comment by brillout** [comment]
If you define `onBeforeRender()` in `.page.server.js` (and not in `.page.js`) then it will always be called on the server-side. You then need to define only a single `fetch` implementation.

**Comment by revenkroz** [comment]
Yes, that's the easiest way to do it, but I need to keep `onBeforeRender()` to be isomorphic to reduce number of requests to node.

The flow I looking for:
1. User requested page
2. Server creates pageContext and some common functions that can be used in `onBeforeRender`
3. User gets the page, client creates the same functions that can work in browser
4. When user clicks a link `onBeforeRender` is executed on client side.

I think I need to pass something to `onBeforeRender` (except pageContext) but I can't find a way to do it.

**Comment by revenkroz** [comment]
How I solved this issue for now:
1. Get cookies from request object and pass them to pageContext (and do not pass them to client)
2. Create file `_default.page.route.ts` in `renderer` directory with this content. This file is required as it loaded before `onBeforeRender`.
```ts
async function onBeforeRoute(pageContext: PageContextBuiltIn & PageContext) {
  let token
  if (import.meta.env.SSR) {
    token = pageContext.cookies['access_token'] // server thing
  } else {
    token = Cookies.get('access_token') // client thing
  }

  const http = createHttpClient(token) // returns a custom `fetch` function

  return {
    pageContext: {
      http,
    }
  }
}
```
3. Use function `pageContext.http()` to make requests in `onBeforeRender`
4. Now it perfectly works in all pages on the client-side as well as server-side and custom `fetch` is isolated between requests from different users.

It's a rather bad solution, but I can't find better for now.

**Comment by brillout** [comment]
Yea it's not ideal.

I believe what you want is https://github.com/brillout/vite-plugin-ssr/issues/164 which is on the roadmap.

It's a common use case to want to control the initialization of `pageContext`.

You can actually already do that on the server-side (`renderPage(pageContextInit)`) but not on the client-side nor while pre-rendering.

**Comment by brillout** [comment]
Closing in favor of #164.

Let me know if you believe `onInit()` wouldn't be enough for you.
