### ISSUE TITLE
Vercel Build Error

### ISSUE THREAD

**Issue by sukiejosh** [brillout/vite-plugin-ssr#257]
![Screenshot from 2022-02-05 19-13-42 (1)](https://user-images.githubusercontent.com/44656210/152653937-6aa2347a-45df-4ea8-9d6d-f4d5bfe5c221.png)

**Comment by sukiejosh** [comment]
i used the docs https://vite-plugin-ssr.com/vercel, but kept getting the error above

**Comment by brillout** [comment]
Just tried again and it works: https://vite-plugin-ssr-vercel-2022-02.vercel.app/.

I made https://vite-plugin-ssr.com/vercel slightly more readable but it's still the same steps.
