### ISSUE TITLE
Feature request: Export typeof renderPage to allow for typing of createPageRenderer

### ISSUE THREAD

**Issue by AlanMorel** [brillout/vite-plugin-ssr#264]
Hello, I'd love to be able to type my `createPageRenderer` like this (or similar):

```
import { createPageRenderer, RenderPage } from "vite-plugin-ssr";

const renderPage: RenderPage = createPageRenderer({ viteDevServer, isProduction, root });
```

But currently, the type isn't being exported:

```
type RenderPage = typeof renderPage
```

Would love to go from `any` to a proper type, thank you!

**Comment by brillout** [comment]
I'm not sure I see the problem? What is it you want to achieve?

**Comment by brillout** [comment]
You're repeating yourself.

Closing as I don't see what your problem is.
