### ISSUE TITLE
Cloudflare with esbuild broken with v0.3.56

### ISSUE THREAD

**Issue by dan-lee** [brillout/vite-plugin-ssr#267]
Hi,

Since the latest version I get the following warning when trying to build with `esbuild`:

> ▲ [WARNING] Import "createPageRenderer" will always be undefined because the file "../../node_modules/vite-plugin-ssr/dist/esm/client/node.js" has no exports
> 
>     worker/index.ts:1:9:
>       1 │ import { createPageRenderer } from 'vite-plugin-ssr'
>         ╵          ~~~~~~~~~~~~~~~~~~
> 

When I ignore this warning, `miniflare` throws this error at me:

> 
> MiniflareCoreError [ERR_MOUNT]: Error mounting "project"
> […]
{
> code: 'ERR_MOUNT',
>    cause: Error: [vite-plugin-ssr@0.3.56][Wrong Usage] The module `vite-plugin-ssr` cannot be imported in the browser. Did you mean to import the module `vite-plugin-ssr/client` instead?
>        at ../../node_modules/vite-plugin-ssr/dist/esm/client/node.js (/…/dist/worker.js:197:5)
>        at __init (/…dist/worker.js:9:56)
>        at /…/dist/worker.js:47083:1

<details>
<summary>My `build.js` file which builds the worker</summary>

```js
import esbuild from 'esbuild'
import { NodeModulesPolyfillPlugin } from '@esbuild-plugins/node-modules-polyfill'

esbuild
  .build({
    external: ['__STATIC_CONTENT_MANIFEST'],
    entryPoints: ['./worker/index.ts'],
    sourcemap: false,
    outfile: './dist/worker.js',
    logLevel: 'info',
    platform: 'browser',
    plugins: [NodeModulesPolyfillPlugin()],
    format: 'esm',
    target: 'es2020',
    bundle: true,
  })
  .then(() => console.log(`Successfully built worker.`))
```

</details>

**Comment by brillout** [comment]
Is there a way to tell esbuild to transpile `package.json#exports["."]["node"]` instead of `package.json#exports["."]["browser"]`?

**Comment by brillout** [comment]
`node_modules/vite-plugin-ssr/package.json#exports["."]["node"]` instead of `node_modules/vite-plugin-ssr/package.json#exports["."]["browser"]`

**Comment by brillout** [comment]
There is a discussion over there https://github.com/evanw/esbuild/issues/1189.

At some point we should stop using that `platform: browser` hack. It's just asking for trouble. Not only for `vite-plugin-ssr` but for other dependencies as well.

One potential problem specific to `vite-plugin-ssr@v0.3.56` is that it doesn't ship ESM server-side code anymore. All browser-side code is ESM and all server-side code is CJS. I know that esbuild is able to transpile CJS to ESM (which is used by Vite for browser-side dependencies that are CJS-only.)

I can revert and add ESM server-side code back, but let's avoid this if possible.

**Comment by dan-lee** [comment]
> At some point we should stop using that `platform: browser` hack. It's just asking for trouble. Not only for `vite-plugin-ssr` but for other dependencies as well.

I agree, it's unfortunate that this workaround has to be used.

> One potential problem specific to `vite-plugin-ssr@v0.3.56` is that it doesn't ship ESM server-side code anymore. All browser-side code is ESM and all server-side code is CJS. I know that esbuild is able to transpile CJS to ESM (which is used by Vite for browser-side dependencies that are CJS-only.)
> 
> I can revert and add ESM server-side code back, but let's avoid this if possible.

Alas, I am not too sure of any other options. I don't know too much about the specifics of CJS/ESM in the current state.

**Comment by brillout** [comment]
Either use wrangler's webpack-based bundler or follow the discussion at https://github.com/evanw/esbuild/issues/1189.

**Comment by brillout** [comment]
Try this:

> The main problem is that esbuild resolves the wrong value of `package.json#exports`. But I'm just seeing the `conditions` config; that should do the trick.

From https://github.com/evanw/esbuild/issues/1189.

**Comment by dan-lee** [comment]
Thanks @brillout! It works now with `conditions: ['node']` in my build.

**Comment by brillout** [comment]
@dan-lee

I propose the following to avoid breaking changes in the future:
 1. You make a PR adding small example `examples/cloudflare-workers-esbuild`.
 2. I add tests to it.

That will ensure that every commit made to vps will not break your esbuild setup. It also ensure that every Vite release will not break your esbuild setup as well. (Vite runs vps tests before each release to ensure it doesn't break the ecosystem.)

**Comment by dan-lee** [comment]
@brillout Great suggestion! I've just opened a PR for this
