### ISSUE TITLE
Should ___vite_plugin_ssr__pageContext end up in the resulting HTML?

### ISSUE THREAD

**Issue by invertedvisuals** [brillout/vite-plugin-ssr#269]
Trying to minimize my bundle and noticed the resulting HTML files after build contain a large data object for this plugin, is this supposed to happen or do I have my config set up wrong? Thanks!

`    <script>
      window.___vite_plugin_ssr__pageContext = {
            [ .... ]
      };
    </script>
`

**Comment by brillout** [comment]
Yes

**Comment by estudiooka** [comment]
it is really necessary ? it increases a lot the page size ...

**Comment by brillout** [comment]
It is.
