### ISSUE TITLE
Conflicts upon multiple vite-plugin-ssr instances installed

### ISSUE THREAD

**Issue by brillout** [brillout/vite-plugin-ssr#273]
Having more than one vite-plugin-ssr instance installed leads to problems such as:

> The `render()` hook exported by /node_modules/framework/renderer/_default.page.server.ts returned `{ documentHtml }`, but `documentHtml` should be a string generated with the `escapeInject` template tag or a string returned by `dangerouslySkipEscape('<p>Some HTML</p>')` ,

> I installed vps in the /framework dir, so it was using that import (and hence a different Symbol i presume) instead of the version in /app 

Vps should either handle such situation or gracefully error out.

**Comment by olemarius** [comment]
I'm getting the same error after scaffolding a project with vue + typescript then running dev. The error appears after opening localhost:3000.

**Comment by brillout** [comment]
Publish a reproduction and I'll have a look.

**Comment by brillout** [comment]
Also try with `0.4.x`, see `npm info vite-plugin-ssr` and the examples at https://github.com/brillout/vite-plugin-ssr/tree/0.4.0. I made some changes in `0.4` that may already fix this.

**Comment by brillout** [comment]
Already done.
