### ISSUE TITLE
Using _default.page.xx files in pages directory 

### ISSUE THREAD

**Issue by naveennamani** [brillout/vite-plugin-ssr#275]
I noticed a strange thing (because it didn't felt quite intuitive to me) that any `_deafult.page.client.jsx` in any folder in pages/ directory is getting included in all the prerendered files.

These are the files I created.
```
welcome/
  _deafult.page.client.jsx
  index.page.jsx
  index.page.server.jsx
  index.page.client.jsx
  tutorial.page.jsx
```

While the index page (/welcome route) has both custom client and server pages, I wanted to have a default client for all remaining files under the welcome directory (like /welcome/tutorial). The index page worked fine without _default.page.client.jsx file. But when I added the file, it was loaded as a client side js file for all files in all other directories.

I didn't find any useful configuration in the docs about overwriting this behaviour. I feel like having an option to respect such _default files in a given directory and to use them for rendering files inside that folder will be quite useful.

One such use case I wanted to build currently is a portfolio app (yet another common example but my first experiment). All common files like about, contact, projects etc. pages may not have a common rendering strategy. For ex. projects may be dynamically fetched on client side while contact page may be HTML only with a form. And blog posts with mdx may need their own renderer for all files inside a /blog folder. If I can help on implementing this feature you can guide me where to start looking in the source code.

Thanks & have a good day.

**Comment by naveennamani** [comment]
My bad, I didn't put the file in renderer folder. I just now find that in the docs. I'll once check and come back to you.

**Comment by brillout** [comment]
I believe vps actually does what you expect.

This should work:

```bash
renderer/_default.* # Default for all pages

marketing/_default.* # Overrides the `renderer/_default.*`
marketing/about.page.js
marketing/contact.page.js

blog/_default.* # Overrides the `renderer/_default.*`
blog/2022-03-07_my-first-vps-app.page.js
```
>  If I can help on implementing this feature

Can you see yourself dedicate a substantial amount of time to OSS?

**Comment by naveennamani** [comment]
> I believe vps actually does what you expect.

Yes it did worked when I placed _default.* in `welcome/renderer` folder instead of placing directly in `welcome` folder. I missed the api documentation for _default pages.

> Can you see yourself dedicate a substantial amount of time to OSS?

I cannot guarantee a substantial amount, but I can work for 12hr weekly. I may not immediately contribute, but once I understand what I should do, then I can contribute effectively.

**Comment by brillout** [comment]
Sounds good. There isn't anything on the roadmap that doesn't require in-depth knowledge about vps. But, if you want, there are things on [Telefunc](https://telefunc.com/)'s side that are good candidates for contributions. For example researching the integration of Telefunc with React 18 Suspense Streams. Is that something you'd be up to?

Closing this ticket since your original problem is resolved.
