### ISSUE TITLE
when isomorphic hooks exists, skipOnBeforeRenderServerHooks is not respected

### ISSUE THREAD

**Issue by wuiyang** [brillout/vite-plugin-ssr#279]
When using isomorphic `onBeforeRender` hooks combined with server-only `onBeforeRender` hooks. Client could not bypass server `onBeforeRender` hook via `skipOnBeforeRenderServerHooks` call.

Example code (trying to render page preview meta tag only on server side):
```ts
// index.onBeforeRender.ts
export async function onBeforeRender(pageContext) {
  if (import.meta.env.SSR) {
    // only run server hooks on server side
    await pageContext.runOnBeforeRenderServerHooks(pageContext);
  } else {
    // skip server hooks on client side
    await pageContext.skipOnBeforeRenderServerHooks();
  }

  return {
    pageContext: {
      documentProps: {
        title: 'Client & Server rendered title',
      },
      pageProps: {
        pageData: 'dynamic page data',
      },
    },
  };
}

// index.page.server.ts
export async function onBeforeRender(pageContext) {
  return {
    pageContext: {
      documentProps: {
        linkPreviewMeta: {
          title: 'link preview meta',
          description: 'This only runs on server side, to produce page metadata for link preview meta tag',
        },
      },
    },
  };
}
```

What I've found is that in `executeOnBeforeRenderHooks` for client router, when checking on server hook call via `assertUsageServerHooksCalled`, it did not handle cases where `skipServerHooks` is true.

https://github.com/brillout/vite-plugin-ssr/blob/0888675c64dc2fa54cc5d1d709c4a0ee1314951f/vite-plugin-ssr/client/router/getPageContext.ts#L229-L247

**Comment by brillout** [comment]
Can you consolidate your two `onBeforeRender()` hooks into one?

The `skipOnBeforeRenderServerHooks` will be removed int the next major release. (It will be replaced by something simpler that covers most uses cases.)

**Comment by wuiyang** [comment]
I tried to consolidate it and it works perfectly, not sure why I did not think of that previously. Thank you!

Look forward for the next major release.
