### ISSUE TITLE
Deploy app on vercel got error "Permission denied" 

### ISSUE THREAD

**Issue by qieman** [brillout/vite-plugin-ssr#280]
Hi, i deploy my vite-plugin-ssr app on vercel followed the documentation [https://vite-plugin-ssr.com/vercel.](https://vite-plugin-ssr.com/vercel.) but it was fail by error 'Permission denied' in building process:

```
Running Build Command: `yarn run vercel-build`
yarn run v1.22.17

$ ./vercel/deploy.sh
/bin/sh: ./vercel/deploy.sh: Permission denied
 error Command failed with exit code 126.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
 Error! Command "yarn run vercel-build" exited with 126
Error: Command "vercel build" exited with 1
```

Am I missing some configuration ？Can someone help ?

i already set environment variable named ENABLE_FILE_SYSTEM_API to 1

**Comment by brillout** [comment]
Seems related to your fs permissions
