### ISSUE TITLE
Prefetch EventListener touchstart (passive)

### ISSUE THREAD

**Issue by jrson83** [brillout/vite-plugin-ssr#285]
If you run an example with `npm run prod` and check the rating with Google Lighthouse, it has almost perfect (99%), just [suggestes to add a passive EventListener](https://web.dev/uses-passive-event-listeners/?utm_source=lighthouse&utm_medium=devtools#how-to-make-event-listeners-passive-to-improve-scrolling-performance) to the `touchstart` event, which is happening in the file `dist/esm/client/router/prefetch.js`.

![2022-03-22_11h51_35](https://user-images.githubusercontent.com/45284565/159466189-8c8788d8-07b0-4aca-8531-dee30db3bb1b.png)

I checked and added it to the code:

```js
linkTag.addEventListener('touchstart', () => prefetch(url), {passive: true});
```

When I run the test again, it has a rating of 100%. I would do a PR for this?

**Comment by brillout** [comment]
Yes!
