### ISSUE TITLE
vite-plugin-pwa not working with vite-plugin-ssr

### ISSUE THREAD

**Issue by robotpapier** [brillout/vite-plugin-ssr#295]
Hi,
did anyone had a chance of making [https://github.com/antfu/vite-plugin-pwa](https://github.com/antfu/vite-plugin-pwa) work ?
I have been successfully used [https://github.com/rubenRP/vite-pwa-boilerplate](https://github.com/rubenRP/vite-pwa-boilerplate) but when adding the vite-plugin-ssr and also adding in the html head the manifest link, the service worker is not detected even tough sw.js is present.

**Comment by brillout** [comment]
Does `vite-plugin-pwa` transforms the HTML?

In SSR production there is no Vite development server. This means that Vite plugins cannot transform the HTML for production.

**Comment by robotpapier** [comment]
Hi, no it doesnt, I had to add the manifest link myself in _default.page.server.ts

UPDATE: ok I forgot add registerSW.js generated byt the plugin so it can register the SW.
now it is working!

`const documentHtml = escapeInject`<!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <link rel="icon" href="${logoUrl}" />

        <link rel="manifest" href="/manifest.webmanifest">
        <script src="registerSW.js"></script>

        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="${desc}" />
        <title>${title}</title>
      </head>
      <body>
        <div id="app">${stream}</div>
      </body>
    </html>`

    return {
      documentHtml,
      pageContext: {
        // We can add some `pageContext` here, which is useful if we want to do page redirection https://vite-plugin-ssr.com/page-redirection
      },
    }`

Thanks!

**Comment by brillout** [comment]
👍
