### ISSUE TITLE
example of layouts with vue-full

### ISSUE THREAD

**Issue by pixelpaulaus** [brillout/vite-plugin-ssr#309]
Hello,
Just wondering if anyone has some example projects with layouts for vue-full.
The layouts example is great, but it doesnt do client side routing when i build:prerender.

**Comment by brillout** [comment]
I'm actually planning to implement layouts examples with vps 0.4 next week.

**Comment by pixelpaulaus** [comment]
That’s great, thanks.
What template/example would be best for me to start on now? To them migrate to the new one your planning.  Vue-full?

**Comment by brillout** [comment]
The general idea with 0.4 is to use "custom exports":

https://github.com/brillout/vite-plugin-ssr/blob/78f2c013abfbd3d78c59b3e033ee5653ab3e518c/examples/framework/app/renderer/layouts/_default.page.jsx#L1

Such custom export can be set by any `.page.js` file.

The renderer can then access these custom exports with `pageContext.exports`:

https://github.com/brillout/vite-plugin-ssr/blob/78f2c013abfbd3d78c59b3e033ee5653ab3e518c/examples/framework/framework/renderer/PageShell.tsx#L8

This is the overall idea of the new layout recommendation with vps 0.4.

Note that `pageContext.exports` doesn't exist in 0.3; use `pageContext.pageExports` instead (see current docs).

You can also use the 0.4 beta, if you want. Let me know if you do and I'll tell you how to get started with 0.4.

**Comment by brillout** [comment]
React example: https://github.com/brillout/vite-plugin-ssr/tree/0.4.0/examples/layouts-react

Vue example: https://github.com/brillout/vite-plugin-ssr/tree/0.4.0/examples/layouts-vue

Docs: https://github.com/brillout/vite-plugin-ssr/blob/0.4.0/docs/pages/layouts.page.server.mdx (will be published along 0.4 release).

Leavining this open unitl 0.4 is released.

**Comment by BrettLargent** [comment]
Hello! This may warrant its own separate ticket, but it seemed better to mention it here first in case I'm just missing something. The `layouts-vue` example seems to be broken currently, such that the index page's ability to use a layout other than the default is throwing an error. Has the custom exports pattern been updated to where this is no longer valid syntax?

Removing the `export { default as Layout } from "..."` statement fixes the server, but that means removing the use of a custom route layout.

```
ReferenceError: _sfc_main is not defined
    at eval (/pages/index/index.page.vue:16:20)
    at async instantiateModule (/home/blargent/git/vite-plugin-ssr/examples/layouts-vue/node_modules/vite/dist/node/chunks/dep-c9998dc6.js:50311:9)
```

**Comment by brillout** [comment]
@BrettLargent I need exact reproduction steps, and yes it'd be good to open a new ticket for this.

The ticket itself is done: https://vite-plugin-ssr.com/layouts.
