### ISSUE TITLE
Route params in ssr

### ISSUE THREAD

**Issue by alsyapukov** [brillout/vite-plugin-ssr#31]
Forgive me for opening a new problem, but I did not understand how it is possible to get on the server in the lower levels of components where I will call ServerPrefetch () and receive data in Vieks and transfer data from the router there.
Example:
```
<script>
import { mapState, mapActions } from 'vuex'

export default {
  name: 'SearchBar',
  serverPrefetch() {
    return this.getSearch()
  },
  mounted() {
    if(!this.searchLocation && !this.searchCategory)
        this.getSearch()
  },
  computed: {
    ...mapState('application', ['viewPort', 'categories']),
    ...mapState('search', ['searchCategory', 'searchLocation', 'searchLoading'])
  },
  methods: {
    ...mapActions('search', ['setSearch']),
    getSearch() {
      if(this.$route && this.$route.params && (!this.searchCategory || !this.searchLocation))
        return this.setSearch({
          location: this.$route.params.location ? this.$route.params.location : null,
          category: this.$route.params.category ? this.$route.params.category : null
        })
      else return null
    },
    toSearch() {
      window.location.href = `/search/${
        this.searchLocation && this.searchLocation.nameEnLowercase
          ? this.searchLocation.nameEnLowercase : 'all_cities'
      }/${
        this.searchCategory && this.searchCategory.translit
          ? this.searchCategory.translit : 'all_categories'
      }`
    }
  }
}
</script>
```
I see route params in *.page.server.js contextProps.url but how I can recive  this parameters in components in serverPrefetch()

**Comment by alsyapukov** [comment]
https://prnt.sc/115zmpi I'm trying to do something like this, get meta data from the server to my client server and display it in html for search engines, I almost succeeded, but this.$route is a vue router object, and I need a server-side route object

**Comment by gryphonmyers** [comment]
You can access routing params from `page.route.js` files in contextProps but these are not part of any vue router - they're just params parsed from pathToRegexp.

**Comment by gryphonmyers** [comment]
BTW I have full guidance for vue router integration in progress. This will become far more straightforward once I've finished

**Comment by alsyapukov** [comment]
@gryphonmyers Please can give me example component with contextProps

**Comment by alsyapukov** [comment]
@gryphonmyers This is great, I hope it will be possible to use it soon, do you have any problems with the scoped styles and the vue router at the same time? Or are you using something else instead of scoped?

**Comment by brillout** [comment]
For v2, you can add some of your `contextProps`/`pageProps` to all components by using `Vue.prototype` as described in https://vuejs.org/v2/cookbook/adding-instance-properties.html#Base-Example. For v3 use `app.config.globalProperties` instead: https://v3.vuejs.org/guide/migration/global-api.html#vue-prototype-replaced-by-config-globalproperties.

Does that solve your problem?

**Comment by alsyapukov** [comment]
![image](https://user-images.githubusercontent.com/55176522/114225998-10b59300-9984-11eb-8cba-c52515814794.png)
![image](https://user-images.githubusercontent.com/55176522/114226090-32af1580-9984-11eb-8f6c-4d6027eb84c5.png)
Thank you very much for guiding me to solve the problem, I was more approached by the method with provide and injection, those solutions that you proposed are also workers! Thanks a lot again.

**Comment by brillout** [comment]
Thanks for sharing; I added your solution to the docs.

Let me know if you have any other question!
