### ISSUE TITLE
Prerender fails when Vite build.assetsDir option is specified

### ISSUE THREAD

**Issue by gryphonmyers** [brillout/vite-plugin-ssr#32]
Steps to Reproduce:

1) add build.assetsDir option to vite.config.js with any path other than the default "assets"
2) run vite build followed by prerender command
3) Observe that an error is thrown originating in `collectAssets` in `/dist/getPreloadTags.node.js`

Expected Results:

Customizing the assetsDir should successfully prerender the site into the customized directory

**Comment by brillout** [comment]
AFAICT, this should fix it. I will release later today.

**Comment by brillout** [comment]
@gryphonmyers Do you need this released?

**Comment by gryphonmyers** [comment]
Sure 😁 maybe automated releases would be nice to put on the todo list?

**Comment by brillout** [comment]
Released in `0.1.0-beta.29`. I didn't test if the fix works, but AFAICT it should. Let me know if there is still a problem and I'll release promptly this time ;-).

The release is already automated. But there were some changes that need thorough manual testing. (I've implemented support for CF workers.)

**Comment by brillout** [comment]
Also btw if you need something from me, feel free to push. I don't mind.
