### ISSUE TITLE
Parent folder for domain objects

### ISSUE THREAD

**Issue by TheFixR** [brillout/vite-plugin-ssr#320]
Currently, to have a [domain-driven project structure](https://vite-plugin-ssr.com/file-structure#domain-driven), I have to place all the domain object folders in the project root, for example:
`/users/*` or `/src/users/*`
`/products/*` or `/src/products/*`
But I'm wondering, can I embed those in a folder (named "features", "modules" or whatever)? File tree will become:
`/features/users/*` or `/src/features/users/*`
`/features/products/*` or `/src/features/products/*`
It will make navigation in a project much better because often the project root contains some other folders such as "assets", "layouts" etc. which should not mix up with domain objects.

**Comment by brillout** [comment]
Yes
