### ISSUE TITLE
Disturbing bug -- weird malware-like scanning behavior

### ISSUE THREAD

**Issue by azarc3** [brillout/vite-plugin-ssr#321]
While working on my project which was executing at [http](http://localhost:8080/), I saw a veritable deluge of errors come streaming in while a hot reload occurred. The dev output suggested that I provide the following error message and stacktrace:
> Error: [vite-plugin-ssr@0.3.7][Internal Failure] You stumbled upon a bug in `vite-plugin-ssr`'s source code (an internal `assert()` failed). This should definitely not be happening, and you should create a new GitHub issue at https://github.com/brillout/vite-plugin-ssr/issues/new that includes this error stack (the error stack is usually enough to debug internal errors). Or reach out on Discord. A fix will be written promptly. Debug info (this is for the `vite-plugin-ssr` maintainers; you can ignore this): `{"url":"http://www.google.com:80/"}`.
>     at handleUrlOrigin (project_root\node_modules\vite-plugin-ssr\shared\utils\parseUrl.ts:25:11)
>     at analyzeUrl (project_root\node_modules\vite-plugin-ssr\node\renderPage.ts:991:24)
>     at initializePageContext (project_root\node_modules\vite-plugin-ssr\node\renderPage.ts:165:48)
>     at renderPage (project_root\node_modules\vite-plugin-ssr\node\renderPage.ts:64:23)
>     at renderPageWithoutThrowing (project_root\node_modules\vite-plugin-ssr\node\renderPage.ts:185:29)
>     at project_root\server\index.ts:44:31
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)

Within about three minutes of the above error, I experienced the following error twice:
> Error: [vite-plugin-ssr@0.3.7][Internal Failure] You stumbled upon a bug in `vite-plugin-ssr`'s source code (an internal `assert()` failed). This should definitely not be happening, and you should create a new GitHub issue at https://github.com/brillout/vite-plugin-ssr/issues/new that includes this error stack (the error stack is usually enough to debug internal errors). Or reach out on Discord. A fix will be written promptly. Debug info (this is for the `vite-plugin-ssr` maintainers; you can ignore this): `{"url":"/dana-na/../dana/html5acc/guacamole/../../../../../../etc/passwd?/dana/html5acc/guacamole/"}`.
>     at getUrlParts (project_root\node_modules\vite-plugin-ssr\shared\utils\parseUrl.ts:71:9)
>     at getUrlParsed (project_root\node_modules\vite-plugin-ssr\shared\utils\parseUrl.ts:87:58)
>     at Object.urlParsedGetter (project_root\node_modules\vite-plugin-ssr\node\renderPage.ts:1020:22)
>     at preparePageContextNode (project_root\node_modules\vite-plugin-ssr\node\renderPage.ts:425:36)
>     at executeRenderHook (project_root\node_modules\vite-plugin-ssr\node\renderPage.ts:705:3)
>     at renderPage (project_root\node_modules\vite-plugin-ssr\node\renderPage.ts:137:34)
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async renderPageWithoutThrowing (project_root\node_modules\vite-plugin-ssr\node\renderPage.ts:185:12)
>     at async project_root\server\index.ts:44:25

Finally, this error was also in the output:
`11:46:42` AM [vite] Internal server error: EISDIR: illegal operation on a directory, read

The above issues aren't all that bad, in my opinion. However, intermixed with these exceptions were reference to URLs that have nothing to do with my application or anything else that I'm working on. I've removed and highlighted the common text you'll see below to eliminate duplication.

> **Unrestricted file system access to:**
> - "/imc/fault/accessMgrServlet"
> - "/cgi-bin/htmlscript"
> - "/cgi-bin/faxquery"
> - "/go/add-on/business-continuity/api/cruise_config"
> - "/~bin/true"
> - "/ui/vropspluginui/rest/services/getstatus"
> - "/cgi-bin/htgrep/file=index.html&hdr=/etc/passwd"
> - "/dana-na/../dana/html5acc/guacamole/../../../../../../etc/passwd"
> - "/frame"
> - "/sys"
> - "/admin"
> - "/page"
> - "/index"
> - "/home"
> - "/rest/v1/AccountService/Accounts"

> **[vite-plugin-ssr@0.3.7][Warning] URL {shown_below} is not matching any of your 256 page routes (this warning is not shown in production):**
> - "/~bin/true"
> - "/admin"
> - "/bb/"
> - "/CFIDE/AIR/"
> - "/CFIDE/adminiapi/"
> - "/CFIDE/administrator/"
> - "/CFIDE/appdeployment/"
> - "/CFIDE/componentutils/"
> - "/CFIDE/orm/"
> - "/CFIDE/portlets/"
> - "/CFIDE/scheduler/"
> - "/CFIDE/servermanager/"
> - "/CFIDE/services/"
> - "/CFIDE/websocket/"
> - "/CFIDE/wizards/common/"
> - "/cgi-bin/faxquery"
> - "/cgi-bin/faxsurvey"
> - "/cgi-bin/htgrep/file=index.html&hdr=/etc/passwd"
> - "/cgi-bin/htmlscript"
> - "/etc/passwd"
> - "/frame"
> - "/go/add-on/business-continuity/api/cruise_config"
> - "/home"
> - "/imc/fault/accessMgrServlet"
> - "/index"
> - "/page"
> - "/phpmyadmin/"
> - "/rest/v1/AccountService/Accounts"
> - "/sys"
> - "/ui/vropspluginui/rest/services/getstatus"

I'm REALLY hoping this is some kind of pen testing module you guys have in there for some odd reason. Please advise?

**Comment by brillout** [comment]
That's expected when the crawl path is `/`. Seems like you are doing something unconventional here. You can disable Express.js's pendant for [`host`](https://vitejs.dev/config/#server-host) if you want to ensure your local network to not access your filesystem while developing.
