### ISSUE TITLE
How to save data to sessionStorage

### ISSUE THREAD

**Issue by rrd108** [brillout/vite-plugin-ssr#327]
I started to play around vite-plugin-ssr with vue today.

What I was not able to find out how to store data to `sessionStorage`.

My `index.page.server.js` file make an `axios.get()` request to an API. I return the data in `pageContext` and `passToClient`, and I can read the data in my vue component.

What I was not able to figure out how (and where) to save this data to the `sessionStorage`.

Some hint would be much appreciated.

**Comment by brillout** [comment]
Checked the Rules on Discord.
