### ISSUE TITLE
Allow wrapping exported functions in `.page.*.ts` in single object that is passed to function

### ISSUE THREAD

**Issue by louwers** [brillout/vite-plugin-ssr#332]
Say we have a file `movie.page.server.js`.

Instead of this:

```ts
export { prerender } 
async function prerender() {
}
```

I expect to be able to do this:

```ts
import { defineServerPage } from 'vite'; 

export default defineServerPage({
  async prerender() {
  }
})
```

This would allow for better discoveribility of `vite-plugin-ssr`'s API, it will make it easier to define pages (auto-completion) and it will allow catching typos in the exported functions. 

Of course, there would be a `defineClientPage` and `defineRoute` as well as a `definePage` as well.

**Comment by brillout** [comment]
Yes and vps 0.4 actually allows you to define hooks over the default export.

That said some exports (e.g. `render`, `Page`, and `clientRouting`) need to be statically analyzable with https://github.com/guybedford/es-module-lexer, so this wouldn't work for these.

**Comment by louwers** [comment]
> Yes and vps 0.4 actually allows you to define hooks over the default export.

Cool. With some function wrapper that allows type checking I assume?

> That said some exports (e.g. render, Page, and clientRouting) need to be statically analyzable

Wouldn't it be possible to use a more intelligent parser?

I can only see that library being used [here](https://github.com/brillout/vite-plugin-ssr/blob/2230f9b4043b85294fc0099209faaacc5d7675d1/vite-plugin-ssr/node/plugin/transformPageServerFiles.ts).

**Comment by brillout** [comment]
> Wouldn't it be possible to use a more intelligent parser?

I don't think so, unfortunately.

> Cool. With some function wrapper that allows type checking I assume?

Not yet but this can easily be added later. It's low priority though.

**Comment by brillout** [comment]
It's low prio because there is no clear way of how to handle these static exports.

**Comment by brillout** [comment]
(I do share the sentiment for having the interface discoverable with TS.)

**Comment by brillout** [comment]
The V1 design offers this.
