### ISSUE TITLE
partial spa project example

### ISSUE THREAD

**Issue by AlanNabiev** [brillout/vite-plugin-ssr#334]
### Description

Hi guys. 

First of all, I would like to thank you for your work. Thanks to which we have a powerful tool for ssr.

I would like to create a question with a request. At the moment, I am engaged in a crypto exchange, we are faced with the task of making 3 pages in ssr mode, and the rest that are associated with the account in spa mode. Partly thanks to the documentation, I managed to do this. 

However, I would like to see the best practice of this solution. It would be cool if you added an example for such a non-trivial task.

Stack: vue 3, vue-router, pinia, i18n, vite

**Comment by brillout** [comment]
Vps 0.4 has improved support for mixed render modes.

See https://github.com/brillout/vite-plugin-ssr/tree/0.4.0/examples/render-modes and make sure to use the latest 0.4 beta.
