### ISSUE TITLE
Allow overriding browser entry points ignore list

### ISSUE THREAD

**Issue by hannessolo** [brillout/vite-plugin-ssr#339]
### Description

**Summary**: We would like to be able to override the following list: https://github.com/brillout/vite-plugin-ssr/blob/547e5ebaf76b2300457ec85bd027956abba31ef4/vite-plugin-ssr/node/plugin/build.ts#L85

**Background**:

We are developing an abstraction layer over `vite`/`vite-plugin-ssr`. Users can install our npm module, which handles the rendering for certain use cases with minimal code from the user's side. The entry point to the project and build options are also handled by the npm module. This means in the user's project, the entry point will be in `node_modules`, in our module. The line of code linked above is causing us issues as it ignores files in `node_modules`.

We would like to be able to provide a config option to `vite-plugin-ssr` to override this ignore list with custom entries.

**Implementation**:

I wanted to implement this and make a PR but wasn't sure which approach to take from a design perspective, as the plugin as it is now doesn't take any options that I could look at for guidance.

**Comment by brillout** [comment]
> developing an abstraction layer

Which is?

Vps 0.4 is designed to enable folks to build on top of vps.

**Comment by hannessolo** [comment]
> > developing an abstraction layer
> 
> Which is?

We are developing a tool to create websites with minimal user code. The tool (npm dependency) uses vite and vite-plugin-ssr internally. I use "abstraction" because the tool handles all the vite config, as well as the vite entry point.
> 
> Vps 0.4 is designed to enable folks to build on top of vps.

I was not aware. What is the recommended way to get started with this (do I need to build the docs myself?), and do you have a planned release date?

Thanks!

**Comment by brillout** [comment]
Your use case is the kind of thing vps 0.4 is aiming at enabling.

There are already a couple of folks using it in production and building frameworks with it. So release is coming soon.

Is your current workaround satisfactory or do you need something sooner rather than later?

**Comment by hannessolo** [comment]
We're currently shipping a git patch file and applying it on npm install. For internal demos it's fine but we will need a more permanent fix within the next 6 weeks or so. Sounds like this would align with the release timeline for 0.4?

**Comment by hannessolo** [comment]
I do not mean to impose a deadline (implied or otherwise) - sorry. 

We're looking forward to the 0.4 release. Until then our patch will be fine. If we end up forking and making changes that we think would benefit general public interest, we would obviously create a PR.

Thank you for your help and for your work!

**Comment by brillout** [comment]
I guess we close this.

Let me know if you have questions.

**Comment by brillout** [comment]
Btw. feel free to elaborate your use case if you believe that you may need something from vps beyond it's current state.

Being able to build frameworks on top of vps is going to be my primary focus in the next coming weeks.

**Comment by brillout** [comment]
> @brillout thanks. Is there already a document where you describe the features for framework development you plan to add to 0.4?

Not yet but there will be. There will be a recommended way to develop, build, and release frameworks to npm.

> I can try to summarize some of the issues we've run into so far while developing our framework if that would be helpful for your development.

I'm probably already aware of most of them. But what would help are high-level feature requests.

**Comment by brillout** [comment]
@hannessolo Any news on your side? I'm seeing that https://github.com/adobe-rnd/franklin doesn't exist anymore. Feel free to let me know if you have any questions.

**Comment by hannessolo** [comment]
An update: Thank you for the release of 0.4, we've updated our code to make use of the new features. We had to make our repo private for now, but are still using VPS.

**Comment by brillout** [comment]
👍 Let me know if you need something. I'm keen on supporting use cases like yours. Note that, as the author of vps, I may find solutions to problems you think are not solvable; so feel free to keep me updated.

**Comment by brillout** [comment]
No offense taken :-).

I'm looking forward to enabling easy framework building :-).
