### ISSUE TITLE
Project with 5000 files

### ISSUE THREAD

**Issue by hemengke1997** [brillout/vite-plugin-ssr#348]
### Question / Discussion

Great project, thanks for the open source. I am trying to use vps to build a large mpa project. This project may grow to have hundreds of pages, and if I use import.meta.glob to find the files every time I package it, it may become very slow e.g.: https://github.com/vitejs/vite/issues/8393
Is there a way to package in a specific folder? Or not let the vps find all the files.
I thought about using monorepo, but the pageFiles file `'/*/*/*.page.*([a-zA-Z0-9])'` will still find all files.

**Comment by hemengke1997** [comment]
Each page is unrelated. If we can't specify the folder, it will take more time to start the server or build each time

**Comment by hemengke1997** [comment]
Hi! Thanks you for your reply.

Here is the repo:  https://github.com/hemengke1997/vite-ssr-repo

1. pnpm i
2. node create.js
3. npm run start

Then you will see, the page will only be rendered after a long time
Becase [`pageFiles.ts` => `import.meta.glob`](https://github.com/brillout/vite-plugin-ssr/blob/HEAD/vite-plugin-ssr/node/page-files/pageFiles.ts#L5) took a lot of time.

**Comment by hemengke1997** [comment]
I am new to the srr.
It was hard for me to make an ssr from 0 to 1, so I had to use some plugins. I find vps perfect for me, so I hope to continue developing on this basis

5000 files, it would take almost a minute to start up. In fact, for me, these 5000 files are not related to each other, I want only one file to start each time I start the service. Ditto for the packaging.

My English is very poor, if there is something I do not understand, please let me know, thank you very much

**Comment by brillout** [comment]
👍

> Because pageFiles.ts => import.meta.glob took a lot of time.

What makes you think that? It would make sense if vps would be using [`import.meta.globEager()`](https://vitejs.dev/guide/features.html#glob-import) but it uses `import.meta.glob()`.

**Comment by brillout** [comment]
> Ditto for the packaging.

That's expected. I'm not aware of any tool that supports splitting building. Vite is no exception.

As for dev, in principle it should work. But it's possible that there are some issues around this. Most likely on Vite's side, not vite-plugin-ssr's side though.

**Comment by hemengke1997** [comment]
Thank you very much.

I think it might be possible if we use this: `import.meta.glob(`${variable}`)`. But sad, I found this is impossible in vite. 
https://vitejs.dev/guide/features.html#glob-import
> You should also be aware that glob imports do not accept variables, you need to directly pass the string pattern.

Fine! Anyway, thanks for your answer

**Comment by brillout** [comment]
> I think it might be possible if we use this: import.meta.glob(${variable}). But sad, I found this is impossible in vite.
https://vitejs.dev/guide/features.html#glob-import

That's functionally equivalent. So that's not the culprit.

If I were you I'd first try to make it work with Vite, then try again with vps.

If it doesn't work with Vite, open a new issue on the Vite repository.

If it works with Vite but not vps, then open a new issue here on the vite-plugin-ssr repository.
