### ISSUE TITLE
ssr assets link inject missing base url

### ISSUE THREAD

**Issue by uuau99999** [brillout/vite-plugin-ssr#351]
### Description

In my vite.config.ts, I set base to a host other than the server host(cause I need to deploy my static assets to a cdn).
in client side build, the generated html respects the base and inject asset with url started with base.
However, while starting server in production and the server render html with assets reference without base which leads to 404.
I inspect the source code and find the following logic:
<img width="1381" alt="image" src="https://user-images.githubusercontent.com/6498327/176341267-6bddcfcd-59d3-42d6-9b1d-feb8f725d12d.png">
<img width="1571" alt="image" src="https://user-images.githubusercontent.com/6498327/176341421-3959e901-673f-458a-a5d7-1499e9131c8b.png">
It seems that when server render html it just simply use the client side manifest assets links as url to create link tags without prepending the base to them.

### Error Stack

See description above.

**Comment by brillout** [comment]
It does work, see the `examples/base-url-cdn/` example.

Create a reproduction, e.g. starting from that example, and I'll have a look at it.

Closing in the meantime.

**Comment by uuau99999** [comment]
Oh I miss the baseAssets property while using createPageRenderer.  Thanks for replying.
