### ISSUE TITLE
Preload svg link tag support custom crossorigin attribute?

### ISSUE THREAD

**Issue by uuau99999** [brillout/vite-plugin-ssr#355]
### Description

In our project, we use a cdn as aseets host and while deploying to production, the svg preload link tags generated by server will be blocked by the browser for credentials mode does not match and need to set attribute crossorigin to "anonymous".
Maybe vite-plugin-ssr can provide option to customize that?
<img width="842" alt="image" src="https://user-images.githubusercontent.com/6498327/177903433-25d1a139-65db-479d-98e6-caff5b9caf01.png">

**Comment by brillout** [comment]
Isn't that happening because of your CDN? I don't think there is anything vps can do here? The cross-origin policy is about protecting the CDN so it would defeat the purpose of the policy if vps can circumvent it.

**Comment by uuau99999** [comment]
If you provide the preload link with an attribute `cross-origin=""` then the warning is gone. The problem is when vite-plugin-ssr generates preload link we cannot custom the preload link attribute. It would be better to provide options to customize the preload links. 
Maybe take a look at this: https://github.com/vercel/next.js/discussions/16850

**Comment by brillout** [comment]
Released in `v0.4.1`.
