### ISSUE TITLE
Can't get WindiCSS working

### ISSUE THREAD

**Issue by CanRau** [brillout/vite-plugin-ssr#36]
Hey there, your plugin looks very promising, thanks a lot for your efforts 🙏
I'm completely new to vite, worked only with Gatsby and Next so far with Tailwind.

I tried WindiCSS in a "raw" Vite scaffold (using the CLI) then installing Windi according to the [vite-plugin-windicss docs](https://github.com/windicss/vite-plugin-windicss) which worked just as expected.

Trying to do replicate this in my beforehand scaffolded vite-plugin-ssr project using the CLI failed to import the CSS styles (only the custom properties --tw-* are included in the final build .css).

I've put the `import "virtual:windi.css";` "everywhere" starting in `_default.page.client.tsx` than added to `index.page.tsx` without any changes.

Uh I'm also using `useClientRouter` in `_default.page.client.tsx`.

What am I missing or doing wrong?

**Comment by CanRau** [comment]
Haven't tried any direct Tailwind stuff yet 🤔 How should I go about it?

Yes, `WindiCSS()` is in my `vite.config.js`, followed all setup steps which worked correctly as expected in plain vite-react-ts 🤷‍♂️

**Comment by brillout** [comment]
Let me have a look

**Comment by brillout** [comment]
Working example: https://github.com/brillout/vite-plugin-ssr-vite-plugin-windicss

**Comment by CanRau** [comment]
My fault I should have read the docs better 😅

It defaults to only working with files in `/src` had to include `/pages` to options as described here https://windicss.org/guide/vite.html#scanning

(already provided a PR to fix the typo in the example `windcss/helpers`, misses the second **i**)

**Comment by brillout** [comment]
👍 Let me know if you have any ohter question

**Comment by CanRau** [comment]
> Working example: https://github.com/brillout/vite-plugin-ssr-vite-plugin-windicss

Just out of curiosity, I couldn't find any mention of actual Tailwind classNames, have you confirmed they're working?
As according to my trials and the Windi docs on [scanning](https://windicss.org/guide/vite.html#scanning) it shouldn't work ^^

**Comment by brillout** [comment]
I was wondering the same ^^; I just saw the Tailwind CSS included so I was assumings that things work. (I never used Tailwind CSS.)

> had to include /pages to options 

If this necessary then we should def add a little guide to vite-plugin-ssr's README. A PR would be warmly welcome :-).

**Comment by konsumer** [comment]
@brillout your demo didn't use any tailwind util classes. It doesn't error for me, but it doesn't apply any windicss styles either.

If I `import 'virtual:windi.css'` in PageLayout.jsx, it should work, but it doesn't:

<img width="572" alt="Screen Shot 2022-09-05 at 10 20 17 PM" src="https://user-images.githubusercontent.com/83857/188552890-54dfaae2-bd3d-4637-a9cd-7275a13be126.png">

Do I need to do something else?

**Comment by brillout** [comment]
It does: https://github.com/brillout/vite-plugin-ssr_windi-css/blob/2310ad8ea3889c0c9fe5f73d902be49b25315273/pages/index/index.page.jsx#L9.

> Do I need to do something else?

Yes, see the warning at https://vite-plugin-ssr.com/windi-css.

Please read the docs before asking for help. See https://brillout.github.io/rules/.
