### ISSUE TITLE
Cannot find production build. Make sure to import `importBuild.cjs`

### ISSUE THREAD

**Issue by kryptus36** [brillout/vite-plugin-ssr#360]
### Question / Discussion

Upgrading to 0.4.2 from 0.3.36

The given URL instructs me to contact you with related issues.

The file importBuild.cjs doesn't exist anywhere in my project. So I am unsure how to import it.

**Comment by kryptus36** [comment]
When I call renderPage() I get:

```
Error: [vite-plugin-ssr@0.4.2][Wrong Usage] Cannot find production build. Make sure to import `importBuild.cjs`, see https://vite-plugin-ssr.com/importBuild.cjs
```

**Comment by brillout** [comment]
Do you use Yarn PnP and did you change `vite.config.js#build.outDir`?

> The file importBuild.cjs doesn't exist anywhere in my project

It should exist in `dist/server/`. If you import it it should fix the problem.

**Comment by kryptus36** [comment]
Sorry, disregard. I had another problem in my build chain that was causing this.
