### ISSUE TITLE
Reduce `pageContext` size (when HTML serialized `pageContext` is getting large)

### ISSUE THREAD

**Issue by brillout** [brillout/vite-plugin-ssr#364]
### Description

See title

**Comment by brillout** [comment]
@spacedawwwg 

> We have some hefty sustainability KPI's to hit and reducing the page weight is high up on that. Since we've moved to VPS we've managed to lower everything except the HTML file size (which has gone up due to embedded context,

Isn't that a user land thing? *You* populate the `pageContext` so *you* have the power to decide what's in it.

One thing that you may want to consider is to have multiple `renderer/` but this may be overkill if all you want to do is to reduce what gets populated to `pageContext`.

The question here is: how do you currently populate `pageContext`? Is there a way to populate certain things only conditionally?

> whereas before the 'hydration' payload was split into smaller files)

How so?

**Comment by spacedawwwg** [comment]
As an example, our raw pageContext's are ~160kb. 

130kb of that is actually 'global' data (we have so hefty mega-nav data unfortunately which is pumping up that size).

So by separating the global part of that data into a context that only needs to be loaded once, we're getting the HTML file size back down to a respectable size. 

Which is also good for Non-JS users as they don't need any of the payload.

**Comment by brillout** [comment]
Closing but let me know if you still run into issues.
