### ISSUE TITLE
vps start slow with antd

### ISSUE THREAD

**Issue by hemengke1997** [brillout/vite-plugin-ssr#367]
### Description

Repo: https://github.com/hemengke1997/vps-antd-repo.git

> antd is a UI lib: https://github.com/ant-design/ant-design/

I've tested four condition.
1. only vps: start fast
2. vps with antd: start slow
3. only vite: start fast
4. vite with antd: start fast

## vps with antd
![1](https://user-images.githubusercontent.com/49073282/179946958-8f4eb318-31a9-4657-80ab-857a95ea5b63.png)
Every startup is slow, seems that vite dep optimization is useless.

## only vps
![2](https://user-images.githubusercontent.com/49073282/179946975-4ef79bd1-8f0d-492a-bdd0-06484b2faccb.png)

## vite with antd
![image](https://user-images.githubusercontent.com/49073282/179951058-8c47cacf-5a8c-4616-86b7-e66e7e7d7ddd.png)
The first cold start is a little bit slow, but the later start will be faster because of dep optimization

**Comment by brillout** [comment]
So if you remove antd then it's fast again?

**Comment by brillout** [comment]
Is it also slow with Vite 2?

**Comment by hemengke1997** [comment]
> Is it also slow with Vite 2?

Yes, I've tested

**Comment by hemengke1997** [comment]
Thank you for replying so quickly!
I have one question. I used `cross-env DEBUG=vps:* npm run dev`,  but there is no log.

**Comment by brillout** [comment]
and vps 0.3.64?

> I used `cross-env DEBUG=vps:* npm run dev`, but there is no log.

Hm, that should work though. Btw you may want to also use `DEBUG=vite:deps` which is for Vite's dep scanner.

**Comment by hemengke1997** [comment]
> and vps 0.3.64?

fist startup:
![1658312173922](https://user-images.githubusercontent.com/49073282/179958389-4811a09b-bce4-4109-b8c6-f6859007761b.png)

second startup with deps optimization
![1658312109118](https://user-images.githubusercontent.com/49073282/179958477-6eb5c109-6e71-4dd7-9727-1e66e10604b4.jpg)

**Comment by brillout** [comment]
Alright, let me open a Vite ticket for this.

**Comment by brillout** [comment]
Actually: https://github.com/vitejs/vite/issues/8850

Are you on windows?

**Comment by brillout** [comment]
FYI while running your reproduction I also stumbled upon this Vite error:

```bash
> @ dev /home/romuuu/tmp/vps-antd-repo
> npm run server


> server
> node ./server

Server running at http://localhost:3001

🍃 DOM ready in 42.55 s

4:19:22 PM [vite] error while updating dependencies:
Error: ENOENT: no such file or directory, rename '/home/romuuu/tmp/vps-antd-repo/node_modules/.vite/deps_temp' -> '/home/romuuu/tmp/vps-antd-repo/node_modules/.vite/deps'
    at renameSync (node:fs:1001:3)
    at Object.commit (file:///home/romuuu/tmp/vps-antd-repo/node_modules/.pnpm/vite@3.0.2/node_modules/vite/dist/node/chunks/dep-1513d487.js:36856:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async commitProcessing (file:///home/romuuu/tmp/vps-antd-repo/node_modules/.pnpm/vite@3.0.2/node_modules/vite/dist/node/chunks/dep-1513d487.js:36331:17)
    at async runOptimizer (file:///home/romuuu/tmp/vps-antd-repo/node_modules/.pnpm/vite@3.0.2/node_modules/vite/dist/node/chunks/dep-1513d487.js:36369:17)
```

**Comment by hemengke1997** [comment]
Thank you very much.
I'm sorry, I thought it was vps's bug.

> It's an upstream bug.
I don't know why it's so slow every time vite starts. May I ask you why vite dep optimization dose not work? 😊 

Thank you again.

**Comment by hemengke1997** [comment]
In other word, I'm confused about how you find that it's upsteam bug? 
Thank you!

**Comment by brillout** [comment]
It's a Vite bug, not a vps bug.

**Comment by hemengke1997** [comment]
> I'm sorry, I thought it was vps's bug.

Sorry for my bad english. I know it's vite bug.
I mean... I was wrong about vps. Sorry

**Comment by brillout** [comment]
No worries :-)
