### ISSUE TITLE
Allow defining `_error.page.vue` at `pages/_default/`

### ISSUE THREAD

**Issue by AaronBeaudoin** [brillout/vite-plugin-ssr#374]
### Description

Recently support was added for placing `_default.page.[server|client].[js|ts]` files at `pages/_default/` which I have found to be a really clean and intuitive file structure.

I do however feel that `_error.page.vue` makes a lot of sense at this location as well, because **it is other only page which VPS treats specially**, and it is very much a "default" or "fallback" in the sense it is what VPS shows when no other pages are matched. I also would expect to need to update this file very infrequently, so tucking it at `pages/_default/` feels natural.

**Comment by brillout** [comment]
Doesn't it already work? Normally `_error.page.*` can live wherever it wants (it's actually a flaw if someone wants multiple/different `_error` pages).

I just double checked and it should work: https://github.com/brillout/vite-plugin-ssr/blob/c129b9ed7e619455078baff073bd51b86ca12563/vite-plugin-ssr/shared/route/error-page.ts.

**Comment by AaronBeaudoin** [comment]
Minimal reproduction:

https://github.com/AaronBeaudoin/vps-issue-error-in-default-dir
