### ISSUE TITLE
HMR doesn't work for SPA pages

### ISSUE THREAD

**Issue by AaronBeaudoin** [brillout/vite-plugin-ssr#375]
### Description

When a page filename is written as `[name].page.client.xyz` to make it client-side only (SPA), HMR doesn't seem to work on that particular page.

### Error Stack

N/A

**Comment by brillout** [comment]
Normally it should work as shown by this test: https://github.com/brillout/vite-plugin-ssr/blob/c129b9ed7e619455078baff073bd51b86ca12563/examples/render-modes/.testRun.ts#L91-L95.

I'd need a reproduction for this.

**Comment by AaronBeaudoin** [comment]
Minimal reproduction:

https://github.com/AaronBeaudoin/vps-issue-client-only-hmr

**Comment by brillout** [comment]
Closing in favor of https://github.com/vitejs/vite/issues/9341.

HMR is handled by Vite. I wouldn't know why vps would break Vite's HMR support.
