### ISSUE TITLE
Pre-rendered HTML-only pages are missing CSS from components

### ISSUE THREAD

**Issue by AaronBeaudoin** [brillout/vite-plugin-ssr#376]
### Description

When using `[name].page.server.xyz` in combination with `ssr({ prerender: true })`, component CSS is not included in the outputted HTML page. Adding `includeAssetsImportedByServer: true` to the config doesn't seem to make any difference.

### Error Stack

N/A

**Comment by brillout** [comment]
Normally it should work as shown by `examples/render-modes/pages/html-only/index.page.server.jsx`: https://github.com/brillout/vite-plugin-ssr/blob/c129b9ed7e619455078baff073bd51b86ca12563/examples/render-modes/pages/html-only/index.page.server.jsx#L3.

I'd need a reproduction for this.

**Comment by AaronBeaudoin** [comment]
Minimal reproduction:

https://github.com/AaronBeaudoin/vps-issue-server-only-css

**Comment by spacedawwwg** [comment]
Could this be related to https://github.com/vitejs/vite/issues/9308 @brillout ?

**Comment by brillout** [comment]
@spacedawwwg No, these are unrelated. I wouldn't be afraid of bisecting your app to isolate the problem: bisecting (exponential reduction of search space) + thoughtful deletion usually quickly gets you to a fairly minimal reproduction. (The reproduction doesn't need to be *that* minimal, it just shouldn't contain 30 dependencies, but more like 8 dependencies.)
