### ISSUE TITLE
`doNotPrerender` not working unless `[name].page.server.xyz`

### ISSUE THREAD

**Issue by AaronBeaudoin** [brillout/vite-plugin-ssr#378]
### Description

When pre-rendering pages, only those with filenames like `[name].page.server.xyz` seem to be affected by the `doNotPrerender` export.

Minimal reproduction:

https://github.com/AaronBeaudoin/vps-issue-prerender

### Error Stack

N/A

**Comment by brillout** [comment]
For `.page.client.js` that's expected since these files are only loaded in the browser.

For `.page.js` I'll have a look.

Thanks for the bug report 👌.

**Comment by brillout** [comment]
I can confirm this, I'll fix it tomorrow.

I'll release it tomorrow along with all other fixes.

**Comment by brillout** [comment]
Actually, `export { doNotPrerender }` can now also be defined in `.page.client.js`. (Good timing: it's using a new technique introduced in vps 0.4 :-).)
