### ISSUE TITLE
`doNotPrerender` not working if page uses TypeScript

### ISSUE THREAD

**Issue by AaronBeaudoin** [brillout/vite-plugin-ssr#381]
### Description

If my `.vue` file's script tag has a `lang="ts"` then `doNotPrerender` has no effect.

Minimal reproduction:

https://github.com/AaronBeaudoin/vps-issue-donotprerender-ts

### Error Stack

N/A

**Comment by brillout** [comment]
I see what's going on. I'll fix this later today/tomorrow.

Thanks for the bug report! It's actually very insightful (turns out that Vue's SFCs with `lang=ts` are not statically analyzable).

**Comment by brillout** [comment]
For reference, this is the root cause: https://github.com/brillout/vps-issue-donotprerender-ts.

**Comment by brillout** [comment]
> not statically analyzable

Actually, spreading the `?extractExportNames` query does the trick. Similarly to `?extractStyles`.

This is fixed.
