### ISSUE TITLE
clientRouting not working with i18n recipe or query arguments

### ISSUE THREAD

**Issue by javiertury** [brillout/vite-plugin-ssr#383]
### Description

`clientRouting` makes the browser raise an error because `pageContext.url` is different from `url`.

https://github.com/brillout/vite-plugin-ssr/blob/5a7fb53606b5efac6188cff6dac8bd80285449ae/vite-plugin-ssr/client/router/useClientRouter.ts#L156

This happens after following [the official i18n recipe](https://vite-plugin-ssr.com/i18n) and adding `clientRouting` on top. E.g. `/about` is different from real url `/en/about`.

It also happens when using `clientRouting` and query parameters. E.g. `/contact` is different from real url `/contact?ref=1234`.

Could this restriction be relaxed? Perhaps it can be removed or perhaps vite could detect if a route exports an optional function `isUrlAllowed` and match it against the real `url`.

### Error Stack

```
Uncaught (in promise) Error: [vite-plugin-ssr@0.4.9][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Reach out at https://github.com/brillout/vite-plugin-ssr/issues/new or https://discord.com/invite/qTq92FQzKb and include this error stack (the error stack is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Do not hesitate to reach out as it makes vite-plugin-ssr more robust. 
    O newError.js:8
    i assert.js:25
    t useClientRouter.js:111
    o useClientRouter.js:113
    cn useClientRouter.js:39
    <anonymous> entry.js:4
[newError.js:8:14](http://localhost:3000/node_modules/.pnpm/@brillout+libassert@0.5.8/node_modules/@brillout/libassert/dist/esm/newError.js)
    o useClientRouter.js:131
    AsyncFunctionThrow self-hosted:637
    (Async: async)
    cn useClientRouter.js:39
    <anonymous> entry.js:4
    InnerModuleEvaluation self-hosted:2355
    evaluation self-hosted:2312
```

**Comment by brillout** [comment]
Yes, I think it can be relaxed/removed.

Does what you want to achieve work if you remove that assertion?

**Comment by brillout** [comment]
I'll release the fix later today / tomorrow.
