### ISSUE TITLE
Can't get @vitejs/plugin-legacy working

### ISSUE THREAD

**Issue by CanRau** [brillout/vite-plugin-ssr#39]
Me again 😅

I (think) I can't get [@vitejs/plugin-legacy](https://github.com/vitejs/vite/tree/main/packages/plugin-legacy) working properly, I've set up `helmet` for express to generate the `Content-Security-Policy` headers for the script hashes and it's generating the legacy bundles, but I think it's not actually referencing anything in my html not in `<head/>` nor in `<body/>`

My `vite.config.js` plugins looks like this
```js
plugins: [legacy(), reactRefresh(), ssr()],
```
Also tried different ordering just to make sure.

Do I have to include anything in my `_default.page.server.tsx` manually?

I guess it's due to `vite-plugin-ssr` not using Vites static `index.html` file 🤔

**Comment by brillout** [comment]
Hello again 😊 

I will have a look.

> I guess it's due to vite-plugin-ssr not using Vites static index.html file 🤔

No, the HTML transformers of all plugins are applied.

**Comment by CanRau** [comment]
Thank you 😇

> No, the HTML transformers of all plugins are applied.

Yea, I imagined that, but than don't understand why it's not working, so I guessed it might be somehow not the case ^^

Also I noticed
```html
<script>
window.__vite_plugin_ssr = ...
</script>
```
in DevTools, I guess this'd need a hash nonce as well to get CSP working properly, right?

**Comment by brillout** [comment]
Actually, the HTML transformers are only applied in dev.

I will check tomorrow how to apply the HTML transformers in production.

> I guess this'd need a hash nonce as well to get CSP working properly, right?

Isn't there a way to tell CSP to allow inline scripts? IIRC CSP is quite configurable.

Any other problems with the legacy plugin?

**Comment by CanRau** [comment]
Uh okay, so we both were right^^ Thank you 🙏

> Isn't there a way to tell CSP to allow inline scripts? IIRC CSP is quite configurable.

Yea pretty sure there is, thought it's desirable to disallow if possible though, maybe I'm over restrictive here 🤷‍♂️

**Comment by brillout** [comment]
> Yea pretty sure there is, thought it's desirable to disallow if possible though, maybe I'm over restrictive here 🤷‍♂️

I agree that'd be nice.

> I will check tomorrow 

It's getting late here

**Comment by brillout** [comment]
Had a closer look; the legacy plugin doesn't support SSR (its HTML transformer assumes that the HTML is rendered at build-time). `vite-plugin-ssr` could apply the required HTML changes itself, but it would require time to implement. AFAICT I don't see it to be worth it as the JS ecosystem is increasingly dropping IE11 support. For example IIRC Vue 3 won't support IE 11.

Do you really need IE 11 support?

**Comment by CanRau** [comment]
Good question, I leave it out for now and see how it feels, thanks for looking into it 🙏
I'll close this for now then.

**Comment by kadiryazici** [comment]
@brillout @vitejs/plugin-legacy does not add just IE 11 support. It adds

**Comment by kadiryazici** [comment]
@brillout @vitejs/plugin-legacy does not add just IE 11 support. It adds `es modules` support for browsers those don't support it.

For example `vue@3` uses `Proxy`, proxies are available in `Chrome 49+` but `es modules` are available in `Chrome 60+`. That is huge actually and latest chrome version of `windows xp` is `49`.

[Vite SSR](https://github.com/frandiox/vite-ssr) had the same problem, what id does now is it compiles `ONLY` client files with `@vitejs/plugin-legacy` [See](https://github.com/frandiox/vite-ssr/commit/347cc16bbc9986294f8a4202fe87bce425312653#diff-25a6634263c1b1f6fc4697a04e2b9904ea4b042a89af59dc93ec1f5d44848a26)

**Comment by brillout** [comment]
@kadiryazici

Windows XP is deprecated since 2014; I'm all to inclined to spend time on supporting environments that are dying.

Do you have a use case that justifies support for older browser?

**Comment by kadiryazici** [comment]
@brillout Government 😀

**Comment by brillout** [comment]
Have you tried the plugin? I believe it works as long as you don't pre-render. For pre-rendering I've a solution in mind.

**Comment by kadiryazici** [comment]
I used `vite-plugin-ssr` but not `@vitejs/plugin-legacy` I just saw this issue and wanted to send a comment. 
And I'm sorry for commenting before using it.

**Comment by brillout** [comment]
No worries, let me know if & how you run into problems.

**Comment by loafofpiecrust** [comment]
Any update on a solution for this with pre-rendering? @brillout you mentioned having something in mind. I'm also working on a project with government users that can only use IE11 and hoping to use this tool. `@vitejs/plugin-legacy` doesn't seem to be working properly with this on my first attempt at SSG.

**Comment by brillout** [comment]
@loafofpiecrust What's your tech stack? A lot of tools are dropping IE11 support.

**Comment by loafofpiecrust** [comment]
Yeah I know, I'm trying to figure out how many features I can support for the IE11 users without losing solid dev tools. The front-end is a React app that is statically rendered and then hydrated at load. I'm using [`vanilla-extract`](https://vanilla-extract.style/) to generate fully static CSS. Beyond that, all of the data fetching is through GraphQL using `urql`.

**Comment by brillout** [comment]
`@vitejs/plugin-legacy` has an HTML transform which `vite-plugin-ssr` cannot aply (it's a Vite design shortcoming), and also `vite-plugin-ssr`'s client uses ES6 proxy which IE11 doesn't support.

That said, I believe these two issues are fixable but it would consume some of my time and, as you can understand, IE11 support is not on top of priority list.

If your employer is willing to, I can work on this against monetary compensation.

**Comment by lukastaegert** [comment]
Also check out #477
