### ISSUE TITLE
html streaming is not starting emit data util custom stream emit first data 

### ISSUE THREAD

**Issue by uuau99999** [brillout/vite-plugin-ssr#396]
### Description

It seems while using html streaming, response will not emit data until my stream emit first data. But since my stream is wrapped in a TemplateWrapped, the static part of that can and should be emitted to client as soon as possible and don't have to wait for my stream to emit first data. 
My currently fix is to emit a useless dom structure to make it emit immediatly, which is not making sense.
Maybe to imporve that? Thanks!

**Comment by brillout** [comment]
I believe this is a sensible default. (E.g. this is what should be done with React 18.)

What UI Framework are you using?

Why isn't the "page shell" sent early (usually your root component has an outer shell that can be sent right away)?

**Comment by uuau99999** [comment]
I' m using Vue 3.  When your app need to fetch init data before render, you can't ensure the stream(E.g. Vue) is emitted immediately. So it would be better that the response emit the static part first regardless of the stream provided.

**Comment by brillout** [comment]
How does Vue handle errors during the stream? E.g. if the init data couldn't be fetched.

**Comment by uuau99999** [comment]
Even if init data couln't be fetched the static part of the page still need to be sent to the client. Apart from that it is the app logic to handle such error scenes. Since the static part of the page which wraps the stream is provided, why should the response wait for the first data from the stream to be emitted?

**Comment by brillout** [comment]
> why should the response wait for the first data from the stream to be emitted

Because of the status code which, once sent to the browser, cannot be changed. The React team recommends this approach.

Imagine the `googlebot` crawling your website and there is an error. The bot certainly shouldn't get a `200`, otherwise it will overwrite the content of your website with the content of the error page.

What's Vue official recommendation around that problem?

**Comment by brillout** [comment]
Just implemented `pageContext.enableEagerStreaming`. I didn't test it but I believe it should work. Let me know if it doesn't.

> What's Vue official recommendation around that problem?

I'd be quite curious about this!

**Comment by brillout** [comment]
Released in `0.4.16`.

**Comment by uuau99999** [comment]
I just test 0.14.16 and it works fine. Thanks!
