### ISSUE TITLE
Must be used vite's build.assetsDir argument instead of hardcoded assets

### ISSUE THREAD

**Issue by oleghalin** [brillout/vite-plugin-ssr#397]
### Description

Must be used vite's build.assetsDir argument instead of hardcoded assets 

For now i have misconfiguration, i cannot use assets name in my env, so it requires changes. 

https://github.com/brillout/vite-plugin-ssr/blob/5a7fb53606b5efac6188cff6dac8bd80285449ae/vite-plugin-ssr/node/plugin/plugins/distFileNames.ts#L30

**Comment by brillout** [comment]
Why do you want to rename `assets`?

**Comment by brillout** [comment]
Makes sense. Let me implement this.

**Comment by brillout** [comment]
I'll release this in a moment.

**Comment by oleghalin** [comment]
@brillout thanks, appreciate fast responses :)

**Comment by brillout** [comment]
Released in `0.4.16`.

**Comment by oleghalin** [comment]
After updating to the latest version built version of the code doesn't resolve assets when assetDir is specified.

**Comment by brillout** [comment]
Just seeing the edit; re-closing.

Let me know if you do end up believing there is a bug in vps.
