### ISSUE TITLE
`BUG`: css assets error

### ISSUE THREAD

**Issue by hemengke1997** [brillout/vite-plugin-ssr#398]
### Description

# vps@0.4.13
![1659345148988](https://user-images.githubusercontent.com/49073282/182115702-1297a474-63be-469a-9630-afda390dcca4.jpg)

# vps@0.4.15
![1659345264587](https://user-images.githubusercontent.com/49073282/182115737-53cda3ff-1b35-49c9-bd66-9f056734e0e7.jpg)

![1659345303800](https://user-images.githubusercontent.com/49073282/182115750-f1e3a1b0-c941-426c-9056-baf0280b615d.jpg)

![image](https://user-images.githubusercontent.com/49073282/182115849-1f51bfd0-6866-4869-b066-1eb9c19b3b18.png)

# bug repo
https://github.com/hemengke1997/vps0.4.15-cssbug-repo

# bug source
https://github.com/brillout/vite-plugin-ssr/blob/main/vite-plugin-ssr/node/retrievePageAssets.ts#L118

**Comment by brillout** [comment]
I'll have a look.

**Comment by brillout** [comment]
That's because of https://github.com/brillout/vite-plugin-ssr/pull/395/files which I believe is the correct behavior.

The fix is probably to load some other CSS `antd` entry.

**Comment by hemengke1997** [comment]
Okay, but actually because of this, 240 css modules were loaded by the browser, and an error was occured due to incorrect css loading sequence or incorrect links. 😥

Before vps@0.4.15, it only import one `less` and worked fine 😂

**Comment by brillout** [comment]
It was more a coincidence than something we should support :-).

**Comment by hemengke1997** [comment]
Thank you for your reply.

**Comment by brillout** [comment]
Fix released in `0.4.17`. Let me know if you still run into issues.

**Comment by brillout** [comment]
Thanks for sponsoring @hemengke1997. If you are on Discord, let me know your ID there and I'll give you a Sponsor Badge.

**Comment by brillout** [comment]
I'm glad it helped :-).

Just sent you a friend request (seems to be the only way to connect with a Discord user that doesn't share a common Discord server).

But feel free to ignore it :-).
