### ISSUE TITLE
HMR stops working if `pageProps` is accessed on client side but not in `passToClient`

### ISSUE THREAD

**Issue by AaronBeaudoin** [brillout/vite-plugin-ssr#399]
### Description

Took me a while to narrow down this issue, and I don't know if it's a VPS thing or a Vite thing, but here it is.

If `pageProps` is not in `passToClient`, HMR stops working if `pageContext.pageProps` is accessed on the client side.

### Minimal Reproduction

https://github.com/AaronBeaudoin/vps-issue-hmr-pageprops

**Comment by brillout** [comment]
Thanks for opening the issue.

That's expected because the browser-side throws an error:

```
entry.js:14 Uncaught (in promise) Error: [vite-plugin-ssr@0.4.16][Wrong Usage] `pageContext.pageProps` is not available in the browser. Make sure that `passToClient.includes('pageProps')`. (Currently `passToClient` is `[]`.) More infos at https://vite-plugin-ssr.com/passToClient
    at assertPassToClient (releasePageContext.js:98:5)
```

Which means that the page won't get hydrated and therefore HMR cannot work.
