### ISSUE TITLE
Public dir assets not working correctly

### ISSUE THREAD

**Issue by camiloforero** [brillout/vite-plugin-ssr#406]
### Description

To reproduce the bug:

* Scaffold a brand new project (`npm init vite-plugin-ssr@latest`), and choose the Vue template
* Move the `logo.svg` asset from `renderer` to a new `public` directory
* Modify `renderer/PageShell.vue` and `renderer/_default.page.server.js` like the following diff:

```diff
diff --git a/renderer/logo.svg b/public/logo.svg
similarity index 100%
rename from renderer/logo.svg
rename to public/logo.svg
diff --git a/renderer/PageShell.vue b/renderer/PageShell.vue
index 7485e2c..a7a559d 100644
--- a/renderer/PageShell.vue
+++ b/renderer/PageShell.vue
@@ -2,7 +2,7 @@
   <div class="layout">
     <div class="navigation">
       <a href="/" class="logo">
-        <img src="./logo.svg" height="64" width="64" alt="logo" />
+        <img src="/logo.svg" height="64" width="64" alt="logo" />
       </a>
       <Link href="/">Home</Link>
       <Link href="/about">About</Link>
diff --git a/renderer/_default.page.server.js b/renderer/_default.page.server.js
index bc0ed20..ef902bc 100644
--- a/renderer/_default.page.server.js
+++ b/renderer/_default.page.server.js
@@ -1,7 +1,6 @@
 import { renderToString } from '@vue/server-renderer'
 import { escapeInject, dangerouslySkipEscape } from 'vite-plugin-ssr'
 import { createApp } from './app'
-import logoUrl from './logo.svg'
 
 export { render }
 // See https://vite-plugin-ssr.com/data-fetching
@@ -20,7 +19,7 @@ async function render(pageContext) {
     <html lang="en">
       <head>
         <meta charset="UTF-8" />
-        <link rel="icon" href="${logoUrl}" />
+        <link rel="icon" href="/logo.svg" />
         <meta name="viewport" content="width=device-width, initial-scale=1.0" />
         <meta name="description" content="${desc}" />
         <title>${title}</title>

```
* Run `npm run build`

It should just work (and it used to work in `v0.3.x`) but it throws the error in the Error Stack.

If I change the url to `/public/logo.svg` in `PageShell`, it builds successfully but
* I shouldn't be doing that. It goes explicitly against [Vite's documentation on the public directory](https://vitejs.dev/guide/assets.html#the-public-directory), which says I should reference `public` assets using the root absolute path.
* When checking the `/dist/client` directory, there is both a `logo.svg` file and a `/assets/logo.[chunkhash].svg` file, `_default.page.server.js` uses the first one, and `/PageShell.vue` uses the second one. This tells me Vite is processing the logo in `PageShell` as an asset, when it shouldn't be. This also happens with `index.page.vue` files, which is how I came onto this issue on my own project
![image](https://user-images.githubusercontent.com/6606686/182881178-671dfd8a-e76c-46d2-9221-a5e62bcf8f28.png)

### Error Stack

```shell
[vite]: Rollup failed to resolve import "/logo.svg" from "renderer/PageShell.vue".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
[vite-plugin-ssr:autoFullBuild] [vite]: Rollup failed to resolve import "/logo.svg" from "renderer/PageShell.vue".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
error during build:
Error: [vite]: Rollup failed to resolve import "/logo.svg" from "renderer/PageShell.vue".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at onRollupWarning (/home/camilo/tests/vite-ssr-project/node_modules/vite/dist/node/chunks/dep-c9998dc6.js:41797:19)
    at onwarn (/home/camilo/tests/vite-ssr-project/node_modules/vite/dist/node/chunks/dep-c9998dc6.js:41613:13)
    at Object.onwarn (/home/camilo/tests/vite-ssr-project/node_modules/rollup/dist/shared/rollup.js:23216:13)
    at ModuleLoader.handleResolveId (/home/camilo/tests/vite-ssr-project/node_modules/rollup/dist/shared/rollup.js:22466:26)
    at /home/camilo/tests/vite-ssr-project/node_modules/rollup/dist/shared/rollup.js:22427:26
```

**Comment by brillout** [comment]
Are you sure it's related to vps and not Vite? See https://brillout.github.io/rules/.

That said, if you provide a minimal reproduction I'd be willing to have a quick look.

If you have evidence it's related to vps, then I'll have a deep look and fix it.

Closing in the meantime.

**Comment by camiloforero** [comment]
I get the impression you did not actually read the issue; there was a precise description of how to reproduce it .

I did make a repo with a reproduction though, it has three commits, one to make `logo.svg` public and one to use the latest Vite 3 version instead of the default Vite 2 version that comes with the scaffold. The same bug persists with Vite 3.
https://github.com/camiloforero/vps-with-bug

Also, another repo following the same procedure of scaffolding a new vue3/vite3 project (`npm init vue@latest`) and moving `logo.svg` to the `public` folder; in this one `npm run build` works normally and there is no bug.
https://github.com/camiloforero/vue-vite-scaffold-public-svg

If the bug happens only in the vps scaffold with both vite 2 and vite 3, and does not happen in the default pure vite 3 scaffold, then I'm pretty sure it's a vps issue
https://github.com/camiloforero/vue-vite-scaffold-public-svg

**Comment by brillout** [comment]
Do not create duplicated issues. Never do this. I deleted the second issue.

> Rollup failed to resolve import "/logo.svg" from "renderer/PageShell.vue".

This means you have an `import "/logo.svg"` somewhere in your `PageShell.vue`.

So, yes, it does strongly point to a user land problem, not a vps one.

**Comment by camiloforero** [comment]
Then never prematurely close unhandled issues, especially without taking the effort to actually look into them.

Again, for your convenience, the repo with the reproduction: https://github.com/camiloforero/vps-with-bug. It's literally the result of running `npm init vite-plugin-ssr@latest` and making a few changes

There is no `import "/logo.svg"` anywhere in the code. The only reference to `logo.svg` is here
https://github.com/camiloforero/vps-with-bug/blob/477f7db302d63bc745e1a4a76a88e7cb161d6fde/renderer/PageShell.vue#L5

A link to similar code using the basic `npm init vue@latest`
https://github.com/camiloforero/vue-vite-scaffold-public-svg

It works here. So it's definitely a vps issue

**Comment by brillout** [comment]
Seems like Vue is automatically injecting import statements upon parsing `img.src`.

Look up the Vue documentation if there is a way to tell Vue to not automatically inject imports upon `img.src`.

And please report back so that future readers can benefit from your research.

**Comment by camiloforero** [comment]
That wouldn't make sense because:
* [This project](https://github.com/camiloforero/vue-vite-scaffold-public-svg/blob/main/src/App.vue) also uses Vue 3 and Vite 3, has a `img.src` [here](https://github.com/camiloforero/vue-vite-scaffold-public-svg/blob/7f0417742b715a89431bcb90948672dbc557586a/src/App.vue#L8), and `npm run build` works fine
* I was running a website with vps `v0.3.x` and I had a lot of similar references and they worked just fine. THis bug only appeared when I upgraded it to `v0.4.17`.

**Comment by brillout** [comment]
I can't fathom why this would be a vps issue.

**Comment by camiloforero** [comment]
Doing the same thing using `npm init vite-plugin-ssr@0.0.150` (which uses `v0.3.64`)
https://github.com/camiloforero/vite-ssr-old

`npm run build` works normally, as does `npm run prod`

So it has to be something that happened between the last 0.3 and the current 0.4

**Comment by brillout** [comment]
It's not the only dependency that changed, e.g. `vite` and `@vitesjs/plugin-vue`.

**Comment by camiloforero** [comment]
Cool, so, compare:
https://github.com/camiloforero/vps-with-bug/tree/bf46bbfbf36c1912dcd5b379d02df5e921b0ff32 (the commit right before main, after moving logo.svg to public but without upgrading to vite 3)
https://github.com/camiloforero/vite-ssr-old

Same versions of everything, except vps and `sirv`, which was added by you to the boilerplate.

Anything else?

**Comment by brillout** [comment]
What would be nice is a reproduction with a single commit that only updates vps. Before it works, not after. I'd then have a look at it.

**Comment by camiloforero** [comment]
Doing a manual code migration from vps v0.3 to v0.4 is asinine and time consuming. The reproductions I've made are enough to show the bug's existance, and I will not do further unnecessary work just to convince you that there is in fact a bug, especially if you haven't even actually looked at it, at all.

You have a bug, do with that information what you will.

**Comment by brillout** [comment]
https://github.com/vitejs/vite/issues/10082
