### ISSUE TITLE
Redirect loop when navigating to a 404 with a `#`

### ISSUE THREAD

**Issue by chrisvariety** [brillout/vite-plugin-ssr#41]
Hello again 👋 

I'm seeing a fun redirect loop when navigating to a 404 page that has a `#` in the URL.

https://user-images.githubusercontent.com/44855/115090928-2971fb80-9ee4-11eb-9a1a-c83325974ee3.mp4

Vite: 2.1.4
vite-plugin-ssr: 0.1.0-beta.32 (also an issue in 0.1.0-beta.31, did not test beyond that)

Reproduction steps:

Checkout example at https://github.com/brillout/vite-plugin-ssr/tree/master/examples/react install & run.
Navigate to a 404 page with a `#` at the end, like `/aaa#`.
Notice the page continually loads, and `%23` gets added onto the URL over and over again.

**Comment by brillout** [comment]
Hi @chrisvariety, fix is released in `0.1.0-beta.33`. I'm increasing the priority of my plans to write a test suite about URL edge cases.

**Comment by brillout** [comment]
> fun redirect loop

😀
