### ISSUE TITLE
query parameters

### ISSUE THREAD

**Issue by hamedg68** [brillout/vite-plugin-ssr#413]
### Question / Discussion

how to access query parameters in component?

**Comment by brillout** [comment]
This https://vite-plugin-ssr.com/pageContext#built-in > `pageContext.urlParsed.search` and https://vite-plugin-ssr.com/pageContext-anywhere?

**Comment by hamedg68** [comment]
in  pageContextInit.url I can not access query parameters . why?

**Comment by hamedg68** [comment]
www.xxxxx.com/flights/THR-AZD?adult=1&child=1&infant=1&departing=2022-05-27&returning=2022-06-21

**Comment by brillout** [comment]
It's probably a user land thing.

Check out https://brillout.github.io/rules/.
