### ISSUE TITLE
Deep Integration with React Router

### ISSUE THREAD

**Issue by sebasptsch** [brillout/vite-plugin-ssr#414]
### Description

As someone who is deeply familiar with react router I want to achieve a similar approach to `remix.run` whilst still having the flexibility that `vite-plugin-srr` provides in order to use some parts of my site clientside (Admin UI) and others serverside.
In #9 and in the docs it is mentioned that it should be possible using the onBeforeRoute hook although I wouldn't know where to start.

Thanks!

**Comment by brillout** [comment]
Beyond familiarity, what are your reasons for using React Router?

In general the recommendation is to stick with vps's built-in router. Which we can improve.

That said, I'm open for accommodating vps to make this work. But only to a small extent as I see this as low priority. (Because I still believe using the built-in router to be a superior choice but I'm happy to be shown wrong.)

In a nutshell: feel free to try yourself but consider this experimental and expect that this may never come to fruition.

**Comment by sebasptsch** [comment]
The main reason for using react router is the nested routes system where I can put an <Outlet /> Tag in a component.

**Comment by brillout** [comment]
> nested routes system where I can put an Tag in a component.

What do you mean exactly?

**Comment by sebasptsch** [comment]
Oh sorry. It looks like GitHub tried to parse what I wrote as an html tag. [React Router Outlet Docs](https://reactrouter.com/docs/en/v6/components/outlet)

**Comment by brillout** [comment]
Would https://github.com/brillout/vite-plugin-ssr/issues/346 be a satisfactory alternative to you?

**Comment by sebasptsch** [comment]
> Would https://github.com/brillout/vite-plugin-ssr/issues/346 be a satisfactory alternative to you?

I think so, assuming that NestedView can be used as a component.

**Comment by brillout** [comment]
Yes, `pageContext.nested[i].Page` is the same as `pageContext.Page` but for the nested views.

Let me know if you need this to be implemented sooner rather than later.

**Comment by sebasptsch** [comment]
> 

No rush.

**Comment by tiagoad** [comment]
This issue was closed as completed, but it doesn't look solved. Perhaps reopen as even though it turns out you don't need this, it's still an enhancement that isn't implemented and people will be interested in.

**Comment by brillout** [comment]
In principle, it should be possible by using the `onBeforeRoute()` hook.

**Comment by brillout** [comment]
Simliar Vue Router ticket: https://github.com/brillout/vite-plugin-ssr/issues/611.

**Comment by algesthesiah** [comment]
Can the VPS internally implement a keep-alive feature similar to Vue and React Router? That is, switching the routing URL under the current browser tab will retain the original page instead of re-rendering it.
@brillout

**Comment by brillout** [comment]
@algesthesiah Create a discussion on https://github.com/brillout/vite-plugin-ssr/discussions

**Comment by brillout** [comment]
Closing, see https://vite-plugin-ssr.com/vue-router-and-react-router. Bottom line being:

> If you want a feature provided by Vue Router or React Router that vite-plugin-ssr is missing, then open a new feature request.
