### ISSUE TITLE
An internal heuristic needs to be updated

### ISSUE THREAD

**Issue by brillout** [brillout/vite-plugin-ssr#423]
### Description

Vite-plugin-ssr uses an internal heuristic to detect whether you are using React.

This heuristic may change over time.

If you run into the warning `[vite-plugin-ssr][Warning] An internal heuristic needs to be updated` then help us update the heuristic by doing the following:

1. Edit `node_modules/vite-plugin-ssr/dist/esm/utils/detectHydrationSkipSupport.js` and add a new line:
   ```js
   console.log(`isReact1: ${isReact1}, isReact2: ${isReact2}, isReact3: ${isReact3}`);
   ```
   Just before this line:
   ```js
   assertWarning(isReact1 && isReact2 && isReact3, 'An internal heuristic needs...);
   ```
1. `rm -rf node_modules/.vite/` then start your server and let us know the output of the `console.log()` you just added.
1. What UI framework are you using? Which version?
1. If you use React, let us know the result of:
   - `$ cat node_modules/react/package.json | grep version`
   - `$ cat node_modules/@vitejs/plugin-react/package.json | grep version`

> FYI, this heuristic is only used to set the right default boolean value of an option. This heuristic is not crucial and can be removed (but the option won't be automatically set and the user will have to manually set its value).

**Comment by AlanMorel** [comment]
I use Vue `3.2.37` and my results are `isReact1: true, isReact2: false, isReact3: false`

**Comment by brillout** [comment]
👍 I managed to reproduce. I'll fix this. Thanks for the info.

**Comment by brillout** [comment]
Fix released in `0.4.25`.

**Comment by erictaylor** [comment]
Using `react` `18.2.0`, and `@vitejs/plugin-react` `2.0.1`. Results of log are:
```
isReact1: true, isReact2: false, isReact3: true, isReact4: true
```

**Comment by mcous** [comment]
I'm encountering this log statement in a simple Preact app

- `vite`: `3.0.9`
- `preact`: `10.10.6`
- `@preact/preset-vite`: `2.3.0`
- `vite-plugin-ssr`: `0.4.27`

Following the instructions in the original post, I get the following log statements:

```
isReact1: false, isReact2: false, isReact3: false, isReact4: true [detectHydrationSkipSupport.js:27:17](http://127.0.0.1:3000/node_modules/.pnpm/vite-plugin-ssr@0.4.27_vite@3.0.9/node_modules/vite-plugin-ssr/dist/esm/utils/detectHydrationSkipSupport.js)
[vite-plugin-ssr@0.4.27][Warning] An internal heuristic needs to be updated, see https://github.com/brillout/vite-plugin-ssr/issues/423
```

**Comment by brillout** [comment]
Thanks for the info. I will have a look at it.

**Comment by brillout** [comment]
Updated heuristic released in `v0.4.28`. I didn't test the change but I believe it should work. Let me know if you still get the warning.

**Comment by mcous** [comment]
Looking good from my end! Upgraded and no more warning

**Comment by devunt** [comment]
I encountered same problem today.

```
chunk-83508821.js:1 isReact1: true, isReact2: false, isReact3: false
chunk-8f37d887.js:2 [vite-plugin-ssr@0.4.31][Warning] An internal heuristic needs to be updated, see https://github.com/brillout/vite-plugin-ssr/issues/423
chunk-83508821.js:1 isReact1: true, isReact2: false, isReact3: false
```

* `react`: `18.2.0`
* `@vitejs/plugin-react`: `2.1.0`
* `vite-plugin-ssr`: `0.4.31`

**Comment by brillout** [comment]
Yes, the second log is expected.

The first one is quite unexpected though. What's the HTML of the page throwing that warning?

**Comment by brillout** [comment]
(Btw. I'm thinking of removing that heuristic. Something that I was meant to be a little trick is growing to be too complex to justify its existence.)

**Comment by ArthurSaenz** [comment]
- React: 18.2.0
- @vitejs/plugin-react: 2.2.0
- vite-plugin-ssr: 0.4.43

`isReact1: true, isReact2: false, isReact3: false`

**Comment by brillout** [comment]
Internal heuristic removed. Update to `v0.4.47` and follow the warning instructions.
