### ISSUE TITLE
Passing node.js Request params to pageContext

### ISSUE THREAD

**Issue by rawb1t** [brillout/vite-plugin-ssr#427]
### Description

Hi!

Is it possible to pass nodejs request params (such as Accept-Language) to the pageContext Object so the page (i18n for example) can react to the users prefered language?

Thank you!

**Comment by brillout** [comment]
Yes, check the docs.

Please dig more before reaching for help, see https://brillout.github.io/rules.

**Comment by rawb1t** [comment]
I checked the docs already but couldn't find any hint how to access the request object of nodejs. I even tried to pass it by myself into the renderPage parameter object but I had a look at the code and it seems like only 'url' will be used by the function. So how is it possible?

**Comment by brillout** [comment]
FYI https://github.com/brillout/vite-plugin-ssr/commit/bd50c014fe3443bfa45fd2305600e0e1a61a69a5.
