### ISSUE TITLE
`vite-plugin-ssr` is not cached during development

### ISSUE THREAD

**Issue by kidonng** [brillout/vite-plugin-ssr#438]
### Description

[Dependencies are strongly cached in Vite](https://vitejs.dev/guide/features.html#npm-dependency-resolving-and-pre-bundling), however this is not the case for `vite-plugin-ssr` itself:

<img width="721" alt="image" src="https://user-images.githubusercontent.com/44045911/188284743-cf8ce96e-bd7d-4e8c-9168-de451d827fcf.png">

Dependencies of `vite-plugin-ssr` seem to cache properly though:

<img width="625" alt="image" src="https://user-images.githubusercontent.com/44045911/188284746-02b9caf2-a795-4af5-9cfd-7b1c32a96e30.png">

This is particularly noticeable when I'm testing it out on Codespaces, http/1.1 + >80 chaining requests (with the react-ts boilerplate) is simply a nonstarter as components needs >2s in order to be interactive.

### Error Stack

```shell
N/A
```

**Comment by brillout** [comment]
The caching behavior is determined by Vite.

I don't know why there is a difference.

Both `@brillout/json-s` and `vite-plugin-ssr/client` are included in `optimizeDeps.exclude`: https://github.com/brillout/vite-plugin-ssr/blob/cfc63006b312ca38e0d0ad97e88248e2957f3079/vite-plugin-ssr/node/plugin/plugins/devConfig.ts#L17-L28.

**Comment by kidonng** [comment]
I deleted this entire section and got the same result, so somehow it isn't picked up by Vite?

**Comment by brillout** [comment]
Hm, I don't know. Maybe it's a glitch on Vite's side? I'd be curious to know why Vite treats both differently.

**Comment by brillout** [comment]
Just had a look and it's not a bug.

It's because the module is the entry. Note how `node_modules/vite-plugin-ssr/dist/esm/client/entry.js` is included in the HTML.

```html
      <script id="vite-plugin-ssr_pageContext" type="application/json">{"pageContext":{"_pageId":"/pages/index/index","pageProps":"!undefined","urlPathname":"/"}}</script><script type="module" async>
import RefreshRuntime from "/@react-refresh"
RefreshRuntime.injectIntoGlobalHook(window)
window.$RefreshReg$ = () => {}
window.$RefreshSig$ = () => (type) => type
window.__vite_plugin_react_preamble_installed__ = true
import("/@vite/client");
import("/@fs/home/romuuu/tmp/vite-ssr-project/node_modules/.pnpm/vite-plugin-ssr@0.4.31_vite@3.1.0/node_modules/vite-plugin-ssr/dist/esm/client/entry.js");
</script></body>
    </html>
```

You'll notice that all other `vite-plugin-ssr` modules have a cache hash in their URL.
