### ISSUE TITLE
Prepend base URL to `.pageContext.json` for index route.

### ISSUE THREAD

**Issue by Jearce** [brillout/vite-plugin-ssr#443]
### Description

From: https://discord.com/channels/815937377888632913/1016828144252108800/1017097091832631386

My application server is behind a reverse proxy, which appears to be an issue for the landing page route only on the client side. All other pages with `onBeforeRender` are fine SSR or CSR: base URL is handled as expected. My base URL is `/nano-ui`; thus, upon navigating to the landing page `/nano-ui` when CSR, the `pageContext` URL created is `/nano-ui.pageContext.json`, not `/nano-ui/index.pageContext.json`, which is what I would expect or something similar. To make the reverse proxy forwarding rule easier to define, I want `/nano-ui/index.pageContext.json` instead of `/nano-ui.pageContext.json`, which I believe VPS can handle.

**Comment by brillout** [comment]
FYI in case you(r company) is interested: https://github.com/sponsors/brillout.

**Comment by brillout** [comment]
Released in `0.4.32`.
