### ISSUE TITLE
Vite version out of date

### ISSUE THREAD

**Issue by gryphonmyers** [brillout/vite-plugin-ssr#45]
What is the plan for getting Vite up to date? We're currently pinned to 2.1.4, 2.1.5 has been out for a while and 2.2.1 just dropped. Also what is the deal with `vite-fix-2390`? We expect that to go away eventually?

**Comment by brillout** [comment]
`vite-fix-2390` is not required anymore for `>=2.2.0`. It was a big release and I'm waiting a bit until goes through "real life testing".

If someone needs `2.2.x` now, let me know and I'll skip the waiting and release a new `vite-plugin-ssr` right away.

**Comment by brillout** [comment]
> We're currently pinned

We will not be pinned anymore.

**Comment by gryphonmyers** [comment]
Awesome!!

**Comment by brillout** [comment]
There are still some changes going on in `2.2.x` so the plan is to wait a couple of days.

**Comment by brillout** [comment]
As of `0.1.0-beta.35`, any Vite version `>=2.2.3` can be used; the `vite-fix-2390` package is not necessary anymore.
