### ISSUE TITLE
Could you add an example for Vue3+Vue Router+Vuex?

### ISSUE THREAD

**Issue by atenxyz** [brillout/vite-plugin-ssr#453]
### Question / Discussion

Could you add an example for Vue3+Vue Router+Vuex? Thanks a lot
![image](https://user-images.githubusercontent.com/43084758/190285545-5d3ba04a-4b38-43b2-b3cb-7840320d8715.png)
![image](https://user-images.githubusercontent.com/43084758/190285903-fe0f95de-7022-40b8-859b-f9514a705110.png)

**Comment by brillout** [comment]
PR welcome. Also see https://brillout.github.io/rules.
