### ISSUE TITLE
bootstrap not working 

### ISSUE THREAD

**Issue by faizerturk** [brillout/vite-plugin-ssr#456]
### Question / Discussion

Hi dear, I create an  vite-plugin-ssr app in my local. I want to use bootstrap style but it's not working so my package.json is here :
<img width="356" alt="Screen Shot 2022-09-16 at 14 57 14" src="https://user-images.githubusercontent.com/86715389/190633730-497b18d4-8cca-473f-9989-78d7a2b746e3.png">

So when I try to use  button element it is working without bootstrap style but when ı try to import these lines (
`import "bootstrap/dist/css/bootstrap.css"
import "bootstrap/dist/js/bootstrap.js"`
) it gives first it shows the boostrap style but after page render  there is an error :

<img width="429" alt="Screen Shot 2022-09-16 at 15 00 24" src="https://user-images.githubusercontent.com/86715389/190634216-16b751be-2ee7-4953-b07e-5febbaca367b.png">

my vite.config.ts file here : (I updated my vite.config file but before than that I also get that error)
 
<img width="653" alt="Screen Shot 2022-09-16 at 15 11 59" src="https://user-images.githubusercontent.com/86715389/190636182-ae59d8ba-e640-42e5-aec1-429416658dc1.png">

I also add SSRprovider from react-boostrap
<img width="508" alt="Screen Shot 2022-09-16 at 15 13 19" src="https://user-images.githubusercontent.com/86715389/190636342-fdff058c-a78c-40b9-bb54-f9ea1284207f.png">

**Comment by brillout** [comment]
Seems like a user land thing? See https://brillout.github.io/rules/.

But let me know if you believe it's a vps problem. Closing in the meantime.
