### ISSUE TITLE
Export declared before import

### ISSUE THREAD

**Issue by erictaylor** [brillout/vite-plugin-ssr#457]
### Description

I'm not sure I follow why parts of the codebase declare exports before the import is declared?
https://github.com/brillout/vite-plugin-ssr/commit/eeddad76668f9c91e57b3486634e6a192a234377#diff-cddddc59e34418334b6d62f212dcb8e77abf42ae3bcb062ee2899b535862ec88R1

This is causing problems when we go to build or test in Jest because the variable isn't yet declared at the time of export.

Was this intentional or a mistake?

We've downgraded before this commit (0.4.34 -> 0.4.33) and things work again as expected.

### Error Stack

```
SyntaxError: Export 'loadPageRoutes' is not defined. (2:9)

1 | export { route };
2 | export { loadPageRoutes };
   |               ^
3 | export { isErrorPageId };
4 | export { getErrorPageId } from './route/error-page';
```
```

**Comment by brillout** [comment]
> when we go to build

What tool exactly is choking on that change?

>  or test in Jest

That's surprising since vite-plugin-ssr's CI uses Jest. Maybe you are using an older version of Jest?

**Comment by brillout** [comment]
Note that many folks are already using `0.4.34` so it must be something specific to your stack.

**Comment by erictaylor** [comment]
Hey @brillout.

So this was occurring in Jest. The only thing that stands out to me in our setup that changed recently was maybe an upgrade to babel core. We are currently using babel transformations in our Jest configuration (which needs swapped at some point).

```
    "@babel/core": "^7.19.1",
    "@babel/plugin-transform-runtime": "^7.19.1",
    "@babel/plugin-transform-typescript": "^7.19.1",
    "@babel/preset-env": "^7.19.1",
```

relivant portion of Jest config:
```
{
      collectCoverageFrom: ['src/**/*.{js,jsx,ts,tsx}', '!src/**/*.d.ts'],
      extensionsToTreatAsEsm: ['.ts'],
      moduleNameMapper: {
        '^(\\.{1,2}/.*)\\.js$': '$1',
        '^@/(.*)$': '<rootDir>/src/$1',
      },
      resetMocks: true,
      roots: ['<rootDir>/src'],
      setupFiles: [],
      setupFilesAfterEnv: ['<rootDir>/config/jest/setupTests.cjs'],
      testEnvironment: '<rootDir>/jest.environment.cjs',
      testMatch: [
        '<rootDir>/src/**/__tests__/**/*.{js,jsx,ts,tsx}',
        '<rootDir>/src/**/*.test.{js,jsx,ts,tsx}',
      ],
      transform: {
        '^(?!.*\\.(js|jsx|mjs|cjs|ts|tsx|css|json)$)':
          '<rootDir>/config/jest/fileTransform.cjs',
        '^.+\\.(js|jsx|mjs|cjs|ts|tsx)$': '<rootDir>/node_modules/babel-jest',
        '^.+\\.css$': '<rootDir>/config/jest/cssTransform.cjs',
      },
      transformIgnorePatterns: [
        '/node_modules/(?!(vite-plugin-ssr|@brillout))(.*)',
        '^.+\\.module\\.(css|sass|scss)$',
      ],
      watchPlugins: [
        'jest-watch-typeahead/filename',
        'jest-watch-typeahead/testname',
      ],
    },
 ```
 
 I'll have to play with this some more during the later part of the week, but I did try removing our ignore on transforming this package and that didn't help either.
 
 I'll also dive into this packages Jest config and see what we can gather between setups.

**Comment by brillout** [comment]
The reason I'm asking is because it would allow me to create a failing test, so that this doesn't happen again.

But if it takes too much time for you to find the tool that chokes, then I'll just rearrange the export order and we 🤞 that this won't happen again.

> SyntaxError: Export 'loadPageRoutes' is not defined. (2:9)

Who is throwing that error?

**Comment by erictaylor** [comment]
Quickly upgraded again and ran Jest and grabbed you this example:

<img width="1617" alt="Screen Shot 2022-09-20 at 11 07 15 AM" src="https://user-images.githubusercontent.com/637924/191321069-c02fd234-c79f-4198-b44f-3683f57aaa8a.png">

**Comment by erictaylor** [comment]
I did also manually adjust the export order and verified the error went away (so long as the exports are declared _after_ the references are declared).

**Comment by brillout** [comment]
Do these modifications https://github.com/brillout/vite-plugin-ssr/commit/172fae9f9942b91decf03d76f3c80f51501c95f7 work? Let me know if yes then I'll release the fix.

**Comment by brillout** [comment]
I couldn't reproduce with Babel alone. Failed attempt to reproduce the error with Babel at https://github.com/brillout/vps-babel-bug.

**Comment by brillout** [comment]
> Do these modifications https://github.com/brillout/vite-plugin-ssr/commit/172fae9f9942b91decf03d76f3c80f51501c95f7 work?

The modifications are released, so just use the latest version and let me know if it still doesn't work.
