### ISSUE TITLE
vuefull example runtime error

### ISSUE THREAD

**Issue by hamedg68** [brillout/vite-plugin-ssr#460]
### Description

after fetching packages and run vuefull example at last commit (0.4.36), showing runtime error

### Error Stack

```shell
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'accept') at Counter.vue:2:56
```

**Comment by brillout** [comment]
That's unrelated to vps.

That's probably a problem somewhere between Vue and Vite. Does updating the dependencies solve the problem?

**Comment by hamedg68** [comment]
if I change vite version from ^3.0.9 to 3.0.9 the error can be removed but clientRouting has runtime error while it is true in _default.page.client.ts file 

Uncaught (in promise) Error: [vite-plugin-ssr@0.4.36][Wrong Usage] navigate() is only available when using Client Routing

**Comment by brillout** [comment]
I cannot reproduce (I updated all dependencies expect of `vite` which I pinned to `3.0.4`).

Can you publish a reproduction leading to `Uncaught (in promise) Error: [vite-plugin-ssr@0.4.36][Wrong Usage] navigate() is only available when using Client Routing`?

**Comment by brillout** [comment]
As for the Vite-Vue bug, I can indeed reproduce it. The best would be the create a reproduction starting from `npm init vite-plugin-ssr@latest` and create a new GitHub ticket over at Vite.

**Comment by hamedg68** [comment]
This is repro in Stackblitz and GitHub:

https://stackblitz.com/github/hamedg68/vps-V0.4.36?file=pages/index/index.page.vue

1 - the counter button does not work with this runtime error : 
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'accept') at Counter.vue:2:56

 2 - change vite version from ^3.0.4 to 3.0.4 
counter button works but client routing gives this error :
Uncaught (in promise) Error: [vite-plugin-ssr@0.4.36][Wrong Usage] navigate() is only available when using Client Routing

**Comment by brillout** [comment]
I could reproduce both errors.

For the first error, it's a Vite bug, so we should create a Vite ticket for that.

As for the second error, it's fixable on vite-plugin-ssr's side. It's not a completely trivial fix (Vite's latest version breaks an assumption that vite-plugin-ssr repeatedly relies on). ETA later today / tomorrow.

**Comment by hamedg68** [comment]
for those who want use latest vps version without any error set vite version to 3.1.0-beta.1

**Comment by brillout** [comment]
Alright, the second error is fixed in `0.4.38`. We should create a minimal reproduction showcasing the first error (using `0.4.38`) and create a new GitHub ticket at Vite's repository. @hamedg68 Up for the task? 🙏

> without any error set vite version to 3.1.0-beta.1

👍 Thanks, good to know.

**Comment by milanio** [comment]
I believe the first problem is linked to the same problem as #461 . 
Error `Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'accept') at Counter.vue:2:56` disappears when you set `"target": "ES2020"` in tsconfig.json.  
The error is actually coming from calling `import.meta.hot.accept()`

**Comment by brillout** [comment]
I actually did try setting `vite.config.js#esbuild.target` to `esnext` and it didn't work.

Thanks @milanio.

**Comment by brillout** [comment]
> @hamedg68 Up for the task? 🙏

[Done](https://github.com/vitejs/vite/issues/10167#issuecomment-1255397483).

**Comment by hamedg68** [comment]
https://stackblitz.com/github/hamedg68/vps-V0.4.38?file=pages%2Findex%2Findex.page.vue

now everything is ok , both errors has gone

**Comment by brillout** [comment]
> https://stackblitz.com/github/hamedg68/vps-V0.4.38

That's expected until Vite fixes the bug.
