### ISSUE TITLE
Server Build Output Has Insane Path for Rollup External Modules

### ISSUE THREAD

**Issue by AaronBeaudoin** [brillout/vite-plugin-ssr#462]
### Description

See minimal reproduction here:
https://github.com/AaronBeaudoin/vps-bug-rollup-external

It seems that when marking a URL in Vite as "external" using `build.rollupOptions.external`, VPS outputs an insane path like `../../../../../../../../../<original>`.

## How I Ran Into This

My project will be deployed to Cloudflare Workers. In production, the worker will have "functions" bundled that handle certain routes. In development, I make these functions work by forwarding requests over to `wrangler` using a custom Vite middleware plugin and then falling back to the regular behavior if there was no function.

Problem is, these function might not just return data, that is to say, they might not only be called with `fetch("/some/function")`. They might also be called with `<img src="/some/function">`, because they can return anything, such as images. But in the latter case Vite immediately complains because it can't find the module. Of course, this is expected since the functions are being handled by `wrangler` completely outside of Vite. So it makes sense to just mark the function paths as external so that Vite will just build them "as-is".

It is when I tried this that I ran into the issue above. I was hoping that I could just dynamically add all my "function router" regexes into `build.rollupOptions.external` and voilà! Unfortunately, no.

**Comment by AaronBeaudoin** [comment]
So the temporary workaround I found for this is to simply make the `src="..."` attribute on the `<img>` tag dynamic in Vue like `<img :src"'/test'">` (see Vue [Attribute Bindings](https://vuejs.org/guide/essentials/template-syntax.html#attribute-bindings)). So in this case essentially I'm passing a static JS string literal to the `src` attribute which is effectively the same as just adding a regular attribute, except for the fact that Vite/Rollup doesn't try to see whether the URL actually exists in the project because it simply can't.

This solution kind of sucks because it is adding a bit of overhead in the code, and it also just looks ugly.

**Comment by brillout** [comment]
Yes it’s a Vue SFC thing, not really a vps thing.

**Comment by AaronBeaudoin** [comment]
Just tried reproducing with vanilla Vite SSR, and you're right. Here we go again with waiting for a Vue issue. 😖
