### ISSUE TITLE
How to get Redux working? (getting: could not find react-redux context value)

### ISSUE THREAD

**Issue by chesterlaykin** [brillout/vite-plugin-ssr#470]
### Question / Discussion

I've installed VPS with the react-ts option, then I copied over the [redux example files](https://github.com/brillout/vite-plugin-ssr/tree/main/examples/redux/) .
WHen I run it , I get  "`could not find react-redux context value; please ensure the component is wrapped in a <Provider>`".
The "CreateStore" method is also deprecated.
I have the test project [here](https://stackblitz.com/edit/vps-react-ts-redux-tests?file=src%2Fpages%2Findex%2Findex.page.tsx).

But I would like to use the modern setup with redux toolkit, I looked at the [docs](https://react-redux.js.org/using-react-redux/usage-with-typescript) and this [example](https://www.youtube.com/watch?v=9zySeP5vH9c) [+ repo](https://github.com/learnwithjason/lets-learn-redux-toolkit). 
So that's what I tried first, but the same error message showed up there. Here is an [example](https://stackblitz.com/edit/github-xnykab?file=src%2Fredux%2Fstore.ts,src%2Fpages%2Fredux%2Findex.page.tsx,src%2Fpages%2Findex%2Findex.page.tsx) of that.

I don't think I need Redux on the server side, but I still get the same error if I don't add any Redux stuff to `_default.page.server`.

I tried this with Next.js and works there (no SSR implementation, just wrapping the app in a Provider), [(example)](https://stackblitz.com/edit/nextjs-rv3smt?file=README.md,redux%2Fstore.ts,pages%2F_app.tsx).

**Comment by chesterlaykin** [comment]
I'm also a little confused about routing, where in Next/Nuxt, they have some kind of browser routing without loading a new page on each route, but in VPS it seems that the whole page is loaded when you click a link. 
So if you use VPS with SSR, and you want to use some global state, maybe it has to be implemented in the SSR way(?) (unlike Next/Nuxt) 

Another issue is that I wonder how to be able to export the types created in store.ts for "AppDispatch" and "RootState", because if you wrap the "configureStore" in a function [in a way suggested in this article](https://www.quintessential.gr/blog/development/how-to-integrate-redux-with-next-js-and-ssr)  it doesn't work, or requires some solution..

**Comment by brillout** [comment]
https://brillout.github.io/rules/
