### ISSUE TITLE
Cannot find module 'vite-plugin-ssr/client'

### ISSUE THREAD

**Issue by gspetrou** [brillout/vite-plugin-ssr#476]
### Description

Hi, using `^0.4.41` with Typescript and ESM. I get the following error:

```
Cannot find module 'vite-plugin-ssr/client' or its corresponding type declarations.ts(2307)
```

When attempting to import `PageContextBuiltInClient` from the `types.ts` file provided by the React scaffolding template. Looking in node_modules it seems the client folder does exist but I cannot find the `PageContextBuiltInClient` type, and the folder itself cannot be imported. I believe this is a bug since this issue came with the template.

(I have ensured I did an `npm install`)

### Error Stack

```shell
Cannot find module 'vite-plugin-ssr/client' or its corresponding type declarations.ts(2307)
```

**Comment by brillout** [comment]
I can't reproduce.

What are you reproduction steps?

**Comment by brillout** [comment]
Let me know if you still get this error and I'll re-open.

**Comment by xuanhung1509** [comment]
Recently, I've transfered from a existing Vite SPA app to use vite-plugin-ssr. I encoutered the error, not exactly the same but related to `vite-plugin-ssr/client`.

I made a repo to reproduce the error: [here](https://github.com/xuanhung1509/vite-plugin-ssr-import-error)

The problem happens in the commit `1dea55a3f2a97d7b615642e063059ab3210f3143` when I add `eslint-import-resolver-alias` and the corresponding config to ESLint to handle absolute imports. I've use this library for absolute import for quite a while and haven't face any problems like this so far.

I hope you'll take a look. Thanks.

**Comment by brillout** [comment]
@xuanhung1509 I can't reproduce. What are your reproduction steps? What OS?

**Comment by xuanhung1509** [comment]
Sorry for missing information. Here's the steps to reproduce the errors:
- Clone the repository
- Install dependencies: `yarn install`
- Open `types.ts` (located in `src/renderer`)
- ESLint should warn you about the first line (Resolve error: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './client' is not defined by "exports" in `vite-plugin-ssr-import-error/node_modules/vite-plugin-ssr/package.json`)

I'm on Linux Mint 21. Node version 14/16.

**Comment by brillout** [comment]
@xuanhung1509 Seems like your reproduction is assuming an IDE. This may be an issue with your IDE. Is this reproducable without your IDE but by running eslint's CLI instead?

**Comment by xuanhung1509** [comment]
@brillout Yes, it's reproducible by running eslint from CLI. I've add a `lint` script in package.json and run `yarn lint`:
```bash
Oops! Something went wrong! :(

ESLint: 8.34.0

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './client' is not defined by "exports" in /home/xuanhung/Code/vite-plugin-ssr-import-error/node_modules/vite-plugin-ssr/package.json
    at new NodeError (internal/errors.js:322:7)
    at throwExportsNotFound (internal/modules/esm/resolve.js:332:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:523:7)
    at resolveExports (internal/modules/cjs/loader.js:450:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:490:31)
    at findModulePath (/home/xuanhung/Code/vite-plugin-ssr-import-error/node_modules/eslint-import-resolver-alias/index.js:99:27)
    at Object.exports.resolve (/home/xuanhung/Code/vite-plugin-ssr-import-error/node_modules/eslint-import-resolver-alias/index.js:75:10)
    at v2 (/home/xuanhung/Code/vite-plugin-ssr-import-error/node_modules/eslint-module-utils/resolve.js:116:23)
    at withResolver (/home/xuanhung/Code/vite-plugin-ssr-import-error/node_modules/eslint-module-utils/resolve.js:121:14)
    at fullResolve (/home/xuanhung/Code/vite-plugin-ssr-import-error/node_modules/eslint-module-utils/resolve.js:138:22)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by brillout** [comment]
> Package subpath './client' is not defined by "exports" in /home/xuanhung/Code/vite-plugin-ssr-import-error/node_modules/vite-plugin-ssr/package.json

That's not true though: if you look at the `package.json` you'll see that `./client` is very much defined. It only defines `browser` though, but that's expected, and I'd expect ESLint to be okay with that.

So it seems like a ESLint issue?

**Comment by xuanhung1509** [comment]
I acknowledged the fact that the subpath is defined in `package.json`. But as you state, maybe it's ESLint problem (the `eslint-import-resolver-alias` extension, specifically). For now, I'll go with relative imports. Thanks for your support, @brillout!

**Comment by brillout** [comment]
I think someone should open an issue over at `eslint-import-resolver-alias`. It really seems like a ESLint problem.
