### ISSUE TITLE
`npm init vite-plugin-ssr@latest` logs "fatal" git errors. 

### ISSUE THREAD

**Issue by wilcoxmd** [brillout/vite-plugin-ssr#478]
### Description

When scaffolding a new `vite-plugin-ssr` project with `npm init vite-plugin-ssr@latest`, the following git errors are logged in the command's output: 

```bash
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
error: No such remote 'origin'
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

This doesn't seem to cause any actual issue with git initialization or the first commit.  Rather, this seems to be a normal git behavior when committing for the first time in a fresh repository. The error logs on the first commit but then won't log again on subsequent commits. 

However, this behavior is a little noisy in the scaffolding logs, and made me initially wonder if something went wrong with the operation.

As a solution, we could simply prevent the log from making it to the user by passing `{ stdio: 'ignore' }` in the git-related `execSync` options. As far as I can tell, create-react-app [uses](https://github.com/facebook/create-react-app/blob/d960b9e38c062584ff6cfb1a70e1512509a966e7/packages/react-scripts/scripts/init.js#L59-L82) the same approach to prevent these errors from making it to users. 

I'm not sure of another option offhand; there might be something better. If ignoring the output here sounds like an OK path forward to you as well though, I'd be happy to submit a PR with that change. 

### Error Stack

Included in description

**Comment by brillout** [comment]
I don't think this is related to vps.

**Comment by wilcoxmd** [comment]
This error is created when the boilerplate creation script [creates an initial commit](https://github.com/brillout/vite-plugin-ssr/blob/fafed66a1833ec9cb8d7fbb63183b20e7521c5c3/boilerplates/index.js#L185-L195).

This error happens if you're doing bare git operations as well, but other similar tools (create-react-app) just hide the error log for a nicer scaffolding UX.

**Comment by brillout** [comment]
Ok I see. Yes, PR welcome! Good idea.

**Comment by wilcoxmd** [comment]
Great, I'll put something together!

**Comment by brillout** [comment]
Looking forward to it! Apologies for the hasty closing reaction - it was getting late :-).

**Comment by brillout** [comment]
Done.
