### ISSUE TITLE
disableAutoFullBuild option does not get applied properly from version 0.4.41

### ISSUE THREAD

**Issue by vedranmviu** [brillout/vite-plugin-ssr#482]
### Description

We have an issue with plugin versions [0.4.41](https://github.com/brillout/vite-plugin-ssr/compare/v0.4.40...v0.4.41) and up.
We're using Vite's `build()` API.

### Expected Behavior
In version 0.4.40 when we pass the option `disableAutoFullBuild: true` to the `vite-plugin-ssr` we get the expected behavior. In the dist folder, we have only the client folder because only the client build ran.
**Settings 1**
```javascript
plugins: [
  ssr({
    disableAutoFullBuild: true
  }),
],
```
**Screenshot 1**
<img width="393" alt="Screenshot 2022-10-21 at 10 20 05" src="https://user-images.githubusercontent.com/91721470/197148488-267bfe86-af1b-4222-bdcc-22ef8ee6e93e.png">
If we use the `disableAutoFullBuild: true` in version 0.4.40 we get both client and server folders.

**Settings 2**
```javascript
plugins: [
  ssr({
    disableAutoFullBuild: false
  }),
],
```
**Screenshot 2**
<img width="386" alt="Screenshot 2022-10-21 at 10 22 38" src="https://user-images.githubusercontent.com/91721470/197148990-7dece8c6-eb34-4e65-9c9e-ec2328ab0341.png">

### Wrong behavior
In versions 0.4.41 and above, the `disableAutoFullBuild` option behaves the same way, regardless if the option's value is true or false. 
We get only client build in both cases - like in Screenshot 1.

**Comment by brillout** [comment]
Yes, see `CHANGELOG.md`. Just run `build()` twice.

Let me know if you have any other questions/issues.

**Comment by brillout** [comment]
Actually, I think the current behavior is exactly what should be happening. Running `build()` twice is cleaner.

Btw. in case your company is up for it: https://github.com/sponsors/brillout &mdash; to make vite-plugin-ssr even better :-).
