### ISSUE TITLE
Static HTML is not generated on `vite build` when using `prerender: true`

### ISSUE THREAD

**Issue by ZephyrBlu** [brillout/vite-plugin-ssr#484]
### Description

When running `vite build` static HTML files aren't generated in `dist/client/`. Only when I run `vite build && vite preview` are the HTML files generated.

My intended use case for this is for a full build with static HTML files to be generated on deploy to Cloudflare Pages, which means using `vite build && vite preview` to generate the files is probably not going to work in that environment since preview it starts a server.

<img width="657" alt="vps build problem" src="https://user-images.githubusercontent.com/45195130/197372749-6666c50a-66a8-4634-944a-b97bfd106c5e.png">

---

One thing I noticed is that the plugin doesn't even appear to be running when I run `vite build`.

I tried running `vite build --ssr` and looked through the Vite docs to see if I could figure out why this was happening but I couldn't find anything.

My VPS config is `ssr({ prerender: true })` and I could replicate this on the `react-full` example.

---

I'm not sure whether this a problem with Vite, VPS or my config.

**Comment by brillout** [comment]
I need a minimal reproduction starting from ‘npm init ***@***.***
’.

**Comment by ZephyrBlu** [comment]
This is a fresh repo that I can reproduce this on: https://github.com/ZephyrBlu/vps-ssg-issue

Running `vite build` does not generate HTML files in `dist/client/`.

<img width="652" alt="vps repro" src="https://user-images.githubusercontent.com/45195130/197379513-42fbc2f8-a084-455d-bf49-3bb9ba428930.png">

---

I ran the following commands and selected `react-ts` for project scaffolding:

```
npm init vite-plugin-ssr@latest
npm install
```

Then I added `prerender: true` to the plugin function call in my `vite.config.ts`.

**Comment by brillout** [comment]
I think it's related to your machine. Insert `console.log(execPath);` between the line 9 and 10 of `node_modules/vite-plugin-ssr/dist/cjs/node/plugin/helpers/isViteCliCall.js` and let me know the result.

**Comment by ZephyrBlu** [comment]
The output is `/usr/local/bin/vite` and I'm using yarn. When I run `yarn vite build` it works as expected.

Running `yarn bin` gives me `/usr/local/bin/node_modules/.bin`.

It seems like the difference is that running `yarn vite build` uses the local Vite, whereas running `vite build` uses the global Vite. I'm not familiar enough to know for sure what's going on though.

Is there a particular reason you don't support global CLI calls?

Also, do you know why my setup might be like this? I didn't do anything weird with installing Vite, just followed the instructions in their Getting Started guide.

**Comment by brillout** [comment]
Should be fixed.

In general, you should be using a local installation instead of a global one.

**Comment by ZephyrBlu** [comment]
Thank you 😄. I understand that using a local installation is generally preferable to a global one, so thanks for adding global support ❤️.
