### ISSUE TITLE
Regarding passing component initial state from server to client side

### ISSUE THREAD

**Issue by debasispanigrahi** [brillout/vite-plugin-ssr#489]
### Description

1. Is there any way to pass server side data to client side for components. it is possible for pinia using initial state.  i have used serverPrefetch for changing local state of component but hydration mismatch occurs. Pinia is good for small number of components but for multiple number of components local state matching required. please guide how to implement this feature. Attached screen shot for reference. Same for composition api

![Capture](https://user-images.githubusercontent.com/68457648/198821116-58471abe-ab65-45bb-9f4a-71c5e5150f87.PNG)

2. How to configure it for nodejs 18 version

**Comment by brillout** [comment]
I believe it's a user land thing and I believe it should be fixable on your side.

PR much welcome to add another example to https://vite-plugin-ssr.com/pinia#example (it's common to spend a lot of time with setting up Pinia and further examples would tremendously help).

Closing but let me know if you believe there is a blocking problem on VPS's side.
