### ISSUE TITLE
use web native URL object instead of custom API?

### ISSUE THREAD

**Issue by samuelstroschein** [brillout/vite-plugin-ssr#492]
### Question / Discussion

Would it make sense to consolidate the 4 custom URL properties in page context with the native [URL](https://developer.mozilla.org/en-US/docs/Web/API/URL) object to improve DX, API interop, (and maintainability)?

## Description

PageContext has 4 URL props: 
- url (deprecated #491)
- urlOriginal 
- urlParsed
- urlPathname

The native URL object makes seems to contain all information that those 4 props reflect contain. The API could therefore be consolidated to only contain the native URL object. `urlOriginal` can be replicated with [url.toString](https://developer.mozilla.org/en-US/docs/Web/API/URL/toString). 

## Benefits

- improved DX (just one url prop + native url prop)
- API interop (because native web URL object)
- better maintainability (because less API surface)

**Comment by brillout** [comment]
That was originally my plan. But it didn't work out. The custom URL parser has many subtle but important differences with `new URL`.

I agree the current DX is not ideal, but the plan is to eventually rename `pageContext.urlParsed` to `pageContext.url`. I think the DX will be good then. E.g. I think `pageContext.url.pathname` is a nice DX. Feel free to disagree.

**Comment by samuelstroschein** [comment]
Are the subtle differences related to the input, output, or both? 

Regarding `pageContext.url.pathname`, would be identical to the native URL object. hence, the DX would be good indeed.

**Comment by brillout** [comment]
Both. There is a thorough (i.e. complete) example at https://vite-plugin-ssr.com/pageContext if you want to know more about the differences.

I'm up to further aligning the object schema `pageContext.urlParsed` with `new URL`, but I believe it's already quite similar. (E.g. IIRC `new URL` as well defines `search`.)
