### ISSUE TITLE
Setting Headers for pages

### ISSUE THREAD

**Issue by Baroshem** [brillout/vite-plugin-ssr#493]
### Question / Discussion

Hi!

First of all, huge kudos for this plugin. I am currently building an app with it and I am really happy about the result. 

I wanted to implement certain headers to pages (i.e. Cache-Control) and I was wondering what is the recommended approach here? (I couln't find the answer in the docs or in the issues :( )

I am not using any server middleware. Just basic project with few pages created accordingly to the docs (no framework as well, just TS).

**Comment by brillout** [comment]
I'd go for ETag if you use SSR since the HTML is dynamic.
