### ISSUE TITLE
[Bug] VPS chokes when URL is `///en/?redirect_zone=ru'`

### ISSUE THREAD

**Issue by DaniilIsupov** [brillout/vite-plugin-ssr#495]
### Description

Error: [vite-plugin-ssr@0.4.43][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Reach out at https://github.com/brillout/vite-plugin-ssr/issues/new or https://discord.com/invite/qTq92FQzKb and include this error stack (the error stack is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Do not hesitate to reach out as it makes vite-plugin-ssr more robust.

### Error Stack

```shell
at assertUrlPathname (/var/web/info/releases/2.1.1/node_modules/vite-plugin-ssr/dist/cjs/utils/parseUrl.js:130:25)
at analyzeBaseUrl (/var/web/info/releases/2.1.1/node_modules/vite-plugin-ssr/dist/cjs/utils/parseUrl.js:134:5)
```

**Comment by brillout** [comment]
I need the entire stack trace.

**Comment by DaniilIsupov** [comment]
> 


```

**Comment by brillout** [comment]
Inject `console.log(url, baseUrl, pathnameResolved)` right before the line `node_modules/vite-plugin-ssr/dist/cjs/utils/parseUrl.js#48` and let me know the result.

**Comment by DaniilIsupov** [comment]
> 

```

**Comment by DaniilIsupov** [comment]
> Inject `console.log(url, baseUrl, pathnameResolved)` right before the line `node_modules/vite-plugin-ssr/dist/cjs/utils/parseUrl.js#48` and let me know the result.

path is very strange in fairness
```
{
  url: '///en/?redirect_zone=ru',
  baseUrl: '/',
  pathnameResolved: '///en/?redirect_zone=ru'
}
```

**Comment by DaniilIsupov** [comment]
> 

perhaps we have some kind of bug with a redirect to similar url.
perhaps some of the users purposefully entered such an address.

error fell in production, and I just reproduced it based on logs from server

**Comment by brillout** [comment]
Let me know if it's urgent, I'll then release sooner rather than later.

Also, in case your company is interested: https://github.com/sponsors/brillout. Enabling me to make VPS even better :-).
