### ISSUE TITLE
Error: [vite-plugin-ssr@0.4.43][Wrong Usage][`navigate(url)`] Something is wrong with your environment (it loads the wrong `vite-plugin-ssr/client/router` entry). This may be happening if you use Jest or Babel. Open a new GitHub issue to discuss a solution.

### ISSUE THREAD

**Issue by robinelvin** [brillout/vite-plugin-ssr#496]
### Question / Discussion

After adding `import { navigate } from 'vite-plugin-ssr/client/router'` to one of my components I now get the following error when trying to test it:

```
Error: [vite-plugin-ssr@0.4.43][Wrong Usage][`navigate(url)`] Something is wrong with your environment (it loads the wrong `vite-plugin-ssr/client/router` entry). This may be happening if you use Jest or Babel. Open a new GitHub issue to discuss a solution.
```

I am using [React Testing Library](https://testing-library.com/docs/react-testing-library/intro) to render and test my component. I am *not* using Jest or Babel.

**Comment by brillout** [comment]
Do you get this error in the browser or in the terminal?

**Comment by robinelvin** [comment]
This is the error in the terminal from my test run.

**Comment by brillout** [comment]
I'd suggest to play around with `node_modules/vite-plugin-ssr/package.json#exports["./client/router"]` and report back if you find another export schema that works.

The underlying question here is: why do your tests load the wrong `package.json#exports` entry?

Alternatively, create a reproduction and I'll have a look at it myself.

**Comment by robinelvin** [comment]
From my investigations it looks like it's: https://github.com/brillout/vite-plugin-ssr/blob/8f8cab47c2a229ab6161e8bb01d3fda447602ceb/vite-plugin-ssr/node/client/router.ts#L6

In tests this is being evaluated when the function is imported which is before the jsdom window object has been created. If I remove this assertion my tests then run as expected. I'm not sure what the solution is - perhaps detect if in a test environment?

**Comment by brillout** [comment]
Let me know if you need the fix to be released sooner rather than later.

Also, in case your employer has the financial capabilities: https://github.com/sponsors/brillout. Sponsors make a huge difference and allow me to further work on VPS.
