### ISSUE TITLE
I would like to find an example of vite-plugin-ssr with redux toolkit

### ISSUE THREAD

**Issue by fernandoamz** [brillout/vite-plugin-ssr#497]
### Question / Discussion

Hi guys, I hope your are doing great, I am using your awesome plugin, but I have a blocker I can not find clear information about how to implement it with redux toolkit I am getting weird errors. 

I searched here I didn't find anything regarding it.

https://github.com/brillout/vite-plugin-ssr/tree/main/boilerplates
https://github.com/brillout/vite-plugin-ssr/tree/main/examples
https://github.com/vitejs/awesome-vite

I found a lot of integrations with vitejs, but anything for the vite-ssr-plugin. 

thanks so much && regard I really appreciate your time

**Comment by brillout** [comment]
See `examples/` or the docs. Also https://brillout.github.io/rules, thanks.

**Comment by fernandoamz** [comment]
Hi @brillout, as I commented, I searched your documentation and saw the folder you mentioned; there isn't anything on the examples regarding RKT. but well, thanks for your support

**Comment by brillout** [comment]
PR welcome to improve the example/docs :-)
