### ISSUE TITLE
onBeforeRender() + pinia

### ISSUE THREAD

**Issue by hamedg68** [brillout/vite-plugin-ssr#499]
### Description

**onBeforeRender()** does not work with pinia, actually I want to use **onBerforeRender()** for both server and client side in **.page.ts** file, I got the following error while pinia is initialized.
there is a way which solve the problem, using **onServerPrefetch()** and **onMounted()** hook  according to pinia example, but I want to use **onBeforeRender()**

### Error Stack

```shell
Error: [🍍]: getActivePinia was called with no active Pinia. Did you forget to install pinia?
```

**Comment by brillout** [comment]
Please respect https://brillout.github.io/rules/.

**Comment by apappas1129** [comment]
I am confused with the difference between `onBeforeRender` and Vue's `onServerPrefetch`. Can someone help me with when I should use which? I am using Client Routing, `enableEagerStreaming`, and `pinia`.
