### ISSUE TITLE
navigate() wrong declaration file

### ISSUE THREAD

**Issue by samuelstroschein** [brillout/vite-plugin-ssr#501]
### Description

The declaration file of `navigate()` is incorrect. TypeScript lints that navigate expects 0 arguments.

<img width="562" alt="image" src="https://user-images.githubusercontent.com/35429197/200172152-516ab6c4-d36f-44fa-a4ab-a1d4cf8fe8a5.png">

The declaration file in dist reveals why. Navigate is exported but has no arguments. 

```ts
// dist/cjs/node/client/router.d.ts
export { navigate };
declare function navigate(): void;
```

The implementation takes multiple arguments. 

```ts
// vite-plugin-ssr/client/router/useClientRouter.ts
async function navigate(
  url: string,
  { keepScrollPosition = false, overwriteLastHistoryEntry = false } = {}
): Promise<void>
```

I was not able to figure out why typescript creates a wrong declaration file for `navigate`, and potentially other declarations too.

### Error Stack

```shell
version 0.44.4
```

**Comment by brillout** [comment]
I can't reproduce with `/examples/react-full/pages/index.page.tsx`. What TypeScript version are you using?

**Comment by samuelstroschein** [comment]
TypeScript 4.8.3 is used in the project. I found the root cause(s).

1. `node16` as module resolution resolves the declaration file [dist/cjs/node/client/router.d.ts](https://cdn.jsdelivr.net/npm/vite-plugin-ssr@0.4.44/dist/cjs/node/client/router.d.ts) which contains wrong types.   

```js
{
  "compilerOptions": {
    "target": "esnext",
    // module resolution node16 resolves a different declaration file
    "moduleResolution": "node16"
  }
}

```

#504 fixes the type imports for client/router

2. Why dist/cjs/node/client/router.d.ts contains wrong declarations is unknown
