### ISSUE TITLE
Example of Next.js or Nuxt clone

### ISSUE THREAD

**Issue by brillout** [brillout/vite-plugin-ssr#508]
### Question / Discussion

From @shishkin:

> I like this plugin's claim "_Hundreds of lines of code are enough to build your own Next.js / Nuxt_". I think to truly fulfill it there needs to be an example of an actual Next.js or Nuxt clone. And having a single-page experience is part of that.

**Comment by brillout** [comment]
@shishkin I agree, although I think the clone can and should be different/better.

(Closing because it isn't really an issue, but further discussion welcome.)

**Comment by shishkin** [comment]
Would it make sense to use GitHub's Discussions for this project to avoid creating issues like this?

**Comment by brillout** [comment]
Maybe. I'll think about it.
