### ISSUE TITLE
Async Loader pattern from Remix

### ISSUE THREAD

**Issue by karibertils** [brillout/vite-plugin-ssr#515]
### Description

Would it be possible for vite-plugin-ssr to support similar pattern as the async loader in Remix ?

I know I could use the onBeforeRender, but the best way to handle types is not really clear here.

The async loader pattern just feels more cleaner way of doing this, and works really well with typescript.

**Comment by brillout** [comment]
It's on the radar to improve TypeScript support.

Depending on your UI framework, you can recreate Remix's async loaders in user-land. E.g. there are prototypes of doing that with [react-streaming](https://github.com/brillout/react-streaming) and [Telefunc](https://telefunc.com/) (with even better TypeScript support than Remix).

Also note that RSC is going to have async components.

**Comment by karibertils** [comment]
Ok, I am looking forward to seeing greater adoption of RSC. But I found they have some drawbacks as well, like Ryan outlines at https://remix.run/blog/react-server-components

I'm interested in checking out how doing this in userland looks like. Can you point me to a prototype ?

**Comment by brillout** [comment]
> Can you point me to a prototype ?

https://github.com/brillout/telefunc/blob/98dcc43c861558d09ab7f5715a9d93edcf3467a3/examples/vite-plugin-ssr/pages/index/TodoList.tsx#L8

For React users I foresee RSC's server components to eventually become the norm.

**Comment by brillout** [comment]
Closing since it's not a specific feature request but more a discussion.

Feel free to continue the discussion.
