### ISSUE TITLE
Access to all route data in PageContext

### ISSUE THREAD

**Issue by reedspool** [brillout/vite-plugin-ssr#521]
### Description

Hello, I am making a page which links to all my MDX pages in my blog directory. I found that I can get all of this information via `pageContext._pageFilesAll`, but obviously this is not a public/stable API due to the leading underscore. 

Specifically I'm doing this `pageContext._pageFilesAll.filter((f) => f.pageId.match(/^\/pages\/blog/))` And that gets me all the information I need to do what I want, but I wish I could do this in an official way, without a plugin.

Can this or similar access be made official? Or is there already an official way to do this? 

Thank you!

**Comment by reedspool** [comment]
I refined my request - I'd like to access all pageExports. For example, on my blog, I want to create links that include the `title` exported from each page.

I found that _pageFilesAll only includes the fileExports in `vite build` and not in dev mode `vite`, so this doesn't work for me.

**Comment by brillout** [comment]
I'd recommend using something like https://github.com/brillout/vite-plugin-ssr/blob/main/docs/headings.tsx instead. (Eagerly loading all pages is an anti-pattern given Vite's lazy transpiling appraoch.)

**Comment by reedspool** [comment]
I am prerendering my entire site, using the HTML-only approach, as it's a static blog. Thus preserving any lazy properties is not applicable to my use-case - it all gets done at once anyways.

Somehow all of this information becomes available in that `pageContext._pageFilesAll` when I use `$ vite build` but not `$ vite`. So this does seem to be possible, and something that can be switched on or off via configuration, right? Unless I'm mistaken which is highly probable.

Using a separate, manual configuration file is my very last resort. All of that information is already in the document exports of each blog file, so it would be a duplication on top of extra effort. This is a really common pattern in static site generators like Eleventy and it aligns naturally with the HTML-only approach with `vite-plugin-ssr`.

**Comment by brillout** [comment]
In dev, Vite doesn't load all your files which is what makes Vite faster than other tools such as Eleventy.

**Comment by reedspool** [comment]
I see that makes sense. Thanks for your time and consideration

**Comment by reedspool** [comment]
In case anyone comes asking about similar features again, I got myself rolling today with this code, which uses Vite's dynamic imports to read and import the MDX for every blog page on the fly. I understand this isn't a direction you want to go with the core plugin tho.

This file is `<vite-root>/pages/blog.page.server.jsx` and all blog pages are at `<vite-root>/pages/<urlName>.page.server.mdx`

```
import { readdir } from 'node:fs/promises';

// Read the real file names which include `.page.server.mdx`
// NOTE: PWD is the Vite root, so we need to dig
const postFiles = await readdir('./pages/blog');

// Load all of the pages' data at once
const pages = await Promise.all(
    postFiles.map(
        (fileName) => {
            console.log(fileName)
            const urlName = fileName.substring(0, fileName.indexOf('.page'));
            // Even though we have the full file name, vite:dynamic-import-vars
            // requires that the dynamic import contains a static suffix which
            // is fine since we need to get this for the url anyways
            const x = import(`./blog/${urlName}.page.server.mdx`)
            return new Promise((resolve) => {
                x.then(({ documentProps }) => {
                    resolve({
                        fileName,
                        urlName,
                        documentProps
                    })
                })
            })
        })
)

export const Page = () =>
    <ul>
        {pages.map(({ urlName, documentProps }) =>
            <li>
                <a href={`blog/${urlName}`}>{documentProps.title}</a>
            </li>)}
    </ul>
```

**Comment by reedspool** [comment]
Hello again @brillout, the above solution breaks on build, but not on dev. Here is the error:

```
[commonjs--resolver] [vite-plugin-ssr@0.4.48][Bug] You stumbled upon a bug in vite-plugin-ssr's source 
code. Reach out at https://github.com/brillout/vite-plugin-ssr/issues/new or https://discord.com/invite
/qTq92FQzKb and include this error stack (the error stack is usually enough to fix the problem). A main
tainer will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes vite-plugin-s
sr more robust. Debug info (this is for the vite-plugin-ssr maintainers; you can ignore this): `{"sourc
e":"./blog/20220923-my-fresh-website.page.server.mdx","importer":"<my-project-root-path>/app/site/pages
/getBlogPages.tsx?extractAssets&lang.tsx"}`.
error during build:
Error: [vite-plugin-ssr@0.4.48][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Reach ou
t at https://github.com/brillout/vite-plugin-ssr/issues/new or https://discord.com/invite/qTq92FQzKb an
d include this error stack (the error stack is usually enough to fix the problem). A maintainer will fi
x the bug (usually under 24 hours). Don't hesitate to reach out as it makes vite-plugin-ssr more robust
. Debug info (this is for the vite-plugin-ssr maintainers; you can ignore this): `{"source":"./blog/202
20923-my-fresh-website.page.server.mdx","importer":"<my-project-root-path>/app/site/pa
ges/getBlogPages.tsx?extractAssets&lang.tsx"}`.
    at Object.resolveId (<my-project-root-path>/app/site/node_modules/vite-plugin-ssr/
dist/cjs/node/plugin/plugins/extractAssetsPlugin.js:71:40)
    at file://<my-project-root-path>/app/site/node_modules/rollup/dist/es/shared/rollu
p.js:22748:40
```

I understand you won't support this but I wonder if you could help me understand the root of the error, so I could ideate ways around it.

The error seems to point to this line in `extractAssetsPlugin.ts`:

```
          // When building for the server, there should never be a `?extractAssets` query
```

If you could help me understand that statement, that would be a big help. Thank you!

**Comment by brillout** [comment]
I do support fixing internal bugs like these. I'll have a look at it.

**Comment by reedspool** [comment]
Thank you. Repro should be simple:

1. Clone https://github.com/reedspool/reeds-website
2. Check out commit (first commit) 87d5107f2eebfae6b4c24fc7a93350c7d193aea1
3. cd `app/site`
4. `npm install && npm run build`

**Comment by brillout** [comment]
Thanks for the repro. I'll have a look at it later today.

**Comment by brillout** [comment]
I could reproduce indeed. I'll resume tomorrow.

**Comment by brillout** [comment]
@reedspool Is the internal bug blocking you? It's not completely trivial to fix and I'd postpone it to the end of this week / beginning of next week.

**Comment by reedspool** [comment]
Not blocking - I just replaced all that business with explicit data for
now.

**Comment by brillout** [comment]
Fixed, which will be released today.
