### ISSUE TITLE
Detect whether the current component is running on server side rendering or client side,

### ISSUE THREAD

**Issue by msonowal** [brillout/vite-plugin-ssr#522]
### Question / Discussion

Detect whether the current component is running on server side rendering or client side,

As I suppose want to do say import some libraries etc only on client side not on server side rendering?

How to achieve that?

Basically conditioanly rendering some component in server side or client side like we have in nuxt <ClientOnly/> how to achieve that in vannila

**Comment by brillout** [comment]
https://vite-plugin-ssr.com/client-only-components
https://brillout.github.io/rules/
