### ISSUE TITLE
Favicon or other assets not bundled in production build

### ISSUE THREAD

**Issue by bradchristensen** [brillout/vite-plugin-ssr#523]
### Description

I noticed that in my project, the favicon was visible when running in dev mode, but it wasn't getting bundled into the production build. The URL was being generated correctly, including the file hash, as if it should point to the bundled asset, but the asset didn't exist on disk.

I tested with `npm init vite-plugin-ssr@latest` and the problem doesn't exist in that template out of the box, but I noticed that the favicon file was being imported twice - once on the client side and once on the server side. Importing it server-side is obviously where the URL is injected into the HTML page, whereas on the client-side it's just being displayed as an image. If I removed it from the client-side file (`PageShell.tsx`) and rebuilt, then as I suspected, the file didn't get bundled.

Therefore, there is obviously a workaround to import the file client-side to ensure that it gets bundled, so I have a path forward, but I thought you might want to be aware of the issue 😄

**Comment by brillout** [comment]
https://vite-plugin-ssr.com/includeAssetsImportedByServer

I may switch it to on by default in a minor release and see if it breaks someone's app 😀.

**Comment by bradchristensen** [comment]
Gosh, I can't believe I missed that page of the docs considering it reads almost word for word like the description I wrote above 🤣 Thanks for the heads up!

I don't know what nuance there is underneath that switch, but I certainly like the idea of switching it on by default - going by the principle of least surprise, it definitely seemed like a "bug" to me that my favicon worked correctly in dev mode but not in production mode. If it's intended as a performance optimisation, that would be the kind of thing I'd prefer to opt into after understanding the risks.

**Comment by brillout** [comment]
I agree, and the only reason for not making it the default is because the implementation may have unwanted side-effects. Let's see.

**Comment by brillout** [comment]
Btw. in case your company would be up for it: https://github.com/sponsors/brillout.

:-)
