### ISSUE TITLE
Dynamically set html lang attribute

### ISSUE THREAD

**Issue by vladeze** [brillout/vite-plugin-ssr#525]
### Question / Discussion

Is there a way to dynamically set html `lang` attribute?
For example depending on cookie value.
Maybe somehow passing cookies through **renderPage** in `server/index.js`.
And generaly server rendering pages depending on cookie

**Comment by brillout** [comment]
https://brillout.github.io/rules/

**Comment by vladeze** [comment]
Okay, I get it. I haven't provided any information about my own attempts, but that's because I don't even know where to start.
I wanted a push in some direction.
And in any case, it's not hard to just leave at least one sentence, like "Can't help", than to throw a link with the rules at me

**Comment by brillout** [comment]
https://github.com/brillout/vite-plugin-ssr/discussions/526
