### ISSUE TITLE
Failed to resolve dependencies while prerendering if Vite's `build.outDir` is in parent folder

### ISSUE THREAD

**Issue by MrFoxPro** [brillout/vite-plugin-ssr#535]
### Description

Unable to prerender pages if outDir is located not in current Node/NPM project.
I think solution might be to pass current `process.cwd()` or `__dirname` of vite.config.js to prerendering script.

```js
ssr({
   includeAssetsImportedByServer: true,
   prerender: {
      partial: true,
      noExtraDir: true
   }
}),
```
### Error Message + Error Stack
`build.outDir: '../dist/web'`  ->
```shell
vite-plugin-ssr v0.4.54 pre-rendering HTML...
Error: Cannot find package 'solid-js' imported from /home/foxpro/Desktop/bloki/dist/web/server/assets/ssr.page.d8c94661.js
Did you mean to import solid-js@1.6.2/node_modules/solid-js/web/dist/server.cjs?
```

`build.outDir: './dist'` -> build successful.

**Comment by brillout** [comment]
I think it's a Vite/Rollup bug. Have you tried without vite-plugin-ssr? Does it work then?

A possible workaround is to move the folder in a post-build script.

**Comment by brillout** [comment]
Closing. I'll reopen if we have evidence it's related to VPS.

**Comment by MrFoxPro** [comment]
> I think it's a Vite/Rollup bug. Have you tried without vite-plugin-ssr? Does it work then?
> 
> A possible workaround is to move the folder in a post-build script.
@brillout 
Yeah, it has been in my app and worked fine.  -_-
Check out repro: https://stackblitz.com/edit/solidjs-templates-bzpfte?file=project/vite.config.js
Uncomment VPS plugin and see an error

**Comment by stefanmaric** [comment]
I am facing the same issue with react. In my case I'm using `prerender`.

In the `client/` build the dependencies are bundled as expected (couldn't work any other way in the browser), but in the server they are not:

```javascript
// _build/server/assets/_default.page.server.544b0a7f.js

import { jsx, jsxs } from "react/jsx-runtime.js";
import ReactDOMServer from "react-dom/server.js";
import { escapeInject, dangerouslySkipEscape } from "vite-plugin-ssr";
import React, { createContext } from "react";
import { C as Container } from "./chunk-43b9a9d3.js";
const logo$1 = "/assets/logo-squared.bcc3c438.png";
const logo = "/assets/logo.b52434d9.svg";
const Header = "_Header_18e0h_1";
const HomepageLink = "_HomepageLink_18e0h_5";
const Logo = "_Logo_18e0h_12";
const styles = {
  Header,
  HomepageLink,
  Logo
};
const Context = createContext({});
const PageContextProvider = ({
  pageContext,
  children
}) => /* @__PURE__ */ jsx(Context.Provider, { value: pageContext, children });
// ...
```

It kinda makes sense that you can load dependencies from the node_modules if running in the server, but is it intended? :thinking:

**Comment by MrFoxPro** [comment]
It's expected that VPS should run prerendering (ssr) server from project folder, not output.

**Comment by brillout** [comment]
If your server code `dist/server/` cannot access your `node_modules/`, then there's nothing VPS can do here. It's a Node.js thing, not a VPS thing.

**Comment by MrFoxPro** [comment]
Couldn't VPS start SSR server for prerendering stage in child process with cwd of project?

**Comment by brillout** [comment]
That‘s not how Node.js works.
