### ISSUE TITLE
Convenient configuration

### ISSUE THREAD

**Issue by MrFoxPro** [brillout/vite-plugin-ssr#536]
Thanks for your hard work on this handy tool.

### Description

I want to make app with SSG/HTML-JS and SPA pages, so I don't need SSR output. But I can't configure exactly which steps I need.
My suggestion is to replace `disableAutoFullBuild` and `prerenderer.partial` with property like `mode`, which type is enum flag.
By default it will produce default SPA.
SSG of certain pages: 
```js
ssr({
   mode: RenderMode.SPA | RenderMode.SSG
}),
```
Prerender (SSG) all pages. Omit server directory (place it to `fs.mkdtemp` or `os.tmpdir` or even `node_modules/.vite/` while prerendering)
```js
ssr({
   mode: RenderMode.SSG
}),
```
Preserve SPA pages, prerender SSG pages, produce SSR build for SSR pages and corresponding server runtime.
```js
ssr({
   mode: RenderMode.SPA | RenderMode.SSG | RenderMode.SSR
}),
```
Manual build script
```js
ssr({
   mode: RenderMode.Manual
}),
```

For consistency, introduce setting for every case, something like:
```js
ssr({
   // mode: ...
   client: {
      defaultSSRPage?: String, // page with hydration script, default: `renderer/_default.page.client.tsx`,
      defaultSPAPage?: String, // page with render script, default: `renderer/_default.page.client.tsx`
      html?: 'vite' (vite HTML middleware) | String (path to html file) ,
      clientOutputDir: String, // default is `${outDir}/client`,
      filter?: ({ pageContext, filename, ... }) => pageContext.exports['SPA'] === true,
   },
   server: {
      defaultScript?: String, // needed for generating hydratable HTML, default: `renderer/_default.page.server.tsx`
      serverOutputDir?: String, // default is `${outDir}/server`
      filter: ({ pageContext, filename, ... }) => pageContext.exports['SSR'] === true
   },
   prerender: {
      defaultScript?: String, // needed for generating non-hydratable HTML, default: `renderer/_default.page.server.tsx`,
      noExtraDir: Boolean,
      filter?: ({ pageContext, filename, ... }) => pageContext.exports['SSG'] === true
   },
})
```

I believe this flexible approach will make it clear how to use this plugin without looking for examples and why it's better than alternative solutions.

**Comment by samuelstroschein** [comment]
I think this overlaps with https://github.com/brillout/vite-plugin-ssr/issues/53#issuecomment-1327915337

**Comment by MrFoxPro** [comment]
> I think this overlaps with [#53 (comment)](https://github.com/brillout/vite-plugin-ssr/issues/53#issuecomment-1327915337)

I see now, Yes. This could be better then defining all in configuration

**Comment by brillout** [comment]
I agree the DX of configuring render modes can be improved. It's on the radar.
