### ISSUE TITLE
Release first non-beta version

### ISSUE THREAD

**Issue by brillout** [brillout/vite-plugin-ssr#54]
We will release `0.1.0` soon.

**Comment by chrisvariety** [comment]
👍 Upgrade to v0.1.0-beta.45 went fine FYI (and upgrades in-between the betas), I think we're ready.

**Comment by brillout** [comment]
Yes, we are almost there :-).

There is one last breaking change #76, which I'll ship tentatively today. After a couple of days I'll release `0.1.0` :-).

I know breaking changes are annoying but it's worth it long term. Once we are out of beta you can expect an order of magnitude less breaking changes. I also aim for `1.0.0` soon, after I do some marketing for `vite-plugin-ssr`.

One long-term neat thing here is that, because `vite-plugin-ssr` is not tied to React/Vue/..., there will actually be *much* less breaking changes than Next.js and Nuxt.

**Comment by chrisvariety** [comment]
@brillout no problem updating to v0.1.0-beta.46 either, FYI.

For 1.0.0 I'd recommend a docs website vs. a reallllly long readme, which is great, don't get me wrong, just multiple pages would help organize.

**Comment by brillout** [comment]
Thanks for the info 👍 .

> I'd recommend a docs website vs. a reallllly long readme, which is great, don't get me wrong, just multiple pages would help organize.

How does it help organize?

I'm the author of the Readme so for me the structure of it is clear. I'd definitely appreciate help to get an idea of how the table of content works for someone who isn't me.

**Comment by chrisvariety** [comment]
@brillout sure, it's more of a UX thing. If you look at other similar projects, at a certain size they grow out of the Readme and onto a dedicated docs site. Personally, I find seeing that much content all at once overwhelming, like you don't really know where to begin, and once I click on something, I feel stuck in the middle (though just discovered Github has nice ways to reveal table of contents and scroll to top, not sure everyone knows about those.) See e.g.

https://vitejs.dev/guide/
https://mswjs.io/docs/
https://chakra-ui.com/docs/

All of these have a sidebar which contains the table of contents, allowing for easy navigation. Search is a huge plus too, but not 100% necessary for an MVP.

https://www.gitbook.com is an easy way to spin something like this up, but there are a lot of alternatives out there as well.

**Comment by brillout** [comment]
Makes sense, created a ticket for it #78.

**Comment by brillout** [comment]
Released `0.1.0`.
