### ISSUE TITLE
Closing script tags inside the generated html output contain whitespaces

### ISSUE THREAD

**Issue by Csszabi98** [brillout/vite-plugin-ssr#541]
### Description

In some cases the script tag containing the serialized page context gets a funky output.
This is a slimmed down version of my generated output:

```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- HEAD CONTENT -->
    </head>
    <body>
        <script id="vite-plugin-ssr_pageContext" type="application/json">
               {"pageContext": { /* ... */ } }
                </s
                cript>
            <script type="module" src="/assets/js/entry-server-routing.js" async>
                    </s
                    cript>
    </body>
</html>

```

Sometimes the browser still manages to parse this as an HTML file, but other times the browser will just 
render the contents of "head" inside the body, instead of the contents of "body".

**Comment by brillout** [comment]
I'd need a reproduction.

**Comment by brillout** [comment]
> I'd need a reproduction.

Doesn't have to be minimal.

**Comment by Csszabi98** [comment]
After some investigation, it turned out that I was copying the HTML template from the network preview tab, which shows the HTML this way. After looking at the actual source it turned out that the HTML file is correct indeed. The part about rendering "head" to "body" came down to another issue, which was unrelated.
