### ISSUE TITLE
Release 0.4.55 breaks Vite's default ENV variables 

### ISSUE THREAD

**Issue by bagr001** [brillout/vite-plugin-ssr#554]
### Description

Hi, I have noticed that release 0.4.55 breaks Vite's default ENV variables functionality so they are not accessible via `import.meta.env.VITE_SOME_VARAIBLE`.

I have done some investigation and found this:

[ This line ](https://github.com/brillout/vite-plugin-ssr/blame/05edfc37885e32b7a59ac4c80185d56f8a5f40a3/vite-plugin-ssr/node/plugin/plugins/baseUrls.ts#L23) overrides default Vite `envPrefix` setting which is by default `['VITE_']` and is causing this problem.

I am able to fix it by manually setting the `envPrefix: ['VITE_'],` in the `vite.config.ts` but IMO when using VPS it should keep working automatically. Do you agree @brillout?

Thanks!

**Comment by brillout** [comment]
Fix released in `0.4.58`.

Thanks for reporting this!
