### ISSUE TITLE
Add deno/no package.json support

### ISSUE THREAD

**Issue by Suyashtnt** [brillout/vite-plugin-ssr#579]
### Description

Vite and deno work near perfectly together, however, since this ssr plugin requires a package.json file to be present, it does not work. I would like this plugin to have the ability to run without a package.json present (why is a package.json needed?)

**Comment by brillout** [comment]
VPS doesn't strictly need the user to have a pacakge.json. (I'ts only needed for the automatic loading of Stem integrations which can be made optional.)

What's the error Deno throws? Reproduction much welcome.

**Comment by Suyashtnt** [comment]
> VPS doesn't strictly need the user to have a pacakge.json. (I'ts only needed for the automatic loading of Stem integrations which can be made optional.)
> 
> What's the error Deno throws? Reproduction much welcome.

The error is the SSR plugin simply saying that a package.json does not exist.

**Comment by brillout** [comment]
Reproduction?

**Comment by LePichu** [comment]
> Reproduction?

![image](https://user-images.githubusercontent.com/62379502/209840176-ff8515de-f49f-4b88-9229-b7e3ec264d90.png)
Generating a Solid-js + Deno workspace then adding SSR plugin does this, here's the code:
```ts
import { defineConfig } from 'npm:vite'
import solid from 'npm:vite-plugin-solid'
import ssr from "npm:vite-plugin-ssr/plugin"

import 'npm:solid-js'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [solid(), ssr()]
})

```

**Comment by LePichu** [comment]
Same story with Svelte it seems, code again:
```ts
import { defineConfig } from 'npm:vite'
import { svelte } from 'npm:@sveltejs/vite-plugin-svelte'
import ssr from "npm:vite-plugin-ssr/plugin"

import 'npm:svelte'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [svelte(), ssr()]
})

```
![image](https://user-images.githubusercontent.com/62379502/209840431-0d802706-8de2-4242-8b4a-88dc6c1f6741.png)


You can replicate both by running:
```sh
$ deno run -A npm:create-vite-extra # choose solid or svelte here
$ cd <your_generated_project>
```
add `import ssr from "npm:vite-plugin-ssr/plugin"` to the Vite config, activate plugin, you'll get the same.

**Comment by brillout** [comment]
[/examples/deno/](https://github.com/brillout/vite-plugin-ssr/tree/main/examples/deno)

**Comment by Suyashtnt** [comment]
There seems to be an issue where 80% of the time `vite-plugin-ssr` does not get picked up by vite, strange

repo where I see this happen: https://github.com/Suyashtnt/svelte-vite-deno-ssr-demo

**Comment by brillout** [comment]
@Suyashtnt What's the thrown error? I guess it's a problem on Deno's side?
