### ISSUE TITLE
Expose open file limit option for prerender command

### ISSUE THREAD

**Issue by gryphonmyers** [brillout/vite-plugin-ssr#59]
With very large sites, it is possible that the prerender process will fail with an `EMFILE, too many open files` error. Currently this can be mitigated only be editing os configuration to increase open file limit. If we exposed an option for configuring the max number of open files, users would have more control over this issue, making the plugin more scalable.

**Comment by brillout** [comment]
Released in `v0.1.0-beta.42`.

**Comment by brillout** [comment]
There should be no performance degradation, but let me know if you notice the pre-rendering taking longer than usual.
