### ISSUE TITLE
Build command not exiting on finish

### ISSUE THREAD

**Issue by rivatove** [brillout/vite-plugin-ssr#590]
### Description

When using _prerender: true_, the build command doesn't exit after pre-rendering HTML files. My server can't know that the build has been successful.

https://prnt.sc/lthmQrwdIdDh

**Comment by brillout** [comment]
It should though, as attested by the many `/examples/` using pre-rendering. It's probably a user land thing (e.g. if you use the prerender hook or VPS's JS API).

If you're confident it's a VPS bug, then reproduction welcome.

Closing but I'll re-open if there is evidence it's a VPS bug.

**Comment by rivatove** [comment]
> It should though, as attested by the many `/examples/` using pre-rendering. It's probably a user land thing (e.g. if you use the prerender hook or VPS's JS API).
> 
> If you're confident it's a VPS bug, then reproduction welcome.
> 
> Closing but I'll re-open if there is evidence it's a VPS bug.

You're right, I should've tried to reproduce it before reporting. It was [Vite Checker](https://github.com/fi3ework/vite-plugin-checker) getting in the way somehow, I had to disable it for builds. Still kinda interesting that it worked without the pre-rendering.
