### ISSUE TITLE
HMR doesn't work properly with @vitejs/plugin-react-swc

### ISSUE THREAD

**Issue by enpitsuLin** [brillout/vite-plugin-ssr#592]
### Description

vps can't work fine with `@vitejs/plugin-react-swc`

Minimal Reproduction: [link](https://github.com/enpitsuLin/vps-react-swc-issue)

change `/pages/index/index.page.tsx` to test can see HMR not work properly, page doesn't change

### Error Message + Error Stack

```shell
None
```

**Comment by brillout** [comment]
The bug most likely lives in `@vitesjs/plugin-react-swc` - I think we should open a ticket over there instead. The maintainer is very welcoming and feel free to CC me.
