### ISSUE TITLE
Migration guide: NextJS to vite-plugin-ssr 

### ISSUE THREAD

**Issue by redbar0n** [brillout/vite-plugin-ssr#594]
### Description

Would be nice with a guide / screencast detailing how to migrate an existing app from NextJS to vite-plugin-ssr. To lower the barrier to adoption. It would also give people a quick overview of the practical code/repo differences between the two.

Possibilities for example apps to migrate:
- HelloWorld app (good since minimal, and for focusing on the framework differences instead of app specifics).
- TodoMVC app: https://todomvc.com/
- RealWorld app: https://github.com/gothinkster/realworld and https://github.com/reck1ess/next-realworld-example-app or the more recent https://github.com/Dima-Abramenko/next-layouts-realworld-example-app from https://github.com/gothinkster/realworld/discussions/1082

**Comment by brillout** [comment]
👍 I like idea of having a screencast and/or a single commit showcasing a migration.

Contribution welcome.

**Comment by rtritto** [comment]
What is migration for `getServerSideProps`?

I'm using [solid-ssr](https://github.com/brillout/vite-plugin-ssr/tree/main/examples/solid-ssr) example, how can it be done in [index](https://github.com/brillout/vite-plugin-ssr/tree/main/examples/solid-ssr/pages/index) page?

**Comment by brillout** [comment]
Contribution much welcome to write a migration guide.
