### ISSUE TITLE
Monorepo support

### ISSUE THREAD

**Issue by rivatove** [brillout/vite-plugin-ssr#598]
### Description

Hello,

It would be cool to be able to specify a path to the _pages_ & _renderer_ folders.

**Comment by brillout** [comment]
This is already possible: https://vite-plugin-ssr.com/filesystem-routing.

Also https://brillout.github.io/rules/.

**Comment by rivatove** [comment]
> This is already possible: https://vite-plugin-ssr.com/filesystem-routing.
> 
> Also https://brillout.github.io/rules/.

I am not sure how it adressess the issue. AFAIK there's no way to build only one folder so the bundles of all apps will get interwined.

Also, one app may require a different renderer which can't be easily changed.

**Comment by brillout** [comment]
> there's no way to build only one folder

That's true but that's a Vite issue, not a VPS one.

> Also, one app may require a different renderer which can't be easily changed.

You can have multiple renderers that apply to different pages, as documented in the docs.

**Comment by rivatove** [comment]
**Update:** The _root_ property of vite.config.js was exactly what I was looking for.
