### ISSUE TITLE
[Security] pageContext internal state is exposed to client

### ISSUE THREAD

**Issue by zim32** [brillout/vite-plugin-ssr#608]
### Description

In my prerendered pages, if I write console.log(pageContext) I got all internal fields prefixed by "_" in the browser.

Here is my passToClient:

`export const passToClient = ['pageProps', 'urlPathname', 'routeParams', 'initialStoreState', 'isEditPage', 'locale']`

But I can read fields such as _pageContextRetrievedFromServer, _pageFilesAll and others.

**Comment by zim32** [comment]
It seems like when you do like mention in this page https://vite-plugin-ssr.com/pageContext-anywhere 

app.provide('pageContext', pageContext)

you are injecting private properties too.

**Comment by brillout** [comment]
Please don't use GitHub Issues for questions. Use GitHub discussions instead, see https://github.com/brillout/vite-plugin-ssr/discussions/526.

Also see https://brillout.github.io/rules/.

**Comment by zim32** [comment]
This is not a question. This is bug in documentation which leads to security hole

**Comment by brillout** [comment]
Nothing beyond `passToClient` is serialized/passed from server to client. Those internal props aren't coming from the server.

Reproduction welcome if you still believe there is a bug.

**Comment by zim32** [comment]
Ok I will write a youtube video on my channel and Il will send you the link. Because I don't know hot to reproduce prerendering

**Comment by zim32** [comment]
So just install empty project, open **pages/index/index.page.vue**, paste this code

```
<template>
  <h1>Welcome</h1>
  This page is:
  <ul>
    <li>Rendered to HTML.</li>
    <li>Interactive. <Counter /></li>
  </ul>
</template>

<script lang="ts" setup>
import Counter from './Counter.vue'
import {usePageContext} from "../../renderer/usePageContext";
import {onMounted} from "vue";

const pageContext = usePageContext()

onMounted(() => {
    console.log(JSON.stringify(pageContext))
})

</script>
```

Run npm run prod
Open http://127.0.0.1:3000/

and you will see this

`{"_comesDirectlyFromServer":true,"_pageContextRetrievedFromServer":{"_pageId":"/pages/index/index","urlPathname":"/"},"_pageFilesAll":[{"filePath":"/pages/about/index.page.vue","fileType":".page","isDefaultPageFile":false,"isRendererPageFile":false,"isErrorPageFile":false,"pageId":"/pages/about/index"},{"filePath":"/pages/index/index.page.vue","fileType":".page","isDefaultPageFile":false,"isRendererPageFile":false,"isErrorPageFile":false,"pageId":"/pages/index/index","fileExports":{"default":{"__name":"index.page"}}},{"filePath":"/renderer/_error.page.vue","fileType":".page","isDefaultPageFile":false,"isRendererPageFile":false,"isErrorPageFile":true,"pageId":"/renderer/_error"},{"filePath":"/renderer/_default.page.client.ts","fileType":".page.client","isDefaultPageFile":true,"isRendererPageFile":true,"isErrorPageFile":false,"pageId":"/renderer/_default","fileExports":{}}],"_pageFilesLoaded":[{"filePath":"/pages/index/index.page.vue","fileType":".page","isDefaultPageFile":false,"isRendererPageFile":false,"isErrorPageFile":false,"pageId":"/pages/index/index","fileExports":{"default":{"__name":"index.page"}}},{"filePath":"/renderer/_default.page.client.ts","fileType":".page.client","isDefaultPageFile":true,"isRendererPageFile":true,"isErrorPageFile":false,"pageId":"/renderer/_default","fileExports":{}}],"_pageId":"/pages/index/index","exports":{"Page":{"__name":"index.page"}},"exportsAll":{"Page":[{"exportValue":{"__name":"index.page"},"filePath":"/pages/index/index.page.vue","_filePath":"/pages/index/index.page.vue","_fileType":".page","_isFromDefaultExport":true}],"render":[{"filePath":"/renderer/_default.page.client.ts","_filePath":"/renderer/_default.page.client.ts","_fileType":".page.client","_isFromDefaultExport":false}]},"isBackwardNavigation":null,"isHydration":true,"Page":{"__name":"index.page"},"pageExports":{},"urlPathname":"/"}`

**Comment by brillout** [comment]
I don't see any problem.

**Comment by zim32** [comment]
I fixed this in my code, because I don't need this unexpected extra metadata about every page in every page. Moreover ot doesn't look like this properties are passed intentionally,.and there is no guarantee that you will add some more metada later, f.e. absolute file path or something else, so I decided to sanitize this context
