### ISSUE TITLE
`onBeforeRender` leads to props being undefined for a short moment 

### ISSUE THREAD

**Issue by samuelstroschein** [brillout/vite-plugin-ssr#623]
### Description

The `onBeforeRender` return value seems to be undefined for a brief second in both server-side and client-side environments. It might be due to our implementation or a bug in VPS. I am unsure. Adding bullish coalescing operators fixed the bug. 

Opening the issue in case this is VPS related. 

 

### Error Message + Error Stack

See the history of https://github.com/inlang/inlang/issues/282

The `onBeforeRender` hook in question can be found here https://github.com/inlang/inlang/blob/63e53030e5718d7eb67c50708fc9ae7ac4cf2298/source-code/website/src/pages/documentation/*/index.page.server.tsx

**Comment by brillout** [comment]
I wouldn't know how it could be related to VPS. Let's reopen if someone can reproduce.

**Comment by brillout** [comment]
(Thanks for opening the ticket, this may help future users.)
