### ISSUE TITLE
Asset injection causes "A charset attribute on a meta element found after the first 1024 bytes." error in Lighthouse

### ISSUE THREAD

**Issue by Csszabi98** [brillout/vite-plugin-ssr#638]
### Description

The asset injection strategy causes the following lighthouse error: "A charset attribute on a meta element found after the first 1024 bytes." .

My template looks like this:

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
<!-- ... -->
```

What my output template will be in production:
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <link rel="stylesheet" type="text/css" href="/assets/css/ResponsiveLayout-435854b2.css">
    <link rel="stylesheet" type="text/css" href="/assets/css/ClientOnly-8a52504d.css">
    <link rel="stylesheet" type="text/css" href="/assets/css/default-f8722781.css">
    <link rel="stylesheet" type="text/css" href="/assets/css/_default.page.client-ba829c0f.css">
    <meta charset="UTF-8">
<!-- ... -->
```

As the assets are injected to the beginning of the head the meta charset gets pushed down which causes the lighthouse error.

**Possible solutions:**
Injecting assets to the end of the head tag would solve this issue. (Although I don't know what type of drawbacks it would bring)

**Comment by brillout** [comment]
I don't think this has any real consequence? I'll re-open if there is a real problem here.

> Injecting assets to the end of the head tag would solve this issue. (Although I don't know what type of drawbacks it would bring)

CSS should be loaded ASAP, so I don't think this is an option.

**Comment by Csszabi98** [comment]
@brillout 
It does have real consequences and can cause issues.
Browsers are not defaulting to "utf-8" character encoding, in fact, they are using heuristics to determine which encoding to use, and this process can lead to performance issues or even incorrectly inferred character encoding in some rare cases.

Cited from the WHATWG docs:
> § 13.2.3.2 Determining the character encoding
> ...
> The user agent may wait for more bytes of the resource to be available, either in this step or at any later step in this algorithm. For instance, a user agent might wait 500ms or 1024 bytes, whichever came first. In general preparsing the source to find the encoding improves performance, as it reduces the need to throw away the data structures used when parsing upon finding the encoding information. However, if the user agent delays too long to obtain data to determine the encoding, then the cost of the delay could outweigh any performance improvements from the preparse.

https://html.spec.whatwg.org/multipage/parsing.html#determining-the-character-encoding

Perhaps vite-plugin-ssr could auto-include the `<meta charset="$encoding">` tag at the beginning of the HTML head and the encoding could be coming from the configuration defaulting to `utf-8`.

**Comment by brillout** [comment]
I'm aware of that &ndash; the question here is whether injecting scripts before charset has consequences?

**Comment by brillout** [comment]
> The user agent may wait for more bytes of the resource to be available, either in this step or at any later step in this algorithm.

👍 I didn't know that.

> For instance, a user agent might wait 500ms or 1024 bytes, whichever came first.

That should be plenty to accomodate `<script>` tags.

**Comment by brillout** [comment]
To be clear, I'm also in favor of implementing a solution here (let alone to get rid of the Lighthouse warning), but it seems like low priority.

**Comment by brillout** [comment]
And PR welcome to implement following solution: make VPS inject `<script>` after charset if charset is the first tag in `<head>`. AFAICT this should solve the problem without the need for an extra config.

**Comment by Csszabi98** [comment]
Other than overflowing the 1024bytes/500ms limit I don't think injecting scripts/links before the charset has any other consequences.
500ms might seem plenty, but on mobile when traveling on a train for instance network speeds can be really slow. So either way putting the charset meta tag first would have benefits. Also, it must not be assumed that a browser chose to implement this with 500ms limit other and not a 1024bytes one.

So considering all that would put the `meta` tag before the link tags, as there is no telling how many of them there are on a rendered page, and they can trigger this issue too.

I agree with you that it is low prio, other than the lighthouse warning I could not find any issues so far, but regardless of that, it could cause issues.

I will draft a PR soon.

**Comment by brillout** [comment]
> I will draft a PR soon.

Neat. Looking forward to it 👀 .

(I agree about everything in your last reply.)

**Comment by brillout** [comment]
Also, thinking, we could add a little `assertWarning()` if charset isn't the first child of `<head>`.

**Comment by brillout** [comment]
https://github.com/brillout/vite-plugin-ssr/issues/695
