### ISSUE TITLE
Injecting tags above injected assets

### ISSUE THREAD

**Issue by schneefux** [brillout/vite-plugin-ssr#662]
### Description

I have a feature request similar to #419. I need to add third party `<script async>` tags to the document's `<head>`. The third party wants me to put them above the `<link>` tags that VPS generates because link tags are render blocking (see https://web.dev/critical-rendering-path-render-blocking-css/) and apparently the scripts need to be executed as early as possible.

As far as I can tell from reading the source and debugging `injectFilter()`, it is currently not possible to add assets before VPS' so it would be nice if the hook allowed that.

**Comment by brillout** [comment]
> the scripts need to be executed as early as possible

Can you elaborate on that?

**Comment by brillout** [comment]
I've a simple design in mind.

> Can you elaborate on that?

The only thing left is a good reason for implementing it.

**Comment by brillout** [comment]
https://github.com/brillout/vite-plugin-ssr/issues/695
