### ISSUE TITLE
<link rel=preload> must have a valid `as` value (chrome dev)

### ISSUE THREAD

**Issue by yoroshikun** [brillout/vite-plugin-ssr#68]
Just a small error popping up in my console of generated preload links.

Firefox error:` Preload of https://page/assets/favicon.adc4dd5b.png was ignored due to unknown “as” or “type” values, or non-matching “media” attribute.`

Think it might just be missing `as="image"`

**Comment by brillout** [comment]
Released in `0.1.0-beta.44`.
