### ISSUE TITLE
Stage Hooks instead of `addPageContext`.

### ISSUE THREAD

**Issue by brillout** [brillout/vite-plugin-ssr#71]
The idea here is to replace `addPageContext` with more granular "stage" hooks.

```js
// .page.server.js

export { onInitializeContext }
export { onBeforeRouting }
export { onBeforeRender }
```

@deckchairlabs
@gryphonmyers
@yoroshikun 
@chrisvariety

**Comment by gryphonmyers** [comment]
I like it, especially because it directly addresses issues I've raised 😂. I think it will be important to include a life cycle diagram in the docs so people can easily understand the order of operations

**Comment by brillout** [comment]
> I like it, especially because it directly addresses issues I've raised 😂

I know 😀 

> include a life cycle diagram in the docs

Yes, I also greatly care about clarity :-). Although it could be so simple that no diagram would even be needed. We'll see if we'll end up needing one.

**Comment by brillout** [comment]
All stage hooks would need to be called after routing (explanation [here](https://github.com/brillout/vite-plugin-ssr/issues/26#issuecomment-847663236)). This leaves us with two sages: onBeforeRender and onAfterRender. So far, I don't see use cases for onAfterRender that cannot be already achieved today.

I'm therefore closing this for now. Maybe something will change in the future that will make this relevant again.

**Comment by brillout** [comment]
Every hook is now a stage hook. I.e. `addPageContext()` is now `onBeforeRender()`.

Thanks for all the lovely feedback.
