### ISSUE TITLE
types: cannot resolve `vite-plugin-ssr/client` with `moduleResolution: "nodenext"`

### ISSUE THREAD

**Issue by ezracelli** [brillout/vite-plugin-ssr#716]
### Description

I’m using Node’s native ESM support + TypeScript for my server, so I have `moduleResolution` set to `"nodenext"` in my `tsconfig.json`. This setting (among other things) configures TypeScript to resolve modules from the `exports` field of `package.json`.

Since the `./client` export only has a `browser` condition (not one [implemented by Node](https://nodejs.org/api/packages.html#conditional-exports)), TypeScript is unable to resolve `vite-plugin-ssr/client`.

(Note: This will be able to be bypassed with [TS 5.0’s `customConditions`](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#customconditions), but I’m not able to upgrade yet.)

The only place this is being used in my project is inside `renderer/pageContext.ts` to get the `PageContextBuiltInClient` type:

```ts
import type { ReactElement } from "react";
import type { PageContextBuiltIn } from "vite-plugin-ssr";
import type { PageContextBuiltInClient } from "vite-plugin-ssr/client";
//                                            ^^^^^^^^^^^^^^^^^^^^^^^^
// Cannot find module 'vite-plugin-ssr/client' or its corresponding type declarations. ts(2307)

type Page = (pageProps: PageProps) => ReactElement;
type PageProps = {};

export type PageContext = {
    Page: Page;
    pageProps?: PageProps;
};

export type PageContextServer = PageContextBuiltIn<Page> & PageContext;
export type PageContextClient = PageContextBuiltInClient<Page> & PageContext;
```

Not 100% sure what the resolution should be here. `vite-plugin-ssr/client` should probably _not_ be importable from Node. Maybe `PageContextBuiltInClient` should be exported from the main `vite-plugin-ssr` export as well?

### Error Message + Error Stack

```shell
N/A (see above)
```

**Comment by brillout** [comment]
I actually added `package.json#exports[string].types` two days ago. IIRC `nodenext` supports `package.json#exports` so I believe it fixes it.

Let me release.

**Comment by brillout** [comment]
Released in `0.4.95`. Let me know if you still run into issues.

**Comment by ezracelli** [comment]
Woah, thanks for the quick response! In `0.4.95`, I do see that `exports["."].types` was set, but I don’t see an entry for `exports["./client"].types` &mdash; is that expected?

https://github.com/brillout/vite-plugin-ssr/blob/b679c402649a327eeb46014cfabc0a2d3aa7de41/vite-plugin-ssr/package.json#L51-L59

**Comment by brillout** [comment]
Indeed. Fixed in `0.4.96`.

Btw, in case your company is up for it: https://github.com/sponsors/brillout &ndash; any amount is appreciated.

**Comment by brillout** [comment]
Let me know if you still run into issues with `"nodenext"`. I only tested `import type { PageContextBuiltInClient } from "vite-plugin-ssr/client";`.

**Comment by ezracelli** [comment]
Works perfectly on `0.4.96` &mdash; thank you!
