### ISSUE TITLE
Bug in Vue Layouts example

### ISSUE THREAD

**Issue by shortpoet** [brillout/vite-plugin-ssr#724]
### Description

`ReferenceError: _sfc_main is not defined`

This bug is referenced in [this issue](https://github.com/brillout/vite-plugin-ssr/issues/309). If the example is run from the monorepo, all tests pass. If you pull the example out and run just the example in isolation, the bug will be encountered. I tried to add [the repro](https://github.com/zorbae/vps-repro-vue-layouts) to stackblitz, but couldn't get it to run there. 

I think there is an [open issue](https://github.com/vuejs/core/issues/7038) in Vue about it. It gave me a clue to fix the 'bug.' I have no idea why the monorepo seems to avoid the issue and would love to learn if you know.

The fix is to change [this line](https://github.com/brillout/vite-plugin-ssr/blob/6c6bf63b9914ebbbccee0f3190889bad004aec6d/examples/layouts-vue/pages/index/index.page.vue#L23)

from 

```typescript
export { default as Layout } from './Layout.vue'
```

to 

```typescript
import { default as Layout } from './Layout.vue'
export { Layout }
```

I can confirm that tests still pass (the ones that didn't fail otherwise) on the monorepo with this change. Would love the opportunity to submit a PR if appropriate.

### Error Message + Error Stack

```shell
ReferenceError: _sfc_main is not defined
    at eval (/pages/index.page.vue:16:20)
    at async instantiateModule (file:///Users/Shared/source/repos/zorbae/vps-repro-vue-layouts/node_modules/.pnpm/vite@4.1.4/node_modules/vite/dist/node/chunks/dep-ca21228b.js:52420:9)
```

**Comment by brillout** [comment]
Hm, that's quite surprising indeed. And in many ways.

Yea, PR welcome to update that line!

**Comment by brillout** [comment]
Closing since it's not really a VPS bug. Looking forward to your PR.
