### ISSUE TITLE
Extract library runtime into a separate package "vite-plugin-ssr/runtime"

### ISSUE THREAD

**Issue by Csszabi98** [brillout/vite-plugin-ssr#733]
### Description

Currently when you add `vite-plugin-ssr` to the `package.json` of an AWS lambda and do an `npm install --omit=dev`, the produced `node_modules` folder is way too big. This is caused by vite-plugin-ssr including dependencies upon vite, vite on esbuild, etc.. We can see by this that this greatly increases the size of the final lambda zip.

**Example output of terraform**
```
  adding: node_modules/.bin/ (stored 0%)
  adding: node_modules/.bin/esbuild (deflated 58%)
  adding: node_modules/.bin/fxparser (deflated 68%)
  adding: node_modules/.bin/nanoid (deflated 53%)
  adding: node_modules/.bin/rollup (deflated 75%)
  adding: node_modules/.bin/resolve (deflated 59%)
  adding: node_modules/.bin/symlink-dir (deflated 19%)
  adding: node_modules/.bin/rimraf (deflated 59%)
  adding: node_modules/.bin/vite-plugin-ssr (deflated 6%)
  adding: node_modules/.bin/vite (deflated 56%)
  adding: node_modules/.package-lock.json (deflated 79%)
  adding: package-lock.json (deflated 78%)
  adding: package.json (deflated 38%)
```

**Benefits of implementing this:**
- Not polluting the serverless bundles (we can fit more, actually used code into the ~50mb limit of AWS for example)
- Potentially better cold starts (not sure about this one)

**Proposed solution:**
Extract the core runtime of vite-plugin-ssr into a new leaner package, which only installs dependencies which are needed for serverless runtimes.

e.g.:
```
import { renderPage } from 'vite-plugin-ssr/runtime'
```

**Comment by brillout** [comment]
That was actually already implemented two days ago.

Updated to the latest version and follow the warning's instructions for how to update outdated imports.

**Comment by brillout** [comment]
Let me know if the latest version addresses your issue. Closing in the meantime.

**Comment by Csszabi98** [comment]
Unfortunately this extraction is not enough, as the "vite-plugin-ssr/server" export is still under the same npm package. This means that the dependencies of vite-plugin-ssr will be installed with `npm install --omit=dev`. The only way to solve this would be to publish the /server export as a separate npm package, with minimal dependencies.

**Comment by brillout** [comment]
I'd go for a workaround in user land. E.g. set Vite's `noExternal` to `true` and only upload `dist/`, or use esbuild to bundle `vite-plugin-ssr/server` and only upload that.

**Comment by Csszabi98** [comment]
I think we can rule out `"noExternal": true`, as it disallows importing any node built-ins (looks like the target is webworkers in that case). One can use a regex value for it instead like `"noExternal": /.*/` which bundles all of the npm packages, except for `vite-plugin-ssr` which explicitly adds itself to `external`. But even if it would be bundled you would still be needing to access `renderPage` somehow in the lambda function. 

This leads us to bundling the whole lambda with esbuild, which also has a blocker limitation (https://github.com/evanw/esbuild/issues/2663). You can patch the output bundle directly, but it is for sure a complicated workaround to get this done.

That is why I think it would be best to do something like removing `vite-plugin-ssr` from the explicit externals, and let vite bundle it along with all other dependencies (it would only happen if the vite config defines `"noExternal": /.*/`). With this there could be an entry point file which can be imported from lambdas, what could just re-export the `renderPage` function.
