### ISSUE TITLE
Get error when using client routing

### ISSUE THREAD

**Issue by chuankaiwei** [brillout/vite-plugin-ssr#745]
### Description

When I use client routing by set `export const clientRouting = true;` on `_default.page.client.js`, but I get an error on the browser.
I saw an `assertServerRouting` assertion at the `client/entry.ts`. I think it does not make sense 🤔.

### Error Message + Error Stack

```shell
Error: [vite-plugin-ssr@0.4.103][Wrong Usage] `import { something } from 'vite-plugin-ssr/client/router'` is forbidden when using Server Routing
    at assertServerRouting (entry-client-routing.2f516636.js:63:4480)
    at entry-client-routing.2f516636.js:66:11032
```

**Comment by brillout** [comment]
Just released `0.4.105` which contains refactored assertions.

Closing but I'll re-open if you still encounter your problem. Keep me updated.
