### ISSUE TITLE
Add flag `tolerateMultipleIntances` for stacks that load multiple vite-plugin-ssr instances

### ISSUE THREAD

**Issue by brillout** [brillout/vite-plugin-ssr#751]
### Description

> Copy-pasted from https://github.com/brillout/vite-plugin-ssr/commit/fee06f38179eb0fe1a2cef867d96ae682727358f#r106858569.

Is it possible this import causes an issue with the `import { projectInfo }` in `assert.ts`?

<img width="1012" alt="image" src="https://user-images.githubusercontent.com/721128/229001445-5c3b2a02-6e8f-4438-aca4-af2c85ce6893.png">

This error used to be about how `usageErrorPrefix` and/or the like weren't defined, until I patched the `const`s to `var`s so the JS engine would hoist them above execution. Meanwhile, `globalObject$2` above is undefined in `assert.ts`' function bodies, at least when called by the `onProjectInfo` invocation on the compiled line 627.

**Comment by brillout** [comment]
> Aha [[L26](https://github.com/brillout/vite-plugin-ssr/commit/fee06f38179eb0fe1a2cef867d96ae682727358f#diff-e5fc422285a22ff7eca42ecef0c12ce99662a38f94e6284e67661bb844041ee0R26)]! Yes, I think the circular dep can cause problems. Happy to share more about my setup if helpful :)

**Comment by brillout** [comment]
@anulman If you change L26 to `throw new Error(errMsg)` instead of `assertUsage(false, errMsg)`, does it fix the problem?

**Comment by anulman** [comment]
Yes and no—the script was still throwing, but the error was more helpful in that it pointed me to the root cause (a double-initialize) vs. internal lib details.

As for the root cause, something about my environment (mounting my UI via Shopify's App Bridge) seems to be causing a double-initialize. I still needed to patch the plugin to continue execution and so far am not seeing any side effects beyond a slower init. So if you don't expect bad side effects from this, it would be nice to pass a config option for `ignoreDoubleInitializeErrors` or something :)

**Comment by anulman** [comment]
Thanks btw! Love the lib ♥️

**Comment by brillout** [comment]
Could you provide a reproduction (doesn't have to be minimal)? That would be the best as it'd enable me to polish many things.

> it would be nice to pass a config option for `ignoreDoubleInitializeErrors` or something

Just to be clear: you know that this means that VPS is included twice and you're bloating your client-side bundle, right?

That said, good idea with `ignoreDoubleInitializeErrors` for use cases where bloating the client-side isn't an issue, e.g. private interfaces. But I'd need to dig whether there are edge cases that need to be updated to support multiple instances.

On a tangent: would your employer be up to https://github.com/sponsors/brillout?

> Thanks btw! Love the lib ♥️

I'm glad you like it 💚.

**Comment by anulman** [comment]
> On a tangent: would your employer be up to https://github.com/sponsors/brillout?

Great question; I'm mostly using your libs in a personal project but will :100: ask if / once your packages make their way into work-work :)

> Could you provide a reproduction (doesn't have to be minimal)? That would be the best as it'd enable me to polish many things.

I can invite you to my repo, but the Shopify App Bridge ecosystem is... gnarly. Alternatively I can screenshare and let you poke around. I'll try and record a Loom today and report back so you can make an informed decision :)

> That said, good idea with ignoreDoubleInitializeErrors for use cases where bloating the client-side isn't an issue, e.g. private interfaces. But I'd need to dig whether there are edge cases that need to be updated to support multiple instances.

Tysm! Happy to be pushing this bleeding edge lol

**Comment by brillout** [comment]
> I can invite you to my repo

If setting up the repo is only a matter of cloning it and running a couple of commands then, yea, let's do this.

Otherwise I'd wait for someone to provide a reproduction.

I need to "touch" this thing :-).

**Comment by brillout** [comment]
> That said, good idea with `ignoreDoubleInitializeErrors` for use cases where bloating the client-side isn't an issue, e.g. private interfaces. But I'd need to dig whether there are edge cases that need to be updated to support multiple instances.

Closing for lack of interest.
