### ISSUE TITLE
production build fails with latest version

### ISSUE THREAD

**Issue by ejm-hyesung** [brillout/vite-plugin-ssr#763]
### Description

![image](https://user-images.githubusercontent.com/112405757/230266797-7ee523fa-8b37-4b00-8d1b-e0ab44c4cdb7.png)

seems like there is and additional operand after mkdir or am I missing something?

I upgraded my vps using yarn upgrade vite-plguin-ssr --latest

here is my yarn.lock

![image](https://user-images.githubusercontent.com/112405757/230267243-df2d38e0-901b-489a-b50c-7dc689719821.png)

**Comment by brillout** [comment]
This doesn't seem to be related to VPS. Did you update another dependency as well?

**Comment by ejm-hyesung** [comment]
> This doesn't seem to be related to VPS. Did you update another dependency as well?

no what I did was just yarn upgrade vite-plguin-ssr --latest

**Comment by brillout** [comment]
I wouldn't know how VPS can cause the error. Minimal reproduction welcome.

**Comment by ejm-hyesung** [comment]
> I wouldn't know how VPS can cause the error. Minimal reproduction welcome.

I upgrade vite as well and it solved. sorry for bother thanks for the reply!

**Comment by brillout** [comment]
No problems.

Btw, if you think you can convince your company: https://github.com/sponsors/brillout. Sponsors are starting to make a tremendous difference!
