### ISSUE TITLE
The order of template injection css is reversed

### ISSUE THREAD

**Issue by mofipp** [brillout/vite-plugin-ssr#776]
### Description

<img width="285" alt="image" src="https://user-images.githubusercontent.com/28723473/230897190-7cc9c06e-22e9-4316-9c84-f9f1f8349587.png">
<img width="371" alt="image" src="https://user-images.githubusercontent.com/28723473/230897255-7388c0ef-7edb-46f5-a99d-b63af0dab983.png">

Styles are overwritten because the default.page.client.css is in reverse order
Why is it happen?

**Comment by brillout** [comment]
I don't think that's an issue though? In general, you're supposed to make sure your CSS don't depend on order.

Closing but feel free to let me know if you think it can cause a real problem.

**Comment by kurdin** [comment]
@brillout sorry to reopen but I hit the same problem. In may cases not to preserve order of loaded css could lead to bugs and misbehavior. Dev env should match Prod otherwise it could lead to problems. If there a way to make sure that global (default) layout css always loaded first, it would be nice to have. Remix for example, does preserve styles loading order.

**Comment by brillout** [comment]
I agree but I think this would need to be fixed over at Vite.

**Comment by kurdin** [comment]
@brillout I see, I was hoping that I can manually import baseCSS and insert into the page, something like this in `_default.page.server.tsx` but its not working well. Vite still adding pages css on top of everything in the head.

```js
import baseCSS from './tailwind-base.css?inline';
...
    const documentHtml = escapeInject`<!DOCTYPE html>
    <html lang="en">
        <head>
        <style>${dangerouslySkipEscape(baseCSS)}</style>
	<meta charset="UTF-8" />
        <link rel="icon" href="${logoUrl}" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="${desc}" />
        <title>${title}</title>
      </head>
      <body>
        <div id="page-view">${dangerouslySkipEscape(pageHtml)}</div>
      </body>
    </html>`;
```

Oh well. Thank you for your time and great ssr plugin,

**Comment by brillout** [comment]
Yea, I don't think there is much we can do here. Could be tricky for Vite to address this because of Vite's lazy-transpiling nature, let's see.

> Thank you for your time and great ssr plugin.

I'm glad you like it. Btw. if you can convince your employer: https://github.com/sponsors/brillout.
