### ISSUE TITLE
Create docs website

### ISSUE THREAD

**Issue by brillout** [brillout/vite-plugin-ssr#78]
Let me know if you'd prefer a docs website over the current readme.

**Comment by i3ima** [comment]
One of the options may be a site on `nextjs` with docs described as `.mdx` files styled with [next-mdx-enhanced](https://github.com/hashicorp/next-mdx-enhanced)
Good example of that kinda docs is [`ChakraUI`](https://github.com/chakra-ui/chakra-ui/tree/main/website) docs, package is [here](https://github.com/chakra-ui/chakra-ui/tree/main/website)
I'm not sure if it's possible to do using `Vite`

**Comment by brillout** [comment]
@i3ima I'm going to use vite-plugin-ssr :-) as you can use it as an SSG.

**Comment by aFuzzyBear** [comment]
Hey man, I noticed this thread, just want to throw my name in to say if you need a hand with the writing some doc's for this plugin, I'd be happy to, 
Personally I would suggest looking into the github wiki, build that up, then you can just run those readme's through to a website, two birds, one big github sized stone...

**Comment by brillout** [comment]
@aFuzzyBear My original plan was actually to stick to GitHub's readme/wiki. But, since we'll soon have a dedicated website docs, we can then leverage things that are not possible today with GitHub's markdown. So the plan to go all-in on this new website docs and leave GitHub behind. As much as I love the simplicity of having docs in GitHub, it's just too limiting.

**Comment by aFuzzyBear** [comment]
Awesome, I didnt know about that man, anyway I can help writing the doc's even given them a copyread ?

**Comment by brillout** [comment]
The text of the website docs is going to be the same than the current Readme text. We can start with a small copyread PR to the `README.md` and see how we can align your writing style and mine. I've seen your blog post and I like your writing; I'm looking forward to see how this go.

**Comment by aFuzzyBear** [comment]
Thanks man, Ill get cracking over the weekend on it man. =)

**Comment by brillout** [comment]
No rush :-) Looking forward to discover your PR 👀.

**Comment by brillout** [comment]
Done. I'll implement search once Alogila accepted the website.
