### ISSUE TITLE
`vite-plugin-ssr/types` export can't be resolved

### ISSUE THREAD

**Issue by samuelstroschein** [brillout/vite-plugin-ssr#788]
### Description

Updating VPS yields the following warning: 

```
Error: [vite-plugin-ssr@0.4.113][Warning] You have following imports which are outdated:
  import { something } from 'vite-plugin-ssr'
Replace them with:
  import { something } from 'vite-plugin-ssr/server'
Or if `something` is a type:
  import type { something } from 'vite-plugin-ssr/types'
```

Changing the import to `vite-plugin-ssr/types` can't be resolved though. 

<img width="943" alt="CleanShot 2023-04-17 at 17 20 10@2x" src="https://user-images.githubusercontent.com/35429197/232533125-0dbd6ad7-7d76-4ffa-a648-a7921cc29de3.png">

The package.json of VPS does indeed not contain a `./types` export, see https://github.com/brillout/vite-plugin-ssr/blob/main/vite-plugin-ssr/package.json#L15.

**Comment by brillout** [comment]
Fix released in `0.4.114`.

Thanks for the bug report and you're right this is indeed needed when the user sets TS's `moduleResolution` to `"nodenext"` (or `"bundler"` I guess).

**Comment by samuelstroschein** [comment]
I am wondering whether it makes sense for you to switch the codebase to moduleResolution `node16` (the ESM strict standard). We do that for our repo in anticipation of fewer bugs like this one.

**Comment by brillout** [comment]
Yep, I do plan to make VPS be ESM-only when the time is right. (Some projects still need CJS.)
