### ISSUE TITLE
URL /@vite/client isn't matching any of your page routes

### ISSUE THREAD

**Issue by archit-p** [brillout/vite-plugin-ssr#792]
### Description

When running a vite-plugin-ssr react app in production mode, I see the following error popup in the terminal:

```
Server running at http://localhost:3000
[vite-plugin-ssr@0.4.114][Info] URL /@vite/client isn't matching any of your page routes. See https://vite-plugin-ssr.com/routing for more information about routing. Set the environment variable DEBUG=vps:routing to inspect your app's routing. (This log isn't shown in production.) Your page routes:
ROUTE                     ROUTE TYPE     DEFINED BY
/                         Route String   /pages/index/index.page.route.jsx
/app                      Route String   /pages/app/index.page.route.jsx
/app/project/@projectId   Route String   /pages/project/index.page.route.jsx
```

Investigating the error a bit, I see the page source looks like this:

![image](https://user-images.githubusercontent.com/30985772/232931692-9d5ebb42-9fe6-495c-8212-da97b19dba3b.png)

**Comment by brillout** [comment]
Did you forget to add the Vite dev middleware? Make sure to add it *before* the VPS middleware.

**Comment by archit-p** [comment]
I've added Vite dev middleware when the app is running in dev mode.

Here's my server file, with a reproduction of this issue:

https://codesandbox.io/p/github/archit-p/vite-plugin-ssr-example/master?file=%2Fserver%2Findex.js

**Comment by brillout** [comment]
I can't reproduce (I'm using https://gitpod.io/#github.com/archit-p/vite-plugin-ssr-example/master?file=%2Fserver%2Findex.js).

**Comment by brillout** [comment]
Double check if the Vite dev middleware is indeed installed. That's most likely the problem.

**Comment by brillout** [comment]
I could reproduce indeed. That's quite unexpected. Can you create a minimal reproduction? E.g. starting off `$ pnpm create vite-plugin-ssr@latest`.

**Comment by brillout** [comment]
The latest release `0.4.115` now contains a couple of warnings related to your problem that may help.

FYI I'm suspecting a user land problem, hence my push for a minimal reproduction. I'll close for now but I'll re-open if I'm provided with a minimal reproduction.

**Comment by archit-p** [comment]
Thanks for adding that warning @brillout! The issue in my case was slightly different, and I've fixed it yesterday.

The problem lies in these lines of code:
```js
let viteServer = await createServer({
    root: new URL('..', import.meta.url).pathname,
    server: { middlewareMode: true }
  })

  if (isProduction) {
    app.use(sirv(new URL('../dist/client', import.meta.url).pathname));
  } else {
    app.use(viteServer.middlewares);
  }
```

In the code above, the vite server gets started even in production mode. That causes the error I shared. Fix was:

```js
if (isProduction) {
  app.use(sirv(new URL('../dist/client', import.meta.url).pathname));
} else {
  let viteServer = await createServer({
    root: new URL('..', import.meta.url).pathname,
    server: { middlewareMode: true }
  })
  app.use(viteServer.middlewares);
}
```

**Comment by brillout** [comment]
Makes sense and that's actually a situation that is now catched by the new warnings.

(As always: https://github.com/sponsors/brillout)
