### ISSUE TITLE
`vite.config.js#base should start with '/', 'http://', or 'https://' (it is ./ instead)` when using storybook

### ISSUE THREAD

**Issue by archit-p** [brillout/vite-plugin-ssr#798]
### Description

When using vite-plugin-ssr with storybook, I see this vite-plugin-ssr error come up. I'm not sure why Storybook sets base to './', which is doesn't work with the plugin.

### Error Message + Error Stack

```shell
ERR! Error: [vite-plugin-ssr@0.4.115][Wrong Usage] vite.config.js#base should start with '/', 'http://', or 'https://' (it is ./ instead)
ERR!     at resolve (/Users/archit-p/Workspace/github/vite-storybook/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/plugins/config/resolveBase.js:23:21)
ERR!     at resolveBaseFromUserConfig (/Users/archit-p/Workspace/github/vite-storybook/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/plugins/config/resolveBase.js:17:12)
ERR!     at config (/Users/archit-p/Workspace/github/vite-storybook/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/plugins/baseUrls.js:14:45)
ERR!     at runConfigHook (file:///Users/archit-p/Workspace/github/vite-storybook/node_modules/vite/dist/node/chunks/dep-24daf00c.js:64475:31)
ERR!     at async Module.resolveConfig (file:///Users/archit-p/Workspace/github/vite-storybook/node_modules/vite/dist/node/chunks/dep-24daf00c.js:63965:14)
ERR!     at getOptimizeDeps (/Users/archit-p/Workspace/github/vite-storybook/node_modules/@storybook/builder-vite/dist/index.js:161:9096)
ERR!     at createViteServer (/Users/archit-p/Workspace/github/vite-storybook/node_modules/@storybook/builder-vite/dist/index.js:161:10516)
ERR!     at Module.start (/Users/archit-p/Workspace/github/vite-storybook/node_modules/@storybook/builder-vite/dist/index.js:161:12571)
ERR!     at async storybookDevServer (/Users/archit-p/Workspace/github/vite-storybook/node_modules/@storybook/core-server/dist/index.js:35:7062)
ERR!     at async buildDevStandalone (/Users/archit-p/Workspace/github/vite-storybook/node_modules/@storybook/core-server/dist/index.js:48:2786)
ERR!     at async withTelemetry (/Users/archit-p/Workspace/github/vite-storybook/node_modules/@storybook/core-server/dist/index.js:35:3422)
ERR!     at async dev (/Users/archit-p/Workspace/github/vite-storybook/node_modules/@storybook/cli/dist/generate.js:434:400)
ERR!     at async Command.<anonymous> (/Users/archit-p/Workspace/github/vite-storybook/node_modules/@storybook/cli/dist/generate.js:436:225)
ERR!  Error: [vite-plugin-ssr@0.4.115][Wrong Usage] vite.config.js#base should start with '/', 'http://', or 'https://' (it is ./ instead)
ERR!     at resolve (/Users/archit-p/Workspace/github/vite-storybook/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/plugins/config/resolveBase.js:23:21)
ERR!     at resolveBaseFromUserConfig (/Users/archit-p/Workspace/github/vite-storybook/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/plugins/config/resolveBase.js:17:12)
ERR!     at config (/Users/archit-p/Workspace/github/vite-storybook/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/plugins/baseUrls.js:14:45)
ERR!     at runConfigHook (file:///Users/archit-p/Workspace/github/vite-storybook/node_modules/vite/dist/node/chunks/dep-24daf00c.js:64475:31)
ERR!     at async Module.resolveConfig (file:///Users/archit-p/Workspace/github/vite-storybook/node_modules/vite/dist/node/chunks/dep-24daf00c.js:63965:14)
ERR!     at getOptimizeDeps (/Users/archit-p/Workspace/github/vite-storybook/node_modules/@storybook/builder-vite/dist/index.js:161:9096)
ERR!     at createViteServer (/Users/archit-p/Workspace/github/vite-storybook/node_modules/@storybook/builder-vite/dist/index.js:161:10516)
ERR!     at Module.start (/Users/archit-p/Workspace/github/vite-storybook/node_modules/@storybook/builder-vite/dist/index.js:161:12571)
ERR!     at async storybookDevServer (/Users/archit-p/Workspace/github/vite-storybook/node_modules/@storybook/core-server/dist/index.js:35:7062)
ERR!     at async buildDevStandalone (/Users/archit-p/Workspace/github/vite-storybook/node_modules/@storybook/core-server/dist/index.js:48:2786)
ERR!     at async withTelemetry (/Users/archit-p/Workspace/github/vite-storybook/node_modules/@storybook/core-server/dist/index.js:35:3422)
ERR!     at async dev (/Users/archit-p/Workspace/github/vite-storybook/node_modules/@storybook/cli/dist/generate.js:434:400)
ERR!     at async Command.<anonymous> (/Users/archit-p/Workspace/github/vite-storybook/node_modules/@storybook/cli/dist/generate.js:436:225)
```
```

**Comment by archit-p** [comment]
Here's a minimal reproduction:

https://github.com/archit-p/vite-plugin-ssr-example

**Comment by brillout** [comment]
What is Storyblock's intention for setting the base to `'./'`? VPS can't do anything about it without knowing that.

**Comment by brillout** [comment]
Closing but I'll re-open when we get more information about this.

**Comment by brillout** [comment]
It isn't clear how relative bases, such as `./`, is implementable for SSR apps (for any app with multiples pages really). I doubt it's even possible. Does Next.js & co support this?

So I'm inclined to think it's a Storybook issue. Or do you see a good reason for Storybook to change the `base` to `./`?

**Comment by archit-p** [comment]
Next.js does support it, but Storybook uses webpack there. In our case, since vite-plugin-ssr is vite based, storybook uses vite as a builder.

When I run `npm run storybook` it internally runs `vite serve` with base set to `./`. This causes an issue with vite-plugin-ssr plugin. So making this work, means preventing vite-plugin-ssr plugin from running when `npm run storybook` is run, as vite-plugin-ssr isn't used with storybook?

**Comment by archit-p** [comment]
Yes @brillout. Next doesn't need to support relative paths for Storybook to work with Next. In that case, the builder used is Webpack so I'm not sure what the options there are.

https://storybook.js.org/blog/get-started-with-storybook-and-next-js/

**Comment by brillout** [comment]
> It isn't clear how relative bases, such as `./`, is implementable for SSR apps (for any app with multiples pages really). I doubt it's even possible. Does Next.js & co support this?

You're not answering *that* question.

AFAICT VPS can't fix the situation. I'd recommend you to create an issue over at Storyblook.

**Comment by archit-p** [comment]
I misunderstood your question. NextJS supports Storybook, and my goal is for vite-plugin-ssr to support Storybook too. Its a pretty widely used tool for frontend development.

Here's the workaround I used to make it work:

Run storybook using:
```
cross-env NODE_ENV=storybook && storybook dev -p 6006
```

In `vite.config.js` I disable VPS conditionally.
```
import { defineConfig } from 'vite'
import react from "@vitejs/plugin-react";
import ssr from "vite-plugin-ssr/plugin";

export default defineConfig(({ }) => {
  return {
    plugins: [
      process.env.NODE_ENV !== 'storybook' && ssr(),
      react()
    ]
  }
})
```

I hope this can help others!

**Comment by brillout** [comment]
Thanks for sharing your workaround.

I do agree that VPS should support Storybook. Please (someone) create an issue over at Storybook and ask them why they set `base` to `./` and whether this can be disabled.

@archit-p Another workaround you can try is to override `base` and set it to `/`. You may need to use Vite's `enforce: 'post'` option.

**Comment by re-taro** [comment]
Hello!
I asked to Storybook!

https://github.com/storybookjs/storybook/discussions/23089

**Comment by re-taro** [comment]
I founded why config.base are set to './'

https://github.com/storybookjs/builder-vite/issues/238

**Comment by re-taro** [comment]
Perhaps we need to address this issue here!

**Comment by brillout** [comment]
I see, but:

> It isn't clear how relative bases, such as `./`, is implementable for SSR apps (for any app with multiples pages really). I doubt it's even possible

I think someone should tell the Storybook team about this, as AFAICT this breaks not only vite-plugin-ssr but any other SSR framework as well.

**Comment by re-taro** [comment]
Ok I see. I will build the issue.

**Comment by rhengles** [comment]
@brillout 
> It isn't clear how relative bases, such as ./, is implementable for SSR apps (for any app with multiples pages really). I doubt it's even possible.

Thanks for your replies in this issue.
I just want to understand the root of the problem.
When a page is rendered, isn't the route of the page known ?
Wouldn't this be a matter of replacing each path segment with `..` ?
For exemple, for a page `/route/to/the/page` that loads `./assets/icon.png`, wouldn't it be enough to replace it with `../../../assets/icon.png` ?

I'm not using Storybook, I want to take the prerendered pages and serve them in a subdir of my client's server.

**Comment by brillout** [comment]
@rhengles See https://github.com/vikejs/vike/issues/606.

**Comment by Eddie344** [comment]
> cross-env NODE_ENV=storybook && storybook dev -p 6006

Let me add: the script in package.json should look like this:
```
    "storybook": "cross-env NODE_ENV=storybook storybook dev -p 6006",
```

not this:
```
    "storybook": "cross-env NODE_ENV=storybook && storybook dev -p 6006",
```

(If someone's as dumb as I am :) )

**Comment by brillout** [comment]
@Eddie344 Curious: why do you set `NODE_ENV=storybook`? I couldn't see any mention of doing this in Storybook's docs.

**Comment by Eddie344** [comment]
> @Eddie344 Curious: why do you set `NODE_ENV=storybook`? I couldn't see any mention of doing this in Storybook's docs.

It's not my idea, I just use solution of issue's author. NODE_ENV is changed to avoid running vike plugin. I add my comment because I made a mistake and don't want anybody else made it 😄

**Comment by brillout** [comment]
[The workaround](https://github.com/vikejs/vike/issues/798#issuecomment-1531093835) isn't required anymore (Vike's Vite plugin now removes itself if it detects Storybook https://github.com/vikejs/vike/commit/98040abfd8eb895a7b7fb733b0bf618f7b1dd2ce).
