### ISSUE TITLE
Improve `throw RenderErrorPage()` documentation

### ISSUE THREAD

**Issue by brillout** [brillout/vite-plugin-ssr#801]
### Description

`throw RenderErrorPage()` has grown to become an increasingly powerful technique.
 - [x] ~~Prominently document it.~~ 
 - [ ] ~~Rename it to something else (since it can now also be used to redirect pages: https://vite-plugin-ssr.com/route-function#redirection-404).~~ Create a second utility `throw Redirect()`, make `redirectTo` a built-in property, and update all server integration examples. It's a common use case and its DX should be polished.
 - [x] ~~Check whether it works with Server Rotuing.~~ Should work (although I'd need to test it).

**Comment by SquirrelCoder** [comment]
Thank you very much for your hard work. 

I assume, there is also a bug in the documentation. Maybe you could fix it.

On this page: https://vite-plugin-ssr.com/route-function#redirection-404 the following code snippet did not work for me correctly: 

```
  throw RenderErrorPage({
    pageContext: {
      errorInfo: `Product with ID ${ productId } doesn't exist`
    }
  })
```

I had to change it to the following:

```
  throw RenderErrorPage({
    pageContext: {
      pageProps: {
        errorInfo: `Product with ID ${productId} doesn't exist`,
      },
    },
  });
```

After that, I was able to see the `errorInfo` prop in the vue Component.

Thanks again ❤️

**Comment by brillout** [comment]
@SquirrelCoder Indeed. Fixed https://github.com/brillout/vite-plugin-ssr/commit/7f6282b018e225468ad1bd069808c9ef0179ceaf. Thanks for the ping. I'm glad you're enjoying VPS, and if you think you can convince your employer: https://github.com/brillout/vite-plugin-ssr.

**Comment by brillout** [comment]
Closing in favor of https://github.com/brillout/vite-plugin-ssr/issues/926.
