### ISSUE TITLE
CLI stuck after build successful

### ISSUE THREAD

**Issue by reyamir** [brillout/vite-plugin-ssr#807]
### Description

my app is using pre-rendered mode, but when I run build, it stuck after pre-rendering html successful, in `dist` folder, I see all files are genereted, no error happend.

<img width="962" alt="Screenshot 2023-04-23 at 09 07 28" src="https://user-images.githubusercontent.com/123083837/233815666-24a203ad-6628-4436-ac36-149152098e71.png">

**Comment by reyamir** [comment]
I've found the problem and fixed it

**Comment by brillout** [comment]
> I've found the problem and fixed it

What was the problem?

**Comment by brillout** [comment]
(Re-opening as the pre-rendering process should show a warning instead of silently hanging.)

**Comment by reyamir** [comment]
ah, my code use `RelayProvider` to open websocket connect, in pre-rendering process, it open too and get stuck, so I've updated my code to make sure it only run on client

**Comment by sytabaresa** [comment]
Hi, it appears that this change makes that some plugins (in my case `vite-plugin-pwa`) doesn't execute anymore. Can
 we check this @brillout ?

`vite-plugin-ssr < 0.4.116`
![Screenshot from 2023-04-25 21-22-12](https://user-images.githubusercontent.com/2219914/234449980-1d83fb79-9813-4594-9533-8e1e8c2ec47f.png)

`vite-plugin-ssr >= 0.4.117`
![Screenshot from 2023-04-25 21-22-27](https://user-images.githubusercontent.com/2219914/234449975-94adcbe8-fb91-4c63-b4fe-ce69c62ff660.png)

**Comment by brillout** [comment]
Can you publish a reproduction?

**Comment by brillout** [comment]
@sytabaresa Try `0.4.117-draft.42785` and if that doesn't work then I'll need a reproduction.

**Comment by brillout** [comment]
@sytabaresa Try `0.4.117-draft.92725` instead.

**Comment by sytabaresa** [comment]
No, It's not working with that version :(

I will prepare an example project to reproduce this

**Comment by sytabaresa** [comment]
All right. [Here](https://github.com/sytabaresa/vite-ssr-project ) we can see that. Is a raw project created with `yarn create vite-plugin-ssr` but with `vite-plugin-pwa` installed and configured.

If you use `0.4.115` you can see that in the output log the PWA plugin was used and a `sw.js` file is generated in `dist`.
But with a recent version (including `0.4.118`) the plugin isn't executed and the `sw.js` file is not generated.

 It appears that only occurs in **prerender mode** (`prerender: true` option in `ssr` function ).

**Comment by brillout** [comment]
Fix released in `0.4.118-draft.88304`.

Btw. in case you think you can convince your employer: https://github.com/sponsors/brillout.
