### ISSUE TITLE
Uncaught (in promise) Error: [vite-plugin-ssr@0.4.112][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. 

### ISSUE THREAD

**Issue by ahassan24** [brillout/vite-plugin-ssr#823]
### Description

My application works fine in localhost client side, but on server side the objects does not load .
For ex:  I am trying to display a dropdown and i am setting my object in :options in select dropdown.
But the dropdown is blank.
please check the screenshot for reference.
and fyi i am using client side framework and dropdown will be only shown when object is in below format.
[
     { label: "xx", value: "xxxx" },
    { label: "yy", value: "yyyy" },
]
[](![image](https://user-images.githubusercontent.com/54981547/234573788-6066c17e-67af-46de-afac-48acd00f2ecd.png))

### Error Message + Error Stack

```shell
caught (in promise) Error: [vite-plugin-ssr@0.4.112][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Go to https://github.com/brillout/vite-plugin-ssr/issues/new and copy-paste this error. (The error's stack trace is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes vite-plugin-ssr more robust.
    at getPageContextSerializedInHtml.js?v=a0626ffe:38:9
    at Array.map (<anonymous>)
    at getPageContextsSerializedInHtml (getPageContextSerializedInHtml.js?v=a0626ffe:36:41)
    at getPageContexts (getPageContext.js?v=a0626ffe:20:26)
    at hydrate (entry.js:15:40)
    at entry.js:9:1
```

**Comment by ahassan24** [comment]
function getPageContextSerializedInHtml() {
    var _a;
    const pageContextJson = (_a = getPageContextElement().item(0)) === null || _a === void 0 ? void 0 : _a.textContent;
    return preparePageContext(pageContextJson);
}
function getPageContextsSerializedInHtml() {
    const pageContextJsons = getPageContextElement();
    return Array.from(pageContextJsons).map(pageContextJson => {
        const pageContext = preparePageContext(pageContextJson.textContent);
        assert(hasProp(pageContext, 'tefConfig', 'object'));
        return pageContext;
    });
}

**Comment by ahassan24** [comment]
import { parse } from '/@fs/D:/projectname/apps/typescript/node_modules/@brillout/json-serializer/dist/esm/parse.js?v=a0626ffe';
import { hasProp, objectAssign, assert } from '/@fs/D:/SCS_Project/scs-204-checkout/apps/typescript/node_modules/@mfe/tef-vite-plugin-ssr/dist/esm/client/utils.js?v=a0626ffe';
export { getPageContextSerializedInHtml, getPageContextsSerializedInHtml };
function preparePageContext(pageContextJson) {
    assert(pageContextJson);
    const parseResult = parse(pageContextJson);
    assert(hasProp(parseResult, 'pageContext', 'object'));
    const { pageContext } = parseResult;
    assert(hasProp(pageContext, '_pageId', 'string'));
    /*
    if ('_serverSideErrorWhileStreaming' in pageContext) {
      const err = getProjectError(
        `An error occurred on the server while rendering/streaming to HTML. Check your server logs.`
      )
      throw err
    }
    */
    objectAssign(pageContext, {
        _pageContextRetrievedFromServer: { ...pageContext },
        _comesDirectlyFromServer: true
    });
    return pageContext;
}
function getPageContextElement() {
    // instead of an id-based dom element we are searching for a specific class since
    // there could be multiple page contexts when rendering micro-frontends
    return document.getElementsByClassName('vite-plugin-ssr_pageContext');
}
function getPageContextSerializedInHtml() {
    var _a;
    const pageContextJson = (_a = getPageContextElement().item(0)) === null || _a === void 0 ? void 0 : _a.textContent;
    return preparePageContext(pageContextJson);
}
function getPageContextsSerializedInHtml() {
    const pageContextJsons = getPageContextElement();
    return Array.from(pageContextJsons).map(pageContextJson => {
        const pageContext = preparePageContext(pageContextJson.textContent);
        assert(hasProp(pageContext, 'tefConfig', 'object'));
        return pageContext;
    });
}

**Comment by brillout** [comment]
I’ll need a reproduction

**Comment by brillout** [comment]
Closing as it seems like there is some weird patching going on.

I'll re-open if I'm provided with a reproduction.
