### ISSUE TITLE
V1: Config set via +config does not override convenience file

### ISSUE THREAD

**Issue by dajinchu** [brillout/vite-plugin-ssr#831]
### Description

If I have a config defined via convenience file, such as `renderer/+onHydrationEnd.ts`, I am able to override it on a per-route basis by defining `pages/index/+onHydrationEnd.ts`. 

However, if I define `onHydrationEnd` inside a `pages/index/+config.ts` file, it does not override the one in `renderer`.

It seems like convenience files are taking too much precedence?

[reproduction](https://github.com/brillout/vite-plugin-ssr/compare/main...dajinchu:vite-plugin-ssr:dc/config-cannot-override-convenience)

In reproduction, I would expect to see `override` logged to console, but it doesn't. I also confirmed that deleting `renderer/+onHydrationEnd.ts` allows the override to come through.

**Comment by brillout** [comment]
Let me have a look.

**Comment by brillout** [comment]
I could reproduce. Let me fix this.

**Comment by brillout** [comment]
Fix released in `0.4.120`.
