### ISSUE TITLE
Cannot trigger page redirection in onBeforeRender on each page V1 Design

### ISSUE THREAD

**Issue by harrytran998** [brillout/vite-plugin-ssr#832]
### Description

![image](https://user-images.githubusercontent.com/24296018/235338239-d57f3759-40ae-4ab1-99bd-1cf16c59b996.png)

In the docs, I see the way to redirect on the server in `+onBeforeRender.ts` file. But our code meets the condition needs to redirect --> Not redirect.

Im using the latest VPS version.

If you have any questions, please let me know 🙏.

**Comment by brillout** [comment]
Have you integrated the actual redirection onto your server?

**Comment by brillout** [comment]
Closing in favor of https://github.com/brillout/vite-plugin-ssr/issues/835. But let me know if you believe it's an issue beyond documentation and I'll re-open.
