### ISSUE TITLE
`vite@2.3.5`: `import_meta.glob is not a function`

### ISSUE THREAD

**Issue by brillout** [brillout/vite-plugin-ssr#85]
The latest Vite release `vite@2.3.5` breaks and the browser throws `Uncaught TypeError: import_meta.glob is not a function`.

Seems to be related to the `esbuild` major update.

https://github.com/vitejs/vite/issues/3617

In the meatime stick to `vite@2.3.4`.

**Comment by cedric25** [comment]
After running a `npm init vite-plugin-ssr@latest`, I'm also getting this same error:
```
pageFiles.ts:5 Uncaught TypeError: import_meta.glob is not a function
    at pageFiles.ts:5
```
And nothing happens when clicking on the Counter.

I've tried with node 16 / vue-ts, node 14 / vue, node 14 / react, same problem.
I also tried to bump `vite` to `2.6.2`.
Not sure what I did wrong.

**Comment by brillout** [comment]
@cedric25 I'm having a look

**Comment by brillout** [comment]
I can reproduce

**Comment by brillout** [comment]
Temporary solution: pin to `"vite": "2.5.10"` (note the missing `^`).

**Comment by brillout** [comment]
It's not the same issue, closing in favor of https://github.com/brillout/vite-plugin-ssr/issues/156
