### ISSUE TITLE
config.page.server.mdx / Config.page.server.mdx in the git repo

### ISSUE THREAD

**Issue by vchirikov** [brillout/vite-plugin-ssr#850]
### Description

Hi @brillout ,

Some filesystems (NTFS, fat, exFat) is case-insensitive, thus [config.page.server.mdx](https://github.com/brillout/vite-plugin-ssr/blob/main/docs/pages/config.page.server.mdx)
[Config.page.server.mdx](https://github.com/brillout/vite-plugin-ssr/blob/main/docs/pages/Config.page.server.mdx) conflicts on these FS.

Could you rename one of them?

**Comment by brillout** [comment]
👍

Curious: what happens when you `git clone`? Does it error out already? What's the error?
