### ISSUE TITLE
[VPS 0.4.121 - latest] +config.ts not respect alias import

### ISSUE THREAD

**Issue by harrytran998** [brillout/vite-plugin-ssr#852]
### Description

When I tried to import a custom layout in a specific page --> Impor that layout in `+config.ts` with alias(auto import from VsCode) ---> Not work.

The field config in pageContext will display like this `Layout: '_import:#/layout/LayoutMain:default'`. Normally, must be displayed like `[Function: Mainlayout]`.

But when I tried to import with `../../layout/LayoutMain.tsx` --> Worked. Hope you can take a look

**Comment by brillout** [comment]
That's very much possible. (And it's actually also on my to-do list to support aliases 🙂). Let me have a look.

**Comment by brillout** [comment]
Fix released in `0.4.122`.
