### ISSUE TITLE
Discord Bot [Contribution Welcome]

### ISSUE THREAD

**Issue by brillout** [brillout/vite-plugin-ssr#860]
### Description

Create a new Discord Server for Vike, and use/create a Discord bot to teach users about https://github.com/brillout/vite-plugin-ssr/discussions/526.

Having a cozy firechat-like place to casually chit-chat about general topics could be lovely. Example use cases:
 - Show us what you're building (startup, dev tool, Vike extension, etc.)
 - Philosophical discussions about the future of programming and/or Vike (e.g. vertical integration vs do-one-thing-do-it-well)
 - News
 - Etc.

It's paramount that users don't ask for help in that space. Therefore I think a bot is necessary to to prominently show the rules of https://github.com/brillout/vite-plugin-ssr/discussions/526 with maybe (if possible?) a checkbox "I've read the rules" that users have to check before being able to start chatting.

Contribution much welcome to point us to a Discord bot that does this, or maybe implement one? I'm unfamiliar with Discord's bot API.

**Comment by samuelstroschein** [comment]
I express interest in such a bot for inlang

**Comment by brillout** [comment]
Closing as we don't need this anymore.
