### ISSUE TITLE
`vite-plugin-ssr:extractExportNames` error when running `vite build` on the latest version 0.4.123.

### ISSUE THREAD

**Issue by graphite-admin** [brillout/vite-plugin-ssr#864]
### Description

Encountered this error when running `vite build`. Interestingly `vite dev` runs perfectly fine. The stack trace doesn't really allow me to debug the issue, and directs me to raise an issue here. Hopefully it's a quick fix.

I'm happy to dive in further but some direction would be nice. Thanks for the effort you've put into this plugin, it truly is special.

```txt
[vite-plugin-ssr:extractExportNames] [vite-plugin-ssr@0.4.123][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Go to https://github.com/brillout/vite-plugin-ssr/issues/new and copy-paste this error. (The error's stack trace is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes vite-plugin-ssr more robust.
file: /Users/ecrive/Workspace/company-project/docs/pages/index.page.mdx?extractExportNames&lang.mdx
error during build:
Error: [vite-plugin-ssr@0.4.123][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Go to https://github.com/brillout/vite-plugin-ssr/issues/new and copy-paste this error. (The error's stack trace is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes vite-plugin-ssr more robust.
    at addQuery (/Users/ecrive/Workspace/company-project/node_modules/.pnpm/vite-plugin-ssr@0.4.123_vite@4.3.5/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/plugins/extractExportNamesPlugin.js:68:28)
    at /Users/ecrive/Workspace/company-project/node_modules/.pnpm/vite-plugin-ssr@0.4.123_vite@4.3.5/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/plugins/extractExportNamesPlugin.js:49:63
    at Array.map (<anonymous>)
    at getCode (/Users/ecrive/Workspace/company-project/node_modules/.pnpm/vite-plugin-ssr@0.4.123_vite@4.3.5/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/plugins/extractExportNamesPlugin.js:47:48)
    at getExtractExportNamesCode (/Users/ecrive/Workspace/company-project/node_modules/.pnpm/vite-plugin-ssr@0.4.123_vite@4.3.5/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/plugins/extractExportNamesPlugin.js:42:18)
    at async Object.transform (/Users/ecrive/Workspace/company-project/node_modules/.pnpm/vite-plugin-ssr@0.4.123_vite@4.3.5/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/plugins/extractExportNamesPlugin.js:21:30)
    at async transform (file:///Users/ecrive/Workspace/company-project/node_modules/.pnpm/rollup@3.21.5/node_modules/rollup/dist/es/shared/node-entry.js:23524:16)
    at async ModuleLoader.addModuleSource (file:///Users/ecrive/Workspace/company-project/node_modules/.pnpm/rollup@3.21.5/node_modules/rollup/dist/es/shared/node-entry.js:23730:30)
```

**Comment by brillout** [comment]
Add following line before line `68` of `/Users/ecrive/Workspace/company-project/node_modules/.pnpm/vite-plugin-ssr@0.4.123_vite@4.3.5/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/plugins/extractExportNamesPlugin.js`:

```diff
    else {
        const fileExtension = (0, utils_1.getFileExtension)(moduleName);
+       console.log(moduleName);
        (0, utils_1.assert)(fileExtension);
        moduleName = `${moduleName}?extractExportNames&lang.${fileExtension}`;
    }
```

And report back the output.

**Comment by graphite-admin** [comment]
Okay, that helped thanks. Perhaps an issue on my side but would be glad to hear your thoughts.

The `moduleName` was `../Layout` which makes sense, as my code has a vite plugin to automatically inject: 

```
export * from "../Layout
```

At the end of MDX files. 

Normally `vite` would resolve such an import in the transpiled code to the correct extension, which in this case should resolve to `../Layout.tsx`. I'm happy to always use extensions, since the goal of my current project is to enforce very strict conventions, but I think it will be fairly common that imports may not contain an extension.

As an aside, placing a `console.log` statement actually resulted in another error: 

```
[vite-plugin-ssr:extractExportNames] console.log(...) is not a function
```

I had to use VS Code's debugger to figure out the module name

**Comment by brillout** [comment]
I see. I'll write a fix tomorrow.

**Comment by brillout** [comment]
While a fix is implementable, it isn't completely trivial. Also, the code causing the bug is going to be removed soon (the V1 design doesn't use that code).

Thus, instead of fixing the bug, let me suggest using one of the following workarounds:
 1. Add the file extension to your import statement:
    ```diff
    - export * from '../Layout'
    + export * from '../Layout.jsx'
    ```
 2. Or, use named re-exports instead of a wildcard re-export:
    ```diff
    - export * from '../Layout'
    + export { Layout1, Layout2 } from '../Layout'
    ```
 3. Or, use the [V1 design](https://vite-plugin-ssr.com/migration/v1-design).


Any of these should workaround the bug. But let me know if you still run into any issues.

> Usually, vite-plugin-ssr cares a lot about being bug-free. This is the only exception of a known bug being temporarily tolerated.
