### ISSUE TITLE
escapeInject renders the page in an incorrect way

### ISSUE THREAD

**Issue by SquirrelCoder** [brillout/vite-plugin-ssr#865]
### Description

So, today I did another experiment with VPS and `vueuse/head` and I stumbled upon a very interesting issue or maybe feature 🤔. 

I have integrated the latest version of `vueuse/head` into VPS.

I render the page on the server like the following:

```
const { app, store, head } = createApp(pageContext);
const stream = await renderToNodeStream(app);
const initialStoreState = store.state.value;
const { headTags } = await renderHeadToString(head)

const documentHtml = escapeInject`<!DOCTYPE html>
    <html>
      <head>
      ${ headTags }
      </head>
      <body>
        <div id="app">${ stream }</div>
      </body>
    </html>`;
```

This works, but the `headTags` are **also** rendered in the body-Tag `<body>...</body>` when the page is rendered on the client.

I've changed the above snippet to the following:

```
  const { app, store, head } = createApp(pageContext);
  const { headTags } = await renderHeadToString(head)
  const initialStoreState = store.state.value;
  const appHTML = await renderToString(app)
  const documentHtml = dangerouslySkipEscape(`<!DOCTYPE html>
    <html>
      <head>
      ${ headTags }
   </head>
      <body>
        <div id="app">${ appHTML }</div>
      </body>
    </html>`);
```

And interestingly this works as expected and the tags are rendered correctly on the website and on the server.

I am under the assumption, that `escapeInject` does something (in)correctly, which renders the page like this, because it does not happen with `dangerouslySkipEscape`.

**Reproduction Repo: https://github.com/SquirrelCoder/vps-error-repo**

[I have commented out the second code snippet that works](https://github.com/SquirrelCoder/vps-error-repo/blob/ba4892fec8df72af25c51ba965deea61e3912586/renderer/%2BonRenderHtml.ts#L39)

Thanks a lot ❤️

**Comment by brillout** [comment]
Thanks for the bug report. I'll have a look at it. Apologies for the late reply, I thought it was a discussion and not a bug.

**Comment by SquirrelCoder** [comment]
Hi, thank you very much, you are the best. 
I'm sorry for the dumb question.

**Comment by brillout** [comment]
No problem.

I think I told you already but in case I didn't: https://github.com/sponsors/brillout &mdash; if you think you can convince your employer.

**Comment by brillout** [comment]
FYI the next vite-plugin-ssr version will warn the user when this happens.
