### ISSUE TITLE
Import mapping

### ISSUE THREAD

**Issue by brillout** [brillout/vite-plugin-ssr#87]
Some users, e.g. @LydiaF @felixakiragreen, seem to have problems with import mapping.

What makes you think that this is related to SSR or `vite-plugin-ssr`? AFAICT it's not related.

**Comment by felixakiragreen** [comment]
The only reason I think it is related to `vite-plugin-ssr` is that it was working when I just using a normal SPA. 

But the I wanted to convert my site to being SSR. So I followed all the steps, started the server, but when open localhost it says: "Cannot GET /" and the console says:

```
Server running at http://localhost:3000
Error: Failed to resolve import "@/components" from "src/pages/_default.page.server.tsx". Does the file exist?
```

**Comment by brillout** [comment]
I see. I will have a look.

**Comment by felixakiragreen** [comment]
After about 10 hours, I gave up trying to get SSR working. I'm just going to live without it.

Wanted to let you know so you don't waste too much time trying to get this to work.

**Comment by brillout** [comment]
> After about 10 hours

Sorry about that.

You care that much about import mapping that you are willing to give up SSR because of it? I'm curious.

I actually plan to look at it today.

**Comment by brillout** [comment]
I cannot reproduce any problem with Vite's `resolve.alias` while using `vite-plugin-ssr`.

Working example: [/examples/import-paths-alias-mapping/](examples/import-paths-alias-mapping/).

I've added docs about import mapping: https://github.com/brillout/vite-plugin-ssr#import-paths-alias-mapping

**Comment by brillout** [comment]
Updated the docs and example to showcase how to add path aliases for files that are not processed by Vite.

Let me know if that works for you.

**Comment by chrisvariety** [comment]
There's no problem w/ import mapping following the pattern outlined in https://github.com/brillout/vite-plugin-ssr#import-paths-alias-mapping

I was previously using https://github.com/aleclarson/vite-tsconfig-paths & ran into issues with that, but there's really no need to use that at all?

**Comment by brillout** [comment]
> I was previously using https://github.com/aleclarson/vite-tsconfig-paths & ran into issues with that, but there's really no need to use that at all?

@yoroshikun also had problems with `vite-tsconfig-paths`. Yes it's not needed; it's just a little convenience to skip having to define path aliases twice at `tsconfig.json#compilerOptions.paths` and `vite.config.js#resolve.alias`.

**Comment by brillout** [comment]
Closing this as I believe the docs to now fully cover how to achieve import path aliases.
