### ISSUE TITLE
Package subpath './types' is not defined by "exports"

### ISSUE THREAD

**Issue by galimovkirill** [brillout/vite-plugin-ssr#888]
### Description

Error while import type from `vite-plugin-ssr/types` folder (as described in warning):
![Снимок экрана 2023-05-16 в 13 22 08](https://github.com/brillout/vite-plugin-ssr/assets/55671052/d803b91f-c933-4984-9d72-45c43dc5a24e)

![Снимок экрана 2023-05-16 в 13 14 48](https://github.com/brillout/vite-plugin-ssr/assets/55671052/6e4e8e1e-9f70-4691-b798-e78f5c2d0192)
P.S adding `type` prefix for import has no effect

This works fine for me:
`import { PageContextBuiltIn } from 'vite-plugin-ssr/dist/types/shared/types';`

Node version: v16.20.0
TypeScript version: v4.9.5

**Comment by brillout** [comment]
That's quite unexpected. Can you publish a reproduction?

**Comment by brillout** [comment]
I'll re-open if I can get my hands on a reproduction.
