### ISSUE TITLE
The `data-prefetch` attribute is outdated.

### ISSUE THREAD

**Issue by vchirikov** [brillout/vite-plugin-ssr#889]
### Description

Hi,
Today in v1 the [data-prefetch attribute is outdated](https://github.com/brillout/vite-plugin-ssr/blob/79c396a55cedb5f115b9a66701c23fdcf628facd/vite-plugin-ssr/client/router/prefetch/getPrefetchConfig.ts#L76), but I didn't find anything in the v1 docs to disable prefetch on a single link. From docs/assert isn't clear, which attribute should be used or it will be removed at all.

**Comment by brillout** [comment]
Indeed, the docs are outdated. What's your use case for disabling prefetching on a single link?

**Comment by vchirikov** [comment]
Links which change i18n locale, I think they shouldn't prefetch anything without user click.

**Comment by brillout** [comment]
I'll release it later today/tomorrow.
