### ISSUE TITLE
`import { navigate }` internal assertion failed

### ISSUE THREAD

**Issue by chrisvariety** [brillout/vite-plugin-ssr#91]
(congrats on the 0.1.0 release!)

Happy to put together a sandbox/repro, just let me know.

Code like this is failing for me, not within vite itself, but within my test suite (`jest`):

`import { navigate } from 'vite-plugin-ssr/client/router';`

```
    [vite-plugin-ssr@0.1.0][Internal Failure] You stumbled upon a bug in `vite-plugin-ssr`'s source code (an internal assertion failed). This should definitely not be happening, and you should create a new issue at https://github.com/brillout/vite-plugin-ssr/issues/new that includes this error stack (the error stack is enough to debug this). Or reach out on Discord. A fix will be written promptly.

      at Object.<anonymous> (node_modules/vite-plugin-ssr/client/router/index.node.ts:5:1)
      at Object.<anonymous> (node_modules/vite-plugin-ssr/client/router/index.js:2:18)
      at Object.<anonymous> (pages/session.page.tsx:29:1)
      at Object.<anonymous> (pages/__tests__/session.page.spec.tsx:2:1)
```

It seems like `vite-plugin-ssr/client/router` could either resolve to `index.js` or `index.ts`, and certain environments will prefer the `index.js`, which trips this internal assertion.

**Comment by brillout** [comment]
Is this happening on a speical CI env or locally on your machine?

Something's weird with your CI env, see `node_modules/vite-plugin-ssr/client/router/index.js:2`:

```js
module.exports = require('../../dist/cjs/client/router/index.node.js')
```

So it should load `node_modules/vite-plugin-ssr/dist/cjs/client/router/index.node.js` but surprisingly your env is loading `node_modules/vite-plugin-ssr/client/router/index.node.ts` instead.

Does your env change the `require` behavior? Node.js version?

> congrats on the 0.1.0 release!

Thanks :-)

**Comment by chrisvariety** [comment]
node v14.16.1

Here's what I think is a trivial reproduction, tho the stack trace is weird on code sandbox: https://codesandbox.io/s/red-bash-2mob5?file=/src/index.ts

As far as I can tell this will occur when using babel to transpile/execute `import { navigate } from 'vite-plugin-ssr/client/router';`. I know it's a bit weird to use babel with this library (since vite is powered by esbuild), but a lot of testing libraries (particularly `jest`) use babel internally to execute tests in isolation, and vite doesn't have a [first class jest integration](https://github.com/vitejs/vite/issues/1955) quite yet.

**Comment by brillout** [comment]
So your goal is to unit test a component? Do you want to then also test the `naviagte()` function?

I'll have a look at why Babel transpiles erroneously.

**Comment by chrisvariety** [comment]
You got it! Not planning to test `navigate()` at this time, it's just included on the component.

**Comment by brillout** [comment]
Then simply removing the `assert(isNodejs())` will likely solve the problem.

Let me first have a look at how Babel transpiles, to see if it's a bug on `vite-plugin-ssr`'s part or on Babel's part.

Note that for testing `navitage()` you'll need to use Vite instead of Babel.

**Comment by chrisvariety** [comment]
Sounds good. Yeah, that would be more of an end to end test, I'm more trying to check the component renders properly with various props.

**Comment by brillout** [comment]
Let me know if you still encouter problems.

Btw. I'm curious: how has Vite been working out for you so far?

**Comment by brillout** [comment]
> it's just other tools that need to catch up

If you don't mind me asking: what tools have been difficult to use with Vite? Other than Jest.

**Comment by chrisvariety** [comment]
Storybook comes to mind: https://storybook.js.org

Everything is very "experimental" "early stages" etc. https://github.com/eirslett/storybook-builder-vite

Deno comes to mind as well... https://github.com/vuejs/vite/issues/109

**Comment by brillout** [comment]
I see, thanks.

**Comment by brillout** [comment]
The lead seems quite pushy about supporting Vite https://github.com/storybookjs/storybook/issues/14024. Probably only a question of time.

As for Deno, it's more a Deno problem if you ask me. Deno is just too much of a drastic change for the ecosystem willing to migrate. The only *real* benefit of Deno is the ability the run scripts with lesser permissions, which so far hasn't been a USP enough to justify migration cost. Hopefully things will change, I like Deno.

Let me know if you have further integration problems.

**Comment by brillout** [comment]
(I care a lot about smooth integrations.)
