### ISSUE TITLE
urlParsed.search is empty in prerender mode

### ISSUE THREAD

**Issue by philwinder** [brillout/vite-plugin-ssr#917]
### Description

Hi again, firstly thanks for the fix in #2784ac9. urlParsed is now making its way into the prerender build.

However, I have a follow-on problem. Take a look at the code below:

https://github.com/brillout/vite-plugin-ssr/compare/main...philwinder:vite-plugin-ssr:main?expand=1

In this code I have enabled prerendering, added the usual `usePageContext` script and added the `PageContextProvider`, like in the full react demo.

If you run this example with `yarn dev` and browse to http://localhost:3000/?hello=world#hash-hash then you will see:
```
pageContext.urlParsed: { "origin": null, "pathname": "/", "pathnameOriginal": "/", "search": { "hello": "world" }, "searchAll": { "hello": [ "world" ] }, "searchOriginal": "?hello=world", "hash": "", "hashOriginal": null }
```

But if you run `yarn preview` and browse to the same URL you will see:
```
pageContext.urlParsed: { "origin": null, "pathname": "/", "pathnameOriginal": "/", "search": {}, "searchAll": {}, "searchOriginal": null, "hash": "", "hashOriginal": null }
```

Note how the search* fields are now null, even though they work in dev. Also note how hash doesn't seem to work in either (according to my understanding of what hash should do).

I can't immediately see why this is; I suspect it's being overwritten somewhere else?

Thanks, Phil

**Comment by brillout** [comment]
That's possible. Let me have a quick look.

**Comment by brillout** [comment]
Just checked and VPS actually does preserve the original URL.

Did you provide the search params in your `prerender()` hook(s)? The search params can't be created out of thin air.

**Comment by philwinder** [comment]
You mean in a `onPagePrerender` hook? I'm scared of that because of the:
> DON'T use this option without having contacted a vite-plugin-ssr maintainer

I'll take a look and report back. Thanks.

**Comment by philwinder** [comment]
I tried to add this to [my test repo in a new commit](https://github.com/brillout/vite-plugin-ssr/commit/db8c0ca394d7a253a676990a0a51ee0a5c2e73f7) but it didn't make any difference.

Can you provide a bit more guidance?

**Comment by brillout** [comment]
I mean the prerender() hook

**Comment by philwinder** [comment]
I'm sorry, maybe I'm missing something, but why do I need to call the `prerender` hook? That's used to tell the plugin what _extra_ pages to build, right? I don't have any `@id` pages or anything like that. Just normal index pages like in the example at the top.

As you can see in the example, it works in dev mode, so IMO I would have expected it to work in prerender/preview mode too. 

Reading back, I think there's a misunderstanding. I'm not _creating_ the search params.

I'm passing the query params in the URL like this: `curl http://localhost:3000/?hello=world`

Then I want to parse and read the query params. I could do that myself by parsing the `window.location.href` but I thought they were already parsed as part of the `pageContext`. They are in dev mode, not in prerender mode.

Make sense?

**Comment by philwinder** [comment]
FYI I worked around this with this:
```
  React.useEffect(() => {
    const params = new URLSearchParams(window.location.search);
    const id = params.get('id');
```

Possibly simpler than doing this in the context anyway...

**Comment by brillout** [comment]
`useEffect()` is actually the right way of doing it because, otherwise, you'd get a hydration mismatch.

`pageContext` is meant for rendering and *only* for rendering. When using pre-rendering you render at built-time and the search params don't exist at build-time.

**Comment by philwinder** [comment]
Perfect. That was this bit of information I was missing. I'll add a PR to add this note to the docs.

Thanks for your help!
