### ISSUE TITLE
Add option to change WebSocket port (Can't run two (2) apps simultaneously)

### ISSUE THREAD

**Issue by CGuiho** [brillout/vite-plugin-ssr#921]
## Context
I am trying out vite-plugin-ssr, so I created 2 apps (vue-ts & react-ts).

## Problem
I can't run both apps simultaneously. When I run `npm run dev` on the second app I get an error:
```
WebSocket server error: Port is already in use
```
### Full
```
npm run dev
> dev
> npm run server
> server
> ts-node ./server/index.ts
WebSocket server error: Port is already in use
Server running at http://localhost:6000
```
If I open  `localhost:6000`, nothing is runnig there, but the first app run nicely.

## Reproduction
Create `vite-plugin-ssr`  with `vue-ts`. (app-1)
Open `server/index.ts` change the port to `5000`.
Run the `app-1` - works nicely. (app runs on 5000)

Create `vite-plugin-ssr`  with `react-ts`. (app-2)
Open `server/index.ts` change the port to `6000`.
Run the `app-2` - does not run. Gives the error above.

## Conslusion
I think the WebSocket server of each app use the same port, so I need a way to configure the WebSocket port.

## Environment
`node -v`: 16.20.0

**Comment by brillout** [comment]
It's a Vite thing.

Closing; create a ticket over at Vite instead.

**Comment by CGuiho** [comment]
Thanks for the fast response.

**Comment by CGuiho** [comment]
Fixed the problem by adding `server.hrm.port` to `vite.config.ts`:

```ts
const config: UserConfig = {
  plugins: [react(), ssr()],
  server: {
    hmr: {
      port: 4500 // 👈
    }
  }
}
```
