### ISSUE TITLE
What's wrong? Should I care about?

### ISSUE THREAD

**Issue by PengKen** [brillout/vite-plugin-ssr#922]
### Description

 vite build --ssrManifest --outDir dist/client

vite v4.3.9 building for production...
✓ 121 modules transformed.
dist/client/vite-plugin-ssr.json                      0.16 kB │ gzip:  0.14 kB
dist/client/manifest.json                             0.89 kB │ gzip:  0.28 kB
dist/client/ssr-manifest.json                        10.54 kB │ gzip:  1.32 kB
dist/client/assets/entry-server-routing.6fd316bf.js   1.82 kB │ gzip:  1.01 kB
dist/client/assets/chunks/43a2a681.js                26.66 kB │ gzip:  9.40 kB
dist/client/assets/entry-client-routing.0142b296.js  33.87 kB │ gzip: 11.33 kB
dist/client/assets/src/home/index.page.05936c74.js   51.85 kB │ gzip: 21.01 kB
Error: [vite-plugin-ssr@0.4.101][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Go to https://github.com/brillout/vite-plugin-ssr/issues/new and copy-paste this error (the error alone is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes vite-plugin-ssr more robust.

**Comment by brillout** [comment]
What’s the error stack trace?

**Comment by brillout** [comment]
I couldn't reproduce with the boilerplates.

I'll re-open if I'm provided with a reproduction or a stack trace.

**Comment by brillout** [comment]
> [vite-plugin-ssr@0.4.101]

Also make sure to update to the latest version.
