### ISSUE TITLE
`[vite] Error when evaluating SSR module`, `SyntaxError: Unexpected token '.'`

### ISSUE THREAD

**Issue by brillout** [brillout/vite-plugin-ssr#94]
Follow up of https://github.com/brillout/vite-plugin-ssr/issues/93#issuecomment-860040841.

@Dema

Does `rm -r ./node_modules/.vite/` get rid of the error?

I couldn't reproduce with following steps.

```shell
1. Run  `yarn create vite-plugin-ssr`
2. Select `react-ts`
3. `cd vite-project`
4. Move pages to ./src/pages
5. `yarn install`
6. Run `yarn dev`
7. Open http://localhost:3000/
```

**Comment by Dema** [comment]
Damn it, node v12 struck again!. It works on v14.  I had similar issue on my laptop and I think created an issue for this plugin with some other cryptic error that was caused by incompatibilities of vite with node v12. And now I moved to my work computer and completely forgot about v12 issue

Maybe we should add 
```json
{ 
  "engines" : { 
    "node" : ">=14.0.0" 
  }
}
```

**Comment by brillout** [comment]
What `v12` version were you on?

Currently:

```
{ 
  "engines" : { 
    "node" : ">=14.0.0" 
  }
}
```

Maybe that's outdated; Vite had lot's of changes recently that could have regressed Node version compability.

**Comment by Dema** [comment]
I was on latest in Arch `community/nodejs-lts-erbium 12.22.0-2`

**Comment by brillout** [comment]
I just checked and Vite does support the latest v12 version (https://github.com/vitejs/vite/blob/9703bcd7e594769792779306f8f978dcc010d92f/.github/workflows/ci.yml#L20).

I'll have a look at what could have caused v12 to choke.

**Comment by brillout** [comment]
Typo in my pre-previous message; it's currenlty

```json
{ 
  "engines" : { 
    "node" : ">=12.19.0" 
  }
}
```

**Comment by Dema** [comment]
this was my previous issue with exact same problem :) https://github.com/brillout/vite-plugin-ssr/issues/77

**Comment by brillout** [comment]
Hm, I cannot reproduce with `v12.22.1`, also on Linux. I'll investigate more if someone else runs into this.

No progress after all 😀.

**Comment by brillout** [comment]
You can now use the latest boilerplate which now works with Node v12 `$ npm init vite-plugin-ssr@latest`.

**Comment by cmmartin** [comment]
I randomly started getting this error in a project that worked previously for weeks. AFAIK nothing changed on my end

```
$ node -v
v15.4.0
```

**Comment by brillout** [comment]
@cmmartin What's your stack trace?

**Comment by cmmartin** [comment]
```
SyntaxError: Unexpected token '.'
    at new AsyncFunction (<anonymous>)
    at instantiateModule (/Users/charlie/Projects/editor/node_modules/vite/dist/node/chunks/dep-36bf480c.js:75139:28)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
```

Not super useful. Looking at the line number referenced (`75139`), I see...

```
$ sed -n 75139p /Users/charlie/Projects/editor/node_modules/vite/dist/node/chunks/dep-36bf480c.js

        const initModule = new AsyncFunction(`global`, ssrModuleExportsKey, ssrImportMetaKey, ssrImportKey, ssrDynamicImportKey, ssrExportAllKey, result.code + `\n//# sourceURL=${mod.url}`);
```

**Comment by cmmartin** [comment]
Ok @brillout, I figured it out...

The file that was throwing (`Typography.ts`) looked something like this...

```javascript
import modularScale from './modularScale'

export default class Typography {
    constructor () {
        this.modularScale = modularScale(...)
    }
}
```

The fix was to simply rename the imported module (moduleScale --> ms), so it doesn't conflict with the class property name...

```javascript
import ms from './modularScale'

...
this.modularScale = ms(...)
```

I can't explain why this fixes it exactly, but there was clearly some kind of naming conflict between the exported module's property name and the imported module name

**Comment by brillout** [comment]
Seems like a bug on Vite's or Node.js's side. Anyways good to know; thanks for reporting back.
