### ISSUE TITLE
bundle size is too large

### ISSUE THREAD

**Issue by cbbfcd** [brillout/vite-plugin-ssr#952]
### Description

esbuild bundle analyze:

<img width="1595" alt="image" src="https://github.com/brillout/vite-plugin-ssr/assets/20987775/c9b6dd30-fe5e-4c8c-9f16-a303dfbc9ebf">

**Comment by brillout** [comment]
Closing in favor of https://github.com/brillout/vite-plugin-ssr/issues/951.

FYI:

> the currently bundle size (minified & gzipped) turns out to be 11kb with client-side routing disabled and 20kb with it enabled

I agree it's still too big though.

**Comment by brillout** [comment]
> Am I configuring something wrong?
> 
> I used `esbuild` to package the worker and got a bundle size of `600kb`, of which the `vps` took up `140kb+`

Can you configure it to display a break down showing the size of each file summing up to `140kb+`?

**Comment by cbbfcd** [comment]
<img width="1668" alt="image" src="https://github.com/brillout/vite-plugin-ssr/assets/20987775/04e74658-623d-4240-9913-eef70592cb5f">

my esbuild config:
```js
treeShaking: true,
    splitting: false,
    minify: !isDev,
    platform: "browser",
    conditions: ["worker", "browser"],
    format: "esm",
    target: "es2020",
```

**Comment by brillout** [comment]
That's the server-side which is expected to be *much* larger than what is being loaded on the client-side.

As for CJS, I actually found a neat way to publish only ESM code without introducing a breaking change. I'm very much eager to implement it, but I'm focus other things at the moment. This will also considerably reduce the base size (i.e. the size of the `node_modules/vite-plugin-ssr/` directory).

**Comment by cbbfcd** [comment]
That must be cool.

**Comment by cbbfcd** [comment]
@brillout hi~

> As for CJS, I actually found a neat way to publish only ESM code without introducing a breaking change. 

Is there anything new here, or can you share some ideas, and if I can contribute something

**Comment by brillout** [comment]
@cbbfcd Instead of setting `package.json#type` to `'module'` (it would force users to use ESM and it's therefore is a breaking change which we can't do in `0.4.x`), the idea is to rename all `.ts` files to `.mts` (we can then remove the CJS build). I believe that should do the trick.
