### ISSUE TITLE
Page loads successfully but none of the reactivity works.

### ISSUE THREAD

**Issue by BenjaminTom** [brillout/vite-plugin-ssr#96]
_default.page.client.ts:10 Uncaught (in promise) Error: [vite-plugin-ssr@0.1.1][Internal Failure] You stumbled upon a bug in `vite-plugin-ssr`'s source code (an internal assertion failed). This should definitely not be happening, and you should create a new issue at https://github.com/brillout/vite-plugin-ssr/issues/new that includes this error stack (the error stack is enough to debug this). Or reach out on Discord. A fix will be written promptly.
    at newError2 (newError.ts:18)
    at assert (assert.ts:21)
    at getPageById (getPage.client.ts:33)
    at async getPage (getPage.client.ts:14)
    at async hydrate (_default.page.client.ts:8)

**Comment by brillout** [comment]
Thanks for opening this ticket.

I inspected the strack trace and I've an idea what may cause this.

What is the HTML of the page that leads to this error?

**Comment by BenjaminTom** [comment]
I was just playing around with vue3 and vite but this is what caused it... 
https://lonelycoder.netlify.app

It works fine when it's on the home page but as soon I created a new route and copied that component in there it broke. I thought it might be the component so I tried to create a new route with just a H1 with some text and it still showed that error.

**Comment by brillout** [comment]
How can I reproduce the error at https://lonelycoder.netlify.app?

Is your local machine or your deployment machine running windows?

**Comment by brillout** [comment]
If you reload the page, does the error persist, or is it a volatile error?

**Comment by BenjaminTom** [comment]
Okay, so I started up the dev environment again and tried to reproduce the error and it seems to be working fine now. Must be one of those phantom errors you get when everything your playing with is so new. Thanks for your help with this though.

**Comment by brillout** [comment]
Yes I suspect a rare race condition. I narrowed down the assertions so we'll have more info next time it happens.

> as soon I created a new route

Yes it probably happens upon adding/reming a page file.
