### ISSUE TITLE
Restart server when any code in server modified.

### ISSUE THREAD

**Issue by BanDroid** [brillout/vite-plugin-ssr#964]
### Description

i found this problem when modifying /server/index.js and adding some middleware. i had to close the server and run it again manually to be able seeing the changes.

i hope the boilerplate could use nodemon to watch the changes in server directory.

**Comment by brillout** [comment]
See the comment on top of the server file:

> // This file isn't processed by Vite, see https://github.com/brillout/vite-plugin-ssr/issues/562

Please respect https://brillout.github.io/rules/. Thanks!

**Comment by brillout** [comment]
> Please respect https://brillout.github.io/rules/. Thanks!

That said, feel free to reach out if you believe it's related to VPS. And, actually, turns out this conversation is actually constructive: https://github.com/brillout/vite-plugin-ssr/commit/65b5b1b706a8836c3bf30e758570bd11b41959a8. So thanks for reaching out.

**Comment by BanDroid** [comment]
for typescript it is fine cause it uses ts-node to watch the server changes, for javascript boilerplates still use node which not watching any changes and have to manually restart the server.

**Comment by royalswe** [comment]
> That said, feel free to reach out if you believe it's related to VPS. And, actually, turns out this conversation is actually constructive: [65b5b1b](https://github.com/brillout/vite-plugin-ssr/commit/65b5b1b706a8836c3bf30e758570bd11b41959a8). So thanks for reaching out.

You could just add this line in package.json
`    "server:watch": "nodemon src -e ts,json --exec 'npm run server'",
`

complete scripts
```
  "scripts": {
    "dev": "npm run server:watch",
    "prod": "npm run build && npm run server:prod",
    "build": "vite build",
    "server": "ts-node ./server/index.ts",
    "server:watch": "nodemon src -e ts,json --exec 'npm run server'",
    "server:prod": "cross-env NODE_ENV=production ts-node ./server/index.ts"
  },
```

and off course you need to have nodemon installed globally or add it as dependencies.

**Comment by brillout** [comment]
Correct me if I'm wrong, but I think the problem with that is that it would restart the server even when a Vite file is being HMR'd.

**Comment by BanDroid** [comment]
> Correct me if I'm wrong, but I think the problem with that is that it would restart the server even when a Vite file is being HMR'd.

my script command does fine, only watching in server directory. anyway, any reason you dont want to use nodemon in boilerplate? if you dont want to do it, i could help you with that to save you some time

**Comment by royalswe** [comment]
Both my and BanDroid's example restarts the server even when vite.config makes changes.

**Comment by brillout** [comment]
The problem with that then is that it won't watch dependencies outside of `server/`. Let's follow https://github.com/brillout/vite-plugin-ssr/issues/562#issuecomment-1524777997 instead.
