### ISSUE TITLE
Routing folder name * cannot be used on Windows file systems

### ISSUE THREAD

**Issue by openscript** [brillout/vite-plugin-ssr#967]
### Description

I'm trying to run [inlangs](https://inlang.com/) tests on Windows. The repository cannot be cloned on Windows because of a folder with a [reserved character `*`](https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions) in it. This folder is part of the [file system routing](https://vite-plugin-ssr.com/filesystem-routing) of a package that uses vite-plugin-ssr.

```
  Error: fatal: cannot create directory at 'source-code/website/src/pages/documentation/*': Invalid argument
  Error: The process 'C:\Program Files\Git\bin\git.exe' failed with exit code 128
```

This is a blocker for all who want to use vite-plugin-ssr on ntfs/exfat file systems with a wild card file system route. Any suggestion to get rid of the asterisks folder name?

**Comment by samuelstroschein** [comment]
@brillout is VPS 1.0 still using `*` for catch-all routes?

**Comment by brillout** [comment]
Use a [Route String](https://vite-plugin-ssr.com/route-string).

> @brillout is VPS 1.0 still using `*` for catch-all routes?

Yes.

**Comment by samuelstroschein** [comment]
@brillout to verify, the possibility of defining routes as `*` in the filesystem has been removed?

**Comment by brillout** [comment]
It was never there. Nothing changed about this.

The regression is probably due to some change on your side.

**Comment by samuelstroschein** [comment]
@brillout you sure catch all filesystem routes was never possible? 

This is the route of question https://github.com/inlang/inlang/tree/37c3913f18d267e4ab176419265a4b188acd0b44/source-code/website/src/pages/documentation/* . Worked from day 1

**Comment by brillout** [comment]
> If not, the feature of defining catch-all routes with filesystem routes should probably be removed to make VPS work on windows by default

Showing a warning could be nice for users running their CI against Windows, but the warning would be useless and annoying for  Linux users. So I'm relunctant to add a warning.

> you sure catch all filesystem routes was never possible?

98.5% sure.

**Comment by samuelstroschein** [comment]
Well we gonna go with route strings. 

But, 100% sure VPS (maybe implicitly) supports catch all filesystem routes. Otherwise it wouldn't work in  https://github.com/inlang/inlang/tree/37c3913f18d267e4ab176419265a4b188acd0b44/source-code/website/src/pages/documentation/*

Thanks for the quick help

**Comment by brillout** [comment]
👍 Let me know if there is anything else.

And thanks again for sponsoring 💚.
