### ISSUE TITLE
Async route functions

### ISSUE THREAD

**Issue by deckchairlabs** [brillout/vite-plugin-ssr#97]
Came across a need for Async route functions. Would this be possible?

**Comment by brillout** [comment]
In principle it should be possible, but it is highly inefficient as all your functions are called upon each page request. Are you sure it is what you want?

I'm curious, what is your use case?

**Comment by deckchairlabs** [comment]
I want to be able to check if a "page" exists via an API call to a backend, and return a match value that indicates as such.

**Comment by deckchairlabs** [comment]
And performance isn't a concern as this is sitting behind a CDN

**Comment by brillout** [comment]
One thing we could do:

```js
export const iKnowThePerformanceRisksOfAsyncFunctions = true
export default async function() {
   /*...*/
}
```

Thoughts?

> I want to be able to check if a "page" exists via an API call to a backend, and return a match value that indicates as such.

This is actually the kind of things that `vite-plugin-ssr` should discourage. Your async route function will slow down the rendering of *all* your pages. Your sure it's ok?

**Comment by deckchairlabs** [comment]
I very much understand the risks. The way I'm setting this up, a page will only render when the content actually changes, it is then returned to the CDN and served from there until that url is purged.

And if it needs to be an opt in, I'm okay with that! :)

**Comment by brillout** [comment]
Sounds good, I'll implement the solution after I'm done with the page assets thing.

(Seems interesting what you are doing :-).)

**Comment by deckchairlabs** [comment]
Just seeing what's possible at the moment, but it should be pretty cool!

**Comment by brillout** [comment]
:-) Is it for your remix clone project?

**Comment by deckchairlabs** [comment]
It is! I'll probably write that up as a guide/tutorial I think, as most of the grunt work is done by this fine plugin.

Here's a very basic version running on the stack https://deckchair-test.web.app/

**Comment by brillout** [comment]
Neat.

FYI I've got some plans to highlight frameworks/boilerplates built on on top of `vite-plugin-ssr`.

**Comment by deckchairlabs** [comment]
Wonderful!
