### ISSUE TITLE
Built-in `.env` support

### ISSUE THREAD

**Issue by brillout** [brillout/vite-plugin-ssr#989]
### Description

While [Vite has built-in support for `.env` files](https://vitejs.dev/guide/env-and-mode.html#env-files), it only includes environment variables prefixed with `VITE_`.

[The official recommendation is to install `dotenv`](https://vite-plugin-ssr.com/env). But better yet, vite-plugin-ssr should have built-in support including niceties such as HMR and accessing *all* environment variable over `import.meta.env` (only on the server-side of course). Maybe also changing the prefix from `VITE_` to `PUBLIC_`.

**Comment by carlreid** [comment]
This would be great! Was just trying to find why the .`env.local` values weren't being loaded via `/server/index.ts`, which I assume related to this.

**Comment by brillout** [comment]
You're right and I'm realizing that [the new docs](https://github.com/brillout/vite-plugin-ssr/commit/d84d32dbee4da2b4ca532d1e2803bc2b94937820#diff-668194c039f01db73ece8bad36a7c1492cbdf6845346fcb637cdd831e0efb5fc) actually don't work for the server-side. I'll implement it tentatively this weekend.

**Comment by brillout** [comment]
Almost done, I'll finish tomorrow.

**Comment by brillout** [comment]
Done: use `0.4.133` and see udpated docs https://vite-plugin-ssr.com/env.

> Was just trying to find why the .`env.local` values weren't being loaded via `/server/index.ts`, which I assume related to this.

As descried in the docs, you'll still need to manutally install `dotenv` until https://github.com/brillout/vite-plugin-ssr/issues/562 is implemented.

Closing: once https://github.com/brillout/vite-plugin-ssr/issues/562 is implemented I'll consider environement variables to have well polished DX.

**Comment by carlreid** [comment]
Wonderful. Thanks for the quick turnaround !

**Comment by brillout** [comment]
Sure 👍 Btw. in case you're able to convince your employer: https://github.com/sponsors/brillout &mdash; it has a substantial impact.

**Comment by carlreid** [comment]
In this case, it's just for a personal project. Though if I do use it for my employer then I will for sure 😊

**Comment by brillout** [comment]
Thanks & have fun with your personal project (can't wait to fix all paper cuts and release the v1 👀).
