### ISSUE TITLE
Become more user friendly

### ISSUE THREAD

**Issue by MrFoxPro** [brillout/vite-plugin-ssr#999]
### Description

I appreciate attention to security and design decisions from Vike, but I think it's more politely to give users freedom of choices.
My suggestions are:
- Introduce flag like `allowBadDesignDecisions` to suppress warnings like `X defines an alias '@' that cannot be distinguished from npm package imports`
- Allow to skip `dangerouslySkipEscape` and `escapeInject` and pass raw string, show warning instead. Currently to bypass restrictions for simple cases I need to do this dirty hack:
```js
const documentHtml = html`
  <!DOCTYPE html>
  <html lang="en">
     <head>
        <meta
           name="viewport"
           content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, viewport-fit=cover" />
        ${head.join('\n')}
     </head>
     <body class="@dark:(bg-#17181A color-white)">
        ${body}
     </body>
  </html>
`
return {
  documentHtml: {
     _template: {
        templateStrings: [documentHtml],
        templateVariables: [],
     },
  },
}
```
- Expose internal properties that are underscored with `_` and `__`, e.g. within special type. Now for implementing some features like inserting css `<style>` in `<head>` it is necessary.

**Comment by brillout** [comment]
Thanks for the feedback :100:.

> * Introduce flag `allowBadDesignDecisions` to suppress warnings like `X defines an alias '@' that cannot be distinguished from npm package imports`

Update to the latest VPS version. The new warning is less strict. The warning does need to stay though (for many reasons).

> * Allow to skip `dangerouslySkipEscape` and `escapeInject` and pass raw string, show warning instead.

That's a good idea.

> * Expose internal properties that are underscored with `_` and `__`, e.g. within special type. Now for implementing some features like inserting css `<style>` in `<head>` it is necessary.

You're not supposed to use these internals without reaching out to a maintainer. If anything, I'll make it harder to use them (which is actually something I'll do as soon as vite-plugin-ssr/Vike becomes more popular.)

**Comment by brillout** [comment]
> That's a good idea.

[Done](https://github.com/brillout/vite-plugin-ssr/commit/846a92ee74ad2f006ebd60fae60a3625fbc12e6a). FYI you can use `dangerouslySkipEscape()` instead of your hack.

Closing but let me know if there is anything else.

**Comment by brillout** [comment]
> * Expose internal properties that are underscored with `_` and `__`, e.g. within special type. Now for implementing some features like inserting css `<style>` in `<head>` it is necessary.

Also: what is it you're doing? Ideally you shouldn't need any internal.

**Comment by MrFoxPro** [comment]
> > * Expose internal properties that are underscored with `_` and `__`, e.g. within special type. Now for implementing some features like inserting css `<style>` in `<head>` it is necessary.
> 
> Also: what is it you're doing? Ideally you shouldn't need any internal.

I was doing this https://github.com/brillout/vite-plugin-ssr/discussions/688

**Comment by brillout** [comment]
I updated [my comment about this](https://github.com/brillout/vite-plugin-ssr/discussions/688#discussioncomment-5239333).

**Comment by zhujiageng** [comment]
@brillout where is the allowBadDesignDecisions flag? i want to disable the warnig 'that cannot be distinguished from npm package imports'

**Comment by brillout** [comment]
@zhujiageng I've added instructions at https://vite-plugin-ssr.com/path-aliases#vite.

**Comment by brillout** [comment]
I don't understand why you need path aliases that start with `@` as I'm not familiar with Nx. Elaborate in a new GitHub Dicussion. FYI 16e41f3189137b402ed1f3a600b759db4c41cc90, so you won't be able to use such path alias in the next major release, unless you elaborate on your use case and in that case I'll dig into a solution.

**Comment by zhujiageng** [comment]
@brillout [nx]([nx](https://nx.dev/)) is a widely used monorepo tool, and all the internal libraries managed with it start with "@" as a prefix, and this prefix cannot be modified. If Vike is not compatible with "@" symbol, it will result in losing all the developers who rely on nx.

**Comment by brillout** [comment]
Monorepos typically don't need aliases: each package of a monorepo is, well, a package. It just happens that the package is never publishes to npm. There is no need for aliases as your package manager will already correctly resolve the package names.

I stand to be corrected, but I still don't see the need for aliases here.

And please create a new GitHub discussion for this.
